<?php
// This is file installs the map data for the WesternEurope1300 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('&Icirc;le-de-France (ILE)', 'Land', 'Yes', 1, 589, 647, 585, 643),
	array('London (LON)', 'Coast', 'Yes', 2, 547, 463, 546, 464),
	array('Scotland (SCO)', 'Coast', 'Yes', 0, 497, 219, 501, 208),
	array('Northumbria (NRT)', 'Coast', 'No', 2, 527, 272, 538, 273),
	array('Yorkshire (YOR)', 'Coast', 'Yes', 2, 563, 324, 570, 337),
	array('Lancashire (LNC)', 'Coast', 'No', 2, 505, 363, 502, 359),
	array('Wales (WAL)', 'Coast', 'Yes', 0, 466, 378, 465, 385),
	array('Devon (DEV)', 'Coast', 'Yes', 2, 402, 469, 403, 469),
	array('Gloucestershire (GLO)', 'Coast', 'No', 2, 485, 434, 486, 434),
	array('Lincolnshire (LIN)', 'Coast', 'Yes', 2, 569, 375, 566, 378),
	array('Dorset (DOR)', 'Coast', 'No', 2, 476, 482, 472, 479),
	array('Severn (SVR)', 'Land', 'No', 2, 502, 393, 499, 389),
	array('Frisia (FRI)', 'Coast', 'No', 0, 746, 422, 746, 423),
	array('Flanders (FLA)', 'Coast', 'Yes', 1, 626, 511, 625, 509),
	array('Luxembourg (LUX)', 'Land', 'Yes', 0, 714, 559, 718, 554),
	array('Switzerland (SWI)', 'Land', 'Yes', 0, 745, 725, 746, 730),
	array('Franche-Comt&eacute; (FRA)', 'Land', 'Yes', 5, 684, 748, 686, 745),
	array('Burgundy (BUR)', 'Land', 'Yes', 5, 649, 724, 647, 722),
	array('Lorraine (LOR)', 'Land', 'Yes', 0, 710, 620, 714, 619),
	array('Piedmont (PIE)', 'Coast', 'Yes', 0, 734, 873, 737, 869),
	array('Savoy (SAV)', 'Land', 'No', 0, 723, 821, 729, 817),
	array('Anjou (ANJ)', 'Land', 'Yes', 1, 508, 653, 514, 649),
	array('Normandy (NOR)', 'Coast', 'Yes', 1, 533, 584, 529, 582),
	array('Brittany (BRI)', 'Coast', 'Yes', 0, 446, 601, 444, 599),
	array('Toulouse (TOU)', 'Land', 'Yes', 1, 558, 808, 555, 810),
	array('Auvergne (AUV)', 'Land', 'No', 1, 587, 759, 590, 758),
	array('Champagne (CHA)', 'Land', 'No', 1, 654, 576, 652, 576),
	array('Maine (MAI)', 'Land', 'No', 1, 494, 607, 494, 605),
	array('Provence (PRO)', 'Coast', 'No', 1, 701, 875, 698, 876),
	array('Dauphin&eacute; (DAU)', 'Land', 'No', 1, 678, 843, 678, 836),
	array('Languedoc (LAN)', 'Coast', 'Yes', 1, 568, 870, 561, 871),
	array('Lyonnais (LYO)', 'Land', 'Yes', 5, 616, 765, 617, 761),
	array('Bourbonnais (BOU)', 'Land', 'No', 1, 592, 711, 592, 710),
	array('Poitou (POI)', 'Coast', 'Yes', 0, 454, 679, 458, 678),
	array('Gascony (GAS)', 'Coast', 'Yes', 2, 446, 802, 440, 798),
	array('Guyenne (GUY)', 'Coast', 'Yes', 2, 466, 736, 466, 736),
	array('Berry (BER)', 'Land', 'No', 1, 544, 693, 543, 695),
	array('Blois (BLO)', 'Land', 'Yes', 1, 555, 672, 555, 668),
	array('Vermandois (VER)', 'Coast', 'No', 1, 597, 537, 599, 541),
	array('East Anglia (EAS)', 'Coast', 'No', 2, 591, 416, 589, 417),
	array('Sussex (SUS)', 'Coast', 'Yes', 2, 566, 491, 566, 490),
	array('Brabant (BRA)', 'Coast', 'Yes', 0, 690, 495, 692, 493),
	array('Sardinia (SAR)', 'Coast', 'Yes', 0, 747, 1045, 751, 1040),
	array('Catalonia (CAT)', 'Coast', 'Yes', 4, 526, 940, 526, 934),
	array('Aragon (ARA)', 'Land', 'Yes', 4, 423, 897, 422, 936),
	array('Navarre (NAV)', 'Land', 'Yes', 0, 374, 910, 376, 910),
	array('Valencia (VAL)', 'Coast', 'Yes', 4, 414, 993, 409, 1001),
	array('Murcia (MUR)', 'Coast', 'No', 3, 346, 1101, 344, 1093),
	array('Granada (GRA)', 'Coast', 'Yes', 0, 234, 1117, 233, 1115),
	array('Seville (SEV)', 'Coast', 'Yes', 3, 146, 1040, 147, 1031),
	array('New Castile (CAS)', 'Land', 'No', 3, 243, 1035, 253, 1026),
	array('Le&oacute;n (LEO)', 'Land', 'Yes', 3, 311, 897, 301, 911),
	array('Asturias (AST)', 'Coast', 'No', 3, 278, 802, 266, 793),
	array('Galicia (GAL)', 'Coast', 'Yes', 3, 206, 775, 205, 771),
	array('Portugal (POR)', 'Coast', 'Yes', 0, 106, 926, 125, 924),
	array('Basque Country (BAS)', 'Coast', 'No', 3, 331, 819, 326, 816),
	array('Hebrides (HEB)', 'Sea', 'No', 0, 340, 129, 342, 137),
	array('Irish Sea (IRI)', 'Sea', 'No', 0, 478, 318, 479, 315),
	array('Celtic Sea (CEL)', 'Sea', 'No', 0, 391, 407, 391, 401),
	array('North Sea (NTH)', 'Sea', 'No', 0, 700, 201, 699, 216),
	array('Bay of Biscay (BIS)', 'Sea', 'No', 0, 378, 673, 367, 673),
	array('English Channel (ENG)', 'Sea', 'No', 0, 446, 541, 439, 540),
	array('Dover Narrows (DOV)', 'Sea', 'No', 0, 564, 523, 566, 516),
	array('Strait of Gibraltar (GIB)', 'Sea', 'No', 0, 115, 1131, 119, 1132),
	array('Balearic Sea (BAL)', 'Sea', 'No', 0, 605, 952, 606, 953),
	array('Western Mediterranean (MED)', 'Sea', 'No', 0, 624, 1144, 614, 1141),
	array('Tyrrhenian Sea (TYR)', 'Sea', 'No', 0, 811, 1067, 816, 1077),
	array('German Bight (BIG)', 'Sea', 'No', 0, 674, 362, 677, 360),
	array('North Atlantic (ATL)', 'Sea', 'No', 0, 184, 398, 192, 403),
	array('Mid-Atlantic (MID)', 'Sea', 'No', 0, 106, 693, 102, 692),
	array('Costa del Sur (SUR)', 'Sea', 'No', 0, 390, 1127, 392, 1124),
	array('Northumbria (NRT) (West Coast)', 'Coast', 'No', 2, 505, 283, 506, 279),
	array('Northumbria (NRT) (East Coast)', 'Coast', 'No', 2, 550, 279, 550, 278)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('&Icirc;le-de-France (ILE)','Burgundy (BUR)','No','Yes'),
	array('&Icirc;le-de-France (ILE)','Normandy (NOR)','No','Yes'),
	array('&Icirc;le-de-France (ILE)','Champagne (CHA)','No','Yes'),
	array('&Icirc;le-de-France (ILE)','Bourbonnais (BOU)','No','Yes'),
	array('&Icirc;le-de-France (ILE)','Berry (BER)','No','Yes'),
	array('&Icirc;le-de-France (ILE)','Blois (BLO)','No','Yes'),
	array('&Icirc;le-de-France (ILE)','Vermandois (VER)','No','Yes'),
	array('London (LON)','Gloucestershire (GLO)','No','Yes'),
	array('London (LON)','Lincolnshire (LIN)','No','Yes'),
	array('London (LON)','Dorset (DOR)','No','Yes'),
	array('London (LON)','Severn (SVR)','No','Yes'),
	array('London (LON)','East Anglia (EAS)','Yes','Yes'),
	array('London (LON)','Sussex (SUS)','Yes','Yes'),
	array('London (LON)','Dover Narrows (DOV)','Yes','No'),
	array('Scotland (SCO)','Northumbria (NRT)','No','Yes'),
	array('Scotland (SCO)','Hebrides (HEB)','Yes','No'),
	array('Scotland (SCO)','Irish Sea (IRI)','Yes','No'),
	array('Scotland (SCO)','North Sea (NTH)','Yes','No'),
	array('Scotland (SCO)','Northumbria (NRT) (West Coast)','Yes','No'),
	array('Scotland (SCO)','Northumbria (NRT) (East Coast)','Yes','No'),
	array('Northumbria (NRT)','Yorkshire (YOR)','No','Yes'),
	array('Northumbria (NRT)','Lancashire (LNC)','No','Yes'),
	array('Yorkshire (YOR)','Lancashire (LNC)','No','Yes'),
	array('Yorkshire (YOR)','Lincolnshire (LIN)','Yes','Yes'),
	array('Yorkshire (YOR)','North Sea (NTH)','Yes','No'),
	array('Yorkshire (YOR)','German Bight (BIG)','Yes','No'),
	array('Yorkshire (YOR)','Northumbria (NRT) (East Coast)','Yes','No'),
	array('Lancashire (LNC)','Northumbria (NRT)','Yes','No'),
	array('Lancashire (LNC)','Wales (WAL)','Yes','Yes'),
	array('Lancashire (LNC)','Lincolnshire (LIN)','No','Yes'),
	array('Lancashire (LNC)','Severn (SVR)','No','Yes'),
	array('Lancashire (LNC)','Irish Sea (IRI)','Yes','No'),
	array('Lancashire (LNC)','Northumbria (NRT) (West Coast)','Yes','No'),
	array('Wales (WAL)','Gloucestershire (GLO)','Yes','Yes'),
	array('Wales (WAL)','Severn (SVR)','No','Yes'),
	array('Wales (WAL)','Irish Sea (IRI)','Yes','No'),
	array('Wales (WAL)','Celtic Sea (CEL)','Yes','No'),
	array('Devon (DEV)','Gloucestershire (GLO)','Yes','Yes'),
	array('Devon (DEV)','Dorset (DOR)','Yes','Yes'),
	array('Devon (DEV)','Celtic Sea (CEL)','Yes','No'),
	array('Devon (DEV)','English Channel (ENG)','Yes','No'),
	array('Devon (DEV)','North Atlantic (ATL)','Yes','No'),
	array('Gloucestershire (GLO)','Dorset (DOR)','No','Yes'),
	array('Gloucestershire (GLO)','Severn (SVR)','No','Yes'),
	array('Gloucestershire (GLO)','Celtic Sea (CEL)','Yes','No'),
	array('Lincolnshire (LIN)','Severn (SVR)','No','Yes'),
	array('Lincolnshire (LIN)','East Anglia (EAS)','Yes','Yes'),
	array('Lincolnshire (LIN)','German Bight (BIG)','Yes','No'),
	array('Dorset (DOR)','Sussex (SUS)','Yes','Yes'),
	array('Dorset (DOR)','English Channel (ENG)','Yes','No'),
	array('Frisia (FRI)','Brabant (BRA)','Yes','Yes'),
	array('Frisia (FRI)','German Bight (BIG)','Yes','No'),
	array('Flanders (FLA)','Champagne (CHA)','No','Yes'),
	array('Flanders (FLA)','Vermandois (VER)','Yes','Yes'),
	array('Flanders (FLA)','Brabant (BRA)','Yes','Yes'),
	array('Flanders (FLA)','Dover Narrows (DOV)','Yes','No'),
	array('Luxembourg (LUX)','Lorraine (LOR)','No','Yes'),
	array('Luxembourg (LUX)','Champagne (CHA)','No','Yes'),
	array('Luxembourg (LUX)','Brabant (BRA)','No','Yes'),
	array('Switzerland (SWI)','Franche-Comt&eacute; (FRA)','No','Yes'),
	array('Switzerland (SWI)','Lorraine (LOR)','No','Yes'),
	array('Switzerland (SWI)','Savoy (SAV)','No','Yes'),
	array('Switzerland (SWI)','Dauphin&eacute; (DAU)','No','Yes'),
	array('Franche-Comt&eacute; (FRA)','Burgundy (BUR)','No','Yes'),
	array('Franche-Comt&eacute; (FRA)','Lorraine (LOR)','No','Yes'),
	array('Franche-Comt&eacute; (FRA)','Dauphin&eacute; (DAU)','No','Yes'),
	array('Franche-Comt&eacute; (FRA)','Lyonnais (LYO)','No','Yes'),
	array('Burgundy (BUR)','Lorraine (LOR)','No','Yes'),
	array('Burgundy (BUR)','Champagne (CHA)','No','Yes'),
	array('Burgundy (BUR)','Lyonnais (LYO)','No','Yes'),
	array('Burgundy (BUR)','Bourbonnais (BOU)','No','Yes'),
	array('Lorraine (LOR)','Champagne (CHA)','No','Yes'),
	array('Piedmont (PIE)','Savoy (SAV)','No','Yes'),
	array('Piedmont (PIE)','Provence (PRO)','Yes','Yes'),
	array('Piedmont (PIE)','Dauphin&eacute; (DAU)','No','Yes'),
	array('Piedmont (PIE)','Balearic Sea (BAL)','Yes','No'),
	array('Piedmont (PIE)','Tyrrhenian Sea (TYR)','Yes','No'),
	array('Savoy (SAV)','Dauphin&eacute; (DAU)','No','Yes'),
	array('Anjou (ANJ)','Brittany (BRI)','No','Yes'),
	array('Anjou (ANJ)','Maine (MAI)','No','Yes'),
	array('Anjou (ANJ)','Poitou (POI)','No','Yes'),
	array('Anjou (ANJ)','Berry (BER)','No','Yes'),
	array('Anjou (ANJ)','Blois (BLO)','No','Yes'),
	array('Normandy (NOR)','Brittany (BRI)','Yes','Yes'),
	array('Normandy (NOR)','Maine (MAI)','No','Yes'),
	array('Normandy (NOR)','Blois (BLO)','No','Yes'),
	array('Normandy (NOR)','Vermandois (VER)','Yes','Yes'),
	array('Normandy (NOR)','English Channel (ENG)','Yes','No'),
	array('Normandy (NOR)','Dover Narrows (DOV)','Yes','No'),
	array('Brittany (BRI)','Maine (MAI)','No','Yes'),
	array('Brittany (BRI)','Poitou (POI)','Yes','Yes'),
	array('Brittany (BRI)','Bay of Biscay (BIS)','Yes','No'),
	array('Brittany (BRI)','English Channel (ENG)','Yes','No'),
	array('Brittany (BRI)','North Atlantic (ATL)','Yes','No'),
	array('Brittany (BRI)','Mid-Atlantic (MID)','Yes','No'),
	array('Toulouse (TOU)','Auvergne (AUV)','No','Yes'),
	array('Toulouse (TOU)','Languedoc (LAN)','No','Yes'),
	array('Toulouse (TOU)','Gascony (GAS)','No','Yes'),
	array('Toulouse (TOU)','Guyenne (GUY)','No','Yes'),
	array('Auvergne (AUV)','Languedoc (LAN)','No','Yes'),
	array('Auvergne (AUV)','Lyonnais (LYO)','No','Yes'),
	array('Auvergne (AUV)','Bourbonnais (BOU)','No','Yes'),
	array('Auvergne (AUV)','Guyenne (GUY)','No','Yes'),
	array('Auvergne (AUV)','Berry (BER)','No','Yes'),
	array('Champagne (CHA)','Vermandois (VER)','No','Yes'),
	array('Champagne (CHA)','Brabant (BRA)','No','Yes'),
	array('Maine (MAI)','Blois (BLO)','No','Yes'),
	array('Provence (PRO)','Dauphin&eacute; (DAU)','No','Yes'),
	array('Provence (PRO)','Languedoc (LAN)','Yes','Yes'),
	array('Provence (PRO)','Balearic Sea (BAL)','Yes','No'),
	array('Dauphin&eacute; (DAU)','Languedoc (LAN)','No','Yes'),
	array('Dauphin&eacute; (DAU)','Lyonnais (LYO)','No','Yes'),
	array('Languedoc (LAN)','Lyonnais (LYO)','No','Yes'),
	array('Languedoc (LAN)','Gascony (GAS)','No','Yes'),
	array('Languedoc (LAN)','Catalonia (CAT)','Yes','Yes'),
	array('Languedoc (LAN)','Balearic Sea (BAL)','Yes','No'),
	array('Lyonnais (LYO)','Bourbonnais (BOU)','No','Yes'),
	array('Bourbonnais (BOU)','Berry (BER)','No','Yes'),
	array('Poitou (POI)','Guyenne (GUY)','Yes','Yes'),
	array('Poitou (POI)','Berry (BER)','No','Yes'),
	array('Poitou (POI)','Bay of Biscay (BIS)','Yes','No'),
	array('Gascony (GAS)','Guyenne (GUY)','Yes','Yes'),
	array('Gascony (GAS)','Catalonia (CAT)','No','Yes'),
	array('Gascony (GAS)','Aragon (ARA)','No','Yes'),
	array('Gascony (GAS)','Navarre (NAV)','No','Yes'),
	array('Gascony (GAS)','Basque Country (BAS)','Yes','Yes'),
	array('Gascony (GAS)','Bay of Biscay (BIS)','Yes','No'),
	array('Guyenne (GUY)','Berry (BER)','No','Yes'),
	array('Guyenne (GUY)','Bay of Biscay (BIS)','Yes','No'),
	array('Berry (BER)','Blois (BLO)','No','Yes'),
	array('Vermandois (VER)','Dover Narrows (DOV)','Yes','No'),
	array('East Anglia (EAS)','Dover Narrows (DOV)','Yes','No'),
	array('East Anglia (EAS)','German Bight (BIG)','Yes','No'),
	array('Sussex (SUS)','English Channel (ENG)','Yes','No'),
	array('Sussex (SUS)','Dover Narrows (DOV)','Yes','No'),
	array('Brabant (BRA)','Dover Narrows (DOV)','Yes','No'),
	array('Brabant (BRA)','German Bight (BIG)','Yes','No'),
	array('Sardinia (SAR)','Balearic Sea (BAL)','Yes','No'),
	array('Sardinia (SAR)','Western Mediterranean (MED)','Yes','No'),
	array('Sardinia (SAR)','Tyrrhenian Sea (TYR)','Yes','No'),
	array('Catalonia (CAT)','Aragon (ARA)','No','Yes'),
	array('Catalonia (CAT)','Valencia (VAL)','Yes','Yes'),
	array('Catalonia (CAT)','Balearic Sea (BAL)','Yes','No'),
	array('Aragon (ARA)','Navarre (NAV)','No','Yes'),
	array('Aragon (ARA)','Valencia (VAL)','No','Yes'),
	array('Aragon (ARA)','Le&oacute;n (LEO)','No','Yes'),
	array('Navarre (NAV)','Le&oacute;n (LEO)','No','Yes'),
	array('Navarre (NAV)','Basque Country (BAS)','No','Yes'),
	array('Valencia (VAL)','Murcia (MUR)','Yes','Yes'),
	array('Valencia (VAL)','New Castile (CAS)','No','Yes'),
	array('Valencia (VAL)','Balearic Sea (BAL)','Yes','No'),
	array('Valencia (VAL)','Costa del Sur (SUR)','Yes','No'),
	array('Murcia (MUR)','Granada (GRA)','Yes','Yes'),
	array('Murcia (MUR)','New Castile (CAS)','No','Yes'),
	array('Murcia (MUR)','Costa del Sur (SUR)','Yes','No'),
	array('Granada (GRA)','Seville (SEV)','Yes','Yes'),
	array('Granada (GRA)','New Castile (CAS)','No','Yes'),
	array('Granada (GRA)','Strait of Gibraltar (GIB)','Yes','No'),
	array('Granada (GRA)','Costa del Sur (SUR)','Yes','No'),
	array('Seville (SEV)','New Castile (CAS)','No','Yes'),
	array('Seville (SEV)','Le&oacute;n (LEO)','No','Yes'),
	array('Seville (SEV)','Portugal (POR)','Yes','Yes'),
	array('Seville (SEV)','Strait of Gibraltar (GIB)','Yes','No'),
	array('New Castile (CAS)','Le&oacute;n (LEO)','No','Yes'),
	array('Le&oacute;n (LEO)','Asturias (AST)','No','Yes'),
	array('Le&oacute;n (LEO)','Galicia (GAL)','No','Yes'),
	array('Le&oacute;n (LEO)','Portugal (POR)','No','Yes'),
	array('Le&oacute;n (LEO)','Basque Country (BAS)','No','Yes'),
	array('Asturias (AST)','Galicia (GAL)','Yes','Yes'),
	array('Asturias (AST)','Basque Country (BAS)','Yes','Yes'),
	array('Asturias (AST)','Bay of Biscay (BIS)','Yes','No'),
	array('Galicia (GAL)','Portugal (POR)','Yes','Yes'),
	array('Galicia (GAL)','Bay of Biscay (BIS)','Yes','No'),
	array('Galicia (GAL)','Mid-Atlantic (MID)','Yes','No'),
	array('Portugal (POR)','Strait of Gibraltar (GIB)','Yes','No'),
	array('Portugal (POR)','Mid-Atlantic (MID)','Yes','No'),
	array('Basque Country (BAS)','Bay of Biscay (BIS)','Yes','No'),
	array('Hebrides (HEB)','Irish Sea (IRI)','Yes','No'),
	array('Hebrides (HEB)','North Sea (NTH)','Yes','No'),
	array('Hebrides (HEB)','North Atlantic (ATL)','Yes','No'),
	array('Irish Sea (IRI)','Celtic Sea (CEL)','Yes','No'),
	array('Irish Sea (IRI)','Northumbria (NRT) (West Coast)','Yes','No'),
	array('Celtic Sea (CEL)','North Atlantic (ATL)','Yes','No'),
	array('North Sea (NTH)','German Bight (BIG)','Yes','No'),
	array('North Sea (NTH)','Northumbria (NRT) (East Coast)','Yes','No'),
	array('Bay of Biscay (BIS)','Mid-Atlantic (MID)','Yes','No'),
	array('English Channel (ENG)','Dover Narrows (DOV)','Yes','No'),
	array('English Channel (ENG)','North Atlantic (ATL)','Yes','No'),
	array('Dover Narrows (DOV)','German Bight (BIG)','Yes','No'),
	array('Strait of Gibraltar (GIB)','Mid-Atlantic (MID)','Yes','No'),
	array('Strait of Gibraltar (GIB)','Costa del Sur (SUR)','Yes','No'),
	array('Balearic Sea (BAL)','Western Mediterranean (MED)','Yes','No'),
	array('Balearic Sea (BAL)','Tyrrhenian Sea (TYR)','Yes','No'),
	array('Balearic Sea (BAL)','Costa del Sur (SUR)','Yes','No'),
	array('Western Mediterranean (MED)','Tyrrhenian Sea (TYR)','Yes','No'),
	array('Western Mediterranean (MED)','Costa del Sur (SUR)','Yes','No'),
	array('North Atlantic (ATL)','Mid-Atlantic (MID)','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
