<?php
// This is file installs the map data for the WorldAtWar1937 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Alaska (ASK)', 'Coast', 'Yes', 2, 1, 1, 77, 173),
	array('Juneau (JUN)', 'Coast', 'No', 2, 1, 1, 169, 180),
	array('North Central Canada (NCC)', 'Coast', 'No', 1, 0, 0, 265, 143),
	array('Nunavut (NNV)', 'Coast', 'Yes', 1, 0, 0, 451, 162),
	array('Quebec (QUE)', 'Coast', 'Yes', 0, 0, 0, 628, 224),
	array('Newfoundland (NFL)', 'Coast', 'Yes', 1, 0, 0, 577, 291),
	array('Ontario (ONT)', 'Land', 'Yes', 0, 0, 0, 473, 299),
	array('Central Canada (CCA)', 'Land', 'No', 1, 0, 0, 336, 183),
	array('Yukon Territory (YKT)', 'Land', 'Yes', 1, 0, 0, 227, 177),
	array('British Columbia (BRC)', 'Coast', 'No', 1, 0, 0, 205, 244),
	array('South Central Canada (SCC)', 'Land', 'Yes', 1, 0, 0, 291, 248),
	array('Washington (WSH)', 'Coast', 'Yes', 2, 0, 0, 210, 289),
	array('Montana (MTA)', 'Land', 'No', 2, 0, 0, 286, 308),
	array('Midwest (MWS)', 'Land', 'No', 2, 0, 0, 423, 334),
	array('Northeast US (NES)', 'Coast', 'No', 2, 0, 0, 463, 361),
	array('New England (NEG)', 'Coast', 'Yes', 2, 0, 0, 528, 319),
	array('St. Louis (STL)', 'Land', 'Yes', 2, 0, 0, 387, 376),
	array('Rocky Mountains (RKM)', 'Land', 'No', 2, 0, 0, 276, 359),
	array('California (CLF)', 'Coast', 'Yes', 2, 0, 0, 179, 396),
	array('Nevada (NVD)', 'Land', 'No', 2, 0, 0, 213, 371),
	array('Texas (TEX)', 'Coast', 'Yes', 2, 0, 0, 296, 448),
	array('Florida (FLO)', 'Coast', 'Yes', 2, 0, 0, 415, 447),
	array('Cuba (CBA)', 'Coast', 'Yes', 0, 0, 0, 449, 517),
	array('Coahulia (COA)', 'Coast', 'Yes', 7, 0, 0, 280, 500),
	array('Chihuahua (CHH)', 'Land', 'No', 7, 0, 0, 243, 464),
	array('Baja California (BJA)', 'Coast', 'Yes', 7, 0, 0, 186, 466),
	array('Mexico City (MXC)', 'Coast', 'Yes', 7, 0, 0, 278, 550),
	array('Yucatan (YCT)', 'Coast', 'Yes', 7, 0, 0, 305, 542),
	array('Yucatan (YCT) (North Coast)', 'Coast', 'No', 7, 0, 0, 355, 521),
	array('Yucatan (YCT) (South Coast)', 'Coast', 'No', 7, 0, 0, 319, 566),
	array('Central America (CAM)', 'Coast', 'No', 0, 0, 0, 347, 569),
	array('Central America (CAM) (North Coast)', 'Coast', 'No', 0, 0, 0, 376, 563),
	array('Central America (CAM) (South Coast)', 'Coast', 'No', 0, 0, 0, 360, 589),
	array('Panama (PNM)', 'Coast', 'Yes', 0, 0, 0, 402, 624),
	array('Colombia (COL)', 'Coast', 'Yes', 0, 0, 0, 450, 644),
	array('Colombia (COL) (North Coast)', 'Coast', 'No', 0, 0, 0, 478, 617),
	array('Colombia (COL) (West Coast)', 'Coast', 'No', 0, 0, 0, 433, 660),
	array('Venezuela (VNZ)', 'Coast', 'No', 0, 0, 0, 527, 618),
	array('French Guiana (FGU)', 'Coast', 'Yes', 3, 0, 0, 581, 672),
	array('Amazon (AMZ)', 'Coast', 'No', 6, 0, 0, 611, 723),
	array('Salvador (SVD)', 'Coast', 'Yes', 6, 0, 0, 725, 762),
	array('Peru (PRU)', 'Coast', 'Yes', 1, 0, 0, 439, 794),
	array('Bolivia (BLV)', 'Land', 'No', 0, 0, 0, 527, 814),
	array('Mato Grosso (MGS)', 'Land', 'No', 6, 0, 0, 617, 853),
	array('Rio de Janeiro (RIO)', 'Coast', 'Yes', 6, 0, 0, 702, 878),
	array('Sao Paulo (SPU)', 'Coast', 'Yes', 6, 0, 0, 649, 921),
	array('Paraguay (PGY)', 'Land', 'No', 0, 0, 0, 587, 907),
	array('Chile (CHI)', 'Coast', 'Yes', 0, 0, 0, 511, 956),
	array('Galapagos', 'Coast', 'No', 0, 0, 0, 174, 875),
	array('Argentina (AGT)', 'Coast', 'Yes', 3, 0, 0, 566, 1016),
	array('South Africa (SAF)', 'Coast', 'Yes', 1, 0, 0, 1226, 939),
	array('Namibia (NMB)', 'Coast', 'No', 0, 0, 0, 1137, 860),
	array('Botswana (BSW)', 'Land', 'Yes', 0, 0, 0, 1211, 899),
	array('Mozambique (MZB)', 'Coast', 'Yes', 6, 0, 0, 1287, 853),
	array('Madagascar (MDG)', 'Coast', 'Yes', 3, 0, 0, 1373, 872),
	array('Kenya (KNY)', 'Coast', 'Yes', 0, 0, 0, 1310, 733),
	array('Zimbabwe (ZBW)', 'Land', 'No', 0, 0, 0, 1243, 804),
	array('Angola (AGL)', 'Coast', 'Yes', 6, 0, 0, 1129, 770),
	array('Congo (CNG)', 'Coast', 'Yes', 1, 0, 0, 1164, 739),
	array('Cameroon (CMR)', 'Coast', 'Yes', 3, 0, 0, 1100, 705),
	array('Chad (CHD)', 'Land', 'No', 0, 0, 0, 1167, 596),
	array('Nigeria (NGR)', 'Coast', 'No', 1, 0, 0, 1079, 612),
	array('Ivory Coast (IVC)', 'Coast', 'Yes', 1, 0, 0, 1010, 646),
	array('West Africa (WAF)', 'Coast', 'No', 3, 0, 0, 921, 600),
	array('Mauritania (MAU)', 'Coast', 'Yes', 0, 0, 0, 921, 513),
	array('Morocco (MRC)', 'Coast', 'No', 3, 0, 0, 978, 414),
	array('Gibraltar (GIB)', 'Coast', 'Yes', 0, 0, 0, 1008, 374),
	array('Portugal (PRG)', 'Coast', 'Yes', 6, 0, 0, 960, 375),
	array('Madrid (MDR)', 'Coast', 'Yes', 0, 0, 0, 972, 323),
	array('Barcelona (BRC)', 'Coast', 'No', 0, 0, 0, 1032, 340),
	array('Marseilles (MAR)', 'Coast', 'Yes', 3, 0, 0, 1067, 321),
	array('Bordeaux (BDX)', 'Coast', 'Yes', 3, 0, 0, 1022, 317),
	array('Brittany (BTY)', 'Coast', 'Yes', 3, 0, 0, 998, 283),
	array('Paris (PAR)', 'Land', 'Yes', 3, 0, 0, 1047, 298),
	array('Alsace (ALS)', 'Land', 'No', 3, 0, 0, 1067, 280),
	array('Picardy (PIC)', 'Coast', 'No', 3, 0, 0, 1041, 266),
	array('London (LON)', 'Coast', 'Yes', 1, 0, 0, 1031, 244),
	array('Wales (WAL)', 'Coast', 'No', 1, 0, 0, 1002, 245),
	array('Yorkshire (YOR)', 'Coast', 'Yes', 1, 0, 0, 1010, 226),
	array('Ireland (IRE)', 'Coast', 'Yes', 0, 0, 0, 973, 247),
	array('Iceland (ICE)', 'Coast', 'Yes', 0, 0, 0, 937, 150),
	array('Nuuk (NUK)', 'Coast', 'Yes', 0, 0, 0, 768, 161),
	array('Upper Greenland (UGD)', 'Coast', 'No', 0, 0, 0, 827, 67),
	array('Norway (NWY)', 'Coast', 'Yes', 0, 0, 0, 1100, 160),
	array('Lapland (LPL)', 'Coast', 'No', 0, 0, 0, 1180, 111),
	array('Finland (FIN)', 'Coast', 'No', 0, 0, 0, 1194, 176),
	array('Sweden (SWE)', 'Coast', 'Yes', 0, 0, 0, 1125, 199),
	array('Denmark (DEN)', 'Coast', 'Yes', 0, 0, 0, 1090, 223),
	array('Kiel (KIE)', 'Coast', 'Yes', 4, 0, 0, 1090, 246),
	array('Holland (HO)', 'Coast', 'Yes', 0, 0, 0, 1064, 239),
	array('Belgium (B)', 'Coast', 'Yes', 0, 0, 0, 1049, 256),
	array('Rhineland (RHI)', 'Land', 'Yes', 4, 0, 0, 1086, 274),
	array('Munich (MUN)', 'Land', 'No', 4, 0, 0, 1106, 269),
	array('Austria (AUS)', 'Land', 'Yes', 0, 0, 0, 1121, 288),
	array('Berlin (BER)', 'Land', 'Yes', 4, 0, 0, 1109, 253),
	array('Prussia (PRU)', 'Coast', 'Yes', 4, 0, 0, 1122, 238),
	array('Silesia (SIL)', 'Land', 'Yes', 4, 0, 0, 1136, 257),
	array('Czechoslovakia (CZE)', 'Land', 'No', 0, 0, 0, 1137, 270),
	array('Warsaw (WAR)', 'Coast', 'Yes', 0, 0, 0, 1158, 245),
	array('Danzig (DAN)', 'Coast', 'Yes', 4, 0, 0, 1170, 231),
	array('Baltic States (BTS)', 'Coast', 'Yes', 0, 0, 0, 1185, 202),
	array('Vilnius (VIL)', 'Land', 'Yes', 0, 0, 0, 1192, 267),
	array('Hungary (HNG)', 'Land', 'No', 0, 0, 0, 1171, 288),
	array('Rumania (RUM)', 'Coast', 'Yes', 0, 0, 0, 1221, 301),
	array('Bulgaria (BUL)', 'Coast', 'Yes', 0, 0, 0, 1207, 326),
	array('Serbia (SER)', 'Land', 'Yes', 0, 0, 0, 1181, 326),
	array('Greece (GRE)', 'Coast', 'Yes', 0, 0, 0, 1180, 354),
	array('Albania (ALB)', 'Coast', 'Yes', 5, 0, 0, 1163, 337),
	array('Croatia (CRO)', 'Coast', 'Yes', 0, 0, 0, 1139, 314),
	array('Venice (VEN)', 'Coast', 'Yes', 5, 0, 0, 1113, 320),
	array('Piedmont (PIE)', 'Coast', 'No', 5, 0, 0, 1093, 317),
	array('Rome (ROM)', 'Coast', 'Yes', 5, 0, 0, 1116, 339),
	array('Naples (NAP)', 'Coast', 'Yes', 5, 0, 0, 1138, 355),
	array('Tunis (TUN)', 'Coast', 'Yes', 3, 0, 0, 1091, 385),
	array('South Tunisia (STU)', 'Land', 'No', 3, 0, 0, 1069, 443),
	array('Fezzan (FEZ)', 'Land', 'No', 0, 0, 0, 1132, 527),
	array('Tripoli (TPO)', 'Coast', 'No', 5, 0, 0, 1122, 463),
	array('Benghazi (BGZ)', 'Coast', 'Yes', 5, 0, 0, 1179, 430),
	array('Aswan (ASW)', 'Coast', 'No', 1, 0, 0, 1220, 471),
	array('Aswan (ASW) (North Coast)', 'Coast', 'No', 1, 0, 0, 1215, 435),
	array('Aswan (ASW) (East Coast)', 'Coast', 'No', 1, 0, 0, 1273, 490),
	array('Cairo (CAI)', 'Coast', 'Yes', 1, 0, 0, 1243, 447),
	array('Sudan (SDN)', 'Coast', 'Yes', 0, 0, 0, 1280, 544),
	array('Ethiopia (ETH)', 'Coast', 'No', 5, 0, 0, 1318, 587),
	array('Somaliland (SOM)', 'Coast', 'Yes', 5, 0, 0, 1375, 653),
	array('Oman (OMA)', 'Coast', 'Yes', 0, 0, 0, 1442, 526),
	array('Saudi Arabia (SDA)', 'Coast', 'Yes', 1, 0, 0, 1336, 479),
	array('Saudi Arabia (SDA) (West Coast)', 'Coast', 'No', 1, 0, 0, 1338, 524),
	array('Saudi Arabia (SDA) (East Coast)', 'Coast', 'No', 1, 0, 0, 1373, 469),
	array('Iraq (IRQ)', 'Coast', 'No', 1, 0, 0, 1357, 428),
	array('Syria (SYR)', 'Coast', 'Yes', 0, 0, 0, 1286, 425),
	array('Adana (ADA)', 'Coast', 'Yes', 9, 0, 0, 1263, 377),
	array('Istanbul (IST)', 'Coast', 'Yes', 9, 0, 0, 1231, 347),
	array('Ankara (ANK)', 'Coast', 'Yes', 9, 0, 0, 1306, 348),
	array('Caucasus (CAU)', 'Coast', 'No', 8, 0, 0, 1306, 311),
	array('Ukraine (UKR)', 'Coast', 'Yes', 8, 0, 0, 1268, 282),
	array('Belarus (BLR)', 'Land', 'No', 8, 0, 0, 1225, 247),
	array('Leningrad (LNG)', 'Coast', 'Yes', 8, 0, 0, 1224, 195),
	array('Murmansk (MSK)', 'Coast', 'Yes', 8, 0, 0, 1247, 125),
	array('Moscow (MOS)', 'Land', 'Yes', 8, 0, 0, 1333, 204),
	array('Stalingrad (STA)', 'Land', 'Yes', 8, 0, 0, 1277, 251),
	array('Western Siberia (WSB)', 'Land', 'Yes', 8, 0, 0, 1429, 253),
	array('Nenets (NNT)', 'Coast', 'No', 8, 0, 0, 1403, 141),
	array('Northern Siberia (NSB)', 'Coast', 'Yes', 8, 0, 0, 1630, 108),
	array('Siberia (SIB)', 'Land', 'No', 8, 0, 0, 1592, 219),
	array('Southern Siberia (SSB)', 'Land', 'No', 8, 0, 0, 1520, 275),
	array('Irkutsk (IRK)', 'Land', 'Yes', 8, 0, 0, 1735, 235),
	array('Yakutsk (YKK)', 'Land', 'No', 8, 0, 0, 1811, 207),
	array('Magadan (MGD)', 'Coast', 'No', 8, 0, 0, 1892, 175),
	array('Magadan (MGD) (North Coast)', 'Coast', 'No', 8, 0, 0, 1861, 115),
	array('Magadan (MGD) (South Coast)', 'Coast', 'No', 8, 0, 0, 1895, 198),
	array('Kamchatka (KAM)', 'Coast', 'Yes', 8, 0, 0, 2040, 213),
	array('Vladivostok (VDV)', 'Coast', 'Yes', 8, 0, 0, 1949, 302),
	array('Manchuria (MCH)', 'Coast', 'Yes', 11, 0, 0, 1885, 323),
	array('Mongolia (MON)', 'Land', 'Yes', 0, 0, 0, 1748, 315),
	array('Western China (WCH)', 'Land', 'Yes', 10, 0, 0, 1622, 361),
	array('Kazakhstan (KAZ)', 'Land', 'Yes', 0, 0, 0, 1440, 341),
	array('Iran (IRN)', 'Coast', 'Yes', 0, 0, 0, 1415, 434),
	array('Afghanistan (AFG)', 'Land', 'No', 0, 0, 0, 1495, 423),
	array('Punjab (PJB)', 'Land', 'No', 1, 0, 0, 1576, 433),
	array('Bombay (BBY)', 'Coast', 'No', 1, 0, 0, 1552, 503),
	array('South India (SIN)', 'Coast', 'Yes', 1, 0, 0, 1603, 573),
	array('Madras (MDR)', 'Coast', 'No', 1, 0, 0, 1644, 529),
	array('Delhi (DHI)', 'Land', 'Yes', 0, 0, 0, 1627, 472),
	array('Nepal (NPL)', 'Land', 'No', 0, 0, 0, 1654, 454),
	array('Bangladesh (BNG)', 'Coast', 'No', 1, 0, 0, 1702, 498),
	array('Tibet (TIB)', 'Land', 'Yes', 10, 0, 0, 1674, 420),
	array('Xi\\\'an (XIA)', 'Land', 'No', 10, 0, 0, 1798, 399),
	array('Peking (PEK)', 'Coast', 'Yes', 11, 0, 0, 1881, 398),
	array('Jiangxi (JXI)', 'Land', 'Yes', 10, 0, 0, 1866, 444),
	array('Shanghai (SGH)', 'Coast', 'Yes', 0, 0, 0, 1897, 444),
	array('Canton (CTO)', 'Coast', 'Yes', 10, 0, 0, 1859, 505),
	array('Yunan (YNN)', 'Land', 'No', 10, 0, 0, 1817, 471),
	array('Indochina (IDC)', 'Coast', 'Yes', 3, 0, 0, 1835, 569),
	array('Cambodia (CMB)', 'Coast', 'No', 3, 0, 0, 1811, 601),
	array('Bangkok (BGK)', 'Coast', 'Yes', 12, 0, 0, 1789, 577),
	array('Chiang Mai (CHM)', 'Land', 'Yes', 12, 0, 0, 1768, 540),
	array('Burma (BUR)', 'Coast', 'Yes', 0, 0, 0, 1739, 544),
	array('Phuket (PHU)', 'Coast', 'Yes', 12, 0, 0, 1783, 632),
	array('Phuket (PHU) (West Coast)', 'Coast', 'No', 12, 0, 0, 1766, 613),
	array('Phuket (PHU) (East Coast)', 'Coast', 'No', 12, 0, 0, 1775, 600),
	array('Malaysia (MLY)', 'Coast', 'Yes', 0, 0, 0, 1803, 671),
	array('Malaysia (MLY) (East Coast)', 'Coast', 'No', 0, 0, 0, 1805, 653),
	array('Malaysia (MLY) (West Coast)', 'Coast', 'No', 0, 0, 0, 1786, 654),
	array('Singapore (SGP)', 'Coast', 'Yes', 1, 0, 0, 1818, 692),
	array('Sumatra (SUM)', 'Coast', 'No', 0, 0, 0, 1789, 703),
	array('Java (JVA)', 'Coast', 'No', 0, 0, 0, 1877, 761),
	array('Borneo (BNO)', 'Coast', 'Yes', 0, 0, 0, 1865, 705),
	array('Brunei (BNI)', 'Coast', 'Yes', 0, 0, 0, 1888, 665),
	array('Sulawesi (SLW)', 'Coast', 'Yes', 0, 0, 0, 1940, 708),
	array('Kimberley (KIM)', 'Coast', 'No', 1, 0, 0, 1984, 836),
	array('Perth (PER)', 'Coast', 'Yes', 1, 0, 0, 1885, 969),
	array('Outback (OUT)', 'Coast', 'No', 1, 0, 0, 1988, 964),
	array('Northeast Australia', 'Coast', 'No', 1, 0, 0, 2102, 849),
	array('Sydney (SYD)', 'Coast', 'No', 1, 0, 0, 2114, 961),
	array('Victoria (VCT)', 'Coast', 'Yes', 0, 0, 0, 2091, 998),
	array('Queenstown (QTW)', 'Coast', 'No', 0, 0, 0, 2191, 1077),
	array('Wellington (WEL)', 'Coast', 'Yes', 0, 0, 0, 2273, 1027),
	array('New Guinea (NGU)', 'Coast', 'Yes', 0, 0, 0, 2076, 732),
	array('Philippines (PLP)', 'Coast', 'No', 2, 0, 0, 1966, 617),
	array('Manila (MAN)', 'Coast', 'Yes', 2, 0, 0, 1949, 577),
	array('Taiwan (TAI)', 'Coast', 'Yes', 11, 0, 0, 1927, 502),
	array('Okinawa', 'Coast', 'Yes', 11, 0, 0, 1986, 487),
	array('Korea (KOR)', 'Coast', 'Yes', 11, 0, 0, 1942, 390),
	array('Tokyo (TKY)', 'Coast', 'Yes', 11, 0, 0, 2017, 372),
	array('Hokkaido (HOK)', 'Coast', 'Yes', 11, 0, 0, 2008, 317),
	array('Wake Island', 'Coast', 'Yes', 2, 0, 0, 2149, 430),
	array('Midway', 'Coast', 'Yes', 2, 0, 0, 2179, 325),
	array('Hawaii', 'Coast', 'Yes', 2, 0, 0, 2361, 451),
	array('Arctic Circle', 'Sea', 'No', 0, 0, 0, 203, 48),
	array('Beaufort Sea', 'Sea', 'No', 0, 0, 0, 271, 93),
	array('Haida Gwaii', 'Sea', 'No', 0, 0, 0, 158, 248),
	array('Alaskan Gulf', 'Sea', 'No', 0, 0, 0, 103, 240),
	array('Coast of California', 'Sea', 'No', 0, 0, 0, 137, 430),
	array('North Pacific Ocean', 'Sea', 'No', 0, 0, 0, 48, 518),
	array('Coast of Mexico', 'Sea', 'No', 0, 0, 0, 201, 530),
	array('Pacific Ocean', 'Sea', 'No', 0, 0, 0, 103, 754),
	array('Gulf of Panama', 'Sea', 'No', 0, 0, 0, 326, 742),
	array('South Pacific Ocean', 'Sea', 'No', 0, 0, 0, 344, 1022),
	array('West Southern Ocean', 'Sea', 'No', 0, 0, 0, 154, 1198),
	array('Drake Passage', 'Sea', 'No', 0, 0, 0, 544, 1256),
	array('Southern Ocean', 'Sea', 'No', 0, 0, 0, 1229, 1187),
	array('South African Coast', 'Sea', 'No', 0, 0, 0, 1177, 1073),
	array('South Atlantic Ocean', 'Sea', 'No', 0, 0, 0, 939, 1069),
	array('South West Atlantic Ocean', 'Sea', 'No', 0, 0, 0, 702, 1078),
	array('Southern Mid Atlantic Ocean', 'Sea', 'No', 0, 0, 0, 838, 888),
	array('South East Atlantic Ocean', 'Sea', 'No', 0, 0, 0, 1057, 881),
	array('West African Coast', 'Sea', 'No', 0, 0, 0, 1008, 727),
	array('Mid Atlantic Ocean', 'Sea', 'No', 0, 0, 0, 858, 713),
	array('West Atlantic Ocean', 'Sea', 'No', 0, 0, 0, 687, 605),
	array('East Caribbean', 'Sea', 'No', 0, 0, 0, 568, 604),
	array('West Caribbean', 'Sea', 'No', 0, 0, 0, 418, 572),
	array('Gulf of Mexico', 'Sea', 'No', 0, 0, 0, 324, 509),
	array('Bermuda Triangle', 'Sea', 'No', 0, 0, 0, 474, 502),
	array('Sargasso Sea', 'Sea', 'No', 0, 0, 0, 581, 434),
	array('Northern Mid Atlantic Ocean', 'Sea', 'No', 0, 0, 0, 759, 487),
	array('East Atlantic Ocean', 'Sea', 'No', 0, 0, 0, 867, 517),
	array('North West Atlantic Ocean', 'Sea', 'No', 0, 0, 0, 610, 374),
	array('North Atlantic Ocean', 'Sea', 'No', 0, 0, 0, 753, 287),
	array('Hudson Bay', 'Sea', 'No', 0, 0, 0, 508, 208),
	array('Labrador Sea', 'Sea', 'No', 0, 0, 0, 601, 98),
	array('Greenland Sea', 'Sea', 'No', 0, 0, 0, 850, 190),
	array('Norwegian Sea', 'Sea', 'No', 0, 0, 0, 1073, 114),
	array('North Sea', 'Sea', 'No', 0, 0, 0, 1038, 184),
	array('English Channel', 'Sea', 'No', 0, 0, 0, 1019, 262),
	array('Irish Sea', 'Sea', 'No', 0, 0, 0, 996, 233),
	array('North East Atlantic Ocean', 'Sea', 'No', 0, 0, 0, 921, 241),
	array('Iberian Sea', 'Sea', 'No', 0, 0, 0, 917, 381),
	array('Bay of Biscay', 'Sea', 'No', 0, 0, 0, 997, 303),
	array('West Mediterranean Sea', 'Sea', 'No', 0, 0, 0, 1056, 340),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 0, 0, 1106, 360),
	array('Ionian Sea', 'Sea', 'No', 0, 0, 0, 1139, 389),
	array('Adriatic Sea', 'Sea', 'No', 0, 0, 0, 1158, 359),
	array('East Mediterranean Sea', 'Sea', 'No', 0, 0, 0, 1201, 387),
	array('South Black Sea (SBS)', 'Sea', 'No', 0, 0, 0, 1248, 327),
	array('East Black Sea (EBS)', 'Sea', 'No', 0, 0, 0, 1288, 320),
	array('West Black Sea (WBS)', 'Sea', 'No', 0, 0, 0, 1232, 319),
	array('Baltic Sea', 'Sea', 'No', 0, 0, 0, 1135, 217),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 0, 0, 1172, 186),
	array('Barents Sea', 'Sea', 'No', 0, 0, 0, 1173, 81),
	array('White Sea', 'Sea', 'No', 0, 0, 0, 1277, 104),
	array('Kara Sea', 'Sea', 'No', 0, 0, 0, 1321, 45),
	array('Siberian Sea', 'Sea', 'No', 0, 0, 0, 1749, 60),
	array('Bering Sea', 'Sea', 'No', 0, 0, 0, 2299, 202),
	array('North Okhotsk Sea', 'Sea', 'No', 0, 0, 0, 1993, 236),
	array('South Okhotsk Sea', 'Sea', 'No', 0, 0, 0, 1976, 311),
	array('Sea of Japan', 'Sea', 'No', 0, 0, 0, 1970, 344),
	array('North Japanese Coast', 'Sea', 'No', 0, 0, 0, 2100, 380),
	array('South Japanese Coast', 'Sea', 'No', 0, 0, 0, 1990, 446),
	array('East China Sea', 'Sea', 'No', 0, 0, 0, 1911, 396),
	array('North Philippine Sea', 'Sea', 'No', 0, 0, 0, 1978, 566),
	array('Mariana Trench', 'Sea', 'No', 0, 0, 0, 2088, 553),
	array('North West Pacific Ocean', 'Sea', 'No', 0, 0, 0, 2294, 622),
	array('West Pacific Ocean', 'Sea', 'No', 0, 0, 0, 2228, 824),
	array('Tasman Sea', 'Sea', 'No', 0, 0, 0, 2177, 1017),
	array('Eastern Southern Ocean', 'Sea', 'No', 0, 0, 0, 2145, 1231),
	array('South East Indian Ocean', 'Sea', 'No', 0, 0, 0, 1865, 1079),
	array('Timor Sea', 'Sea', 'No', 0, 0, 0, 1896, 803),
	array('Arafura Sea', 'Sea', 'No', 0, 0, 0, 2069, 822),
	array('South Philippine Sea', 'Sea', 'No', 0, 0, 0, 2061, 665),
	array('Celebes Sea', 'Sea', 'No', 0, 0, 0, 1930, 675),
	array('South China Sea', 'Sea', 'No', 0, 0, 0, 1897, 610),
	array('Gulf of Thailand', 'Sea', 'No', 0, 0, 0, 1804, 628),
	array('Malacca Strait', 'Sea', 'No', 0, 0, 0, 1767, 643),
	array('Java Sea', 'Sea', 'No', 0, 0, 0, 1859, 730),
	array('North East Indian Ocean', 'Sea', 'No', 0, 0, 0, 1708, 708),
	array('Indian Ocean', 'Sea', 'No', 0, 0, 0, 1576, 918),
	array('South West Indian Ocean', 'Sea', 'No', 0, 0, 0, 1532, 1153),
	array('Mozambique Channel', 'Sea', 'No', 0, 0, 0, 1322, 871),
	array('North West Indian Ocean', 'Sea', 'No', 0, 0, 0, 1447, 693),
	array('Red Sea', 'Sea', 'No', 0, 0, 0, 1317, 533),
	array('Persian Gulf', 'Sea', 'No', 0, 0, 0, 1462, 484),
	array('North Indian Ocean', 'Sea', 'No', 0, 0, 0, 1520, 576),
	array('Bay of Bengal', 'Sea', 'No', 0, 0, 0, 1674, 596)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Alaska (ASK)','Juneau (JUN)','Yes','Yes'),
	array('Alaska (ASK)','North Central Canada (NCC)','Yes','Yes'),
	array('Alaska (ASK)','Beaufort Sea','Yes','No'),
	array('Alaska (ASK)','Alaskan Gulf','Yes','No'),
	array('Alaska (ASK)','Bering Sea','Yes','No'),
	array('Juneau (JUN)','North Central Canada (NCC)','No','Yes'),
	array('Juneau (JUN)','Yukon Territory (YKT)','No','Yes'),
	array('Juneau (JUN)','British Columbia (BRC)','Yes','Yes'),
	array('Juneau (JUN)','Haida Gwaii','Yes','No'),
	array('Juneau (JUN)','Alaskan Gulf','Yes','No'),
	array('North Central Canada (NCC)','Nunavut (NNV)','Yes','Yes'),
	array('North Central Canada (NCC)','Central Canada (CCA)','No','Yes'),
	array('North Central Canada (NCC)','Yukon Territory (YKT)','No','Yes'),
	array('North Central Canada (NCC)','Beaufort Sea','Yes','No'),
	array('Nunavut (NNV)','Quebec (QUE)','Yes','Yes'),
	array('Nunavut (NNV)','Newfoundland (NFL)','No','Yes'),
	array('Nunavut (NNV)','Ontario (ONT)','No','Yes'),
	array('Nunavut (NNV)','Central Canada (CCA)','No','Yes'),
	array('Nunavut (NNV)','Beaufort Sea','Yes','No'),
	array('Nunavut (NNV)','Hudson Bay','Yes','No'),
	array('Nunavut (NNV)','Labrador Sea','Yes','No'),
	array('Quebec (QUE)','Newfoundland (NFL)','Yes','Yes'),
	array('Quebec (QUE)','North Atlantic Ocean','Yes','No'),
	array('Quebec (QUE)','Hudson Bay','Yes','No'),
	array('Quebec (QUE)','Labrador Sea','Yes','No'),
	array('Newfoundland (NFL)','Ontario (ONT)','No','Yes'),
	array('Newfoundland (NFL)','New England (NEG)','Yes','Yes'),
	array('Newfoundland (NFL)','North West Atlantic Ocean','Yes','No'),
	array('Newfoundland (NFL)','North Atlantic Ocean','Yes','No'),
	array('Ontario (ONT)','Central Canada (CCA)','No','Yes'),
	array('Ontario (ONT)','South Central Canada (SCC)','No','Yes'),
	array('Ontario (ONT)','Midwest (MWS)','No','Yes'),
	array('Ontario (ONT)','Northeast US (NES)','No','Yes'),
	array('Ontario (ONT)','New England (NEG)','No','Yes'),
	array('Central Canada (CCA)','Yukon Territory (YKT)','No','Yes'),
	array('Central Canada (CCA)','South Central Canada (SCC)','No','Yes'),
	array('Yukon Territory (YKT)','British Columbia (BRC)','No','Yes'),
	array('Yukon Territory (YKT)','South Central Canada (SCC)','No','Yes'),
	array('British Columbia (BRC)','South Central Canada (SCC)','No','Yes'),
	array('British Columbia (BRC)','Washington (WSH)','Yes','Yes'),
	array('British Columbia (BRC)','Montana (MTA)','No','Yes'),
	array('British Columbia (BRC)','Haida Gwaii','Yes','No'),
	array('South Central Canada (SCC)','Montana (MTA)','No','Yes'),
	array('South Central Canada (SCC)','Midwest (MWS)','No','Yes'),
	array('Washington (WSH)','Montana (MTA)','No','Yes'),
	array('Washington (WSH)','Rocky Mountains (RKM)','No','Yes'),
	array('Washington (WSH)','California (CLF)','Yes','Yes'),
	array('Washington (WSH)','Haida Gwaii','Yes','No'),
	array('Washington (WSH)','Alaskan Gulf','Yes','No'),
	array('Washington (WSH)','Coast of California','Yes','No'),
	array('Montana (MTA)','Midwest (MWS)','No','Yes'),
	array('Montana (MTA)','St. Louis (STL)','No','Yes'),
	array('Montana (MTA)','Rocky Mountains (RKM)','No','Yes'),
	array('Midwest (MWS)','Northeast US (NES)','No','Yes'),
	array('Midwest (MWS)','St. Louis (STL)','No','Yes'),
	array('Northeast US (NES)','New England (NEG)','Yes','Yes'),
	array('Northeast US (NES)','St. Louis (STL)','No','Yes'),
	array('Northeast US (NES)','Florida (FLO)','Yes','Yes'),
	array('Northeast US (NES)','Sargasso Sea','Yes','No'),
	array('New England (NEG)','Sargasso Sea','Yes','No'),
	array('New England (NEG)','North West Atlantic Ocean','Yes','No'),
	array('St. Louis (STL)','Rocky Mountains (RKM)','No','Yes'),
	array('St. Louis (STL)','Texas (TEX)','No','Yes'),
	array('St. Louis (STL)','Florida (FLO)','No','Yes'),
	array('Rocky Mountains (RKM)','California (CLF)','No','Yes'),
	array('Rocky Mountains (RKM)','Nevada (NVD)','No','Yes'),
	array('Rocky Mountains (RKM)','Texas (TEX)','No','Yes'),
	array('California (CLF)','Nevada (NVD)','No','Yes'),
	array('California (CLF)','Baja California (BJA)','Yes','Yes'),
	array('California (CLF)','Coast of California','Yes','No'),
	array('Nevada (NVD)','Texas (TEX)','No','Yes'),
	array('Nevada (NVD)','Coahulia (COA)','No','Yes'),
	array('Nevada (NVD)','Baja California (BJA)','No','Yes'),
	array('Texas (TEX)','Florida (FLO)','Yes','Yes'),
	array('Texas (TEX)','Coahulia (COA)','Yes','Yes'),
	array('Texas (TEX)','Gulf of Mexico','Yes','No'),
	array('Florida (FLO)','Gulf of Mexico','Yes','No'),
	array('Florida (FLO)','Bermuda Triangle','Yes','No'),
	array('Florida (FLO)','Sargasso Sea','Yes','No'),
	array('Cuba (CBA)','West Caribbean','Yes','No'),
	array('Cuba (CBA)','Bermuda Triangle','Yes','No'),
	array('Coahulia (COA)','Chihuahua (CHH)','No','Yes'),
	array('Coahulia (COA)','Baja California (BJA)','No','Yes'),
	array('Coahulia (COA)','Mexico City (MXC)','No','Yes'),
	array('Coahulia (COA)','Yucatan (YCT)','No','Yes'),
	array('Coahulia (COA)','Yucatan (YCT) (North Coast)','Yes','No'),
	array('Coahulia (COA)','Gulf of Mexico','Yes','No'),
	array('Chihuahua (CHH)','Baja California (BJA)','No','Yes'),
	array('Chihuahua (CHH)','Mexico City (MXC)','No','Yes'),
	array('Baja California (BJA)','Mexico City (MXC)','Yes','Yes'),
	array('Baja California (BJA)','Coast of California','Yes','No'),
	array('Baja California (BJA)','Coast of Mexico','Yes','No'),
	array('Mexico City (MXC)','Yucatan (YCT)','No','Yes'),
	array('Mexico City (MXC)','Yucatan (YCT) (South Coast)','Yes','No'),
	array('Mexico City (MXC)','Coast of Mexico','Yes','No'),
	array('Yucatan (YCT)','Central America (CAM)','No','Yes'),
	array('Yucatan (YCT) (North Coast)','Central America (CAM) (North Coast)','Yes','No'),
	array('Yucatan (YCT) (North Coast)','West Caribbean','Yes','No'),
	array('Yucatan (YCT) (North Coast)','Gulf of Mexico','Yes','No'),
	array('Yucatan (YCT) (South Coast)','Central America (CAM) (South Coast)','Yes','No'),
	array('Yucatan (YCT) (South Coast)','Coast of Mexico','Yes','No'),
	array('Yucatan (YCT) (South Coast)','Gulf of Panama','Yes','No'),
	array('Central America (CAM)','Panama (PNM)','No','Yes'),
	array('Central America (CAM) (North Coast)','Panama (PNM)','Yes','No'),
	array('Central America (CAM) (North Coast)','West Caribbean','Yes','No'),
	array('Central America (CAM) (South Coast)','Panama (PNM)','Yes','No'),
	array('Central America (CAM) (South Coast)','Gulf of Panama','Yes','No'),
	array('Panama (PNM)','Colombia (COL)','No','Yes'),
	array('Panama (PNM)','Colombia (COL) (North Coast)','Yes','No'),
	array('Panama (PNM)','Colombia (COL) (West Coast)','Yes','No'),
	array('Panama (PNM)','Gulf of Panama','Yes','No'),
	array('Panama (PNM)','West Caribbean','Yes','No'),
	array('Colombia (COL)','Venezuela (VNZ)','No','Yes'),
	array('Colombia (COL)','Amazon (AMZ)','No','Yes'),
	array('Colombia (COL)','Peru (PRU)','No','Yes'),
	array('Colombia (COL) (North Coast)','Venezuela (VNZ)','Yes','No'),
	array('Colombia (COL) (North Coast)','East Caribbean','Yes','No'),
	array('Colombia (COL) (North Coast)','West Caribbean','Yes','No'),
	array('Colombia (COL) (West Coast)','Peru (PRU)','Yes','No'),
	array('Colombia (COL) (West Coast)','Gulf of Panama','Yes','No'),
	array('Venezuela (VNZ)','French Guiana (FGU)','Yes','Yes'),
	array('Venezuela (VNZ)','Amazon (AMZ)','No','Yes'),
	array('Venezuela (VNZ)','East Caribbean','Yes','No'),
	array('French Guiana (FGU)','Amazon (AMZ)','Yes','Yes'),
	array('French Guiana (FGU)','East Caribbean','Yes','No'),
	array('Amazon (AMZ)','Salvador (SVD)','Yes','Yes'),
	array('Amazon (AMZ)','Peru (PRU)','No','Yes'),
	array('Amazon (AMZ)','Bolivia (BLV)','No','Yes'),
	array('Amazon (AMZ)','Mato Grosso (MGS)','No','Yes'),
	array('Amazon (AMZ)','Southern Mid Atlantic Ocean','Yes','No'),
	array('Amazon (AMZ)','West Atlantic Ocean','Yes','No'),
	array('Amazon (AMZ)','East Caribbean','Yes','No'),
	array('Salvador (SVD)','Mato Grosso (MGS)','No','Yes'),
	array('Salvador (SVD)','Rio de Janeiro (RIO)','Yes','Yes'),
	array('Salvador (SVD)','Southern Mid Atlantic Ocean','Yes','No'),
	array('Peru (PRU)','Bolivia (BLV)','No','Yes'),
	array('Peru (PRU)','Chile (CHI)','Yes','Yes'),
	array('Peru (PRU)','Gulf of Panama','Yes','No'),
	array('Peru (PRU)','South Pacific Ocean','Yes','No'),
	array('Bolivia (BLV)','Mato Grosso (MGS)','No','Yes'),
	array('Bolivia (BLV)','Paraguay (PGY)','No','Yes'),
	array('Bolivia (BLV)','Chile (CHI)','No','Yes'),
	array('Mato Grosso (MGS)','Rio de Janeiro (RIO)','No','Yes'),
	array('Mato Grosso (MGS)','Sao Paulo (SPU)','No','Yes'),
	array('Mato Grosso (MGS)','Paraguay (PGY)','No','Yes'),
	array('Rio de Janeiro (RIO)','Sao Paulo (SPU)','Yes','Yes'),
	array('Rio de Janeiro (RIO)','South West Atlantic Ocean','Yes','No'),
	array('Rio de Janeiro (RIO)','Southern Mid Atlantic Ocean','Yes','No'),
	array('Sao Paulo (SPU)','Paraguay (PGY)','No','Yes'),
	array('Sao Paulo (SPU)','Argentina (AGT)','Yes','Yes'),
	array('Sao Paulo (SPU)','South West Atlantic Ocean','Yes','No'),
	array('Paraguay (PGY)','Chile (CHI)','No','Yes'),
	array('Paraguay (PGY)','Argentina (AGT)','No','Yes'),
	array('Chile (CHI)','Argentina (AGT)','Yes','Yes'),
	array('Chile (CHI)','South Pacific Ocean','Yes','No'),
	array('Chile (CHI)','Drake Passage','Yes','No'),
	array('Chile (CHI)','South West Atlantic Ocean','Yes','No'),
	array('Galapagos','Pacific Ocean','Yes','No'),
	array('Galapagos','Gulf of Panama','Yes','No'),
	array('Galapagos','South Pacific Ocean','Yes','No'),
	array('Argentina (AGT)','South West Atlantic Ocean','Yes','No'),
	array('South Africa (SAF)','Namibia (NMB)','Yes','Yes'),
	array('South Africa (SAF)','Botswana (BSW)','No','Yes'),
	array('South Africa (SAF)','Mozambique (MZB)','Yes','Yes'),
	array('South Africa (SAF)','South African Coast','Yes','No'),
	array('South Africa (SAF)','South East Atlantic Ocean','Yes','No'),
	array('South Africa (SAF)','Mozambique Channel','Yes','No'),
	array('Namibia (NMB)','Botswana (BSW)','No','Yes'),
	array('Namibia (NMB)','Zimbabwe (ZBW)','No','Yes'),
	array('Namibia (NMB)','Angola (AGL)','Yes','Yes'),
	array('Namibia (NMB)','South East Atlantic Ocean','Yes','No'),
	array('Botswana (BSW)','Mozambique (MZB)','No','Yes'),
	array('Botswana (BSW)','Zimbabwe (ZBW)','No','Yes'),
	array('Mozambique (MZB)','Kenya (KNY)','Yes','Yes'),
	array('Mozambique (MZB)','Zimbabwe (ZBW)','No','Yes'),
	array('Mozambique (MZB)','Mozambique Channel','Yes','No'),
	array('Madagascar (MDG)','Indian Ocean','Yes','No'),
	array('Madagascar (MDG)','Mozambique Channel','Yes','No'),
	array('Kenya (KNY)','Zimbabwe (ZBW)','No','Yes'),
	array('Kenya (KNY)','Congo (CNG)','No','Yes'),
	array('Kenya (KNY)','Sudan (SDN)','No','Yes'),
	array('Kenya (KNY)','Ethiopia (ETH)','No','Yes'),
	array('Kenya (KNY)','Somaliland (SOM)','Yes','Yes'),
	array('Kenya (KNY)','Mozambique Channel','Yes','No'),
	array('Zimbabwe (ZBW)','Angola (AGL)','No','Yes'),
	array('Zimbabwe (ZBW)','Congo (CNG)','No','Yes'),
	array('Angola (AGL)','Congo (CNG)','Yes','Yes'),
	array('Angola (AGL)','South East Atlantic Ocean','Yes','No'),
	array('Congo (CNG)','Cameroon (CMR)','Yes','Yes'),
	array('Congo (CNG)','Chad (CHD)','No','Yes'),
	array('Congo (CNG)','Sudan (SDN)','No','Yes'),
	array('Congo (CNG)','South East Atlantic Ocean','Yes','No'),
	array('Congo (CNG)','West African Coast','Yes','No'),
	array('Cameroon (CMR)','Chad (CHD)','No','Yes'),
	array('Cameroon (CMR)','Nigeria (NGR)','Yes','Yes'),
	array('Cameroon (CMR)','West African Coast','Yes','No'),
	array('Chad (CHD)','Nigeria (NGR)','No','Yes'),
	array('Chad (CHD)','Fezzan (FEZ)','No','Yes'),
	array('Chad (CHD)','Tripoli (TPO)','No','Yes'),
	array('Chad (CHD)','Sudan (SDN)','No','Yes'),
	array('Nigeria (NGR)','Ivory Coast (IVC)','Yes','Yes'),
	array('Nigeria (NGR)','West African Coast','Yes','No'),
	array('Ivory Coast (IVC)','West Africa (WAF)','Yes','Yes'),
	array('Ivory Coast (IVC)','West African Coast','Yes','No'),
	array('West Africa (WAF)','Mauritania (MAU)','Yes','Yes'),
	array('West Africa (WAF)','West African Coast','Yes','No'),
	array('West Africa (WAF)','Mid Atlantic Ocean','Yes','No'),
	array('West Africa (WAF)','East Atlantic Ocean','Yes','No'),
	array('Mauritania (MAU)','Morocco (MRC)','Yes','Yes'),
	array('Mauritania (MAU)','East Atlantic Ocean','Yes','No'),
	array('Morocco (MRC)','Gibraltar (GIB)','Yes','Yes'),
	array('Morocco (MRC)','Tunis (TUN)','Yes','Yes'),
	array('Morocco (MRC)','South Tunisia (STU)','No','Yes'),
	array('Morocco (MRC)','East Atlantic Ocean','Yes','No'),
	array('Morocco (MRC)','Iberian Sea','Yes','No'),
	array('Morocco (MRC)','West Mediterranean Sea','Yes','No'),
	array('Gibraltar (GIB)','Portugal (PRG)','Yes','Yes'),
	array('Gibraltar (GIB)','Madrid (MDR)','No','Yes'),
	array('Gibraltar (GIB)','Barcelona (BRC)','Yes','Yes'),
	array('Gibraltar (GIB)','Iberian Sea','Yes','No'),
	array('Gibraltar (GIB)','West Mediterranean Sea','Yes','No'),
	array('Portugal (PRG)','Madrid (MDR)','Yes','Yes'),
	array('Portugal (PRG)','Iberian Sea','Yes','No'),
	array('Madrid (MDR)','Barcelona (BRC)','No','Yes'),
	array('Madrid (MDR)','Bordeaux (BDX)','Yes','Yes'),
	array('Madrid (MDR)','Iberian Sea','Yes','No'),
	array('Madrid (MDR)','Bay of Biscay','Yes','No'),
	array('Barcelona (BRC)','Marseilles (MAR)','Yes','Yes'),
	array('Barcelona (BRC)','Bordeaux (BDX)','No','Yes'),
	array('Barcelona (BRC)','West Mediterranean Sea','Yes','No'),
	array('Marseilles (MAR)','Bordeaux (BDX)','No','Yes'),
	array('Marseilles (MAR)','Paris (PAR)','No','Yes'),
	array('Marseilles (MAR)','Piedmont (PIE)','Yes','Yes'),
	array('Marseilles (MAR)','West Mediterranean Sea','Yes','No'),
	array('Marseilles (MAR)','Tyrrhenian Sea','Yes','No'),
	array('Bordeaux (BDX)','Brittany (BTY)','Yes','Yes'),
	array('Bordeaux (BDX)','Paris (PAR)','No','Yes'),
	array('Bordeaux (BDX)','Bay of Biscay','Yes','No'),
	array('Brittany (BTY)','Paris (PAR)','No','Yes'),
	array('Brittany (BTY)','Picardy (PIC)','Yes','Yes'),
	array('Brittany (BTY)','English Channel','Yes','No'),
	array('Brittany (BTY)','Bay of Biscay','Yes','No'),
	array('Paris (PAR)','Alsace (ALS)','No','Yes'),
	array('Paris (PAR)','Picardy (PIC)','No','Yes'),
	array('Alsace (ALS)','Picardy (PIC)','No','Yes'),
	array('Alsace (ALS)','Belgium (B)','No','Yes'),
	array('Alsace (ALS)','Rhineland (RHI)','No','Yes'),
	array('Picardy (PIC)','Belgium (B)','Yes','Yes'),
	array('Picardy (PIC)','English Channel','Yes','No'),
	array('London (LON)','Wales (WAL)','Yes','Yes'),
	array('London (LON)','Yorkshire (YOR)','Yes','Yes'),
	array('London (LON)','North Sea','Yes','No'),
	array('London (LON)','English Channel','Yes','No'),
	array('Wales (WAL)','Yorkshire (YOR)','Yes','Yes'),
	array('Wales (WAL)','English Channel','Yes','No'),
	array('Wales (WAL)','Irish Sea','Yes','No'),
	array('Yorkshire (YOR)','North Sea','Yes','No'),
	array('Yorkshire (YOR)','Irish Sea','Yes','No'),
	array('Yorkshire (YOR)','North East Atlantic Ocean','Yes','No'),
	array('Ireland (IRE)','Irish Sea','Yes','No'),
	array('Ireland (IRE)','North East Atlantic Ocean','Yes','No'),
	array('Iceland (ICE)','Greenland Sea','Yes','No'),
	array('Iceland (ICE)','North East Atlantic Ocean','Yes','No'),
	array('Nuuk (NUK)','Upper Greenland (UGD)','Yes','Yes'),
	array('Nuuk (NUK)','North Atlantic Ocean','Yes','No'),
	array('Nuuk (NUK)','Greenland Sea','Yes','No'),
	array('Upper Greenland (UGD)','North Atlantic Ocean','Yes','No'),
	array('Upper Greenland (UGD)','Labrador Sea','Yes','No'),
	array('Upper Greenland (UGD)','Greenland Sea','Yes','No'),
	array('Norway (NWY)','Lapland (LPL)','Yes','Yes'),
	array('Norway (NWY)','Sweden (SWE)','Yes','Yes'),
	array('Norway (NWY)','Norwegian Sea','Yes','No'),
	array('Norway (NWY)','North Sea','Yes','No'),
	array('Lapland (LPL)','Finland (FIN)','No','Yes'),
	array('Lapland (LPL)','Sweden (SWE)','No','Yes'),
	array('Lapland (LPL)','Murmansk (MSK)','Yes','Yes'),
	array('Lapland (LPL)','Norwegian Sea','Yes','No'),
	array('Lapland (LPL)','Barents Sea','Yes','No'),
	array('Finland (FIN)','Sweden (SWE)','Yes','Yes'),
	array('Finland (FIN)','Leningrad (LNG)','Yes','Yes'),
	array('Finland (FIN)','Murmansk (MSK)','No','Yes'),
	array('Finland (FIN)','Gulf of Bothnia','Yes','No'),
	array('Sweden (SWE)','Denmark (DEN)','Yes','Yes'),
	array('Sweden (SWE)','North Sea','Yes','No'),
	array('Sweden (SWE)','Baltic Sea','Yes','No'),
	array('Sweden (SWE)','Gulf of Bothnia','Yes','No'),
	array('Denmark (DEN)','Kiel (KIE)','Yes','Yes'),
	array('Denmark (DEN)','North Sea','Yes','No'),
	array('Denmark (DEN)','Baltic Sea','Yes','No'),
	array('Kiel (KIE)','Holland (HO)','Yes','Yes'),
	array('Kiel (KIE)','Rhineland (RHI)','No','Yes'),
	array('Kiel (KIE)','Berlin (BER)','No','Yes'),
	array('Kiel (KIE)','Prussia (PRU)','Yes','Yes'),
	array('Kiel (KIE)','North Sea','Yes','No'),
	array('Kiel (KIE)','Baltic Sea','Yes','No'),
	array('Holland (HO)','Belgium (B)','Yes','Yes'),
	array('Holland (HO)','Rhineland (RHI)','No','Yes'),
	array('Holland (HO)','North Sea','Yes','No'),
	array('Belgium (B)','Rhineland (RHI)','No','Yes'),
	array('Belgium (B)','North Sea','Yes','No'),
	array('Belgium (B)','English Channel','Yes','No'),
	array('Rhineland (RHI)','Munich (MUN)','No','Yes'),
	array('Rhineland (RHI)','Austria (AUS)','No','Yes'),
	array('Rhineland (RHI)','Berlin (BER)','No','Yes'),
	array('Munich (MUN)','Austria (AUS)','No','Yes'),
	array('Munich (MUN)','Berlin (BER)','No','Yes'),
	array('Munich (MUN)','Czechoslovakia (CZE)','No','Yes'),
	array('Austria (AUS)','Czechoslovakia (CZE)','No','Yes'),
	array('Austria (AUS)','Hungary (HNG)','No','Yes'),
	array('Austria (AUS)','Croatia (CRO)','No','Yes'),
	array('Austria (AUS)','Venice (VEN)','No','Yes'),
	array('Berlin (BER)','Prussia (PRU)','No','Yes'),
	array('Berlin (BER)','Silesia (SIL)','No','Yes'),
	array('Berlin (BER)','Czechoslovakia (CZE)','No','Yes'),
	array('Prussia (PRU)','Silesia (SIL)','No','Yes'),
	array('Prussia (PRU)','Warsaw (WAR)','Yes','Yes'),
	array('Prussia (PRU)','Baltic Sea','Yes','No'),
	array('Silesia (SIL)','Czechoslovakia (CZE)','No','Yes'),
	array('Silesia (SIL)','Warsaw (WAR)','No','Yes'),
	array('Czechoslovakia (CZE)','Warsaw (WAR)','No','Yes'),
	array('Czechoslovakia (CZE)','Vilnius (VIL)','No','Yes'),
	array('Czechoslovakia (CZE)','Hungary (HNG)','No','Yes'),
	array('Warsaw (WAR)','Danzig (DAN)','Yes','Yes'),
	array('Warsaw (WAR)','Vilnius (VIL)','No','Yes'),
	array('Warsaw (WAR)','Baltic Sea','Yes','No'),
	array('Danzig (DAN)','Baltic States (BTS)','Yes','Yes'),
	array('Danzig (DAN)','Vilnius (VIL)','No','Yes'),
	array('Danzig (DAN)','Baltic Sea','Yes','No'),
	array('Baltic States (BTS)','Vilnius (VIL)','No','Yes'),
	array('Baltic States (BTS)','Belarus (BLR)','No','Yes'),
	array('Baltic States (BTS)','Leningrad (LNG)','Yes','Yes'),
	array('Baltic States (BTS)','Baltic Sea','Yes','No'),
	array('Baltic States (BTS)','Gulf of Bothnia','Yes','No'),
	array('Vilnius (VIL)','Hungary (HNG)','No','Yes'),
	array('Vilnius (VIL)','Rumania (RUM)','No','Yes'),
	array('Vilnius (VIL)','Ukraine (UKR)','No','Yes'),
	array('Vilnius (VIL)','Belarus (BLR)','No','Yes'),
	array('Hungary (HNG)','Rumania (RUM)','No','Yes'),
	array('Hungary (HNG)','Croatia (CRO)','No','Yes'),
	array('Rumania (RUM)','Bulgaria (BUL)','Yes','Yes'),
	array('Rumania (RUM)','Serbia (SER)','No','Yes'),
	array('Rumania (RUM)','Croatia (CRO)','No','Yes'),
	array('Rumania (RUM)','Ukraine (UKR)','Yes','Yes'),
	array('Rumania (RUM)','West Black Sea (WBS)','Yes','No'),
	array('Bulgaria (BUL)','Serbia (SER)','No','Yes'),
	array('Bulgaria (BUL)','Greece (GRE)','No','Yes'),
	array('Bulgaria (BUL)','Istanbul (IST)','Yes','Yes'),
	array('Bulgaria (BUL)','West Black Sea (WBS)','Yes','No'),
	array('Serbia (SER)','Greece (GRE)','No','Yes'),
	array('Serbia (SER)','Albania (ALB)','No','Yes'),
	array('Serbia (SER)','Croatia (CRO)','No','Yes'),
	array('Greece (GRE)','Albania (ALB)','Yes','Yes'),
	array('Greece (GRE)','Istanbul (IST)','Yes','Yes'),
	array('Greece (GRE)','Ionian Sea','Yes','No'),
	array('Greece (GRE)','Adriatic Sea','Yes','No'),
	array('Greece (GRE)','East Mediterranean Sea','Yes','No'),
	array('Albania (ALB)','Croatia (CRO)','Yes','Yes'),
	array('Albania (ALB)','Adriatic Sea','Yes','No'),
	array('Croatia (CRO)','Venice (VEN)','Yes','Yes'),
	array('Croatia (CRO)','Adriatic Sea','Yes','No'),
	array('Venice (VEN)','Piedmont (PIE)','No','Yes'),
	array('Venice (VEN)','Rome (ROM)','No','Yes'),
	array('Venice (VEN)','Naples (NAP)','Yes','Yes'),
	array('Venice (VEN)','Adriatic Sea','Yes','No'),
	array('Piedmont (PIE)','Rome (ROM)','Yes','Yes'),
	array('Piedmont (PIE)','Tyrrhenian Sea','Yes','No'),
	array('Rome (ROM)','Naples (NAP)','Yes','Yes'),
	array('Rome (ROM)','Tyrrhenian Sea','Yes','No'),
	array('Naples (NAP)','Tyrrhenian Sea','Yes','No'),
	array('Naples (NAP)','Ionian Sea','Yes','No'),
	array('Naples (NAP)','Adriatic Sea','Yes','No'),
	array('Tunis (TUN)','South Tunisia (STU)','No','Yes'),
	array('Tunis (TUN)','Tripoli (TPO)','Yes','Yes'),
	array('Tunis (TUN)','West Mediterranean Sea','Yes','No'),
	array('Tunis (TUN)','Tyrrhenian Sea','Yes','No'),
	array('Tunis (TUN)','Ionian Sea','Yes','No'),
	array('South Tunisia (STU)','Fezzan (FEZ)','No','Yes'),
	array('South Tunisia (STU)','Tripoli (TPO)','No','Yes'),
	array('Fezzan (FEZ)','Tripoli (TPO)','No','Yes'),
	array('Tripoli (TPO)','Benghazi (BGZ)','Yes','Yes'),
	array('Tripoli (TPO)','Aswan (ASW)','No','Yes'),
	array('Tripoli (TPO)','Sudan (SDN)','No','Yes'),
	array('Tripoli (TPO)','Ionian Sea','Yes','No'),
	array('Benghazi (BGZ)','Aswan (ASW)','No','Yes'),
	array('Benghazi (BGZ)','Aswan (ASW) (North Coast)','Yes','No'),
	array('Benghazi (BGZ)','Ionian Sea','Yes','No'),
	array('Benghazi (BGZ)','East Mediterranean Sea','Yes','No'),
	array('Aswan (ASW)','Cairo (CAI)','No','Yes'),
	array('Aswan (ASW)','Sudan (SDN)','No','Yes'),
	array('Aswan (ASW) (North Coast)','Cairo (CAI)','Yes','No'),
	array('Aswan (ASW) (North Coast)','East Mediterranean Sea','Yes','No'),
	array('Aswan (ASW) (East Coast)','Cairo (CAI)','Yes','No'),
	array('Aswan (ASW) (East Coast)','Sudan (SDN)','Yes','No'),
	array('Aswan (ASW) (East Coast)','Red Sea','Yes','No'),
	array('Cairo (CAI)','Saudi Arabia (SDA)','No','Yes'),
	array('Cairo (CAI)','Saudi Arabia (SDA) (West Coast)','Yes','No'),
	array('Cairo (CAI)','Syria (SYR)','Yes','Yes'),
	array('Cairo (CAI)','East Mediterranean Sea','Yes','No'),
	array('Cairo (CAI)','Red Sea','Yes','No'),
	array('Sudan (SDN)','Ethiopia (ETH)','Yes','Yes'),
	array('Sudan (SDN)','Red Sea','Yes','No'),
	array('Ethiopia (ETH)','Somaliland (SOM)','Yes','Yes'),
	array('Ethiopia (ETH)','Red Sea','Yes','No'),
	array('Somaliland (SOM)','Mozambique Channel','Yes','No'),
	array('Somaliland (SOM)','North West Indian Ocean','Yes','No'),
	array('Somaliland (SOM)','Red Sea','Yes','No'),
	array('Oman (OMA)','Saudi Arabia (SDA)','No','Yes'),
	array('Oman (OMA)','Saudi Arabia (SDA) (West Coast)','Yes','No'),
	array('Oman (OMA)','Saudi Arabia (SDA) (East Coast)','Yes','No'),
	array('Oman (OMA)','North West Indian Ocean','Yes','No'),
	array('Oman (OMA)','Red Sea','Yes','No'),
	array('Oman (OMA)','Persian Gulf','Yes','No'),
	array('Oman (OMA)','North Indian Ocean','Yes','No'),
	array('Saudi Arabia (SDA)','Iraq (IRQ)','No','Yes'),
	array('Saudi Arabia (SDA)','Syria (SYR)','No','Yes'),
	array('Saudi Arabia (SDA) (West Coast)','Red Sea','Yes','No'),
	array('Saudi Arabia (SDA) (East Coast)','Iraq (IRQ)','Yes','No'),
	array('Saudi Arabia (SDA) (East Coast)','Persian Gulf','Yes','No'),
	array('Iraq (IRQ)','Syria (SYR)','No','Yes'),
	array('Iraq (IRQ)','Adana (ADA)','No','Yes'),
	array('Iraq (IRQ)','Iran (IRN)','Yes','Yes'),
	array('Iraq (IRQ)','Persian Gulf','Yes','No'),
	array('Syria (SYR)','Adana (ADA)','Yes','Yes'),
	array('Syria (SYR)','East Mediterranean Sea','Yes','No'),
	array('Adana (ADA)','Istanbul (IST)','Yes','Yes'),
	array('Adana (ADA)','Ankara (ANK)','No','Yes'),
	array('Adana (ADA)','Iran (IRN)','No','Yes'),
	array('Adana (ADA)','East Mediterranean Sea','Yes','No'),
	array('Istanbul (IST)','Ankara (ANK)','Yes','Yes'),
	array('Istanbul (IST)','East Mediterranean Sea','Yes','No'),
	array('Istanbul (IST)','South Black Sea (SBS)','Yes','No'),
	array('Istanbul (IST)','West Black Sea (WBS)','Yes','No'),
	array('Ankara (ANK)','Caucasus (CAU)','Yes','Yes'),
	array('Ankara (ANK)','Iran (IRN)','No','Yes'),
	array('Ankara (ANK)','South Black Sea (SBS)','Yes','No'),
	array('Ankara (ANK)','East Black Sea (EBS)','Yes','No'),
	array('Caucasus (CAU)','Ukraine (UKR)','Yes','Yes'),
	array('Caucasus (CAU)','Stalingrad (STA)','No','Yes'),
	array('Caucasus (CAU)','Western Siberia (WSB)','No','Yes'),
	array('Caucasus (CAU)','Iran (IRN)','No','Yes'),
	array('Caucasus (CAU)','East Black Sea (EBS)','Yes','No'),
	array('Ukraine (UKR)','Belarus (BLR)','No','Yes'),
	array('Ukraine (UKR)','Stalingrad (STA)','No','Yes'),
	array('Ukraine (UKR)','East Black Sea (EBS)','Yes','No'),
	array('Ukraine (UKR)','West Black Sea (WBS)','Yes','No'),
	array('Belarus (BLR)','Leningrad (LNG)','No','Yes'),
	array('Belarus (BLR)','Stalingrad (STA)','No','Yes'),
	array('Leningrad (LNG)','Murmansk (MSK)','No','Yes'),
	array('Leningrad (LNG)','Moscow (MOS)','No','Yes'),
	array('Leningrad (LNG)','Stalingrad (STA)','No','Yes'),
	array('Leningrad (LNG)','Gulf of Bothnia','Yes','No'),
	array('Murmansk (MSK)','Moscow (MOS)','No','Yes'),
	array('Murmansk (MSK)','Nenets (NNT)','Yes','Yes'),
	array('Murmansk (MSK)','Barents Sea','Yes','No'),
	array('Murmansk (MSK)','White Sea','Yes','No'),
	array('Moscow (MOS)','Stalingrad (STA)','No','Yes'),
	array('Moscow (MOS)','Western Siberia (WSB)','No','Yes'),
	array('Moscow (MOS)','Nenets (NNT)','No','Yes'),
	array('Stalingrad (STA)','Western Siberia (WSB)','No','Yes'),
	array('Western Siberia (WSB)','Nenets (NNT)','No','Yes'),
	array('Western Siberia (WSB)','Northern Siberia (NSB)','No','Yes'),
	array('Western Siberia (WSB)','Siberia (SIB)','No','Yes'),
	array('Western Siberia (WSB)','Southern Siberia (SSB)','No','Yes'),
	array('Western Siberia (WSB)','Kazakhstan (KAZ)','No','Yes'),
	array('Nenets (NNT)','Northern Siberia (NSB)','Yes','Yes'),
	array('Nenets (NNT)','White Sea','Yes','No'),
	array('Nenets (NNT)','Siberian Sea','Yes','No'),
	array('Northern Siberia (NSB)','Siberia (SIB)','No','Yes'),
	array('Northern Siberia (NSB)','Irkutsk (IRK)','No','Yes'),
	array('Northern Siberia (NSB)','Yakutsk (YKK)','No','Yes'),
	array('Northern Siberia (NSB)','Magadan (MGD)','No','Yes'),
	array('Northern Siberia (NSB)','Magadan (MGD) (North Coast)','Yes','No'),
	array('Northern Siberia (NSB)','Siberian Sea','Yes','No'),
	array('Siberia (SIB)','Southern Siberia (SSB)','No','Yes'),
	array('Siberia (SIB)','Irkutsk (IRK)','No','Yes'),
	array('Siberia (SIB)','Western China (WCH)','No','Yes'),
	array('Southern Siberia (SSB)','Western China (WCH)','No','Yes'),
	array('Southern Siberia (SSB)','Kazakhstan (KAZ)','No','Yes'),
	array('Irkutsk (IRK)','Yakutsk (YKK)','No','Yes'),
	array('Irkutsk (IRK)','Mongolia (MON)','No','Yes'),
	array('Irkutsk (IRK)','Western China (WCH)','No','Yes'),
	array('Yakutsk (YKK)','Magadan (MGD)','No','Yes'),
	array('Yakutsk (YKK)','Vladivostok (VDV)','No','Yes'),
	array('Yakutsk (YKK)','Manchuria (MCH)','No','Yes'),
	array('Yakutsk (YKK)','Mongolia (MON)','No','Yes'),
	array('Magadan (MGD)','Kamchatka (KAM)','No','Yes'),
	array('Magadan (MGD)','Vladivostok (VDV)','No','Yes'),
	array('Magadan (MGD) (North Coast)','Kamchatka (KAM)','Yes','No'),
	array('Magadan (MGD) (North Coast)','Siberian Sea','Yes','No'),
	array('Magadan (MGD) (South Coast)','Kamchatka (KAM)','Yes','No'),
	array('Magadan (MGD) (South Coast)','Vladivostok (VDV)','Yes','No'),
	array('Magadan (MGD) (South Coast)','North Okhotsk Sea','Yes','No'),
	array('Kamchatka (KAM)','Siberian Sea','Yes','No'),
	array('Kamchatka (KAM)','Bering Sea','Yes','No'),
	array('Kamchatka (KAM)','North Okhotsk Sea','Yes','No'),
	array('Vladivostok (VDV)','Manchuria (MCH)','No','Yes'),
	array('Vladivostok (VDV)','Korea (KOR)','Yes','Yes'),
	array('Vladivostok (VDV)','North Okhotsk Sea','Yes','No'),
	array('Vladivostok (VDV)','South Okhotsk Sea','Yes','No'),
	array('Manchuria (MCH)','Mongolia (MON)','No','Yes'),
	array('Manchuria (MCH)','Xi\\\'an (XIA)','No','Yes'),
	array('Manchuria (MCH)','Peking (PEK)','Yes','Yes'),
	array('Manchuria (MCH)','Korea (KOR)','Yes','Yes'),
	array('Manchuria (MCH)','East China Sea','Yes','No'),
	array('Mongolia (MON)','Western China (WCH)','No','Yes'),
	array('Mongolia (MON)','Xi\\\'an (XIA)','No','Yes'),
	array('Western China (WCH)','Kazakhstan (KAZ)','No','Yes'),
	array('Western China (WCH)','Punjab (PJB)','No','Yes'),
	array('Western China (WCH)','Tibet (TIB)','No','Yes'),
	array('Western China (WCH)','Xi\\\'an (XIA)','No','Yes'),
	array('Kazakhstan (KAZ)','Iran (IRN)','No','Yes'),
	array('Kazakhstan (KAZ)','Afghanistan (AFG)','No','Yes'),
	array('Kazakhstan (KAZ)','Punjab (PJB)','No','Yes'),
	array('Iran (IRN)','Afghanistan (AFG)','No','Yes'),
	array('Iran (IRN)','Bombay (BBY)','Yes','Yes'),
	array('Iran (IRN)','Persian Gulf','Yes','No'),
	array('Afghanistan (AFG)','Punjab (PJB)','No','Yes'),
	array('Afghanistan (AFG)','Bombay (BBY)','No','Yes'),
	array('Punjab (PJB)','Bombay (BBY)','No','Yes'),
	array('Punjab (PJB)','Delhi (DHI)','No','Yes'),
	array('Punjab (PJB)','Nepal (NPL)','No','Yes'),
	array('Punjab (PJB)','Tibet (TIB)','No','Yes'),
	array('Bombay (BBY)','South India (SIN)','Yes','Yes'),
	array('Bombay (BBY)','Madras (MDR)','No','Yes'),
	array('Bombay (BBY)','Delhi (DHI)','No','Yes'),
	array('Bombay (BBY)','Persian Gulf','Yes','No'),
	array('Bombay (BBY)','North Indian Ocean','Yes','No'),
	array('South India (SIN)','Madras (MDR)','Yes','Yes'),
	array('South India (SIN)','North Indian Ocean','Yes','No'),
	array('South India (SIN)','Bay of Bengal','Yes','No'),
	array('Madras (MDR)','Delhi (DHI)','No','Yes'),
	array('Madras (MDR)','Bangladesh (BNG)','Yes','Yes'),
	array('Madras (MDR)','Bay of Bengal','Yes','No'),
	array('Delhi (DHI)','Nepal (NPL)','No','Yes'),
	array('Delhi (DHI)','Bangladesh (BNG)','No','Yes'),
	array('Nepal (NPL)','Bangladesh (BNG)','No','Yes'),
	array('Nepal (NPL)','Tibet (TIB)','No','Yes'),
	array('Bangladesh (BNG)','Tibet (TIB)','No','Yes'),
	array('Bangladesh (BNG)','Xi\\\'an (XIA)','No','Yes'),
	array('Bangladesh (BNG)','Burma (BUR)','Yes','Yes'),
	array('Bangladesh (BNG)','Bay of Bengal','Yes','No'),
	array('Tibet (TIB)','Xi\\\'an (XIA)','No','Yes'),
	array('Xi\\\'an (XIA)','Peking (PEK)','No','Yes'),
	array('Xi\\\'an (XIA)','Jiangxi (JXI)','No','Yes'),
	array('Xi\\\'an (XIA)','Yunan (YNN)','No','Yes'),
	array('Xi\\\'an (XIA)','Burma (BUR)','No','Yes'),
	array('Peking (PEK)','Jiangxi (JXI)','No','Yes'),
	array('Peking (PEK)','Shanghai (SGH)','Yes','Yes'),
	array('Peking (PEK)','East China Sea','Yes','No'),
	array('Jiangxi (JXI)','Shanghai (SGH)','No','Yes'),
	array('Jiangxi (JXI)','Yunan (YNN)','No','Yes'),
	array('Shanghai (SGH)','Canton (CTO)','Yes','Yes'),
	array('Shanghai (SGH)','Yunan (YNN)','No','Yes'),
	array('Shanghai (SGH)','East China Sea','Yes','No'),
	array('Shanghai (SGH)','South China Sea','Yes','No'),
	array('Canton (CTO)','Yunan (YNN)','No','Yes'),
	array('Canton (CTO)','Indochina (IDC)','Yes','Yes'),
	array('Canton (CTO)','South China Sea','Yes','No'),
	array('Yunan (YNN)','Indochina (IDC)','No','Yes'),
	array('Yunan (YNN)','Burma (BUR)','No','Yes'),
	array('Indochina (IDC)','Cambodia (CMB)','Yes','Yes'),
	array('Indochina (IDC)','Bangkok (BGK)','No','Yes'),
	array('Indochina (IDC)','Chiang Mai (CHM)','No','Yes'),
	array('Indochina (IDC)','Burma (BUR)','No','Yes'),
	array('Indochina (IDC)','South China Sea','Yes','No'),
	array('Indochina (IDC)','Gulf of Thailand','Yes','No'),
	array('Cambodia (CMB)','Bangkok (BGK)','Yes','Yes'),
	array('Cambodia (CMB)','Gulf of Thailand','Yes','No'),
	array('Bangkok (BGK)','Chiang Mai (CHM)','No','Yes'),
	array('Bangkok (BGK)','Burma (BUR)','No','Yes'),
	array('Bangkok (BGK)','Phuket (PHU)','No','Yes'),
	array('Bangkok (BGK)','Phuket (PHU) (East Coast)','Yes','No'),
	array('Bangkok (BGK)','Gulf of Thailand','Yes','No'),
	array('Chiang Mai (CHM)','Burma (BUR)','No','Yes'),
	array('Burma (BUR)','Phuket (PHU)','No','Yes'),
	array('Burma (BUR)','Phuket (PHU) (West Coast)','Yes','No'),
	array('Burma (BUR)','Malacca Strait','Yes','No'),
	array('Burma (BUR)','Bay of Bengal','Yes','No'),
	array('Phuket (PHU)','Malaysia (MLY)','No','Yes'),
	array('Phuket (PHU) (West Coast)','Malaysia (MLY) (West Coast)','Yes','No'),
	array('Phuket (PHU) (West Coast)','Malacca Strait','Yes','No'),
	array('Phuket (PHU) (East Coast)','Malaysia (MLY) (East Coast)','Yes','No'),
	array('Phuket (PHU) (East Coast)','Gulf of Thailand','Yes','No'),
	array('Malaysia (MLY)','Singapore (SGP)','No','Yes'),
	array('Malaysia (MLY) (East Coast)','Singapore (SGP)','Yes','No'),
	array('Malaysia (MLY) (East Coast)','Gulf of Thailand','Yes','No'),
	array('Malaysia (MLY) (West Coast)','Singapore (SGP)','Yes','No'),
	array('Malaysia (MLY) (West Coast)','Malacca Strait','Yes','No'),
	array('Singapore (SGP)','Gulf of Thailand','Yes','No'),
	array('Singapore (SGP)','Malacca Strait','Yes','No'),
	array('Sumatra (SUM)','Malacca Strait','Yes','No'),
	array('Sumatra (SUM)','Java Sea','Yes','No'),
	array('Sumatra (SUM)','North East Indian Ocean','Yes','No'),
	array('Java (JVA)','Timor Sea','Yes','No'),
	array('Java (JVA)','Java Sea','Yes','No'),
	array('Borneo (BNO)','Brunei (BNI)','Yes','Yes'),
	array('Borneo (BNO)','Celebes Sea','Yes','No'),
	array('Borneo (BNO)','South China Sea','Yes','No'),
	array('Borneo (BNO)','Gulf of Thailand','Yes','No'),
	array('Borneo (BNO)','Malacca Strait','Yes','No'),
	array('Borneo (BNO)','Java Sea','Yes','No'),
	array('Brunei (BNI)','South China Sea','Yes','No'),
	array('Brunei (BNI)','Gulf of Thailand','Yes','No'),
	array('Sulawesi (SLW)','Timor Sea','Yes','No'),
	array('Sulawesi (SLW)','South Philippine Sea','Yes','No'),
	array('Sulawesi (SLW)','Celebes Sea','Yes','No'),
	array('Kimberley (KIM)','Perth (PER)','Yes','Yes'),
	array('Kimberley (KIM)','Outback (OUT)','No','Yes'),
	array('Kimberley (KIM)','Northeast Australia','Yes','Yes'),
	array('Kimberley (KIM)','Arafura Sea','Yes','No'),
	array('Perth (PER)','Outback (OUT)','Yes','Yes'),
	array('Perth (PER)','South East Indian Ocean','Yes','No'),
	array('Perth (PER)','Timor Sea','Yes','No'),
	array('Perth (PER)','Arafura Sea','Yes','No'),
	array('Outback (OUT)','Northeast Australia','No','Yes'),
	array('Outback (OUT)','Sydney (SYD)','No','Yes'),
	array('Outback (OUT)','Victoria (VCT)','Yes','Yes'),
	array('Outback (OUT)','South East Indian Ocean','Yes','No'),
	array('Northeast Australia','Sydney (SYD)','Yes','Yes'),
	array('Northeast Australia','West Pacific Ocean','Yes','No'),
	array('Northeast Australia','Tasman Sea','Yes','No'),
	array('Northeast Australia','Arafura Sea','Yes','No'),
	array('Sydney (SYD)','Victoria (VCT)','Yes','Yes'),
	array('Sydney (SYD)','Tasman Sea','Yes','No'),
	array('Victoria (VCT)','Tasman Sea','Yes','No'),
	array('Victoria (VCT)','South East Indian Ocean','Yes','No'),
	array('Queenstown (QTW)','Tasman Sea','Yes','No'),
	array('Queenstown (QTW)','Eastern Southern Ocean','Yes','No'),
	array('Wellington (WEL)','Tasman Sea','Yes','No'),
	array('Wellington (WEL)','Eastern Southern Ocean','Yes','No'),
	array('New Guinea (NGU)','West Pacific Ocean','Yes','No'),
	array('New Guinea (NGU)','Timor Sea','Yes','No'),
	array('New Guinea (NGU)','Arafura Sea','Yes','No'),
	array('New Guinea (NGU)','South Philippine Sea','Yes','No'),
	array('Philippines (PLP)','Manila (MAN)','Yes','Yes'),
	array('Philippines (PLP)','South Philippine Sea','Yes','No'),
	array('Philippines (PLP)','Celebes Sea','Yes','No'),
	array('Philippines (PLP)','South China Sea','Yes','No'),
	array('Manila (MAN)','North Philippine Sea','Yes','No'),
	array('Manila (MAN)','South Philippine Sea','Yes','No'),
	array('Manila (MAN)','South China Sea','Yes','No'),
	array('Taiwan (TAI)','East China Sea','Yes','No'),
	array('Taiwan (TAI)','North Philippine Sea','Yes','No'),
	array('Taiwan (TAI)','South China Sea','Yes','No'),
	array('Okinawa','South Japanese Coast','Yes','No'),
	array('Okinawa','East China Sea','Yes','No'),
	array('Okinawa','North Philippine Sea','Yes','No'),
	array('Okinawa','Mariana Trench','Yes','No'),
	array('Korea (KOR)','South Okhotsk Sea','Yes','No'),
	array('Korea (KOR)','Sea of Japan','Yes','No'),
	array('Korea (KOR)','East China Sea','Yes','No'),
	array('Tokyo (TKY)','Sea of Japan','Yes','No'),
	array('Tokyo (TKY)','North Japanese Coast','Yes','No'),
	array('Tokyo (TKY)','South Japanese Coast','Yes','No'),
	array('Tokyo (TKY)','East China Sea','Yes','No'),
	array('Hokkaido (HOK)','South Okhotsk Sea','Yes','No'),
	array('Hokkaido (HOK)','Sea of Japan','Yes','No'),
	array('Hokkaido (HOK)','North Japanese Coast','Yes','No'),
	array('Wake Island','Midway','Yes','No'),
	array('Wake Island','Hawaii','Yes','No'),
	array('Wake Island','North Japanese Coast','Yes','No'),
	array('Wake Island','South Japanese Coast','Yes','No'),
	array('Wake Island','Mariana Trench','Yes','No'),
	array('Wake Island','North West Pacific Ocean','Yes','No'),
	array('Midway','Hawaii','Yes','No'),
	array('Midway','North Pacific Ocean','Yes','No'),
	array('Midway','Bering Sea','Yes','No'),
	array('Midway','North Okhotsk Sea','Yes','No'),
	array('Midway','South Okhotsk Sea','Yes','No'),
	array('Midway','North Japanese Coast','Yes','No'),
	array('Hawaii','North Pacific Ocean','Yes','No'),
	array('Hawaii','North West Pacific Ocean','Yes','No'),
	array('Arctic Circle','Beaufort Sea','Yes','No'),
	array('Arctic Circle','Labrador Sea','Yes','No'),
	array('Arctic Circle','Siberian Sea','Yes','No'),
	array('Arctic Circle','Bering Sea','Yes','No'),
	array('Beaufort Sea','Labrador Sea','Yes','No'),
	array('Beaufort Sea','Bering Sea','Yes','No'),
	array('Haida Gwaii','Alaskan Gulf','Yes','No'),
	array('Alaskan Gulf','Coast of California','Yes','No'),
	array('Alaskan Gulf','North Pacific Ocean','Yes','No'),
	array('Alaskan Gulf','Bering Sea','Yes','No'),
	array('Coast of California','North Pacific Ocean','Yes','No'),
	array('Coast of California','Coast of Mexico','Yes','No'),
	array('North Pacific Ocean','Coast of Mexico','Yes','No'),
	array('North Pacific Ocean','Pacific Ocean','Yes','No'),
	array('North Pacific Ocean','Bering Sea','Yes','No'),
	array('North Pacific Ocean','North West Pacific Ocean','Yes','No'),
	array('Coast of Mexico','Pacific Ocean','Yes','No'),
	array('Coast of Mexico','Gulf of Panama','Yes','No'),
	array('Pacific Ocean','Gulf of Panama','Yes','No'),
	array('Pacific Ocean','South Pacific Ocean','Yes','No'),
	array('Pacific Ocean','West Southern Ocean','Yes','No'),
	array('Pacific Ocean','North West Pacific Ocean','Yes','No'),
	array('Pacific Ocean','West Pacific Ocean','Yes','No'),
	array('Gulf of Panama','South Pacific Ocean','Yes','No'),
	array('South Pacific Ocean','West Southern Ocean','Yes','No'),
	array('South Pacific Ocean','Drake Passage','Yes','No'),
	array('West Southern Ocean','Drake Passage','Yes','No'),
	array('West Southern Ocean','West Pacific Ocean','Yes','No'),
	array('West Southern Ocean','Tasman Sea','Yes','No'),
	array('West Southern Ocean','Eastern Southern Ocean','Yes','No'),
	array('Drake Passage','Southern Ocean','Yes','No'),
	array('Drake Passage','South West Atlantic Ocean','Yes','No'),
	array('Southern Ocean','South African Coast','Yes','No'),
	array('Southern Ocean','South Atlantic Ocean','Yes','No'),
	array('Southern Ocean','South West Atlantic Ocean','Yes','No'),
	array('Southern Ocean','Eastern Southern Ocean','Yes','No'),
	array('Southern Ocean','South East Indian Ocean','Yes','No'),
	array('Southern Ocean','South West Indian Ocean','Yes','No'),
	array('South African Coast','South Atlantic Ocean','Yes','No'),
	array('South African Coast','South East Atlantic Ocean','Yes','No'),
	array('South African Coast','South West Indian Ocean','Yes','No'),
	array('South African Coast','Mozambique Channel','Yes','No'),
	array('South Atlantic Ocean','South West Atlantic Ocean','Yes','No'),
	array('South Atlantic Ocean','Southern Mid Atlantic Ocean','Yes','No'),
	array('South Atlantic Ocean','South East Atlantic Ocean','Yes','No'),
	array('South West Atlantic Ocean','Southern Mid Atlantic Ocean','Yes','No'),
	array('Southern Mid Atlantic Ocean','South East Atlantic Ocean','Yes','No'),
	array('Southern Mid Atlantic Ocean','West African Coast','Yes','No'),
	array('Southern Mid Atlantic Ocean','Mid Atlantic Ocean','Yes','No'),
	array('Southern Mid Atlantic Ocean','West Atlantic Ocean','Yes','No'),
	array('South East Atlantic Ocean','West African Coast','Yes','No'),
	array('West African Coast','Mid Atlantic Ocean','Yes','No'),
	array('Mid Atlantic Ocean','West Atlantic Ocean','Yes','No'),
	array('Mid Atlantic Ocean','Northern Mid Atlantic Ocean','Yes','No'),
	array('Mid Atlantic Ocean','East Atlantic Ocean','Yes','No'),
	array('West Atlantic Ocean','East Caribbean','Yes','No'),
	array('West Atlantic Ocean','Bermuda Triangle','Yes','No'),
	array('West Atlantic Ocean','Sargasso Sea','Yes','No'),
	array('West Atlantic Ocean','Northern Mid Atlantic Ocean','Yes','No'),
	array('East Caribbean','West Caribbean','Yes','No'),
	array('East Caribbean','Bermuda Triangle','Yes','No'),
	array('West Caribbean','Gulf of Mexico','Yes','No'),
	array('West Caribbean','Bermuda Triangle','Yes','No'),
	array('Gulf of Mexico','Bermuda Triangle','Yes','No'),
	array('Bermuda Triangle','Sargasso Sea','Yes','No'),
	array('Sargasso Sea','Northern Mid Atlantic Ocean','Yes','No'),
	array('Sargasso Sea','North West Atlantic Ocean','Yes','No'),
	array('Northern Mid Atlantic Ocean','East Atlantic Ocean','Yes','No'),
	array('Northern Mid Atlantic Ocean','North West Atlantic Ocean','Yes','No'),
	array('Northern Mid Atlantic Ocean','North Atlantic Ocean','Yes','No'),
	array('Northern Mid Atlantic Ocean','Iberian Sea','Yes','No'),
	array('East Atlantic Ocean','Iberian Sea','Yes','No'),
	array('North West Atlantic Ocean','North Atlantic Ocean','Yes','No'),
	array('North Atlantic Ocean','Labrador Sea','Yes','No'),
	array('North Atlantic Ocean','Greenland Sea','Yes','No'),
	array('North Atlantic Ocean','North East Atlantic Ocean','Yes','No'),
	array('North Atlantic Ocean','Iberian Sea','Yes','No'),
	array('Hudson Bay','Labrador Sea','Yes','No'),
	array('Greenland Sea','Norwegian Sea','Yes','No'),
	array('Greenland Sea','North East Atlantic Ocean','Yes','No'),
	array('Greenland Sea','Barents Sea','Yes','No'),
	array('Greenland Sea','Kara Sea','Yes','No'),
	array('Norwegian Sea','North Sea','Yes','No'),
	array('Norwegian Sea','North East Atlantic Ocean','Yes','No'),
	array('Norwegian Sea','Barents Sea','Yes','No'),
	array('North Sea','English Channel','Yes','No'),
	array('North Sea','North East Atlantic Ocean','Yes','No'),
	array('English Channel','Irish Sea','Yes','No'),
	array('English Channel','Bay of Biscay','Yes','No'),
	array('Irish Sea','North East Atlantic Ocean','Yes','No'),
	array('Irish Sea','Bay of Biscay','Yes','No'),
	array('North East Atlantic Ocean','Iberian Sea','Yes','No'),
	array('North East Atlantic Ocean','Bay of Biscay','Yes','No'),
	array('Iberian Sea','Bay of Biscay','Yes','No'),
	array('Iberian Sea','West Mediterranean Sea','Yes','No'),
	array('West Mediterranean Sea','Tyrrhenian Sea','Yes','No'),
	array('Tyrrhenian Sea','Ionian Sea','Yes','No'),
	array('Ionian Sea','Adriatic Sea','Yes','No'),
	array('Ionian Sea','East Mediterranean Sea','Yes','No'),
	array('South Black Sea (SBS)','East Black Sea (EBS)','Yes','No'),
	array('South Black Sea (SBS)','West Black Sea (WBS)','Yes','No'),
	array('East Black Sea (EBS)','West Black Sea (WBS)','Yes','No'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No'),
	array('Barents Sea','White Sea','Yes','No'),
	array('Barents Sea','Kara Sea','Yes','No'),
	array('White Sea','Kara Sea','Yes','No'),
	array('White Sea','Siberian Sea','Yes','No'),
	array('Kara Sea','Siberian Sea','Yes','No'),
	array('Siberian Sea','Bering Sea','Yes','No'),
	array('Bering Sea','North Okhotsk Sea','Yes','No'),
	array('North Okhotsk Sea','South Okhotsk Sea','Yes','No'),
	array('South Okhotsk Sea','Sea of Japan','Yes','No'),
	array('South Okhotsk Sea','North Japanese Coast','Yes','No'),
	array('Sea of Japan','North Japanese Coast','Yes','No'),
	array('Sea of Japan','East China Sea','Yes','No'),
	array('North Japanese Coast','South Japanese Coast','Yes','No'),
	array('South Japanese Coast','East China Sea','Yes','No'),
	array('South Japanese Coast','Mariana Trench','Yes','No'),
	array('East China Sea','North Philippine Sea','Yes','No'),
	array('East China Sea','South China Sea','Yes','No'),
	array('North Philippine Sea','Mariana Trench','Yes','No'),
	array('North Philippine Sea','South Philippine Sea','Yes','No'),
	array('North Philippine Sea','South China Sea','Yes','No'),
	array('Mariana Trench','North West Pacific Ocean','Yes','No'),
	array('Mariana Trench','South Philippine Sea','Yes','No'),
	array('North West Pacific Ocean','West Pacific Ocean','Yes','No'),
	array('North West Pacific Ocean','South Philippine Sea','Yes','No'),
	array('West Pacific Ocean','Tasman Sea','Yes','No'),
	array('West Pacific Ocean','Arafura Sea','Yes','No'),
	array('West Pacific Ocean','South Philippine Sea','Yes','No'),
	array('Tasman Sea','Eastern Southern Ocean','Yes','No'),
	array('Tasman Sea','South East Indian Ocean','Yes','No'),
	array('Eastern Southern Ocean','South East Indian Ocean','Yes','No'),
	array('South East Indian Ocean','Timor Sea','Yes','No'),
	array('South East Indian Ocean','North East Indian Ocean','Yes','No'),
	array('South East Indian Ocean','Indian Ocean','Yes','No'),
	array('South East Indian Ocean','South West Indian Ocean','Yes','No'),
	array('Timor Sea','Arafura Sea','Yes','No'),
	array('Timor Sea','South Philippine Sea','Yes','No'),
	array('Timor Sea','Celebes Sea','Yes','No'),
	array('Timor Sea','Java Sea','Yes','No'),
	array('Timor Sea','North East Indian Ocean','Yes','No'),
	array('South Philippine Sea','Celebes Sea','Yes','No'),
	array('Celebes Sea','South China Sea','Yes','No'),
	array('Celebes Sea','Java Sea','Yes','No'),
	array('South China Sea','Gulf of Thailand','Yes','No'),
	array('Gulf of Thailand','Malacca Strait','Yes','No'),
	array('Malacca Strait','Java Sea','Yes','No'),
	array('Malacca Strait','North East Indian Ocean','Yes','No'),
	array('Malacca Strait','Bay of Bengal','Yes','No'),
	array('Java Sea','North East Indian Ocean','Yes','No'),
	array('North East Indian Ocean','Indian Ocean','Yes','No'),
	array('North East Indian Ocean','North Indian Ocean','Yes','No'),
	array('North East Indian Ocean','Bay of Bengal','Yes','No'),
	array('Indian Ocean','South West Indian Ocean','Yes','No'),
	array('Indian Ocean','Mozambique Channel','Yes','No'),
	array('Indian Ocean','North West Indian Ocean','Yes','No'),
	array('Indian Ocean','North Indian Ocean','Yes','No'),
	array('South West Indian Ocean','Mozambique Channel','Yes','No'),
	array('Mozambique Channel','North West Indian Ocean','Yes','No'),
	array('North West Indian Ocean','Red Sea','Yes','No'),
	array('North West Indian Ocean','North Indian Ocean','Yes','No'),
	array('Persian Gulf','North Indian Ocean','Yes','No'),
	array('North Indian Ocean','Bay of Bengal','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

// Custom footer not changed by edit tool

// Just create the database as usual:
InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

// Copy the smallmap-sample to the cache-directory to avoid a screwed variantpage (there is no smallmap available)
if (!file_exists('variants/'.$this->name.'/cache/sampleMap.png'))
	copy ('variants/'.$this->name.'/resources/sampleMap.png','variants/'.$this->name.'/cache/sampleMap.png');

?>
