<?php
// This is file installs the map data for the ClassicEgypt variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Clyde', 'Coast', 'No', 1, 362, 306, 157, 120),
	array('Edinburgh', 'Coast', 'Yes', 1, 413, 316, 175, 109),
	array('Liverpool', 'Coast', 'Yes', 1, 378, 399, 166, 140),
	array('Yorkshire', 'Coast', 'No', 1, 416, 431, 184, 150),
	array('Wales', 'Coast', 'No', 1, 351, 500, 154, 179),
	array('London', 'Coast', 'Yes', 1, 422, 497, 176, 185),
	array('Portugal', 'Coast', 'Yes', 0, 144, 857, 65, 292),
	array('Spain', 'Coast', 'Yes', 0, 257, 876, 110, 307),
	array('North Africa', 'Coast', 'No', 0, 243, 1158, 111, 399),
	array('Tunis', 'Coast', 'Yes', 0, 467, 1136, 210, 413),
	array('Naples', 'Coast', 'Yes', 3, 663, 1067, 298, 357),
	array('Rome', 'Coast', 'Yes', 3, 611, 935, 272, 330),
	array('Tuscany', 'Coast', 'No', 3, 576, 872, 256, 312),
	array('Piedmont', 'Coast', 'No', 3, 525, 777, 228, 276),
	array('Venice', 'Coast', 'Yes', 3, 584, 824, 258, 292),
	array('Apulia', 'Coast', 'No', 3, 693, 984, 295, 335),
	array('Greece', 'Coast', 'Yes', 0, 837, 1079, 365, 375),
	array('Albania', 'Coast', 'No', 0, 783, 956, 343, 341),
	array('Serbia', 'Land', 'Yes', 0, 816, 930, 357, 324),
	array('Bulgaria', 'Coast', 'Yes', 0, 900, 888, 394, 318),
	array('Rumania', 'Coast', 'Yes', 0, 956, 809, 412, 272),
	array('Constantinople', 'Coast', 'Yes', 6, 968, 932, 433, 345),
	array('Smyrna', 'Coast', 'Yes', 6, 1013, 1047, 480, 363),
	array('Ankara', 'Coast', 'Yes', 6, 1127, 909, 485, 320),
	array('Armenia', 'Coast', 'No', 6, 1253, 918, 572, 323),
	array('Syria', 'Coast', 'No', 6, 1250, 1091, 559, 370),
	array('Sevastopol', 'Coast', 'Yes', 7, 1112, 668, 485, 248),
	array('Ukraine', 'Land', 'No', 7, 957, 632, 418, 220),
	array('Warsaw', 'Land', 'Yes', 7, 773, 621, 358, 209),
	array('Livonia', 'Coast', 'No', 7, 864, 476, 374, 168),
	array('Moscow', 'Land', 'Yes', 7, 1004, 500, 490, 160),
	array('St. Petersburg', 'Coast', 'Yes', 7, 983, 363, 445, 97),
	array('Finland', 'Coast', 'No', 7, 846, 252, 369, 109),
	array('Sweden', 'Coast', 'Yes', 0, 696, 413, 307, 103),
	array('Norway', 'Coast', 'Yes', 0, 620, 272, 265, 113),
	array('Denmark', 'Coast', 'Yes', 0, 604, 442, 264, 150),
	array('Kiel', 'Coast', 'Yes', 4, 587, 575, 253, 193),
	array('Berlin', 'Coast', 'Yes', 4, 663, 554, 287, 189),
	array('Prussia', 'Coast', 'No', 4, 728, 569, 319, 202),
	array('Silesia', 'Land', 'No', 4, 714, 629, 315, 222),
	array('Munich', 'Land', 'Yes', 4, 558, 657, 252, 229),
	array('Ruhr', 'Land', 'No', 4, 534, 603, 227, 221),
	array('Holland', 'Coast', 'Yes', 0, 534, 531, 234, 185),
	array('Belgium', 'Coast', 'Yes', 0, 468, 560, 215, 205),
	array('Picardy', 'Coast', 'No', 2, 425, 597, 182, 213),
	array('Brest', 'Coast', 'Yes', 2, 344, 663, 153, 240),
	array('Paris', 'Land', 'Yes', 2, 402, 693, 176, 233),
	array('Burgundy', 'Land', 'No', 2, 467, 696, 204, 243),
	array('Marseilles', 'Coast', 'Yes', 2, 387, 821, 199, 275),
	array('Gascony', 'Coast', 'No', 2, 348, 762, 154, 265),
	array('Barents Sea', 'Sea', 'No', 0, 929, 53, 427, 15),
	array('Norwegian Sea', 'Sea', 'No', 0, 513, 143, 240, 31),
	array('North Sea', 'Sea', 'No', 0, 486, 395, 216, 125),
	array('Skagerrack', 'Sea', 'No', 0, 645, 422, 284, 146),
	array('Heligoland Bight', 'Sea', 'No', 0, 543, 453, 241, 159),
	array('Baltic Sea', 'Sea', 'No', 0, 768, 483, 338, 177),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 779, 377, 345, 141),
	array('North Atlantic Ocean', 'Sea', 'No', 0, 145, 250, 78, 92),
	array('Irish Sea', 'Sea', 'No', 0, 258, 497, 118, 171),
	array('English Channel', 'Sea', 'No', 0, 311, 570, 145, 205),
	array('Mid-Atlantic Ocean', 'Sea', 'No', 0, 113, 608, 60, 251),
	array('Western Mediterranean', 'Sea', 'No', 0, 414, 1004, 186, 350),
	array('Gulf of Lyon', 'Sea', 'No', 0, 449, 896, 208, 322),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 551, 986, 248, 343),
	array('Ionian Sea', 'Sea', 'No', 0, 714, 1125, 325, 379),
	array('Adriatic Sea', 'Sea', 'No', 0, 672, 906, 316, 329),
	array('Aegean Sea', 'Sea', 'No', 0, 909, 1083, 395, 363),
	array('Eastern Mediterranean', 'Sea', 'No', 0, 1011, 1148, 434, 412),
	array('Black Sea', 'Sea', 'No', 0, 1029, 852, 457, 300),
	array('Tyrolia', 'Land', 'No', 5, 593, 747, 282, 252),
	array('Bohemia', 'Land', 'No', 5, 644, 666, 298, 227),
	array('Vienna', 'Land', 'Yes', 5, 705, 702, 314, 246),
	array('Trieste', 'Coast', 'Yes', 5, 719, 836, 308, 288),
	array('Budapest', 'Land', 'Yes', 5, 798, 800, 350, 260),
	array('Galicia', 'Land', 'No', 5, 852, 678, 378, 240),
	array('Spain (North Coast)', 'Coast', 'No', 0, 210, 810, 90, 273),
	array('Spain (South Coast)', 'Coast', 'No', 0, 251, 968, 106, 345),
	array('St. Petersburg (North Coast)', 'Coast', 'No', 7, 984, 242, 448, 59),
	array('St. Petersburg (South Coast)', 'Coast', 'No', 7, 912, 384, 397, 130),
	array('Bulgaria (North Coast)', 'Coast', 'No', 0, 956, 872, 424, 304),
	array('Bulgaria (South Coast)', 'Coast', 'No', 0, 912, 947, 397, 332),
	array('Libya', 'Coast', 'No', 0, 645, 1296, 289, 456),
	array('Egypt', 'Coast', 'Yes', 0, 1037, 1292, 449, 458),
	array('Suez', 'Coast', 'No', 0, 1158, 1248, 506, 433),
	array('Egypt (North Coast)', 'Coast', 'No', 0, 1038, 1272, 450, 449),
	array('Egypt (East Coast)', 'Coast', 'No', 0, 1131, 1341, 491, 472),
	array('Syria (West Coast)', 'Coast', 'No', 0, 1203, 1131, 530, 398),
	array('Syria (South Coast)', 'Coast', 'No', 0, 1224, 1305, 549, 478),
	array('Red Sea', 'Sea', 'No', 0, 1185, 1382, 517, 494)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Clyde','Edinburgh','Yes','Yes'),
	array('Clyde','Liverpool','Yes','Yes'),
	array('Clyde','Norwegian Sea','Yes','No'),
	array('Clyde','North Atlantic Ocean','Yes','No'),
	array('Edinburgh','Liverpool','No','Yes'),
	array('Edinburgh','Yorkshire','Yes','Yes'),
	array('Edinburgh','Norwegian Sea','Yes','No'),
	array('Edinburgh','North Sea','Yes','No'),
	array('Liverpool','Yorkshire','No','Yes'),
	array('Liverpool','Wales','Yes','Yes'),
	array('Liverpool','North Atlantic Ocean','Yes','No'),
	array('Liverpool','Irish Sea','Yes','No'),
	array('Yorkshire','Wales','No','Yes'),
	array('Yorkshire','London','Yes','Yes'),
	array('Yorkshire','North Sea','Yes','No'),
	array('Wales','London','Yes','Yes'),
	array('Wales','Irish Sea','Yes','No'),
	array('Wales','English Channel','Yes','No'),
	array('London','North Sea','Yes','No'),
	array('London','English Channel','Yes','No'),
	array('Portugal','Spain','No','Yes'),
	array('Portugal','Mid-Atlantic Ocean','Yes','No'),
	array('Portugal','Spain (North Coast)','Yes','No'),
	array('Portugal','Spain (South Coast)','Yes','No'),
	array('Spain','Marseilles','No','Yes'),
	array('Spain','Gascony','No','Yes'),
	array('North Africa','Tunis','Yes','Yes'),
	array('North Africa','Mid-Atlantic Ocean','Yes','No'),
	array('North Africa','Western Mediterranean','Yes','No'),
	array('North Africa','Libya','No','Yes'),
	array('Tunis','Western Mediterranean','Yes','No'),
	array('Tunis','Tyrrhenian Sea','Yes','No'),
	array('Tunis','Ionian Sea','Yes','No'),
	array('Tunis','Libya','Yes','Yes'),
	array('Naples','Rome','Yes','Yes'),
	array('Naples','Apulia','Yes','Yes'),
	array('Naples','Tyrrhenian Sea','Yes','No'),
	array('Naples','Ionian Sea','Yes','No'),
	array('Rome','Tuscany','Yes','Yes'),
	array('Rome','Venice','No','Yes'),
	array('Rome','Apulia','No','Yes'),
	array('Rome','Tyrrhenian Sea','Yes','No'),
	array('Tuscany','Piedmont','Yes','Yes'),
	array('Tuscany','Venice','No','Yes'),
	array('Tuscany','Gulf of Lyon','Yes','No'),
	array('Tuscany','Tyrrhenian Sea','Yes','No'),
	array('Piedmont','Venice','No','Yes'),
	array('Piedmont','Marseilles','Yes','Yes'),
	array('Piedmont','Gulf of Lyon','Yes','No'),
	array('Piedmont','Tyrolia','No','Yes'),
	array('Venice','Apulia','Yes','Yes'),
	array('Venice','Adriatic Sea','Yes','No'),
	array('Venice','Tyrolia','No','Yes'),
	array('Venice','Trieste','Yes','Yes'),
	array('Apulia','Ionian Sea','Yes','No'),
	array('Apulia','Adriatic Sea','Yes','No'),
	array('Greece','Albania','Yes','Yes'),
	array('Greece','Serbia','No','Yes'),
	array('Greece','Bulgaria','No','Yes'),
	array('Greece','Ionian Sea','Yes','No'),
	array('Greece','Aegean Sea','Yes','No'),
	array('Greece','Bulgaria (South Coast)','Yes','No'),
	array('Albania','Serbia','No','Yes'),
	array('Albania','Ionian Sea','Yes','No'),
	array('Albania','Adriatic Sea','Yes','No'),
	array('Albania','Trieste','Yes','Yes'),
	array('Serbia','Bulgaria','No','Yes'),
	array('Serbia','Rumania','No','Yes'),
	array('Serbia','Trieste','No','Yes'),
	array('Serbia','Budapest','No','Yes'),
	array('Bulgaria','Rumania','No','Yes'),
	array('Bulgaria','Constantinople','No','Yes'),
	array('Rumania','Sevastopol','Yes','Yes'),
	array('Rumania','Ukraine','No','Yes'),
	array('Rumania','Black Sea','Yes','No'),
	array('Rumania','Budapest','No','Yes'),
	array('Rumania','Galicia','No','Yes'),
	array('Rumania','Bulgaria (North Coast)','Yes','No'),
	array('Constantinople','Smyrna','Yes','Yes'),
	array('Constantinople','Ankara','Yes','Yes'),
	array('Constantinople','Aegean Sea','Yes','No'),
	array('Constantinople','Black Sea','Yes','No'),
	array('Constantinople','Bulgaria (North Coast)','Yes','No'),
	array('Constantinople','Bulgaria (South Coast)','Yes','No'),
	array('Smyrna','Ankara','No','Yes'),
	array('Smyrna','Armenia','No','Yes'),
	array('Smyrna','Syria','No','Yes'),
	array('Smyrna','Aegean Sea','Yes','No'),
	array('Smyrna','Eastern Mediterranean','Yes','No'),
	array('Smyrna','Syria (West Coast)','Yes','No'),
	array('Ankara','Armenia','Yes','Yes'),
	array('Ankara','Black Sea','Yes','No'),
	array('Armenia','Syria','No','Yes'),
	array('Armenia','Sevastopol','Yes','Yes'),
	array('Armenia','Black Sea','Yes','No'),
	array('Syria','Suez','No','Yes'),
	array('Sevastopol','Ukraine','No','Yes'),
	array('Sevastopol','Moscow','No','Yes'),
	array('Sevastopol','Black Sea','Yes','No'),
	array('Ukraine','Warsaw','No','Yes'),
	array('Ukraine','Moscow','No','Yes'),
	array('Ukraine','Galicia','No','Yes'),
	array('Warsaw','Livonia','No','Yes'),
	array('Warsaw','Moscow','No','Yes'),
	array('Warsaw','Prussia','No','Yes'),
	array('Warsaw','Silesia','No','Yes'),
	array('Warsaw','Galicia','No','Yes'),
	array('Livonia','Moscow','No','Yes'),
	array('Livonia','St. Petersburg','No','Yes'),
	array('Livonia','Prussia','Yes','Yes'),
	array('Livonia','Baltic Sea','Yes','No'),
	array('Livonia','Gulf of Bothnia','Yes','No'),
	array('Livonia','St. Petersburg (South Coast)','Yes','No'),
	array('Moscow','St. Petersburg','No','Yes'),
	array('St. Petersburg','Finland','No','Yes'),
	array('St. Petersburg','Norway','No','Yes'),
	array('Finland','Sweden','Yes','Yes'),
	array('Finland','Norway','No','Yes'),
	array('Finland','Gulf of Bothnia','Yes','No'),
	array('Finland','St. Petersburg (South Coast)','Yes','No'),
	array('Sweden','Norway','Yes','Yes'),
	array('Sweden','Denmark','Yes','Yes'),
	array('Sweden','Skagerrack','Yes','No'),
	array('Sweden','Baltic Sea','Yes','No'),
	array('Sweden','Gulf of Bothnia','Yes','No'),
	array('Norway','Barents Sea','Yes','No'),
	array('Norway','Norwegian Sea','Yes','No'),
	array('Norway','North Sea','Yes','No'),
	array('Norway','Skagerrack','Yes','No'),
	array('Norway','St. Petersburg (North Coast)','Yes','No'),
	array('Denmark','Kiel','Yes','Yes'),
	array('Denmark','North Sea','Yes','No'),
	array('Denmark','Skagerrack','Yes','No'),
	array('Denmark','Heligoland Bight','Yes','No'),
	array('Denmark','Baltic Sea','Yes','No'),
	array('Kiel','Berlin','Yes','Yes'),
	array('Kiel','Munich','No','Yes'),
	array('Kiel','Ruhr','No','Yes'),
	array('Kiel','Holland','Yes','Yes'),
	array('Kiel','Heligoland Bight','Yes','No'),
	array('Kiel','Baltic Sea','Yes','No'),
	array('Berlin','Prussia','Yes','Yes'),
	array('Berlin','Silesia','No','Yes'),
	array('Berlin','Munich','No','Yes'),
	array('Berlin','Baltic Sea','Yes','No'),
	array('Prussia','Silesia','No','Yes'),
	array('Prussia','Baltic Sea','Yes','No'),
	array('Silesia','Munich','No','Yes'),
	array('Silesia','Bohemia','No','Yes'),
	array('Silesia','Galicia','No','Yes'),
	array('Munich','Ruhr','No','Yes'),
	array('Munich','Burgundy','No','Yes'),
	array('Munich','Tyrolia','No','Yes'),
	array('Munich','Bohemia','No','Yes'),
	array('Ruhr','Holland','No','Yes'),
	array('Ruhr','Belgium','No','Yes'),
	array('Ruhr','Burgundy','No','Yes'),
	array('Holland','Belgium','Yes','Yes'),
	array('Holland','North Sea','Yes','No'),
	array('Holland','Heligoland Bight','Yes','No'),
	array('Belgium','Picardy','Yes','Yes'),
	array('Belgium','Burgundy','No','Yes'),
	array('Belgium','North Sea','Yes','No'),
	array('Belgium','English Channel','Yes','No'),
	array('Picardy','Brest','Yes','Yes'),
	array('Picardy','Paris','No','Yes'),
	array('Picardy','Burgundy','No','Yes'),
	array('Picardy','English Channel','Yes','No'),
	array('Brest','Paris','No','Yes'),
	array('Brest','Gascony','Yes','Yes'),
	array('Brest','English Channel','Yes','No'),
	array('Brest','Mid-Atlantic Ocean','Yes','No'),
	array('Paris','Burgundy','No','Yes'),
	array('Paris','Gascony','No','Yes'),
	array('Burgundy','Marseilles','No','Yes'),
	array('Burgundy','Gascony','No','Yes'),
	array('Marseilles','Gascony','No','Yes'),
	array('Marseilles','Gulf of Lyon','Yes','No'),
	array('Marseilles','Spain (South Coast)','Yes','No'),
	array('Gascony','Mid-Atlantic Ocean','Yes','No'),
	array('Gascony','Spain (North Coast)','Yes','No'),
	array('Barents Sea','Norwegian Sea','Yes','No'),
	array('Barents Sea','St. Petersburg (North Coast)','Yes','No'),
	array('Norwegian Sea','North Sea','Yes','No'),
	array('Norwegian Sea','North Atlantic Ocean','Yes','No'),
	array('North Sea','Skagerrack','Yes','No'),
	array('North Sea','Heligoland Bight','Yes','No'),
	array('North Sea','English Channel','Yes','No'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No'),
	array('Gulf of Bothnia','St. Petersburg (South Coast)','Yes','No'),
	array('North Atlantic Ocean','Irish Sea','Yes','No'),
	array('North Atlantic Ocean','Mid-Atlantic Ocean','Yes','No'),
	array('North Atlantic Ocean','Red Sea','Yes','No'),
	array('Irish Sea','English Channel','Yes','No'),
	array('Irish Sea','Mid-Atlantic Ocean','Yes','No'),
	array('English Channel','Mid-Atlantic Ocean','Yes','No'),
	array('Mid-Atlantic Ocean','Western Mediterranean','Yes','No'),
	array('Mid-Atlantic Ocean','Spain (North Coast)','Yes','No'),
	array('Mid-Atlantic Ocean','Spain (South Coast)','Yes','No'),
	array('Mid-Atlantic Ocean','Red Sea','Yes','No'),
	array('Western Mediterranean','Gulf of Lyon','Yes','No'),
	array('Western Mediterranean','Tyrrhenian Sea','Yes','No'),
	array('Western Mediterranean','Spain (South Coast)','Yes','No'),
	array('Gulf of Lyon','Tyrrhenian Sea','Yes','No'),
	array('Gulf of Lyon','Spain (South Coast)','Yes','No'),
	array('Tyrrhenian Sea','Ionian Sea','Yes','No'),
	array('Ionian Sea','Adriatic Sea','Yes','No'),
	array('Ionian Sea','Aegean Sea','Yes','No'),
	array('Ionian Sea','Eastern Mediterranean','Yes','No'),
	array('Ionian Sea','Libya','Yes','No'),
	array('Ionian Sea','Egypt (North Coast)','Yes','No'),
	array('Adriatic Sea','Trieste','Yes','No'),
	array('Aegean Sea','Eastern Mediterranean','Yes','No'),
	array('Aegean Sea','Bulgaria (South Coast)','Yes','No'),
	array('Eastern Mediterranean','Suez','Yes','No'),
	array('Eastern Mediterranean','Egypt (North Coast)','Yes','No'),
	array('Eastern Mediterranean','Syria (West Coast)','Yes','No'),
	array('Black Sea','Bulgaria (North Coast)','Yes','No'),
	array('Tyrolia','Bohemia','No','Yes'),
	array('Tyrolia','Vienna','No','Yes'),
	array('Tyrolia','Trieste','No','Yes'),
	array('Bohemia','Vienna','No','Yes'),
	array('Bohemia','Galicia','No','Yes'),
	array('Vienna','Trieste','No','Yes'),
	array('Vienna','Budapest','No','Yes'),
	array('Vienna','Galicia','No','Yes'),
	array('Trieste','Budapest','No','Yes'),
	array('Budapest','Galicia','No','Yes'),
	array('Libya','Egypt','No','Yes'),
	array('Libya','Egypt (North Coast)','Yes','No'),
	array('Egypt','Suez','No','Yes'),
	array('Suez','Egypt (North Coast)','Yes','No'),
	array('Suez','Egypt (East Coast)','Yes','No'),
	array('Suez','Syria (West Coast)','Yes','No'),
	array('Suez','Syria (South Coast)','Yes','No'),
	array('Suez','Red Sea','Yes','No'),
	array('Egypt (East Coast)','Red Sea','Yes','No'),
	array('Syria (South Coast)','Red Sea','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
