<?php
// This is file installs the map data for the SpiceIslands variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Shan', 'Land', 'No', 0, 268, 167, 103, 63),
	array('Pegu', 'Coast', 'No', 0, 68, 454, 42, 146),
	array('Ava', 'Coast', 'Yes', 0, 51, 188, 26, 44),
	array('Chiangmai', 'Land', 'No', 0, 290, 331, 118, 133),
	array('Roi Et', 'Land', 'Yes', 5, 403, 496, 164, 204),
	array('Wiangjun', 'Land', 'No', 0, 498, 432, 192, 176),
	array('Champassak', 'Land', 'No', 0, 610, 502, 241, 199),
	array('Lan Xang', 'Land', 'Yes', 0, 424, 321, 151, 97),
	array('Hanoi', 'Land', 'Yes', 7, 519, 235, 191, 73),
	array('Haiphong', 'Coast', 'Yes', 7, 612, 258, 250, 78),
	array('Faifo', 'Coast', 'Yes', 7, 736, 568, 278, 212),
	array('Champa', 'Coast', 'No', 0, 752, 684, 281, 269),
	array('Oc Eo', 'Coast', 'Yes', 0, 650, 778, 219, 313),
	array('Khmer', 'Coast', 'No', 0, 487, 731, 184, 270),
	array('Ayutthaya', 'Coast', 'Yes', 5, 342, 616, 141, 241),
	array('Dawei', 'Coast', 'Yes', 5, 242, 692, 92, 258),
	array('Dawei (West Coast)', 'Coast', 'No', 0, 216, 706, 82, 260),
	array('Dawei (East Coast)', 'Coast', 'No', 0, 276, 702, 102, 266),
	array('Chaiya', 'Coast', 'No', 0, 260, 940, 93, 344),
	array('Chaiya (West Coast)', 'Coast', 'No', 0, 268, 990, 79, 339),
	array('Chaiya (East Coast)', 'Coast', 'No', 0, 292, 926, 105, 343),
	array('Kelantan', 'Coast', 'No', 0, 372, 1096, 140, 397),
	array('Pahang', 'Coast', 'Yes', 4, 444, 1198, 164, 444),
	array('Malacca', 'Coast', 'Yes', 4, 370, 1204, 137, 442),
	array('Aceh', 'Coast', 'Yes', 0, 62, 1112, 24, 419),
	array('Pedir', 'Coast', 'No', 0, 248, 1228, 92, 458),
	array('Riau', 'Coast', 'Yes', 4, 378, 1372, 135, 507),
	array('Minangkabau', 'Coast', 'No', 0, 400, 1534, 149, 570),
	array('Jambi', 'Coast', 'No', 0, 482, 1498, 183, 556),
	array('Palembang', 'Coast', 'Yes', 0, 558, 1646, 205, 609),
	array('Sunda', 'Coast', 'No', 0, 698, 1782, 221, 652),
	array('Pajajaran', 'Coast', 'Yes', 2, 642, 1721, 258, 648),
	array('Javadvipa', 'Coast', 'Yes', 2, 858, 1782, 311, 661),
	array('Javadvipa (North Coast)', 'Coast', 'No', 0, 858, 1746, 311, 660),
	array('Javadvipa (South Coast)', 'Coast', 'No', 0, 868, 1808, 322, 678),
	array('Trowulan', 'Coast', 'Yes', 2, 930, 1765, 350, 655),
	array('Lumajang', 'Coast', 'No', 0, 1032, 1822, 387, 682),
	array('Wehali', 'Coast', 'Yes', 0, 1645, 1866, 594, 716),
	array('Seram', 'Coast', 'Yes', 6, 1890, 1552, 711, 583),
	array('Buru', 'Coast', 'Yes', 6, 1704, 1561, 639, 582),
	array('Halmahera', 'Coast', 'Yes', 6, 1774, 1360, 674, 503),
	array('Buton', 'Coast', 'No', 0, 1444, 1554, 542, 586),
	array('Makassar', 'Coast', 'Yes', 0, 1324, 1542, 507, 596),
	array('Luwuk', 'Coast', 'No', 0, 1462, 1448, 560, 537),
	array('Minahassa', 'Coast', 'Yes', 0, 1366, 1354, 510, 512),
	array('Sambas', 'Coast', 'Yes', 0, 792, 1368, 299, 496),
	array('Sukadana', 'Coast', 'No', 0, 884, 1410, 333, 510),
	array('Sukadana (North Coast)', 'Coast', 'No', 0, 902, 1286, 345, 474),
	array('Sukadana (West Coast)', 'Coast', 'No', 0, 850, 1444, 320, 553),
	array('Sampit', 'Coast', 'Yes', 0, 936, 1540, 351, 574),
	array('Negara Daha', 'Land', 'Yes', 0, 1038, 1310, 390, 502),
	array('Kutai', 'Coast', 'No', 0, 1186, 1344, 448, 484),
	array('Brunei', 'Coast', 'Yes', 1, 1050, 1168, 412, 428),
	array('Tunku', 'Coast', 'Yes', 1, 1234, 1066, 472, 403),
	array('Mindanao', 'Coast', 'No', 0, 1644, 1046, 616, 390),
	array('Butuan', 'Coast', 'Yes', 0, 1666, 896, 626, 334),
	array('Zamboanga', 'Coast', 'Yes', 0, 1540, 948, 574, 356),
	array('Palawan', 'Coast', 'Yes', 1, 1286, 860, 486, 321),
	array('Bikol', 'Coast', 'No', 0, 1558, 668, 582, 244),
	array('Namayan', 'Coast', 'Yes', 3, 1433, 583, 534, 232),
	array('Namayan (East Coast)', 'Coast', 'No', 0, 1444, 583, 536, 212),
	array('Namayan (South Coast)', 'Coast', 'No', 0, 1412, 622, 535, 234),
	array('Tondo', 'Coast', 'Yes', 3, 1376, 546, 509, 191),
	array('Kasiguran', 'Coast', 'Yes', 3, 1438, 509, 553, 183),
	array('Luson', 'Coast', 'No', 0, 1426, 402, 540, 154),
	array('Taiwan', 'Coast', 'Yes', 0, 1362, 128, 512, 52),
	array('Sea of India', 'Sea', 'No', 0, 84, 798, 30, 309),
	array('Straits of Malacca', 'Sea', 'No', 0, 238, 1112, 65, 388),
	array('Western Ocean', 'Sea', 'No', 0, 162, 1612, 62, 632),
	array('Southern Ocean', 'Sea', 'No', 0, 1014, 1940, 382, 725),
	array('Timor Sea', 'Sea', 'No', 0, 1868, 1810, 698, 692),
	array('Moluccan Sea', 'Sea', 'No', 0, 1794, 1460, 689, 550),
	array('Banda Sea', 'Sea', 'No', 0, 1576, 1648, 592, 629),
	array('Gulf of Tomini', 'Sea', 'No', 0, 1672, 1362, 628, 510),
	array('Sulawesi Sea', 'Sea', 'No', 0, 1492, 1158, 574, 441),
	array('Makassar Strait', 'Sea', 'No', 0, 1266, 1760, 450, 653),
	array('Java Sea', 'Sea', 'No', 0, 802, 1642, 277, 600),
	array('Karimata Sea', 'Sea', 'No', 0, 598, 1160, 228, 439),
	array('Gulf of Siam', 'Sea', 'No', 0, 380, 870, 146, 326),
	array('Champa Sea', 'Sea', 'No', 0, 900, 956, 368, 347),
	array('Mait Sea', 'Sea', 'No', 0, 1198, 606, 431, 242),
	array('South China Sea', 'Sea', 'No', 0, 1032, 440, 400, 126),
	array('Gulf of Dai Viet', 'Sea', 'No', 0, 734, 372, 286, 135),
	array('Strait of Taiwan', 'Sea', 'No', 0, 1272, 80, 461, 43),
	array('East China Sea', 'Sea', 'No', 0, 1674, 182, 633, 86),
	array('Eastern Ocean', 'Sea', 'No', 0, 1904, 912, 711, 314),
	array('Luson Sea', 'Sea', 'No', 0, 1686, 746, 633, 282),
	array('Visayas Sea', 'Sea', 'No', 0, 1554, 788, 580, 313),
	array('Sibuyan Sea', 'Sea', 'No', 0, 1454, 762, 547, 275),
	array('Sulu Sea', 'Sea', 'No', 0, 1364, 922, 502, 362)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Shan','Pegu','No','Yes'),
	array('Shan','Ava','No','Yes'),
	array('Shan','Chiangmai','No','Yes'),
	array('Shan','Lan Xang','No','Yes'),
	array('Shan','Hanoi','No','Yes'),
	array('Pegu','Ava','Yes','Yes'),
	array('Pegu','Chiangmai','No','Yes'),
	array('Pegu','Roi Et','No','Yes'),
	array('Pegu','Ayutthaya','No','Yes'),
	array('Pegu','Dawei','No','Yes'),
	array('Pegu','Dawei (West Coast)','Yes','No'),
	array('Pegu','Sea of India','Yes','No'),
	array('Ava','Sea of India','Yes','No'),
	array('Chiangmai','Roi Et','No','Yes'),
	array('Chiangmai','Lan Xang','No','Yes'),
	array('Roi Et','Wiangjun','No','Yes'),
	array('Roi Et','Lan Xang','No','Yes'),
	array('Roi Et','Khmer','No','Yes'),
	array('Roi Et','Ayutthaya','No','Yes'),
	array('Wiangjun','Champassak','No','Yes'),
	array('Wiangjun','Lan Xang','No','Yes'),
	array('Wiangjun','Oc Eo','No','Yes'),
	array('Wiangjun','Khmer','No','Yes'),
	array('Champassak','Lan Xang','No','Yes'),
	array('Champassak','Hanoi','No','Yes'),
	array('Champassak','Faifo','No','Yes'),
	array('Champassak','Oc Eo','No','Yes'),
	array('Lan Xang','Hanoi','No','Yes'),
	array('Hanoi','Haiphong','No','Yes'),
	array('Hanoi','Faifo','No','Yes'),
	array('Haiphong','Faifo','Yes','Yes'),
	array('Haiphong','Gulf of Dai Viet','Yes','No'),
	array('Faifo','Champa','Yes','Yes'),
	array('Faifo','Oc Eo','No','Yes'),
	array('Faifo','South China Sea','Yes','No'),
	array('Faifo','Gulf of Dai Viet','Yes','No'),
	array('Champa','Oc Eo','Yes','Yes'),
	array('Champa','Champa Sea','Yes','No'),
	array('Champa','South China Sea','Yes','No'),
	array('Oc Eo','Khmer','Yes','Yes'),
	array('Oc Eo','Karimata Sea','Yes','No'),
	array('Oc Eo','Gulf of Siam','Yes','No'),
	array('Oc Eo','Champa Sea','Yes','No'),
	array('Khmer','Ayutthaya','Yes','Yes'),
	array('Khmer','Gulf of Siam','Yes','No'),
	array('Ayutthaya','Dawei','No','Yes'),
	array('Ayutthaya','Dawei (East Coast)','Yes','No'),
	array('Ayutthaya','Gulf of Siam','Yes','No'),
	array('Dawei','Chaiya','No','Yes'),
	array('Dawei (West Coast)','Chaiya (West Coast)','Yes','No'),
	array('Dawei (West Coast)','Sea of India','Yes','No'),
	array('Dawei (East Coast)','Chaiya (East Coast)','Yes','No'),
	array('Dawei (East Coast)','Gulf of Siam','Yes','No'),
	array('Chaiya','Kelantan','No','Yes'),
	array('Chaiya','Malacca','No','Yes'),
	array('Chaiya (West Coast)','Malacca','Yes','No'),
	array('Chaiya (West Coast)','Sea of India','Yes','No'),
	array('Chaiya (West Coast)','Straits of Malacca','Yes','No'),
	array('Chaiya (East Coast)','Kelantan','Yes','No'),
	array('Chaiya (East Coast)','Gulf of Siam','Yes','No'),
	array('Kelantan','Pahang','Yes','Yes'),
	array('Kelantan','Malacca','No','Yes'),
	array('Kelantan','Karimata Sea','Yes','No'),
	array('Kelantan','Gulf of Siam','Yes','No'),
	array('Pahang','Malacca','Yes','Yes'),
	array('Pahang','Straits of Malacca','Yes','No'),
	array('Pahang','Karimata Sea','Yes','No'),
	array('Malacca','Straits of Malacca','Yes','No'),
	array('Aceh','Pedir','Yes','Yes'),
	array('Aceh','Minangkabau','Yes','Yes'),
	array('Aceh','Sea of India','Yes','No'),
	array('Aceh','Straits of Malacca','Yes','No'),
	array('Aceh','Western Ocean','Yes','No'),
	array('Pedir','Riau','Yes','Yes'),
	array('Pedir','Minangkabau','No','Yes'),
	array('Pedir','Straits of Malacca','Yes','No'),
	array('Riau','Minangkabau','No','Yes'),
	array('Riau','Jambi','Yes','Yes'),
	array('Riau','Straits of Malacca','Yes','No'),
	array('Riau','Karimata Sea','Yes','No'),
	array('Minangkabau','Jambi','No','Yes'),
	array('Minangkabau','Palembang','Yes','Yes'),
	array('Minangkabau','Western Ocean','Yes','No'),
	array('Jambi','Palembang','Yes','Yes'),
	array('Jambi','Karimata Sea','Yes','No'),
	array('Palembang','Western Ocean','Yes','No'),
	array('Palembang','Java Sea','Yes','No'),
	array('Palembang','Karimata Sea','Yes','No'),
	array('Sunda','Pajajaran','Yes','Yes'),
	array('Sunda','Javadvipa','No','Yes'),
	array('Sunda','Javadvipa (South Coast)','Yes','No'),
	array('Sunda','Western Ocean','Yes','No'),
	array('Pajajaran','Javadvipa','No','Yes'),
	array('Pajajaran','Javadvipa (North Coast)','Yes','No'),
	array('Pajajaran','Western Ocean','Yes','No'),
	array('Pajajaran','Java Sea','Yes','No'),
	array('Javadvipa','Trowulan','No','Yes'),
	array('Javadvipa','Lumajang','No','Yes'),
	array('Javadvipa (North Coast)','Trowulan','Yes','No'),
	array('Javadvipa (North Coast)','Java Sea','Yes','No'),
	array('Javadvipa (South Coast)','Lumajang','Yes','No'),
	array('Javadvipa (South Coast)','Western Ocean','Yes','No'),
	array('Javadvipa (South Coast)','Southern Ocean','Yes','No'),
	array('Trowulan','Lumajang','Yes','Yes'),
	array('Trowulan','Makassar Strait','Yes','No'),
	array('Trowulan','Java Sea','Yes','No'),
	array('Lumajang','Southern Ocean','Yes','No'),
	array('Lumajang','Makassar Strait','Yes','No'),
	array('Wehali','Southern Ocean','Yes','No'),
	array('Wehali','Timor Sea','Yes','No'),
	array('Wehali','Banda Sea','Yes','No'),
	array('Wehali','Makassar Strait','Yes','No'),
	array('Seram','Timor Sea','Yes','No'),
	array('Seram','Moluccan Sea','Yes','No'),
	array('Seram','Eastern Ocean','Yes','No'),
	array('Buru','Timor Sea','Yes','No'),
	array('Buru','Moluccan Sea','Yes','No'),
	array('Buru','Banda Sea','Yes','No'),
	array('Halmahera','Moluccan Sea','Yes','No'),
	array('Halmahera','Gulf of Tomini','Yes','No'),
	array('Halmahera','Eastern Ocean','Yes','No'),
	array('Buton','Makassar','Yes','Yes'),
	array('Buton','Luwuk','Yes','Yes'),
	array('Buton','Banda Sea','Yes','No'),
	array('Makassar','Luwuk','No','Yes'),
	array('Makassar','Minahassa','Yes','Yes'),
	array('Makassar','Banda Sea','Yes','No'),
	array('Makassar','Makassar Strait','Yes','No'),
	array('Luwuk','Minahassa','Yes','Yes'),
	array('Luwuk','Banda Sea','Yes','No'),
	array('Luwuk','Gulf of Tomini','Yes','No'),
	array('Minahassa','Gulf of Tomini','Yes','No'),
	array('Minahassa','Sulawesi Sea','Yes','No'),
	array('Minahassa','Makassar Strait','Yes','No'),
	array('Sambas','Sukadana','No','Yes'),
	array('Sambas','Sukadana (North Coast)','Yes','No'),
	array('Sambas','Sukadana (West Coast)','Yes','No'),
	array('Sambas','Java Sea','Yes','No'),
	array('Sambas','Karimata Sea','Yes','No'),
	array('Sambas','Champa Sea','Yes','No'),
	array('Sukadana','Sampit','No','Yes'),
	array('Sukadana','Negara Daha','No','Yes'),
	array('Sukadana','Brunei','No','Yes'),
	array('Sukadana (North Coast)','Brunei','Yes','No'),
	array('Sukadana (North Coast)','Champa Sea','Yes','No'),
	array('Sukadana (West Coast)','Sampit','Yes','No'),
	array('Sukadana (West Coast)','Java Sea','Yes','No'),
	array('Sampit','Negara Daha','No','Yes'),
	array('Sampit','Kutai','Yes','Yes'),
	array('Sampit','Makassar Strait','Yes','No'),
	array('Sampit','Java Sea','Yes','No'),
	array('Negara Daha','Kutai','No','Yes'),
	array('Negara Daha','Brunei','No','Yes'),
	array('Kutai','Brunei','No','Yes'),
	array('Kutai','Tunku','Yes','Yes'),
	array('Kutai','Sulawesi Sea','Yes','No'),
	array('Kutai','Makassar Strait','Yes','No'),
	array('Brunei','Tunku','Yes','Yes'),
	array('Brunei','Champa Sea','Yes','No'),
	array('Brunei','Sulu Sea','Yes','No'),
	array('Tunku','Sulawesi Sea','Yes','No'),
	array('Tunku','Sulu Sea','Yes','No'),
	array('Mindanao','Butuan','Yes','Yes'),
	array('Mindanao','Zamboanga','Yes','Yes'),
	array('Mindanao','Sulawesi Sea','Yes','No'),
	array('Mindanao','Eastern Ocean','Yes','No'),
	array('Butuan','Zamboanga','Yes','Yes'),
	array('Butuan','Eastern Ocean','Yes','No'),
	array('Butuan','Luson Sea','Yes','No'),
	array('Butuan','Visayas Sea','Yes','No'),
	array('Zamboanga','Sulawesi Sea','Yes','No'),
	array('Zamboanga','Visayas Sea','Yes','No'),
	array('Zamboanga','Sulu Sea','Yes','No'),
	array('Palawan','Champa Sea','Yes','No'),
	array('Palawan','Mait Sea','Yes','No'),
	array('Palawan','Sulu Sea','Yes','No'),
	array('Bikol','Namayan','No','Yes'),
	array('Bikol','Namayan (East Coast)','Yes','No'),
	array('Bikol','Namayan (South Coast)','Yes','No'),
	array('Bikol','Luson Sea','Yes','No'),
	array('Bikol','Visayas Sea','Yes','No'),
	array('Namayan','Tondo','No','Yes'),
	array('Namayan','Kasiguran','No','Yes'),
	array('Namayan (East Coast)','Kasiguran','Yes','No'),
	array('Namayan (East Coast)','Luson Sea','Yes','No'),
	array('Namayan (South Coast)','Tondo','Yes','No'),
	array('Namayan (South Coast)','Visayas Sea','Yes','No'),
	array('Namayan (South Coast)','Sibuyan Sea','Yes','No'),
	array('Tondo','Kasiguran','No','Yes'),
	array('Tondo','Luson','Yes','Yes'),
	array('Tondo','Mait Sea','Yes','No'),
	array('Tondo','Sibuyan Sea','Yes','No'),
	array('Kasiguran','Luson','Yes','Yes'),
	array('Kasiguran','East China Sea','Yes','No'),
	array('Kasiguran','Luson Sea','Yes','No'),
	array('Luson','Mait Sea','Yes','No'),
	array('Luson','South China Sea','Yes','No'),
	array('Luson','East China Sea','Yes','No'),
	array('Taiwan','South China Sea','Yes','No'),
	array('Taiwan','Strait of Taiwan','Yes','No'),
	array('Taiwan','East China Sea','Yes','No'),
	array('Sea of India','Straits of Malacca','Yes','No'),
	array('Sea of India','Western Ocean','Yes','No'),
	array('Straits of Malacca','Karimata Sea','Yes','No'),
	array('Western Ocean','Southern Ocean','Yes','No'),
	array('Western Ocean','Java Sea','Yes','No'),
	array('Southern Ocean','Timor Sea','Yes','No'),
	array('Southern Ocean','Makassar Strait','Yes','No'),
	array('Timor Sea','Moluccan Sea','Yes','No'),
	array('Timor Sea','Banda Sea','Yes','No'),
	array('Timor Sea','Eastern Ocean','Yes','No'),
	array('Moluccan Sea','Banda Sea','Yes','No'),
	array('Moluccan Sea','Gulf of Tomini','Yes','No'),
	array('Moluccan Sea','Eastern Ocean','Yes','No'),
	array('Banda Sea','Gulf of Tomini','Yes','No'),
	array('Banda Sea','Makassar Strait','Yes','No'),
	array('Gulf of Tomini','Sulawesi Sea','Yes','No'),
	array('Gulf of Tomini','Eastern Ocean','Yes','No'),
	array('Sulawesi Sea','Makassar Strait','Yes','No'),
	array('Sulawesi Sea','Eastern Ocean','Yes','No'),
	array('Sulawesi Sea','Sulu Sea','Yes','No'),
	array('Makassar Strait','Java Sea','Yes','No'),
	array('Java Sea','Karimata Sea','Yes','No'),
	array('Karimata Sea','Gulf of Siam','Yes','No'),
	array('Karimata Sea','Champa Sea','Yes','No'),
	array('Champa Sea','Mait Sea','Yes','No'),
	array('Champa Sea','South China Sea','Yes','No'),
	array('Champa Sea','Sulu Sea','Yes','No'),
	array('Mait Sea','South China Sea','Yes','No'),
	array('Mait Sea','Sibuyan Sea','Yes','No'),
	array('Mait Sea','Sulu Sea','Yes','No'),
	array('South China Sea','Gulf of Dai Viet','Yes','No'),
	array('South China Sea','Strait of Taiwan','Yes','No'),
	array('South China Sea','East China Sea','Yes','No'),
	array('Strait of Taiwan','East China Sea','Yes','No'),
	array('East China Sea','Eastern Ocean','Yes','No'),
	array('East China Sea','Luson Sea','Yes','No'),
	array('Eastern Ocean','Luson Sea','Yes','No'),
	array('Luson Sea','Visayas Sea','Yes','No'),
	array('Visayas Sea','Sibuyan Sea','Yes','No'),
	array('Visayas Sea','Sulu Sea','Yes','No'),
	array('Sibuyan Sea','Sulu Sea','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
