<?php
// This is file installs the map data for the ClassicPilot variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Clyde', 'Coast', 'No', 1, 299, 336, 160, 109),
	array('Edinburgh', 'Coast', 'Yes', 1, 346, 347, 175, 112),
	array('Liverpool', 'Coast', 'Yes', 1, 315, 413, 170, 144),
	array('Yorkshire', 'Coast', 'No', 1, 355, 440, 184, 150),
	array('Wales', 'Coast', 'No', 1, 294, 473, 154, 169),
	array('London', 'Coast', 'Yes', 1, 361, 481, 186, 175),
	array('Portugal', 'Coast', 'Yes', 0, 91, 718, 60, 305),
	array('Spain', 'Coast', 'Yes', 0, 177, 794, 100, 324),
	array('North Africa', 'Coast', 'No', 0, 181, 949, 118, 386),
	array('Tunis', 'Coast', 'Yes', 0, 434, 961, 212, 390),
	array('Naples', 'Coast', 'Yes', 3, 570, 864, 298, 362),
	array('Rome', 'Coast', 'Yes', 3, 522, 808, 272, 332),
	array('Tuscany', 'Coast', 'No', 3, 485, 767, 256, 309),
	array('Piedmont', 'Coast', 'No', 3, 441, 694, 228, 279),
	array('Venice', 'Coast', 'Yes', 3, 501, 717, 261, 289),
	array('Apulia', 'Coast', 'No', 3, 591, 825, 305, 343),
	array('Greece', 'Coast', 'Yes', 0, 678, 863, 358, 359),
	array('Albania', 'Coast', 'No', 0, 640, 827, 344, 337),
	array('Serbia', 'Land', 'Yes', 0, 667, 776, 354, 315),
	array('Bulgaria', 'Coast', 'Yes', 0, 740, 776, 396, 311),
	array('Rumania', 'Coast', 'Yes', 0, 717, 724, 422, 289),
	array('Constantinople', 'Coast', 'Yes', 6, 821, 852, 441, 341),
	array('Smyrna', 'Coast', 'Yes', 6, 899, 895, 480, 360),
	array('Ankara', 'Coast', 'Yes', 6, 986, 816, 498, 325),
	array('Armenia', 'Coast', 'No', 6, 1073, 785, 572, 323),
	array('Syria', 'Coast', 'No', 6, 1045, 938, 559, 381),
	array('Sevastopol', 'Coast', 'Yes', 7, 923, 595, 500, 244),
	array('Ukraine', 'Land', 'No', 7, 779, 579, 418, 223),
	array('Warsaw', 'Land', 'Yes', 7, 683, 547, 354, 212),
	array('Livonia', 'Coast', 'No', 7, 719, 430, 374, 168),
	array('Moscow', 'Land', 'Yes', 7, 830, 465, 490, 155),
	array('St. Petersburg', 'Coast', 'Yes', 7, 837, 309, 445, 104),
	array('Finland', 'Coast', 'No', 7, 702, 263, 367, 109),
	array('Sweden', 'Coast', 'Yes', 0, 587, 274, 313, 87),
	array('Norway', 'Coast', 'Yes', 0, 518, 270, 271, 100),
	array('Denmark', 'Coast', 'Yes', 0, 501, 422, 264, 156),
	array('Kiel', 'Coast', 'Yes', 4, 485, 516, 256, 200),
	array('Berlin', 'Coast', 'Yes', 4, 551, 477, 292, 193),
	array('Prussia', 'Coast', 'No', 4, 621, 481, 329, 192),
	array('Silesia', 'Land', 'No', 4, 589, 545, 304, 217),
	array('Munich', 'Land', 'Yes', 4, 489, 581, 248, 232),
	array('Ruhr', 'Land', 'No', 4, 448, 545, 234, 214),
	array('Holland', 'Coast', 'Yes', 0, 440, 488, 234, 186),
	array('Belgium', 'Coast', 'Yes', 0, 410, 551, 215, 205),
	array('Picardy', 'Coast', 'No', 2, 359, 559, 189, 214),
	array('Brest', 'Coast', 'Yes', 2, 291, 583, 146, 223),
	array('Paris', 'Land', 'Yes', 2, 336, 620, 179, 238),
	array('Burgundy', 'Land', 'No', 2, 404, 626, 206, 248),
	array('Marseilles', 'Coast', 'Yes', 2, 390, 689, 183, 286),
	array('Gascony', 'Coast', 'No', 2, 301, 679, 150, 274),
	array('Barents Sea', 'Sea', 'No', 0, 836, 33, 420, 20),
	array('Norwegian Sea', 'Sea', 'No', 0, 452, 109, 268, 35),
	array('North Sea', 'Sea', 'No', 0, 414, 378, 216, 136),
	array('Skagerrack', 'Sea', 'No', 0, 516, 363, 279, 133),
	array('Baltic Sea', 'Sea', 'No', 0, 621, 434, 338, 175),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 653, 348, 362, 131),
	array('North Atlantic Ocean', 'Sea', 'No', 0, 153, 237, 78, 87),
	array('Irish Sea', 'Sea', 'No', 0, 218, 478, 110, 178),
	array('English Channel', 'Sea', 'No', 0, 273, 527, 153, 198),
	array('Mid-Atlantic Ocean', 'Sea', 'No', 0, 106, 581, 81, 247),
	array('Western Mediterranean', 'Sea', 'No', 0, 327, 858, 186, 363),
	array('Gulf of Lyons', 'Sea', 'No', 0, 366, 774, 205, 323),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 488, 849, 250, 348),
	array('Ionian Sea', 'Sea', 'No', 0, 602, 947, 325, 384),
	array('Adriatic Sea', 'Sea', 'No', 0, 564, 773, 311, 319),
	array('Aegean Sea', 'Sea', 'No', 0, 740, 863, 400, 378),
	array('Eastern Mediterranean', 'Sea', 'No', 0, 860, 972, 454, 391),
	array('Black Sea', 'Sea', 'No', 0, 905, 743, 469, 300),
	array('Tyrolia', 'Land', 'No', 5, 538, 641, 273, 260),
	array('Bohemia', 'Land', 'No', 5, 562, 590, 292, 232),
	array('Vienna', 'Land', 'Yes', 5, 602, 627, 319, 246),
	array('Trieste', 'Coast', 'Yes', 5, 593, 730, 311, 291),
	array('Budapest', 'Land', 'Yes', 5, 681, 668, 354, 271),
	array('Galicia', 'Land', 'No', 5, 718, 610, 365, 237),
	array('Spain (North Coast)', 'Coast', 'No', 0, 193, 685, 94, 277),
	array('Spain (South Coast)', 'Coast', 'No', 0, 191, 832, 106, 345),
	array('St. Petersburg (North Coast)', 'Coast', 'No', 7, 828, 111, 448, 59),
	array('St. Petersburg (South Coast)', 'Coast', 'No', 7, 780, 355, 398, 133),
	array('Bulgaria (North Coast)', 'Coast', 'No', 0, 785, 762, 420, 304),
	array('Bulgaria (South Coast)', 'Coast', 'No', 0, 749, 815, 397, 329)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Clyde','Edinburgh','Yes','Yes'),
	array('Clyde','Liverpool','Yes','Yes'),
	array('Clyde','Norwegian Sea','Yes','No'),
	array('Clyde','North Atlantic Ocean','Yes','No'),
	array('Edinburgh','Liverpool','No','Yes'),
	array('Edinburgh','Yorkshire','Yes','Yes'),
	array('Edinburgh','Norwegian Sea','Yes','No'),
	array('Edinburgh','North Sea','Yes','No'),
	array('Liverpool','Yorkshire','No','Yes'),
	array('Liverpool','Wales','Yes','Yes'),
	array('Liverpool','North Atlantic Ocean','Yes','No'),
	array('Liverpool','Irish Sea','Yes','No'),
	array('Yorkshire','Wales','No','Yes'),
	array('Yorkshire','London','Yes','Yes'),
	array('Yorkshire','North Sea','Yes','No'),
	array('Wales','London','Yes','Yes'),
	array('Wales','Irish Sea','Yes','No'),
	array('Wales','English Channel','Yes','No'),
	array('London','North Sea','Yes','No'),
	array('London','English Channel','Yes','No'),
	array('Portugal','Spain','No','Yes'),
	array('Portugal','Mid-Atlantic Ocean','Yes','No'),
	array('Portugal','Spain (North Coast)','Yes','No'),
	array('Portugal','Spain (South Coast)','Yes','No'),
	array('Spain','Marseilles','No','Yes'),
	array('Spain','Gascony','No','Yes'),
	array('North Africa','Tunis','Yes','Yes'),
	array('North Africa','Mid-Atlantic Ocean','Yes','No'),
	array('North Africa','Western Mediterranean','Yes','No'),
	array('Tunis','Western Mediterranean','Yes','No'),
	array('Tunis','Tyrrhenian Sea','Yes','No'),
	array('Tunis','Ionian Sea','Yes','No'),
	array('Naples','Rome','Yes','Yes'),
	array('Naples','Apulia','Yes','Yes'),
	array('Naples','Tyrrhenian Sea','Yes','No'),
	array('Naples','Ionian Sea','Yes','No'),
	array('Rome','Tuscany','Yes','Yes'),
	array('Rome','Venice','No','Yes'),
	array('Rome','Apulia','No','Yes'),
	array('Rome','Tyrrhenian Sea','Yes','No'),
	array('Tuscany','Piedmont','Yes','Yes'),
	array('Tuscany','Venice','No','Yes'),
	array('Tuscany','Gulf of Lyons','Yes','No'),
	array('Tuscany','Tyrrhenian Sea','Yes','No'),
	array('Piedmont','Venice','No','Yes'),
	array('Piedmont','Marseilles','Yes','Yes'),
	array('Piedmont','Gulf of Lyons','Yes','No'),
	array('Piedmont','Tyrolia','No','Yes'),
	array('Venice','Apulia','Yes','Yes'),
	array('Venice','Adriatic Sea','Yes','No'),
	array('Venice','Tyrolia','No','Yes'),
	array('Venice','Trieste','Yes','Yes'),
	array('Apulia','Ionian Sea','Yes','No'),
	array('Apulia','Adriatic Sea','Yes','No'),
	array('Greece','Albania','Yes','Yes'),
	array('Greece','Serbia','No','Yes'),
	array('Greece','Bulgaria','No','Yes'),
	array('Greece','Ionian Sea','Yes','No'),
	array('Greece','Aegean Sea','Yes','No'),
	array('Greece','Bulgaria (South Coast)','Yes','No'),
	array('Albania','Serbia','No','Yes'),
	array('Albania','Ionian Sea','Yes','No'),
	array('Albania','Adriatic Sea','Yes','No'),
	array('Albania','Trieste','Yes','Yes'),
	array('Serbia','Bulgaria','No','Yes'),
	array('Serbia','Rumania','No','Yes'),
	array('Serbia','Trieste','No','Yes'),
	array('Serbia','Budapest','No','Yes'),
	array('Bulgaria','Rumania','No','Yes'),
	array('Bulgaria','Constantinople','No','Yes'),
	array('Rumania','Sevastopol','Yes','Yes'),
	array('Rumania','Ukraine','No','Yes'),
	array('Rumania','Black Sea','Yes','No'),
	array('Rumania','Budapest','No','Yes'),
	array('Rumania','Galicia','No','Yes'),
	array('Rumania','Bulgaria (North Coast)','Yes','No'),
	array('Constantinople','Smyrna','Yes','Yes'),
	array('Constantinople','Ankara','Yes','Yes'),
	array('Constantinople','Aegean Sea','Yes','No'),
	array('Constantinople','Black Sea','Yes','No'),
	array('Constantinople','Bulgaria (North Coast)','Yes','No'),
	array('Constantinople','Bulgaria (South Coast)','Yes','No'),
	array('Smyrna','Ankara','No','Yes'),
	array('Smyrna','Armenia','No','Yes'),
	array('Smyrna','Syria','Yes','Yes'),
	array('Smyrna','Aegean Sea','Yes','No'),
	array('Smyrna','Eastern Mediterranean','Yes','No'),
	array('Ankara','Armenia','Yes','Yes'),
	array('Ankara','Black Sea','Yes','No'),
	array('Armenia','Syria','No','Yes'),
	array('Armenia','Sevastopol','Yes','Yes'),
	array('Armenia','Black Sea','Yes','No'),
	array('Syria','Eastern Mediterranean','Yes','No'),
	array('Sevastopol','Ukraine','No','Yes'),
	array('Sevastopol','Moscow','No','Yes'),
	array('Sevastopol','Black Sea','Yes','No'),
	array('Ukraine','Warsaw','No','Yes'),
	array('Ukraine','Moscow','No','Yes'),
	array('Ukraine','Galicia','No','Yes'),
	array('Warsaw','Livonia','No','Yes'),
	array('Warsaw','Moscow','No','Yes'),
	array('Warsaw','Prussia','No','Yes'),
	array('Warsaw','Silesia','No','Yes'),
	array('Warsaw','Galicia','No','Yes'),
	array('Livonia','Moscow','No','Yes'),
	array('Livonia','St. Petersburg','No','Yes'),
	array('Livonia','Prussia','Yes','Yes'),
	array('Livonia','Baltic Sea','Yes','No'),
	array('Livonia','Gulf of Bothnia','Yes','No'),
	array('Livonia','St. Petersburg (South Coast)','Yes','No'),
	array('Moscow','St. Petersburg','No','Yes'),
	array('St. Petersburg','Finland','No','Yes'),
	array('St. Petersburg','Norway','No','Yes'),
	array('Finland','Sweden','Yes','Yes'),
	array('Finland','Norway','No','Yes'),
	array('Finland','Gulf of Bothnia','Yes','No'),
	array('Finland','St. Petersburg (South Coast)','Yes','No'),
	array('Sweden','Norway','Yes','Yes'),
	array('Sweden','Denmark','Yes','Yes'),
	array('Sweden','Skagerrack','Yes','No'),
	array('Sweden','Baltic Sea','Yes','No'),
	array('Sweden','Gulf of Bothnia','Yes','No'),
	array('Norway','Barents Sea','Yes','No'),
	array('Norway','Norwegian Sea','Yes','No'),
	array('Norway','North Sea','Yes','No'),
	array('Norway','Skagerrack','Yes','No'),
	array('Norway','St. Petersburg (North Coast)','Yes','No'),
	array('Denmark','Kiel','Yes','Yes'),
	array('Denmark','North Sea','Yes','No'),
	array('Denmark','Skagerrack','Yes','No'),
	array('Denmark','Baltic Sea','Yes','No'),
	array('Kiel','Berlin','Yes','Yes'),
	array('Kiel','Munich','No','Yes'),
	array('Kiel','Ruhr','No','Yes'),
	array('Kiel','Holland','Yes','Yes'),
	array('Kiel','North Sea','Yes','No'),
	array('Kiel','Baltic Sea','Yes','No'),
	array('Berlin','Prussia','Yes','Yes'),
	array('Berlin','Silesia','No','Yes'),
	array('Berlin','Munich','No','Yes'),
	array('Berlin','Baltic Sea','Yes','No'),
	array('Prussia','Silesia','No','Yes'),
	array('Prussia','Baltic Sea','Yes','No'),
	array('Silesia','Munich','No','Yes'),
	array('Silesia','Bohemia','No','Yes'),
	array('Silesia','Galicia','No','Yes'),
	array('Munich','Ruhr','No','Yes'),
	array('Munich','Burgundy','No','Yes'),
	array('Munich','Tyrolia','No','Yes'),
	array('Munich','Bohemia','No','Yes'),
	array('Ruhr','Holland','No','Yes'),
	array('Ruhr','Belgium','No','Yes'),
	array('Ruhr','Burgundy','No','Yes'),
	array('Holland','Belgium','Yes','Yes'),
	array('Holland','North Sea','Yes','No'),
	array('Belgium','Picardy','Yes','Yes'),
	array('Belgium','Burgundy','No','Yes'),
	array('Belgium','North Sea','Yes','No'),
	array('Belgium','English Channel','Yes','No'),
	array('Picardy','Brest','Yes','Yes'),
	array('Picardy','Paris','No','Yes'),
	array('Picardy','Burgundy','No','Yes'),
	array('Picardy','English Channel','Yes','No'),
	array('Brest','Paris','No','Yes'),
	array('Brest','Gascony','Yes','Yes'),
	array('Brest','English Channel','Yes','No'),
	array('Brest','Mid-Atlantic Ocean','Yes','No'),
	array('Paris','Burgundy','No','Yes'),
	array('Paris','Gascony','No','Yes'),
	array('Burgundy','Marseilles','No','Yes'),
	array('Burgundy','Gascony','No','Yes'),
	array('Marseilles','Gascony','No','Yes'),
	array('Marseilles','Gulf of Lyons','Yes','No'),
	array('Marseilles','Spain (South Coast)','Yes','No'),
	array('Gascony','Mid-Atlantic Ocean','Yes','No'),
	array('Gascony','Spain (North Coast)','Yes','No'),
	array('Barents Sea','Norwegian Sea','Yes','No'),
	array('Barents Sea','St. Petersburg (North Coast)','Yes','No'),
	array('Norwegian Sea','North Sea','Yes','No'),
	array('Norwegian Sea','North Atlantic Ocean','Yes','No'),
	array('North Sea','Skagerrack','Yes','No'),
	array('North Sea','English Channel','Yes','No'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No'),
	array('Gulf of Bothnia','St. Petersburg (South Coast)','Yes','No'),
	array('North Atlantic Ocean','Irish Sea','Yes','No'),
	array('North Atlantic Ocean','Mid-Atlantic Ocean','Yes','No'),
	array('Irish Sea','English Channel','Yes','No'),
	array('Irish Sea','Mid-Atlantic Ocean','Yes','No'),
	array('English Channel','Mid-Atlantic Ocean','Yes','No'),
	array('Mid-Atlantic Ocean','Western Mediterranean','Yes','No'),
	array('Mid-Atlantic Ocean','Spain (North Coast)','Yes','No'),
	array('Mid-Atlantic Ocean','Spain (South Coast)','Yes','No'),
	array('Western Mediterranean','Gulf of Lyons','Yes','No'),
	array('Western Mediterranean','Tyrrhenian Sea','Yes','No'),
	array('Western Mediterranean','Spain (South Coast)','Yes','No'),
	array('Gulf of Lyons','Tyrrhenian Sea','Yes','No'),
	array('Gulf of Lyons','Spain (South Coast)','Yes','No'),
	array('Tyrrhenian Sea','Ionian Sea','Yes','No'),
	array('Ionian Sea','Adriatic Sea','Yes','No'),
	array('Ionian Sea','Aegean Sea','Yes','No'),
	array('Ionian Sea','Eastern Mediterranean','Yes','No'),
	array('Adriatic Sea','Trieste','Yes','No'),
	array('Aegean Sea','Eastern Mediterranean','Yes','No'),
	array('Aegean Sea','Bulgaria (South Coast)','Yes','No'),
	array('Black Sea','Bulgaria (North Coast)','Yes','No'),
	array('Tyrolia','Bohemia','No','Yes'),
	array('Tyrolia','Vienna','No','Yes'),
	array('Tyrolia','Trieste','No','Yes'),
	array('Bohemia','Vienna','No','Yes'),
	array('Bohemia','Galicia','No','Yes'),
	array('Vienna','Trieste','No','Yes'),
	array('Vienna','Budapest','No','Yes'),
	array('Vienna','Galicia','No','Yes'),
	array('Trieste','Budapest','No','Yes'),
	array('Budapest','Galicia','No','Yes')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
