<?php
// This is file installs the map data for the Europe1900 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Morocco','Coast','No','120','877','47','506','0'),
	array('North Africa','Coast','Yes','411','902','221','514','0'),
	array('Libya','Coast','No','495','1007','275','568','5'),
	array('Egypt','Coast','Yes','890','1050','490','584','5'),
	array('Syria','Coast','No','995','883','552','498','5'),
	array('Anatolia','Coast','Yes','807','861','456','486','5'),
	array('Armenia','Coast','No','1018','767','565','433','5'),
	array('Constantinople','Coast','Yes','781','805','439','449','5'),
	array('Bulgaria','Coast','No','743','738','428','390','5'),
	array('Greece','Coast','Yes','672','807','378','446','5'),
	array('Illyria','Coast','No','636','759','357','429','5'),
	array('Western Mediterranean','Sea','No','336','814','209','450','0'),
	array('Gulf of Lyon','Sea','No','367','736','217','412','0'),
	array('Tyrrhenian Sea','Sea','No','481','794','266','466','0'),
	array('Ionian Sea','Sea','No','584','934','335','506','0'),
	array('Adriatic Sea','Sea','No','599','780','340','437','0'),
	array('Eastern Mediterranean','Sea','No','800','980','487','534','0'),
	array('Aegean Sea','Sea','No','737','870','411','482','0'),
	array('Black Sea','Sea','No','838','721','465','407','0'),
	array('Caspian Sea','Sea','No','1189','677','663','395','0'),
	array('Persia','Coast','No','1247','863','669','445','0'),
	array('Central Asia','Coast','Yes','1240','571','688','322','0'),
	array('Azerbaijan','Coast','Yes','1145','730','629','410','0'),
	array('Georgia','Coast','No','1050','711','583','401','0'),
	array('Crimea','Coast','Yes','872','630','530','357','0'),
	array('Bessarabia','Coast','Yes','800','646','447','367','0'),
	array('Transylvania','Land','Yes','711','665','397','374','0'),
	array('Eastern Hungary','Land','No','664','680','367','381','0'),
	array('Western Hungary','Land','Yes','605','689','340','385','0'),
	array('Serbia','Land','Yes','677','750','380','420','0'),
	array('Slovakia','Land','No','643','610','357','342','4'),
	array('Moravia','Land','No','600','594','339','333','4'),
	array('Silisia','Land','No','591','544','327','305','4'),
	array('Bohemia','Land','Yes','568','570','309','329','4'),
	array('Austria','Land','Yes','553','619','310','349','4'),
	array('Tyrolia','Land','No','506','635','281','358','4'),
	array('Styria','Land','No','559','663','305','370','4'),
	array('Croatia','Coast','Yes','578','697','318','393','4'),
	array('Venice','Coast','Yes','492','677','286','378','0'),
	array('Romagna','Coast','No','510','728','285','397','0'),
	array('Rome','Coast','Yes','507','767','283','430','0'),
	array('Tuscany','Coast','No','472','718','270','403','0'),
	array('Savoy','Land','Yes','416','669','234','367','0'),
	array('Flanders','Coast','Yes','385','523','223','294','8'),
	array('France Comte','Land','No','406','615','232','347','8'),
	array('Milan','Land','No','448','668','253','375','8'),
	array('Naples','Coast','Yes','545','783','307','434','8'),
	array('Navarre','Coast','No','188','668','108','371','8'),
	array('Castille','Land','Yes','180','729','106','407','8'),
	array('Aragon','Coast','No','252','759','175','406','8'),
	array('Granada','Coast','Yes','211','807','125','451','8'),
	array('Portugal','Coast','Yes','120','718','75','410','0'),
	array('Mid-Atlantic Ocean','Sea','No','82','554','48','378','0'),
	array('Bay of Biscay','Sea','No','209','590','131','323','0'),
	array('North Atlantic Ocean','Sea','No','155','269','102','144','0'),
	array('Irish Sea','Sea','No','250','471','144','264','0'),
	array('Arctic Ocean','Sea','No','409','39','232','35','0'),
	array('Barents Sea','Sea','No','831','62','448','51','0'),
	array('Norwegian Sea','Sea','No','427','188','257','102','0'),
	array('North Sea','Sea','No','382','370','221','209','0'),
	array('Skaggarak','Sea','No','446','390','252','221','0'),
	array('Helgoland Bight','Sea','No','435','435','248','253','0'),
	array('English Channel','Sea','No','258','519','154','294','0'),
	array('Scotland','Coast','Yes','325','343','190','190','0'),
	array('Ireland','Coast','Yes','245','422','140','238','2'),
	array('Cumbria','Coast','No','323','428','185','245','2'),
	array('Yorkshire','Coast','No','344','435','202','245','2'),
	array('Wales','Coast','Yes','305','459','176','264','2'),
	array('Cornwall','Coast','No','302','499','177','277','2'),
	array('London','Coast','Yes','360','482','200','281','2'),
	array('Brittany','Coast','No','301','574','166','326','3'),
	array('Normandy','Coast','No','364','539','201','305','3'),
	array('Champagne','Land','No','390','575','223','323','3'),
	array('Paris','Land','Yes','338','575','194','325','3'),
	array('Gascony','Coast','Yes','301','640','167','368','3'),
	array('Burgundy','Land','Yes','368','626','209','355','3'),
	array('Languedoc','Coast','No','328','674','193','375','3'),
	array('Provence','Coast','Yes','377','685','217','380','3'),
	array('Lorraine','Land','Yes','445','567','242','324','0'),
	array('Bavaria','Land','Yes','479','603','281','328','0'),
	array('Saxony','Land','No','500','541','284','306','0'),
	array('Hesse','Land','No','475','525','271','299','0'),
	array('Westphalia','Land','No','447','525','255','299','0'),
	array('Netherlands','Coast','Yes','431','485','244','271','0'),
	array('Bremen','Coast','Yes','460','475','264','271','0'),
	array('Holstein','Coast','Yes','479','453','269','256','0'),
	array('Mecklenburg','Coast','No','515','473','293','263','0'),
	array('Pomerania','Coast','Yes','577','472','324','268','0'),
	array('Brandenburg','Land','Yes','523','507','295','289','0'),
	array('Prussia','Coast','Yes','668','463','369','258','0'),
	array('Great Poland','Land','No','618','528','348','298','6'),
	array('Pomerelia','Coast','No','618','470','346','267','6'),
	array('Mazovia','Land','No','705','482','391','272','6'),
	array('Livonia','Coast','No','715','400','394','229','6'),
	array('White Russia','Land','Yes','769','435','425','249','6'),
	array('Warsaw','Coast','Yes','720','545','398','308','6'),
	array('Little Poland','Land','No','656','562','364','317','6'),
	array('Cracow','Coast','Yes','724','581','402','329','6'),
	array('Volhynia','Land','No','785','581','432','328','6'),
	array('Ukraine','Land','No','836','526','471','323','6'),
	array('Voronezj','Coast','Yes','963','543','536','289','7'),
	array('Uralsk','Coast','No','1054','572','576','345','7'),
	array('Moscow','Land','Yes','958','372','547','194','7'),
	array('Tula','Land','No','874','489','485','276','7'),
	array('Pskov','Land','No','763','373','423','218','7'),
	array('Novgorod','Coast','Yes','814','317','445','200','7'),
	array('Siberia','Coast','No','1029','138','571','78','7'),
	array('Archangel','Coast','No','848','242','488','164','7'),
	array('Karelia','Coast','No','763','168','425','75','7'),
	array('Ingria','Coast','No','758','304','421','187','7'),
	array('Gulf of Bothnia','Sea','No','633','302','355','158','0'),
	array('Baltic Sea','Sea','No','640','390','354','224','0'),
	array('Sea of Bornholm','Sea','No','537','452','324','252','0'),
	array('Kattegat','Sea','No','519','371','290','219','0'),
	array('Jutland','Coast','Yes','483','396','274','226','1'),
	array('Zealand','Coast','Yes','516','430','293','246','1'),
	array('Scania','Coast','Yes','555','418','313','242','1'),
	array('Ostlandet','Coast','No','531','325','299','190','1'),
	array('Vestlandet','Coast','Yes','484','338','273','195','1'),
	array('Troendelag','Coast','No','561','228','320','130','1'),
	array('Lappland','Land','No','627','158','347','113','9'),
	array('Finland','Coast','Yes','695','305','389','169','9'),
	array('Estonia','Coast','Yes','702','349','387','200','9'),
	array('Stockholm','Coast','Yes','590','298','338','181','9'),
	array('Bergslagen','Land','Yes','565','324','318','194','9'),
	array('West Gothland','Coast','No','544','370','310','208','9'),
	array('Smaland','Coast','No','590','382','330','218','9'),
	array('Holstein (West Coast)','Coast','No','468','446','264','255','0'),
	array('Holstein (East Coast)','Coast','No','492','446','281','255','0')
);

foreach($territoryRawData as $territoryRawRow) 
{
	list($name, $type, $supply, $x, $y, $sx, $sy, $countryID)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);


$bordersRawData=array(
array('Morocco', 'North Africa', 'No', 'Yes'),
array('Morocco', 'Mid-Atlantic Ocean', 'Yes', 'No'),
array('Morocco', 'Western Mediterranean', 'Yes', 'No'),
array('North Africa', 'Morocco', 'Yes', 'Yes'),
array('North Africa', 'Libya', 'Yes', 'Yes'),
array('North Africa', 'Western Mediterranean', 'Yes', 'No'),
array('North Africa', 'Tyrrhenian Sea', 'Yes', 'No'),
array('North Africa', 'Ionian Sea', 'Yes', 'No'),
array('Libya', 'North Africa', 'Yes', 'Yes'),
array('Libya', 'Egypt', 'Yes', 'Yes'),
array('Libya', 'Ionian Sea', 'Yes', 'No'),
array('Libya', 'Eastern Mediterranean', 'Yes', 'No'),
array('Egypt', 'Libya', 'Yes', 'Yes'),
array('Egypt', 'Syria', 'Yes', 'Yes'),
array('Egypt', 'Eastern Mediterranean', 'Yes', 'No'),
array('Syria', 'Egypt', 'Yes', 'Yes'),
array('Syria', 'Anatolia', 'Yes', 'Yes'),
array('Syria', 'Armenia', 'No', 'Yes'),
array('Syria', 'Azerbaijan', 'No', 'Yes'),
array('Syria', 'Persia', 'No', 'Yes'),
array('Syria', 'Eastern Mediterranean', 'Yes', 'No'),
array('Anatolia', 'Syria', 'Yes', 'Yes'),
array('Anatolia', 'Constantinople', 'Yes', 'Yes'),
array('Anatolia', 'Armenia', 'No', 'Yes'),
array('Anatolia', 'Eastern Mediterranean', 'Yes', 'No'),
array('Anatolia', 'Aegean Sea', 'Yes', 'No'),
array('Armenia', 'Constantinople', 'Yes', 'Yes'),
array('Armenia', 'Anatolia', 'No', 'Yes'),
array('Armenia', 'Syria', 'No', 'Yes'),
array('Armenia', 'Azerbaijan', 'No', 'Yes'),
array('Armenia', 'Georgia', 'Yes', 'Yes'),
array('Armenia', 'Black Sea', 'Yes', 'No'),
array('Constantinople', 'Anatolia', 'Yes', 'Yes'),
array('Constantinople', 'Armenia', 'Yes', 'Yes'),
array('Constantinople', 'Bulgaria', 'Yes', 'Yes'),
array('Constantinople', 'Serbia', 'No', 'Yes'),
array('Constantinople', 'Greece', 'Yes', 'Yes'),
array('Constantinople', 'Black Sea', 'Yes', 'No'),
array('Constantinople', 'Aegean Sea', 'Yes', 'No'),
array('Bulgaria', 'Constantinople', 'Yes', 'Yes'),
array('Bulgaria', 'Serbia', 'No', 'Yes'),
array('Bulgaria', 'Transylvania', 'No', 'Yes'),
array('Bulgaria', 'Bessarabia', 'Yes', 'Yes'),
array('Bulgaria', 'Black Sea', 'Yes', 'No'),
array('Greece', 'Constantinople', 'Yes', 'Yes'),
array('Greece', 'Serbia', 'No', 'Yes'),
array('Greece', 'Illyria', 'Yes', 'Yes'),
array('Greece', 'Aegean Sea', 'Yes', 'No'),
array('Greece', 'Ionian Sea', 'Yes', 'No'),
array('Illyria', 'Greece', 'Yes', 'Yes'),
array('Illyria', 'Serbia', 'No', 'Yes'),
array('Illyria', 'Western Hungary', 'No', 'Yes'),
array('Illyria', 'Croatia', 'Yes', 'Yes'),
array('Illyria', 'Adriatic Sea', 'Yes', 'No'),
array('Illyria', 'Ionian Sea', 'Yes', 'No'),
array('Western Mediterranean', 'Mid-Atlantic Ocean', 'Yes', 'No'),
array('Western Mediterranean', 'Morocco', 'Yes', 'No'),
array('Western Mediterranean', 'North Africa', 'Yes', 'No'),
array('Western Mediterranean', 'Tyrrhenian Sea', 'Yes', 'No'),
array('Western Mediterranean', 'Gulf of Lyon', 'Yes', 'No'),
array('Western Mediterranean', 'Aragon', 'Yes', 'No'),
array('Western Mediterranean', 'Granada', 'Yes', 'No'),
array('Gulf of Lyon', 'Western Mediterranean', 'Yes', 'No'),
array('Gulf of Lyon', 'Tyrrhenian Sea', 'Yes', 'No'),
array('Gulf of Lyon', 'Tuscany', 'Yes', 'No'),
array('Gulf of Lyon', 'Provence', 'Yes', 'No'),
array('Gulf of Lyon', 'Languedoc', 'Yes', 'No'),
array('Gulf of Lyon', 'Aragon', 'Yes', 'No'),
array('Tyrrhenian Sea', 'Western Mediterranean', 'Yes', 'No'),
array('Tyrrhenian Sea', 'Gulf of Lyon', 'Yes', 'No'),
array('Tyrrhenian Sea', 'Tuscany', 'Yes', 'No'),
array('Tyrrhenian Sea', 'Rome', 'Yes', 'No'),
array('Tyrrhenian Sea', 'Naples', 'Yes', 'No'),
array('Tyrrhenian Sea', 'Ionian Sea', 'Yes', 'No'),
array('Tyrrhenian Sea', 'North Africa', 'Yes', 'No'),
array('Ionian Sea', 'North Africa', 'Yes', 'No'),
array('Ionian Sea', 'Tyrrhenian Sea', 'Yes', 'No'),
array('Ionian Sea', 'Naples', 'Yes', 'No'),
array('Ionian Sea', 'Adriatic Sea', 'Yes', 'No'),
array('Ionian Sea', 'Illyria', 'Yes', 'No'),
array('Ionian Sea', 'Greece', 'Yes', 'No'),
array('Ionian Sea', 'Aegean Sea', 'Yes', 'No'),
array('Ionian Sea', 'Eastern Mediterranean', 'Yes', 'No'),
array('Ionian Sea', 'Libya', 'Yes', 'No'),
array('Adriatic Sea', 'Naples', 'Yes', 'No'),
array('Adriatic Sea', 'Romagna', 'Yes', 'No'),
array('Adriatic Sea', 'Venice', 'Yes', 'No'),
array('Adriatic Sea', 'Illyria', 'Yes', 'No'),
array('Adriatic Sea', 'Croatia', 'Yes', 'No'),
array('Adriatic Sea', 'Ionian Sea', 'Yes', 'No'),
array('Eastern Mediterranean', 'Ionian Sea', 'Yes', 'No'),
array('Eastern Mediterranean', 'Aegean Sea', 'Yes', 'No'),
array('Eastern Mediterranean', 'Anatolia', 'Yes', 'No'),
array('Eastern Mediterranean', 'Syria', 'Yes', 'No'),
array('Eastern Mediterranean', 'Egypt', 'Yes', 'No'),
array('Eastern Mediterranean', 'Libya', 'Yes', 'No'),
array('Aegean Sea', 'Greece', 'Yes', 'No'),
array('Aegean Sea', 'Constantinople', 'Yes', 'No'),
array('Aegean Sea', 'Anatolia', 'Yes', 'No'),
array('Aegean Sea', 'Eastern Mediterranean', 'Yes', 'No'),
array('Aegean Sea', 'Ionian Sea', 'Yes', 'No'),
array('Black Sea', 'Bulgaria', 'Yes', 'No'),
array('Black Sea', 'Bessarabia', 'Yes', 'No'),
array('Black Sea', 'Crimea', 'Yes', 'No'),
array('Black Sea', 'Georgia', 'Yes', 'No'),
array('Black Sea', 'Armenia', 'Yes', 'No'),
array('Black Sea', 'Constantinople', 'Yes', 'No'),
array('Caspian Sea', 'Azerbaijan', 'Yes', 'No'),
array('Caspian Sea', 'Uralsk', 'Yes', 'No'),
array('Caspian Sea', 'Central Asia', 'Yes', 'No'),
array('Caspian Sea', 'Persia', 'Yes', 'No'),
array('Persia', 'Central Asia', 'Yes', 'Yes'),
array('Persia', 'Syria', 'No', 'Yes'),
array('Persia', 'Azerbaijan', 'Yes', 'Yes'),
array('Persia', 'Caspian Sea', 'Yes', 'No'),
array('Central Asia', 'Persia', 'Yes', 'Yes'),
array('Central Asia', 'Uralsk', 'Yes', 'Yes'),
array('Central Asia', 'Moscow', 'No', 'Yes'),
array('Central Asia', 'Siberia', 'No', 'Yes'),
array('Central Asia', 'Caspian Sea', 'Yes', 'No'),
array('Azerbaijan', 'Uralsk', 'Yes', 'Yes'),
array('Azerbaijan', 'Georgia', 'No', 'Yes'),
array('Azerbaijan', 'Armenia', 'No', 'Yes'),
array('Azerbaijan', 'Syria', 'No', 'Yes'),
array('Azerbaijan', 'Persia', 'Yes', 'Yes'),
array('Azerbaijan', 'Caspian Sea', 'Yes', 'No'),
array('Georgia', 'Crimea', 'Yes', 'Yes'),
array('Georgia', 'Uralsk', 'No', 'Yes'),
array('Georgia', 'Azerbaijan', 'No', 'Yes'),
array('Georgia', 'Armenia', 'Yes', 'Yes'),
array('Georgia', 'Black Sea', 'Yes', 'No'),
array('Crimea', 'Bessarabia', 'Yes', 'Yes'),
array('Crimea', 'Ukraine', 'No', 'Yes'),
array('Crimea', 'Voronezj', 'Yes', 'Yes'),
array('Crimea', 'Uralsk', 'No', 'Yes'),
array('Crimea', 'Georgia', 'Yes', 'Yes'),
array('Crimea', 'Black Sea', 'Yes', 'No'),
array('Bessarabia', 'Transylvania', 'No', 'Yes'),
array('Bessarabia', 'Cracow', 'Yes', 'Yes'),
array('Bessarabia', 'Volhynia', 'No', 'Yes'),
array('Bessarabia', 'Ukraine', 'No', 'Yes'),
array('Bessarabia', 'Crimea', 'Yes', 'Yes'),
array('Bessarabia', 'Bulgaria', 'Yes', 'Yes'),
array('Bessarabia', 'Black Sea', 'Yes', 'No'),
array('Transylvania', 'Eastern Hungary', 'No', 'Yes'),
array('Transylvania', 'Slovakia', 'No', 'Yes'),
array('Transylvania', 'Cracow', 'No', 'Yes'),
array('Transylvania', 'Bessarabia', 'No', 'Yes'),
array('Transylvania', 'Bulgaria', 'No', 'Yes'),
array('Transylvania', 'Serbia', 'No', 'Yes'),
array('Eastern Hungary', 'Western Hungary', 'No', 'Yes'),
array('Eastern Hungary', 'Austria', 'No', 'Yes'),
array('Eastern Hungary', 'Slovakia', 'No', 'Yes'),
array('Eastern Hungary', 'Transylvania', 'No', 'Yes'),
array('Eastern Hungary', 'Serbia', 'No', 'Yes'),
array('Western Hungary', 'Croatia', 'No', 'Yes'),
array('Western Hungary', 'Styria', 'No', 'Yes'),
array('Western Hungary', 'Austria', 'No', 'Yes'),
array('Western Hungary', 'Eastern Hungary', 'No', 'Yes'),
array('Western Hungary', 'Serbia', 'No', 'Yes'),
array('Western Hungary', 'Illyria', 'No', 'Yes'),
array('Serbia', 'Illyria', 'No', 'Yes'),
array('Serbia', 'Western Hungary', 'No', 'Yes'),
array('Serbia', 'Eastern Hungary', 'No', 'Yes'),
array('Serbia', 'Transylvania', 'No', 'Yes'),
array('Serbia', 'Bulgaria', 'No', 'Yes'),
array('Serbia', 'Constantinople', 'No', 'Yes'),
array('Serbia', 'Greece', 'No', 'Yes'),
array('Slovakia', 'Austria', 'No', 'Yes'),
array('Slovakia', 'Moravia', 'No', 'Yes'),
array('Slovakia', 'Cracow', 'No', 'Yes'),
array('Slovakia', 'Transylvania', 'No', 'Yes'),
array('Slovakia', 'Eastern Hungary', 'No', 'Yes'),
array('Moravia', 'Bohemia', 'No', 'Yes'),
array('Moravia', 'Silisia', 'No', 'Yes'),
array('Moravia', 'Little Poland', 'No', 'Yes'),
array('Moravia', 'Cracow', 'No', 'Yes'),
array('Moravia', 'Slovakia', 'No', 'Yes'),
array('Moravia', 'Austria', 'No', 'Yes'),
array('Silisia', 'Saxony', 'No', 'Yes'),
array('Silisia', 'Brandenburg', 'No', 'Yes'),
array('Silisia', 'Great Poland', 'No', 'Yes'),
array('Silisia', 'Little Poland', 'No', 'Yes'),
array('Silisia', 'Moravia', 'No', 'Yes'),
array('Silisia', 'Bohemia', 'No', 'Yes'),
array('Bohemia', 'Bavaria', 'No', 'Yes'),
array('Bohemia', 'Saxony', 'No', 'Yes'),
array('Bohemia', 'Silisia', 'No', 'Yes'),
array('Bohemia', 'Moravia', 'No', 'Yes'),
array('Bohemia', 'Austria', 'No', 'Yes'),
array('Austria', 'Bavaria', 'No', 'Yes'),
array('Austria', 'Bohemia', 'No', 'Yes'),
array('Austria', 'Moravia', 'No', 'Yes'),
array('Austria', 'Slovakia', 'No', 'Yes'),
array('Austria', 'Eastern Hungary', 'No', 'Yes'),
array('Austria', 'Western Hungary', 'No', 'Yes'),
array('Austria', 'Styria', 'No', 'Yes'),
array('Austria', 'Tyrolia', 'No', 'Yes'),
array('Tyrolia', 'Bavaria', 'No', 'Yes'),
array('Tyrolia', 'Austria', 'No', 'Yes'),
array('Tyrolia', 'Styria', 'No', 'Yes'),
array('Tyrolia', 'Venice', 'No', 'Yes'),
array('Styria', 'Venice', 'No', 'Yes'),
array('Styria', 'Tyrolia', 'No', 'Yes'),
array('Styria', 'Austria', 'No', 'Yes'),
array('Styria', 'Western Hungary', 'No', 'Yes'),
array('Styria', 'Croatia', 'No', 'Yes'),
array('Croatia', 'Venice', 'Yes', 'Yes'),
array('Croatia', 'Styria', 'No', 'Yes'),
array('Croatia', 'Western Hungary', 'No', 'Yes'),
array('Croatia', 'Illyria', 'Yes', 'Yes'),
array('Croatia', 'Adriatic Sea', 'Yes', 'No'),
array('Venice', 'Milan', 'No', 'Yes'),
array('Venice', 'Tyrolia', 'No', 'Yes'),
array('Venice', 'Styria', 'No', 'Yes'),
array('Venice', 'Croatia', 'Yes', 'Yes'),
array('Venice', 'Romagna', 'Yes', 'Yes'),
array('Venice', 'Tuscany', 'No', 'Yes'),
array('Venice', 'Adriatic Sea', 'Yes', 'No'),
array('Romagna', 'Tuscany', 'No', 'Yes'),
array('Romagna', 'Venice', 'Yes', 'Yes'),
array('Romagna', 'Rome', 'No', 'Yes'),
array('Romagna', 'Adriatic Sea', 'Yes', 'No'),
array('Romagna', 'Naples', 'Yes', 'No'),
array('Rome', 'Tuscany', 'Yes', 'Yes'),
array('Rome', 'Romagna', 'No', 'Yes'),
array('Rome', 'Naples', 'Yes', 'Yes'),
array('Rome', 'Tyrrhenian Sea', 'Yes', 'No'),
array('Tuscany', 'Provence', 'Yes', 'Yes'),
array('Tuscany', 'Savoy', 'No', 'Yes'),
array('Tuscany', 'Milan', 'No', 'Yes'),
array('Tuscany', 'Venice', 'No', 'Yes'),
array('Tuscany', 'Romagna', 'No', 'Yes'),
array('Tuscany', 'Rome', 'Yes', 'Yes'),
array('Tuscany', 'Gulf of Lyon', 'Yes', 'No'),
array('Tuscany', 'Tyrrhenian Sea', 'Yes', 'No'),
array('Savoy', 'Provence', 'No', 'Yes'),
array('Savoy', 'Burgundy', 'No', 'Yes'),
array('Savoy', 'France Comte', 'No', 'Yes'),
array('Savoy', 'Milan', 'No', 'Yes'),
array('Savoy', 'Tuscany', 'No', 'Yes'),
array('Flanders', 'Normandy', 'Yes', 'Yes'),
array('Flanders', 'Netherlands', 'Yes', 'Yes'),
array('Flanders', 'Westphalia', 'No', 'Yes'),
array('Flanders', 'Lorraine', 'No', 'Yes'),
array('Flanders', 'Champagne', 'No', 'Yes'),
array('Flanders', 'English Channel', 'Yes', 'No'),
array('Flanders', 'North Sea', 'Yes', 'No'),
array('France Comte', 'Burgundy', 'No', 'Yes'),
array('France Comte', 'Champagne', 'No', 'Yes'),
array('France Comte', 'Lorraine', 'No', 'Yes'),
array('France Comte', 'Bavaria', 'No', 'Yes'),
array('France Comte', 'Savoy', 'No', 'Yes'),
array('Milan', 'Savoy', 'No', 'Yes'),
array('Milan', 'Venice', 'No', 'Yes'),
array('Milan', 'Tuscany', 'No', 'Yes'),
array('Naples', 'Rome', 'Yes', 'Yes'),
array('Naples', 'Romagna', 'Yes', 'Yes'),
array('Naples', 'Tyrrhenian Sea', 'Yes', 'No'),
array('Naples', 'Adriatic Sea', 'Yes', 'No'),
array('Naples', 'Ionian Sea', 'Yes', 'No'),
array('Navarre', 'Portugal', 'Yes', 'Yes'),
array('Navarre', 'Gascony', 'Yes', 'Yes'),
array('Navarre', 'Languedoc', 'No', 'Yes'),
array('Navarre', 'Aragon', 'No', 'Yes'),
array('Navarre', 'Castille', 'No', 'Yes'),
array('Navarre', 'Mid-Atlantic Ocean', 'Yes', 'No'),
array('Navarre', 'Bay of Biscay', 'Yes', 'No'),
array('Castille', 'Portugal', 'No', 'Yes'),
array('Castille', 'Navarre', 'No', 'Yes'),
array('Castille', 'Aragon', 'No', 'Yes'),
array('Castille', 'Granada', 'No', 'Yes'),
array('Aragon', 'Granada', 'Yes', 'Yes'),
array('Aragon', 'Castille', 'No', 'Yes'),
array('Aragon', 'Navarre', 'No', 'Yes'),
array('Aragon', 'Gascony', 'No', 'Yes'),
array('Aragon', 'Languedoc', 'Yes', 'Yes'),
array('Aragon', 'Gulf of Lyon', 'Yes', 'No'),
array('Aragon', 'Western Mediterranean', 'Yes', 'No'),
array('Granada', 'Portugal', 'Yes', 'Yes'),
array('Granada', 'Castille', 'No', 'Yes'),
array('Granada', 'Aragon', 'Yes', 'Yes'),
array('Granada', 'Mid-Atlantic Ocean', 'Yes', 'No'),
array('Granada', 'Western Mediterranean', 'Yes', 'No'),
array('Portugal', 'Granada', 'Yes', 'Yes'),
array('Portugal', 'Castille', 'No', 'Yes'),
array('Portugal', 'Navarre', 'Yes', 'Yes'),
array('Portugal', 'Mid-Atlantic Ocean', 'Yes', 'No'),
array('Mid-Atlantic Ocean', 'Morocco', 'Yes', 'No'),
array('Mid-Atlantic Ocean', 'Western Mediterranean', 'Yes', 'No'),
array('Mid-Atlantic Ocean', 'Granada', 'Yes', 'No'),
array('Mid-Atlantic Ocean', 'Portugal', 'Yes', 'No'),
array('Mid-Atlantic Ocean', 'Navarre', 'Yes', 'No'),
array('Mid-Atlantic Ocean', 'Bay of Biscay', 'Yes', 'No'),
array('Mid-Atlantic Ocean', 'English Channel', 'Yes', 'No'),
array('Mid-Atlantic Ocean', 'Irish Sea', 'Yes', 'No'),
array('Mid-Atlantic Ocean', 'North Atlantic Ocean', 'Yes', 'No'),
array('Bay of Biscay', 'Mid-Atlantic Ocean', 'Yes', 'No'),
array('Bay of Biscay', 'English Channel', 'Yes', 'No'),
array('Bay of Biscay', 'Brittany', 'Yes', 'No'),
array('Bay of Biscay', 'Gascony', 'Yes', 'No'),
array('Bay of Biscay', 'Navarre', 'Yes', 'No'),
array('North Atlantic Ocean', 'Arctic Ocean', 'Yes', 'No'),
array('North Atlantic Ocean', 'Norwegian Sea', 'Yes', 'No'),
array('North Atlantic Ocean', 'Scotland', 'Yes', 'No'),
array('North Atlantic Ocean', 'Cumbria', 'Yes', 'No'),
array('North Atlantic Ocean', 'Irish Sea', 'Yes', 'No'),
array('North Atlantic Ocean', 'Ireland', 'Yes', 'No'),
array('North Atlantic Ocean', 'Mid-Atlantic Ocean', 'Yes', 'No'),
array('Irish Sea', 'Mid-Atlantic Ocean', 'Yes', 'No'),
array('Irish Sea', 'North Atlantic Ocean', 'Yes', 'No'),
array('Irish Sea', 'Ireland', 'Yes', 'No'),
array('Irish Sea', 'Cumbria', 'Yes', 'No'),
array('Irish Sea', 'Wales', 'Yes', 'No'),
array('Irish Sea', 'Cornwall', 'Yes', 'No'),
array('Irish Sea', 'English Channel', 'Yes', 'No'),
array('Arctic Ocean', 'Barents Sea', 'Yes', 'No'),
array('Arctic Ocean', 'Norwegian Sea', 'Yes', 'No'),
array('Arctic Ocean', 'North Atlantic Ocean', 'Yes', 'No'),
array('Barents Sea', 'Norwegian Sea', 'Yes', 'No'),
array('Barents Sea', 'Arctic Ocean', 'Yes', 'No'),
array('Barents Sea', 'Siberia', 'Yes', 'No'),
array('Barents Sea', 'Archangel', 'Yes', 'No'),
array('Barents Sea', 'Karelia', 'Yes', 'No'),
array('Barents Sea', 'Troendelag', 'Yes', 'No'),
array('Norwegian Sea', 'North Atlantic Ocean', 'Yes', 'No'),
array('Norwegian Sea', 'Arctic Ocean', 'Yes', 'No'),
array('Norwegian Sea', 'Barents Sea', 'Yes', 'No'),
array('Norwegian Sea', 'Troendelag', 'Yes', 'No'),
array('Norwegian Sea', 'Vestlandet', 'Yes', 'No'),
array('Norwegian Sea', 'Skaggarak', 'Yes', 'No'),
array('Norwegian Sea', 'North Sea', 'Yes', 'No'),
array('Norwegian Sea', 'Scotland', 'Yes', 'No'),
array('North Sea', 'London', 'Yes', 'No'),
array('North Sea', 'Yorkshire', 'Yes', 'No'),
array('North Sea', 'Scotland', 'Yes', 'No'),
array('North Sea', 'Norwegian Sea', 'Yes', 'No'),
array('North Sea', 'Skaggarak', 'Yes', 'No'),
array('North Sea', 'Helgoland Bight', 'Yes', 'No'),
array('North Sea', 'Netherlands', 'Yes', 'No'),
array('North Sea', 'Flanders', 'Yes', 'No'),
array('North Sea', 'English Channel', 'Yes', 'No'),
array('Skaggarak', 'North Sea', 'Yes', 'No'),
array('Skaggarak', 'Norwegian Sea', 'Yes', 'No'),
array('Skaggarak', 'Vestlandet', 'Yes', 'No'),
array('Skaggarak', 'Kattegat', 'Yes', 'No'),
array('Skaggarak', 'Jutland', 'Yes', 'No'),
array('Skaggarak', 'Helgoland Bight', 'Yes', 'No'),
array('Helgoland Bight', 'North Sea', 'Yes', 'No'),
array('Helgoland Bight', 'Skaggarak', 'Yes', 'No'),
array('Helgoland Bight', 'Jutland', 'Yes', 'No'),
array('Helgoland Bight', 'Holstein', 'Yes', 'No'),
array('Helgoland Bight', 'Bremen', 'Yes', 'No'),
array('Helgoland Bight', 'Netherlands', 'Yes', 'No'),
array('English Channel', 'Mid-Atlantic Ocean', 'Yes', 'No'),
array('English Channel', 'Irish Sea', 'Yes', 'No'),
array('English Channel', 'Cornwall', 'Yes', 'No'),
array('English Channel', 'London', 'Yes', 'No'),
array('English Channel', 'North Sea', 'Yes', 'No'),
array('English Channel', 'Flanders', 'Yes', 'No'),
array('English Channel', 'Normandy', 'Yes', 'No'),
array('English Channel', 'Brittany', 'Yes', 'No'),
array('English Channel', 'Bay of Biscay', 'Yes', 'No'),
array('Scotland', 'Cumbria', 'Yes', 'Yes'),
array('Scotland', 'Yorkshire', 'Yes', 'Yes'),
array('Scotland', 'North Atlantic Ocean', 'Yes', 'No'),
array('Scotland', 'Norwegian Sea', 'Yes', 'No'),
array('Scotland', 'North Sea', 'Yes', 'No'),
array('Ireland', 'North Atlantic Ocean', 'Yes', 'No'),
array('Ireland', 'Irish Sea', 'Yes', 'No'),
array('Cumbria', 'Scotland', 'Yes', 'Yes'),
array('Cumbria', 'Yorkshire', 'No', 'Yes'),
array('Cumbria', 'Wales', 'Yes', 'Yes'),
array('Cumbria', 'North Atlantic Ocean', 'Yes', 'No'),
array('Cumbria', 'Irish Sea', 'Yes', 'No'),
array('Yorkshire', 'Wales', 'No', 'Yes'),
array('Yorkshire', 'Cumbria', 'No', 'Yes'),
array('Yorkshire', 'Scotland', 'Yes', 'Yes'),
array('Yorkshire', 'London', 'Yes', 'Yes'),
array('Yorkshire', 'North Sea', 'Yes', 'No'),
array('Wales', 'Cumbria', 'Yes', 'Yes'),
array('Wales', 'Yorkshire', 'No', 'Yes'),
array('Wales', 'London', 'No', 'Yes'),
array('Wales', 'Cornwall', 'Yes', 'Yes'),
array('Wales', 'Irish Sea', 'Yes', 'No'),
array('Cornwall', 'Wales', 'Yes', 'Yes'),
array('Cornwall', 'London', 'Yes', 'Yes'),
array('Cornwall', 'Irish Sea', 'Yes', 'No'),
array('Cornwall', 'English Channel', 'Yes', 'No'),
array('London', 'Cornwall', 'Yes', 'Yes'),
array('London', 'Wales', 'No', 'Yes'),
array('London', 'Yorkshire', 'Yes', 'Yes'),
array('London', 'North Sea', 'Yes', 'No'),
array('London', 'English Channel', 'Yes', 'No'),
array('Brittany', 'Normandy', 'Yes', 'Yes'),
array('Brittany', 'Paris', 'No', 'Yes'),
array('Brittany', 'Gascony', 'Yes', 'Yes'),
array('Brittany', 'Bay of Biscay', 'Yes', 'No'),
array('Brittany', 'English Channel', 'Yes', 'No'),
array('Normandy', 'Brittany', 'Yes', 'Yes'),
array('Normandy', 'Flanders', 'Yes', 'Yes'),
array('Normandy', 'Champagne', 'No', 'Yes'),
array('Normandy', 'Paris', 'No', 'Yes'),
array('Normandy', 'English Channel', 'Yes', 'No'),
array('Champagne', 'Paris', 'No', 'Yes'),
array('Champagne', 'Normandy', 'No', 'Yes'),
array('Champagne', 'Flanders', 'No', 'Yes'),
array('Champagne', 'Lorraine', 'No', 'Yes'),
array('Champagne', 'France Comte', 'No', 'Yes'),
array('Champagne', 'Burgundy', 'No', 'Yes'),
array('Paris', 'Brittany', 'No', 'Yes'),
array('Paris', 'Normandy', 'No', 'Yes'),
array('Paris', 'Champagne', 'No', 'Yes'),
array('Paris', 'Burgundy', 'No', 'Yes'),
array('Paris', 'Gascony', 'No', 'Yes'),
array('Gascony', 'Brittany', 'Yes', 'Yes'),
array('Gascony', 'Paris', 'No', 'Yes'),
array('Gascony', 'Burgundy', 'No', 'Yes'),
array('Gascony', 'Languedoc', 'No', 'Yes'),
array('Gascony', 'Navarre', 'Yes', 'Yes'),
array('Gascony', 'Bay of Biscay', 'Yes', 'No'),
array('Burgundy', 'Gascony', 'No', 'Yes'),
array('Burgundy', 'Paris', 'No', 'Yes'),
array('Burgundy', 'Champagne', 'No', 'Yes'),
array('Burgundy', 'France Comte', 'No', 'Yes'),
array('Burgundy', 'Savoy', 'No', 'Yes'),
array('Burgundy', 'Provence', 'No', 'Yes'),
array('Burgundy', 'Languedoc', 'No', 'Yes'),
array('Languedoc', 'Navarre', 'No', 'Yes'),
array('Languedoc', 'Gascony', 'No', 'Yes'),
array('Languedoc', 'Burgundy', 'No', 'Yes'),
array('Languedoc', 'Provence', 'Yes', 'Yes'),
array('Languedoc', 'Aragon', 'Yes', 'Yes'),
array('Languedoc', 'Gulf of Lyon', 'Yes', 'No'),
array('Provence', 'Languedoc', 'Yes', 'Yes'),
array('Provence', 'Burgundy', 'No', 'Yes'),
array('Provence', 'Savoy', 'No', 'Yes'),
array('Provence', 'Tuscany', 'Yes', 'Yes'),
array('Provence', 'Gulf of Lyon', 'Yes', 'No'),
array('Lorraine', 'Champagne', 'No', 'Yes'),
array('Lorraine', 'Flanders', 'No', 'Yes'),
array('Lorraine', 'Westphalia', 'No', 'Yes'),
array('Lorraine', 'Hesse', 'No', 'Yes'),
array('Lorraine', 'Saxony', 'No', 'Yes'),
array('Lorraine', 'Bavaria', 'No', 'Yes'),
array('Lorraine', 'France Comte', 'No', 'Yes'),
array('Bavaria', 'France Comte', 'No', 'Yes'),
array('Bavaria', 'Lorraine', 'No', 'Yes'),
array('Bavaria', 'Saxony', 'No', 'Yes'),
array('Bavaria', 'Bohemia', 'No', 'Yes'),
array('Bavaria', 'Austria', 'No', 'Yes'),
array('Bavaria', 'Tyrolia', 'No', 'Yes'),
array('Saxony', 'Lorraine', 'No', 'Yes'),
array('Saxony', 'Hesse', 'No', 'Yes'),
array('Saxony', 'Brandenburg', 'No', 'Yes'),
array('Saxony', 'Silisia', 'No', 'Yes'),
array('Saxony', 'Bohemia', 'No', 'Yes'),
array('Saxony', 'Bavaria', 'No', 'Yes'),
array('Hesse', 'Westphalia', 'No', 'Yes'),
array('Hesse', 'Bremen', 'No', 'Yes'),
array('Hesse', 'Mecklenburg', 'No', 'Yes'),
array('Hesse', 'Brandenburg', 'No', 'Yes'),
array('Hesse', 'Saxony', 'No', 'Yes'),
array('Hesse', 'Lorraine', 'No', 'Yes'),
array('Westphalia', 'Flanders', 'No', 'Yes'),
array('Westphalia', 'Netherlands', 'No', 'Yes'),
array('Westphalia', 'Bremen', 'No', 'Yes'),
array('Westphalia', 'Hesse', 'No', 'Yes'),
array('Westphalia', 'Lorraine', 'No', 'Yes'),
array('Netherlands', 'Bremen', 'Yes', 'Yes'),
array('Netherlands', 'Westphalia', 'No', 'Yes'),
array('Netherlands', 'Flanders', 'Yes', 'Yes'),
array('Netherlands', 'North Sea', 'Yes', 'No'),
array('Netherlands', 'Helgoland Bight', 'Yes', 'No'),
array('Bremen', 'Netherlands', 'Yes', 'Yes'),
array('Bremen', 'Holstein', 'Yes', 'Yes'),
array('Bremen', 'Mecklenburg', 'No', 'Yes'),
array('Bremen', 'Hesse', 'No', 'Yes'),
array('Bremen', 'Westphalia', 'No', 'Yes'),
array('Bremen', 'Helgoland Bight', 'Yes', 'No'),
array('Holstein', 'Jutland', 'No', 'Yes'),
array('Holstein', 'Mecklenburg', 'No', 'Yes'),
array('Holstein', 'Bremen', 'No', 'Yes'),
array('Holstein', 'Zealand', 'No', 'Yes'),
array('Holstein (West Coast)', 'Bremen', 'Yes', 'No'),
array('Holstein (West Coast)', 'Helgoland Bight', 'Yes', 'No'),
array('Holstein (West Coast)', 'Jutland', 'Yes', 'No'),
array('Holstein (East Coast)', 'Mecklenburg', 'Yes', 'No'),
array('Holstein (East Coast)', 'Jutland', 'Yes', 'No'),
array('Holstein (East Coast)', 'Zealand', 'Yes', 'No'),
array('Holstein (East Coast)', 'Sea of Bornholm', 'Yes', 'No'),
array('Mecklenburg', 'Bremen', 'No', 'Yes'),
array('Mecklenburg', 'Holstein', 'Yes', 'Yes'),
array('Mecklenburg', 'Pomerania', 'Yes', 'Yes'),
array('Mecklenburg', 'Brandenburg', 'No', 'Yes'),
array('Mecklenburg', 'Hesse', 'No', 'Yes'),
array('Mecklenburg', 'Sea of Bornholm', 'Yes', 'No'),
array('Pomerania', 'Mecklenburg', 'Yes', 'Yes'),
array('Pomerania', 'Pomerelia', 'Yes', 'Yes'),
array('Pomerania', 'Brandenburg', 'No', 'Yes'),
array('Pomerania', 'Sea of Bornholm', 'Yes', 'No'),
array('Pomerania', 'Baltic Sea', 'Yes', 'No'),
array('Brandenburg', 'Hesse', 'No', 'Yes'),
array('Brandenburg', 'Mecklenburg', 'No', 'Yes'),
array('Brandenburg', 'Pomerania', 'No', 'Yes'),
array('Brandenburg', 'Pomerelia', 'No', 'Yes'),
array('Brandenburg', 'Great Poland', 'No', 'Yes'),
array('Brandenburg', 'Silisia', 'No', 'Yes'),
array('Brandenburg', 'Saxony', 'No', 'Yes'),
array('Prussia', 'Pomerelia', 'Yes', 'Yes'),
array('Prussia', 'Livonia', 'Yes', 'Yes'),
array('Prussia', 'Mazovia', 'No', 'Yes'),
array('Prussia', 'Baltic Sea', 'Yes', 'No'),
array('Great Poland', 'Brandenburg', 'No', 'Yes'),
array('Great Poland', 'Pomerelia', 'No', 'Yes'),
array('Great Poland', 'Warsaw', 'No', 'Yes'),
array('Great Poland', 'Little Poland', 'No', 'Yes'),
array('Great Poland', 'Silisia', 'No', 'Yes'),
array('Pomerelia', 'Pomerania', 'Yes', 'Yes'),
array('Pomerelia', 'Prussia', 'Yes', 'Yes'),
array('Pomerelia', 'Mazovia', 'No', 'Yes'),
array('Pomerelia', 'Warsaw', 'Yes', 'Yes'),
array('Pomerelia', 'Great Poland', 'No', 'Yes'),
array('Pomerelia', 'Brandenburg', 'No', 'Yes'),
array('Pomerelia', 'Baltic Sea', 'Yes', 'No'),
array('Mazovia', 'Pomerelia', 'No', 'Yes'),
array('Mazovia', 'Prussia', 'No', 'Yes'),
array('Mazovia', 'White Russia', 'No', 'Yes'),
array('Mazovia', 'Livonia', 'No', 'Yes'),
array('Mazovia', 'Warsaw', 'No', 'Yes'),
array('Livonia', 'Estonia', 'Yes', 'Yes'),
array('Livonia', 'Pskov', 'No', 'Yes'),
array('Livonia', 'White Russia', 'No', 'Yes'),
array('Livonia', 'Mazovia', 'No', 'Yes'),
array('Livonia', 'Prussia', 'Yes', 'Yes'),
array('Livonia', 'Baltic Sea', 'Yes', 'No'),
array('White Russia', 'Mazovia', 'No', 'Yes'),
array('White Russia', 'Livonia', 'No', 'Yes'),
array('White Russia', 'Pskov', 'No', 'Yes'),
array('White Russia', 'Tula', 'No', 'Yes'),
array('White Russia', 'Ukraine', 'No', 'Yes'),
array('White Russia', 'Volhynia', 'No', 'Yes'),
array('White Russia', 'Warsaw', 'No', 'Yes'),
array('Warsaw', 'Great Poland', 'No', 'Yes'),
array('Warsaw', 'Pomerelia', 'Yes', 'Yes'),
array('Warsaw', 'Mazovia', 'No', 'Yes'),
array('Warsaw', 'White Russia', 'No', 'Yes'),
array('Warsaw', 'Volhynia', 'No', 'Yes'),
array('Warsaw', 'Cracow', 'No', 'Yes'),
array('Warsaw', 'Little Poland', 'No', 'Yes'),
array('Little Poland', 'Silisia', 'No', 'Yes'),
array('Little Poland', 'Great Poland', 'No', 'Yes'),
array('Little Poland', 'Warsaw', 'No', 'Yes'),
array('Little Poland', 'Cracow', 'No', 'Yes'),
array('Little Poland', 'Moravia', 'No', 'Yes'),
array('Cracow', 'Moravia', 'No', 'Yes'),
array('Cracow', 'Little Poland', 'No', 'Yes'),
array('Cracow', 'Warsaw', 'No', 'Yes'),
array('Cracow', 'Volhynia', 'No', 'Yes'),
array('Cracow', 'Bessarabia', 'Yes', 'Yes'),
array('Cracow', 'Transylvania', 'No', 'Yes'),
array('Cracow', 'Slovakia', 'No', 'Yes'),
array('Volhynia', 'Cracow', 'No', 'Yes'),
array('Volhynia', 'Warsaw', 'No', 'Yes'),
array('Volhynia', 'White Russia', 'No', 'Yes'),
array('Volhynia', 'Ukraine', 'No', 'Yes'),
array('Volhynia', 'Bessarabia', 'No', 'Yes'),
array('Ukraine', 'Volhynia', 'No', 'Yes'),
array('Ukraine', 'White Russia', 'No', 'Yes'),
array('Ukraine', 'Tula', 'No', 'Yes'),
array('Ukraine', 'Voronezj', 'No', 'Yes'),
array('Ukraine', 'Crimea', 'No', 'Yes'),
array('Ukraine', 'Bessarabia', 'No', 'Yes'),
array('Voronezj', 'Ukraine', 'No', 'Yes'),
array('Voronezj', 'Tula', 'No', 'Yes'),
array('Voronezj', 'Moscow', 'No', 'Yes'),
array('Voronezj', 'Uralsk', 'No', 'Yes'),
array('Voronezj', 'Crimea', 'Yes', 'Yes'),
array('Uralsk', 'Crimea', 'No', 'Yes'),
array('Uralsk', 'Voronezj', 'No', 'Yes'),
array('Uralsk', 'Moscow', 'No', 'Yes'),
array('Uralsk', 'Central Asia', 'Yes', 'Yes'),
array('Uralsk', 'Azerbaijan', 'Yes', 'Yes'),
array('Uralsk', 'Georgia', 'No', 'Yes'),
array('Uralsk', 'Caspian Sea', 'Yes', 'No'),
array('Moscow', 'Tula', 'No', 'Yes'),
array('Moscow', 'Novgorod', 'No', 'Yes'),
array('Moscow', 'Archangel', 'No', 'Yes'),
array('Moscow', 'Siberia', 'No', 'Yes'),
array('Moscow', 'Central Asia', 'No', 'Yes'),
array('Moscow', 'Uralsk', 'No', 'Yes'),
array('Moscow', 'Voronezj', 'No', 'Yes'),
array('Tula', 'White Russia', 'No', 'Yes'),
array('Tula', 'Pskov', 'No', 'Yes'),
array('Tula', 'Novgorod', 'No', 'Yes'),
array('Tula', 'Moscow', 'No', 'Yes'),
array('Tula', 'Voronezj', 'No', 'Yes'),
array('Tula', 'Ukraine', 'No', 'Yes'),
array('Pskov', 'Estonia', 'No', 'Yes'),
array('Pskov', 'Ingria', 'No', 'Yes'),
array('Pskov', 'Novgorod', 'No', 'Yes'),
array('Pskov', 'Tula', 'No', 'Yes'),
array('Pskov', 'White Russia', 'No', 'Yes'),
array('Pskov', 'Livonia', 'No', 'Yes'),
array('Novgorod', 'Ingria', 'Yes', 'Yes'),
array('Novgorod', 'Karelia', 'No', 'Yes'),
array('Novgorod', 'Archangel', 'No', 'Yes'),
array('Novgorod', 'Moscow', 'No', 'Yes'),
array('Novgorod', 'Tula', 'No', 'Yes'),
array('Novgorod', 'Pskov', 'No', 'Yes'),
array('Siberia', 'Central Asia', 'No', 'Yes'),
array('Siberia', 'Archangel', 'Yes', 'Yes'),
array('Siberia', 'Moscow', 'No', 'Yes'),
array('Siberia', 'Barents Sea', 'Yes', 'No'),
array('Archangel', 'Ingria', 'No', 'Yes'),
array('Archangel', 'Karelia', 'Yes', 'Yes'),
array('Archangel', 'Siberia', 'Yes', 'Yes'),
array('Archangel', 'Moscow', 'No', 'Yes'),
array('Archangel', 'Novgorod', 'No', 'Yes'),
array('Archangel', 'Barents Sea', 'Yes', 'No'),
array('Karelia', 'Lappland', 'No', 'Yes'),
array('Karelia', 'Finland', 'No', 'Yes'),
array('Karelia', 'Troendelag', 'Yes', 'Yes'),
array('Karelia', 'Archangel', 'Yes', 'Yes'),
array('Karelia', 'Ingria', 'No', 'Yes'),
array('Karelia', 'Barents Sea', 'Yes', 'No'),
array('Ingria', 'Finland', 'Yes', 'Yes'),
array('Ingria', 'Archangel', 'No', 'Yes'),
array('Ingria', 'Novgorod', 'Yes', 'Yes'),
array('Ingria', 'Pskov', 'No', 'Yes'),
array('Ingria', 'Estonia', 'Yes', 'Yes'),
array('Ingria', 'Karelia', 'No', 'Yes'),
array('Ingria', 'Gulf of Bothnia', 'Yes', 'No'),
array('Gulf of Bothnia', 'Stockholm', 'Yes', 'No'),
array('Gulf of Bothnia', 'Finland', 'Yes', 'No'),
array('Gulf of Bothnia', 'Ingria', 'Yes', 'No'),
array('Gulf of Bothnia', 'Estonia', 'Yes', 'No'),
array('Gulf of Bothnia', 'Baltic Sea', 'Yes', 'No'),
array('Baltic Sea', 'Smaland', 'Yes', 'No'),
array('Baltic Sea', 'Stockholm', 'Yes', 'No'),
array('Baltic Sea', 'Gulf of Bothnia', 'Yes', 'No'),
array('Baltic Sea', 'Estonia', 'Yes', 'No'),
array('Baltic Sea', 'Livonia', 'Yes', 'No'),
array('Baltic Sea', 'Prussia', 'Yes', 'No'),
array('Baltic Sea', 'Pomerelia', 'Yes', 'No'),
array('Baltic Sea', 'Pomerania', 'Yes', 'No'),
array('Baltic Sea', 'Sea of Bornholm', 'Yes', 'No'),
array('Baltic Sea', 'Scania', 'Yes', 'No'),
array('Sea of Bornholm', 'Holstein', 'Yes', 'No'),
array('Sea of Bornholm', 'Zealand', 'Yes', 'No'),
array('Sea of Bornholm', 'Scania', 'Yes', 'No'),
array('Sea of Bornholm', 'Smaland', 'Yes', 'No'),
array('Sea of Bornholm', 'Baltic Sea', 'Yes', 'No'),
array('Sea of Bornholm', 'Pomerania', 'Yes', 'No'),
array('Sea of Bornholm', 'Mecklenburg', 'Yes', 'No'),
array('Sea of Bornholm', 'Kattegat', 'Yes', 'No'),
array('Kattegat', 'Skaggarak', 'Yes', 'No'),
array('Kattegat', 'Vestlandet', 'Yes', 'No'),
array('Kattegat', 'Ostlandet', 'Yes', 'No'),
array('Kattegat', 'West Gothland', 'Yes', 'No'),
array('Kattegat', 'Scania', 'Yes', 'No'),
array('Kattegat', 'Sea of Bornholm', 'Yes', 'No'),
array('Kattegat', 'Zealand', 'Yes', 'No'),
array('Kattegat', 'Jutland', 'Yes', 'No'),
array('Jutland', 'Holstein', 'Yes', 'Yes'),
array('Jutland', 'Zealand', 'Yes', 'Yes'),
array('Jutland', 'Helgoland Bight', 'Yes', 'No'),
array('Jutland', 'Skaggarak', 'Yes', 'No'),
array('Jutland', 'Kattegat', 'Yes', 'No'),
array('Scania', 'West Gothland', 'Yes', 'Yes'),
array('Scania', 'Smaland', 'Yes', 'Yes'),
array('Scania', 'Kattegat', 'Yes', 'No'),
array('Scania', 'Sea of Bornholm', 'Yes', 'No'),
array('Zealand', 'Jutland', 'Yes', 'Yes'),
array('Zealand', 'Holstein', 'Yes', 'Yes'),
array('Zealand', 'Kattegat', 'Yes', 'No'),
array('Zealand', 'Sea of Bornholm', 'Yes', 'No'),
array('Ostlandet', 'Vestlandet', 'Yes', 'Yes'),
array('Ostlandet', 'Troendelag', 'No', 'Yes'),
array('Ostlandet', 'Stockholm', 'No', 'Yes'),
array('Ostlandet', 'Bergslagen', 'No', 'Yes'),
array('Ostlandet', 'West Gothland', 'Yes', 'Yes'),
array('Ostlandet', 'Kattegat', 'Yes', 'No'),
array('Vestlandet', 'Troendelag', 'Yes', 'Yes'),
array('Vestlandet', 'Ostlandet', 'Yes', 'Yes'),
array('Vestlandet', 'Norwegian Sea', 'Yes', 'No'),
array('Vestlandet', 'Kattegat', 'Yes', 'No'),
array('Vestlandet', 'Skaggarak', 'Yes', 'No'),
array('Troendelag', 'Vestlandet', 'Yes', 'Yes'),
array('Troendelag', 'Karelia', 'Yes', 'Yes'),
array('Troendelag', 'Lappland', 'No', 'Yes'),
array('Troendelag', 'Stockholm', 'No', 'Yes'),
array('Troendelag', 'Ostlandet', 'No', 'Yes'),
array('Troendelag', 'Norwegian Sea', 'Yes', 'No'),
array('Troendelag', 'Barents Sea', 'Yes', 'No'),
array('Lappland', 'Troendelag', 'No', 'Yes'),
array('Lappland', 'Karelia', 'No', 'Yes'),
array('Lappland', 'Finland', 'No', 'Yes'),
array('Lappland', 'Stockholm', 'No', 'Yes'),
array('Finland', 'Stockholm', 'Yes', 'Yes'),
array('Finland', 'Lappland', 'No', 'Yes'),
array('Finland', 'Karelia', 'No', 'Yes'),
array('Finland', 'Ingria', 'Yes', 'Yes'),
array('Finland', 'Gulf of Bothnia', 'Yes', 'No'),
array('Estonia', 'Ingria', 'Yes', 'Yes'),
array('Estonia', 'Pskov', 'No', 'Yes'),
array('Estonia', 'Livonia', 'Yes', 'Yes'),
array('Estonia', 'Baltic Sea', 'Yes', 'No'),
array('Estonia', 'Gulf of Bothnia', 'Yes', 'No'),
array('Stockholm', 'Ostlandet', 'No', 'Yes'),
array('Stockholm', 'Troendelag', 'No', 'Yes'),
array('Stockholm', 'Lappland', 'No', 'Yes'),
array('Stockholm', 'Finland', 'Yes', 'Yes'),
array('Stockholm', 'Smaland', 'Yes', 'Yes'),
array('Stockholm', 'Bergslagen', 'No', 'Yes'),
array('Stockholm', 'Baltic Sea', 'Yes', 'No'),
array('Stockholm', 'Gulf of Bothnia', 'Yes', 'No'),
array('Bergslagen', 'Ostlandet', 'No', 'Yes'),
array('Bergslagen', 'Stockholm', 'No', 'Yes'),
array('Bergslagen', 'West Gothland', 'No', 'Yes'),
array('West Gothland', 'Ostlandet', 'Yes', 'Yes'),
array('West Gothland', 'Bergslagen', 'No', 'Yes'),
array('West Gothland', 'Smaland', 'No', 'Yes'),
array('West Gothland', 'Scania', 'Yes', 'Yes'),
array('West Gothland', 'Kattegat', 'Yes', 'No'),
array('Smaland', 'Scania', 'Yes', 'Yes'),
array('Smaland', 'West Gothland', 'No', 'Yes'),
array('Smaland', 'Stockholm', 'Yes', 'Yes'),
array('Smaland', 'Sea of Bornholm', 'Yes', 'No'),
array('Smaland', 'Baltic Sea', 'Yes', 'No'),
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
