<?php
// This is file installs the map data for the Imperium variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Alamanni', 'Land', 'No', 1, 438, 245, 217, 121),
	array('Langobardi', 'Land', 'No', 1, 480, 104, 246, 53),
	array('Quadi', 'Land', 'No', 1, 650, 225, 327, 112),
	array('Vandales', 'Land', 'No', 6, 490, 205, 244, 102),
	array('Asdingi', 'Land', 'No', 6, 750, 235, 365, 121),
	array('Silingi', 'Land', 'No', 6, 640, 130, 320, 62),
	array('Ostrogothi', 'Coast', 'No', 3, 1092, 269, 540, 148),
	array('Visigothi', 'Land', 'No', 3, 845, 230, 423, 118),
	array('Dacia', 'Coast', 'No', 3, 725, 425, 351, 228),
	array('Franci', 'Land', 'No', 2, 404, 120, 202, 62),
	array('Ripuari', 'Land', 'No', 2, 530, 143, 265, 72),
	array('Suebi', 'Land', 'No', 2, 586, 212, 293, 107),
	array('Hunni Primi', 'Land', 'No', 4, 690, 48, 346, 27),
	array('Hunni Secundi', 'Land', 'No', 4, 720, 178, 362, 89),
	array('Hunni Terti', 'Land', 'No', 4, 800, 98, 395, 58),
	array('Hunni Quarti', 'Coast', 'No', 4, 932, 310, 466, 156),
	array('Jutii', 'Coast', 'No', 5, 440, 67, 225, 38),
	array('Iazygi', 'Land', 'No', 5, 780, 340, 400, 180),
	array('Teutones', 'Land', 'No', 5, 444, 162, 222, 82),
	array('Mare Adriaticum', 'Sea', 'No', 0, 585, 415, 310, 225),
	array('Aegaeis', 'Sea', 'No', 0, 830, 592, 417, 300),
	array('Aemilia', 'Land', 'No', 0, 461, 333, 231, 163),
	array('Alexandria', 'Coast', 'Yes', 0, 968, 772, 487, 388),
	array('Alpes', 'Coast', 'No', 0, 412, 375, 205, 175),
	array('Ancona', 'Coast', 'Yes', 0, 540, 426, 268, 216),
	array('Antiochia', 'Coast', 'Yes', 0, 1112, 625, 558, 310),
	array('Aquitania', 'Coast', 'No', 0, 250, 330, 130, 163),
	array('Athenum', 'Coast', 'Yes', 0, 765, 583, 380, 292),
	array('Oceanus Atlanticus', 'Sea', 'No', 0, 35, 330, 16, 165),
	array('Baetica', 'Coast', 'No', 0, 150, 570, 75, 280),
	array('Baleares', 'Sea', 'No', 0, 350, 542, 181, 271),
	array('Belgica', 'Coast', 'No', 0, 294, 176, 147, 89),
	array('Oceanus Britannicus', 'Sea', 'No', 0, 50, 178, 20, 95),
	array('Brundisium', 'Coast', 'Yes', 0, 622, 505, 311, 247),
	array('Burdigala', 'Coast', 'Yes', 0, 214, 398, 110, 198),
	array('Byzantium', 'Coast', 'Yes', 0, 900, 484, 473, 247),
	array('Mare Cantabricum', 'Sea', 'No', 0, 122, 340, 65, 168),
	array('Capova', 'Coast', 'Yes', 0, 570, 493, 290, 249),
	array('Carthago', 'Coast', 'Yes', 0, 430, 630, 215, 313),
	array('Chatti', 'Land', 'No', 0, 577, 178, 290, 88),
	array('Chersonesus', 'Coast', 'Yes', 0, 1035, 343, 519, 173),
	array('Colonia Agrippa', 'Coast', 'Yes', 0, 365, 180, 185, 95),
	array('Mare Cypris', 'Sea', 'No', 0, 950, 680, 462, 340),
	array('Dalmatia', 'Coast', 'No', 0, 630, 375, 305, 195),
	array('Eburacum', 'Coast', 'Yes', 0, 170, 32, 86, 10),
	array('Eburacum (West Coast)', 'Coast', 'No', 0, 140, 30, 70, 11),
	array('Eburacum (East Coast)', 'Coast', 'No', 0, 215, 40, 108, 20),
	array('Pontus Euxinus', 'Sea', 'No', 0, 1030, 414, 502, 205),
	array('Flavia Caesarensis', 'Coast', 'No', 0, 142, 88, 73, 50),
	array('Frisii', 'Coast', 'No', 0, 375, 78, 189, 42),
	array('Galatia', 'Coast', 'No', 0, 970, 538, 490, 269),
	array('Genova', 'Coast', 'Yes', 0, 466, 374, 234, 187),
	array('Mare Germanicum', 'Sea', 'No', 0, 330, 30, 160, 22),
	array('Haithabu', 'Coast', 'Yes', 0, 532, 50, 268, 30),
	array('Mare Internum', 'Sea', 'No', 0, 664, 668, 335, 340),
	array('Mare Ionium', 'Sea', 'No', 0, 668, 566, 337, 282),
	array('Mare Ligusticum', 'Sea', 'No', 0, 412, 430, 206, 218),
	array('Londinum', 'Coast', 'Yes', 0, 170, 141, 95, 74),
	array('Lugdunensis', 'Coast', 'No', 0, 206, 257, 75, 128),
	array('Lutetia', 'Land', 'Yes', 0, 300, 245, 155, 124),
	array('Lybia', 'Coast', 'No', 0, 765, 755, 382, 378),
	array('Macedonia', 'Coast', 'No', 0, 742, 512, 368, 252),
	array('Macedonia (West Coast)', 'Coast', 'No', 0, 700, 508, 351, 252),
	array('Macedonia (East Coast)', 'Coast', 'No', 0, 775, 525, 397, 257),
	array('Massilia', 'Coast', 'Yes', 0, 375, 400, 187, 196),
	array('Mauretania', 'Coast', 'No', 0, 220, 694, 110, 347),
	array('Maxima Caesarensis', 'Coast', 'No', 0, 194, 84, 97, 44),
	array('Miletus', 'Coast', 'Yes', 0, 920, 580, 459, 289),
	array('Narbonensis', 'Coast', 'No', 0, 285, 420, 152, 203),
	array('Numidia', 'Coast', 'No', 0, 496, 754, 248, 372),
	array('Olisipo', 'Coast', 'Yes', 0, 55, 528, 20, 268),
	array('Orientes', 'Coast', 'No', 0, 1110, 730, 555, 358),
	array('Pontica', 'Coast', 'No', 0, 1080, 492, 550, 255),
	array('Ravenna', 'Coast', 'Yes', 0, 505, 382, 259, 191),
	array('Castra Regina', 'Land', 'Yes', 0, 494, 263, 244, 134),
	array('Rhegium', 'Coast', 'Yes', 0, 610, 535, 310, 273),
	array('Roma', 'Coast', 'Yes', 0, 535, 463, 270, 232),
	array('Rotomagus', 'Coast', 'Yes', 0, 249, 215, 105, 113),
	array('Saguntum', 'Coast', 'Yes', 0, 217, 500, 120, 241),
	array('Samnium', 'Coast', 'No', 0, 580, 460, 296, 239),
	array('Litus Saxonicum', 'Sea', 'No', 0, 240, 177, 115, 91),
	array('Scytia', 'Coast', 'No', 0, 870, 418, 439, 209),
	array('Sequanorum', 'Land', 'No', 0, 385, 285, 192, 142),
	array('Syracusae', 'Coast', 'Yes', 0, 560, 586, 285, 295),
	array('Taraconensis', 'Coast', 'No', 0, 135, 445, 40, 220),
	array('Thracia', 'Coast', 'No', 0, 835, 457, 417, 240),
	array('Tuscia', 'Coast', 'No', 0, 495, 423, 248, 213),
	array('Mare Tyrrhenicum', 'Sea', 'No', 0, 520, 520, 255, 263),
	array('Verona', 'Coast', 'Yes', 0, 525, 328, 264, 163),
	array('Viennensis', 'Land', 'No', 0, 336, 310, 169, 140),
	array('Vindobona', 'Land', 'Yes', 0, 616, 296, 308, 148)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Alamanni','Vandales','No','Yes'),
	array('Alamanni','Colonia Agrippa','No','Yes'),
	array('Alamanni','Castra Regina','No','Yes'),
	array('Alamanni','Sequanorum','No','Yes'),
	array('Langobardi','Franci','No','Yes'),
	array('Langobardi','Ripuari','No','Yes'),
	array('Langobardi','Jutii','No','Yes'),
	array('Langobardi','Teutones','No','Yes'),
	array('Langobardi','Haithabu','No','Yes'),
	array('Quadi','Asdingi','No','Yes'),
	array('Quadi','Suebi','No','Yes'),
	array('Quadi','Hunni Secundi','No','Yes'),
	array('Quadi','Vindobona','No','Yes'),
	array('Vandales','Ripuari','No','Yes'),
	array('Vandales','Suebi','No','Yes'),
	array('Vandales','Teutones','No','Yes'),
	array('Vandales','Chatti','No','Yes'),
	array('Vandales','Colonia Agrippa','No','Yes'),
	array('Vandales','Castra Regina','No','Yes'),
	array('Asdingi','Visigothi','No','Yes'),
	array('Asdingi','Hunni Secundi','No','Yes'),
	array('Asdingi','Iazygi','No','Yes'),
	array('Asdingi','Vindobona','No','Yes'),
	array('Silingi','Ripuari','No','Yes'),
	array('Silingi','Suebi','No','Yes'),
	array('Silingi','Hunni Primi','No','Yes'),
	array('Silingi','Hunni Secundi','No','Yes'),
	array('Silingi','Hunni Terti','No','Yes'),
	array('Silingi','Chatti','No','Yes'),
	array('Silingi','Haithabu','No','Yes'),
	array('Ostrogothi','Hunni Terti','No','Yes'),
	array('Ostrogothi','Hunni Quarti','No','Yes'),
	array('Ostrogothi','Chersonesus','Yes','Yes'),
	array('Ostrogothi','Pontus Euxinus','Yes','No'),
	array('Visigothi','Hunni Secundi','No','Yes'),
	array('Visigothi','Hunni Terti','No','Yes'),
	array('Visigothi','Hunni Quarti','No','Yes'),
	array('Visigothi','Iazygi','No','Yes'),
	array('Dacia','Iazygi','No','Yes'),
	array('Dacia','Mare Adriaticum','Yes','No'),
	array('Dacia','Dalmatia','Yes','Yes'),
	array('Dacia','Macedonia','No','Yes'),
	array('Dacia','Macedonia (West Coast)','Yes','No'),
	array('Dacia','Thracia','No','Yes'),
	array('Franci','Jutii','No','Yes'),
	array('Franci','Teutones','No','Yes'),
	array('Franci','Colonia Agrippa','No','Yes'),
	array('Franci','Frisii','No','Yes'),
	array('Ripuari','Teutones','No','Yes'),
	array('Ripuari','Chatti','No','Yes'),
	array('Ripuari','Haithabu','No','Yes'),
	array('Suebi','Hunni Secundi','No','Yes'),
	array('Suebi','Chatti','No','Yes'),
	array('Suebi','Castra Regina','No','Yes'),
	array('Suebi','Vindobona','No','Yes'),
	array('Hunni Primi','Hunni Terti','No','Yes'),
	array('Hunni Primi','Haithabu','No','Yes'),
	array('Hunni Secundi','Hunni Terti','No','Yes'),
	array('Hunni Terti','Hunni Quarti','No','Yes'),
	array('Hunni Quarti','Iazygi','No','Yes'),
	array('Hunni Quarti','Chersonesus','Yes','Yes'),
	array('Hunni Quarti','Pontus Euxinus','Yes','No'),
	array('Hunni Quarti','Scytia','Yes','Yes'),
	array('Jutii','Frisii','Yes','Yes'),
	array('Jutii','Mare Germanicum','Yes','No'),
	array('Jutii','Haithabu','Yes','Yes'),
	array('Iazygi','Dalmatia','No','Yes'),
	array('Iazygi','Scytia','No','Yes'),
	array('Iazygi','Thracia','No','Yes'),
	array('Iazygi','Vindobona','No','Yes'),
	array('Teutones','Colonia Agrippa','No','Yes'),
	array('Mare Adriaticum','Ancona','Yes','No'),
	array('Mare Adriaticum','Brundisium','Yes','No'),
	array('Mare Adriaticum','Dalmatia','Yes','No'),
	array('Mare Adriaticum','Mare Ionium','Yes','No'),
	array('Mare Adriaticum','Macedonia (West Coast)','Yes','No'),
	array('Mare Adriaticum','Ravenna','Yes','No'),
	array('Mare Adriaticum','Samnium','Yes','No'),
	array('Mare Adriaticum','Verona','Yes','No'),
	array('Aegaeis','Athenum','Yes','No'),
	array('Aegaeis','Byzantium','Yes','No'),
	array('Aegaeis','Mare Cypris','Yes','No'),
	array('Aegaeis','Galatia','Yes','No'),
	array('Aegaeis','Mare Internum','Yes','No'),
	array('Aegaeis','Macedonia (East Coast)','Yes','No'),
	array('Aegaeis','Miletus','Yes','No'),
	array('Aegaeis','Thracia','Yes','No'),
	array('Aemilia','Alpes','No','Yes'),
	array('Aemilia','Genova','No','Yes'),
	array('Aemilia','Ravenna','No','Yes'),
	array('Aemilia','Castra Regina','No','Yes'),
	array('Aemilia','Verona','No','Yes'),
	array('Alexandria','Mare Cypris','Yes','No'),
	array('Alexandria','Lybia','Yes','Yes'),
	array('Alexandria','Orientes','Yes','Yes'),
	array('Alpes','Genova','Yes','Yes'),
	array('Alpes','Mare Ligusticum','Yes','No'),
	array('Alpes','Massilia','Yes','Yes'),
	array('Alpes','Castra Regina','No','Yes'),
	array('Alpes','Sequanorum','No','Yes'),
	array('Alpes','Viennensis','No','Yes'),
	array('Ancona','Ravenna','Yes','Yes'),
	array('Ancona','Roma','No','Yes'),
	array('Ancona','Samnium','Yes','Yes'),
	array('Ancona','Tuscia','No','Yes'),
	array('Antiochia','Mare Cypris','Yes','No'),
	array('Antiochia','Galatia','No','Yes'),
	array('Antiochia','Miletus','Yes','Yes'),
	array('Antiochia','Orientes','Yes','Yes'),
	array('Antiochia','Pontica','No','Yes'),
	array('Aquitania','Burdigala','Yes','Yes'),
	array('Aquitania','Mare Cantabricum','Yes','No'),
	array('Aquitania','Lugdunensis','Yes','Yes'),
	array('Aquitania','Lutetia','No','Yes'),
	array('Aquitania','Massilia','No','Yes'),
	array('Aquitania','Narbonensis','No','Yes'),
	array('Aquitania','Viennensis','No','Yes'),
	array('Athenum','Mare Internum','Yes','No'),
	array('Athenum','Mare Ionium','Yes','No'),
	array('Athenum','Macedonia','No','Yes'),
	array('Athenum','Macedonia (West Coast)','Yes','No'),
	array('Athenum','Macedonia (East Coast)','Yes','No'),
	array('Oceanus Atlanticus','Baetica','Yes','No'),
	array('Oceanus Atlanticus','Baleares','Yes','No'),
	array('Oceanus Atlanticus','Oceanus Britannicus','Yes','No'),
	array('Oceanus Atlanticus','Mare Cantabricum','Yes','No'),
	array('Oceanus Atlanticus','Mauretania','Yes','No'),
	array('Oceanus Atlanticus','Olisipo','Yes','No'),
	array('Oceanus Atlanticus','Taraconensis','Yes','No'),
	array('Baetica','Baleares','Yes','No'),
	array('Baetica','Mauretania','Yes','Yes'),
	array('Baetica','Olisipo','Yes','Yes'),
	array('Baetica','Saguntum','Yes','Yes'),
	array('Baetica','Taraconensis','No','Yes'),
	array('Baleares','Carthago','Yes','No'),
	array('Baleares','Mare Ligusticum','Yes','No'),
	array('Baleares','Mauretania','Yes','No'),
	array('Baleares','Saguntum','Yes','No'),
	array('Baleares','Mare Tyrrhenicum','Yes','No'),
	array('Belgica','Colonia Agrippa','Yes','Yes'),
	array('Belgica','Mare Germanicum','Yes','No'),
	array('Belgica','Lutetia','No','Yes'),
	array('Belgica','Rotomagus','Yes','Yes'),
	array('Belgica','Litus Saxonicum','Yes','No'),
	array('Oceanus Britannicus','Mare Cantabricum','Yes','No'),
	array('Oceanus Britannicus','Eburacum (West Coast)','Yes','No'),
	array('Oceanus Britannicus','Flavia Caesarensis','Yes','No'),
	array('Oceanus Britannicus','Londinum','Yes','No'),
	array('Oceanus Britannicus','Lugdunensis','Yes','No'),
	array('Oceanus Britannicus','Rotomagus','Yes','No'),
	array('Oceanus Britannicus','Litus Saxonicum','Yes','No'),
	array('Brundisium','Capova','No','Yes'),
	array('Brundisium','Mare Ionium','Yes','No'),
	array('Brundisium','Rhegium','Yes','Yes'),
	array('Brundisium','Samnium','Yes','Yes'),
	array('Burdigala','Mare Cantabricum','Yes','No'),
	array('Burdigala','Narbonensis','No','Yes'),
	array('Burdigala','Taraconensis','Yes','Yes'),
	array('Byzantium','Pontus Euxinus','Yes','No'),
	array('Byzantium','Galatia','Yes','Yes'),
	array('Byzantium','Pontica','Yes','Yes'),
	array('Byzantium','Scytia','Yes','Yes'),
	array('Byzantium','Thracia','Yes','Yes'),
	array('Mare Cantabricum','Lugdunensis','Yes','No'),
	array('Mare Cantabricum','Taraconensis','Yes','No'),
	array('Capova','Rhegium','Yes','Yes'),
	array('Capova','Roma','Yes','Yes'),
	array('Capova','Samnium','No','Yes'),
	array('Capova','Mare Tyrrhenicum','Yes','No'),
	array('Carthago','Mare Internum','Yes','No'),
	array('Carthago','Mauretania','Yes','Yes'),
	array('Carthago','Numidia','Yes','Yes'),
	array('Carthago','Mare Tyrrhenicum','Yes','No'),
	array('Chersonesus','Pontus Euxinus','Yes','No'),
	array('Colonia Agrippa','Frisii','Yes','Yes'),
	array('Colonia Agrippa','Mare Germanicum','Yes','No'),
	array('Colonia Agrippa','Lutetia','No','Yes'),
	array('Colonia Agrippa','Sequanorum','No','Yes'),
	array('Colonia Agrippa','Viennensis','No','Yes'),
	array('Mare Cypris','Mare Internum','Yes','No'),
	array('Mare Cypris','Lybia','Yes','No'),
	array('Mare Cypris','Miletus','Yes','No'),
	array('Mare Cypris','Orientes','Yes','No'),
	array('Dalmatia','Verona','Yes','Yes'),
	array('Dalmatia','Vindobona','No','Yes'),
	array('Eburacum','Flavia Caesarensis','No','Yes'),
	array('Eburacum','Maxima Caesarensis','No','Yes'),
	array('Eburacum (West Coast)','Flavia Caesarensis','Yes','No'),
	array('Eburacum (East Coast)','Mare Germanicum','Yes','No'),
	array('Eburacum (East Coast)','Maxima Caesarensis','Yes','No'),
	array('Pontus Euxinus','Pontica','Yes','No'),
	array('Pontus Euxinus','Scytia','Yes','No'),
	array('Flavia Caesarensis','Londinum','Yes','Yes'),
	array('Flavia Caesarensis','Maxima Caesarensis','No','Yes'),
	array('Frisii','Mare Germanicum','Yes','No'),
	array('Galatia','Miletus','Yes','Yes'),
	array('Galatia','Pontica','No','Yes'),
	array('Galatia','Thracia','Yes','Yes'),
	array('Genova','Mare Ligusticum','Yes','No'),
	array('Genova','Ravenna','No','Yes'),
	array('Genova','Tuscia','Yes','Yes'),
	array('Mare Germanicum','Haithabu','Yes','No'),
	array('Mare Germanicum','Londinum','Yes','No'),
	array('Mare Germanicum','Maxima Caesarensis','Yes','No'),
	array('Mare Germanicum','Litus Saxonicum','Yes','No'),
	array('Mare Internum','Mare Ionium','Yes','No'),
	array('Mare Internum','Lybia','Yes','No'),
	array('Mare Internum','Numidia','Yes','No'),
	array('Mare Internum','Syracusae','Yes','No'),
	array('Mare Internum','Mare Tyrrhenicum','Yes','No'),
	array('Mare Ionium','Macedonia (West Coast)','Yes','No'),
	array('Mare Ionium','Rhegium','Yes','No'),
	array('Mare Ionium','Syracusae','Yes','No'),
	array('Mare Ionium','Mare Tyrrhenicum','Yes','No'),
	array('Mare Ligusticum','Massilia','Yes','No'),
	array('Mare Ligusticum','Narbonensis','Yes','No'),
	array('Mare Ligusticum','Roma','Yes','No'),
	array('Mare Ligusticum','Saguntum','Yes','No'),
	array('Mare Ligusticum','Tuscia','Yes','No'),
	array('Mare Ligusticum','Mare Tyrrhenicum','Yes','No'),
	array('Londinum','Maxima Caesarensis','Yes','Yes'),
	array('Londinum','Litus Saxonicum','Yes','No'),
	array('Lugdunensis','Lutetia','No','Yes'),
	array('Lugdunensis','Rotomagus','Yes','Yes'),
	array('Lutetia','Rotomagus','No','Yes'),
	array('Lutetia','Viennensis','No','Yes'),
	array('Lybia','Numidia','Yes','Yes'),
	array('Macedonia','Thracia','No','Yes'),
	array('Macedonia (East Coast)','Thracia','Yes','No'),
	array('Massilia','Narbonensis','Yes','Yes'),
	array('Massilia','Viennensis','No','Yes'),
	array('Mauretania','Numidia','No','Yes'),
	array('Narbonensis','Saguntum','Yes','Yes'),
	array('Narbonensis','Taraconensis','No','Yes'),
	array('Olisipo','Taraconensis','Yes','Yes'),
	array('Orientes','Pontica','No','Yes'),
	array('Ravenna','Tuscia','No','Yes'),
	array('Ravenna','Verona','Yes','Yes'),
	array('Castra Regina','Sequanorum','No','Yes'),
	array('Castra Regina','Verona','No','Yes'),
	array('Castra Regina','Vindobona','No','Yes'),
	array('Rhegium','Mare Tyrrhenicum','Yes','No'),
	array('Roma','Samnium','No','Yes'),
	array('Roma','Tuscia','Yes','Yes'),
	array('Roma','Mare Tyrrhenicum','Yes','No'),
	array('Rotomagus','Litus Saxonicum','Yes','No'),
	array('Saguntum','Taraconensis','No','Yes'),
	array('Scytia','Thracia','No','Yes'),
	array('Sequanorum','Viennensis','No','Yes'),
	array('Syracusae','Mare Tyrrhenicum','Yes','No'),
	array('Verona','Vindobona','No','Yes')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

// Custom footer not changed by edit tool

// Make a "fake" SC for every country to fool the Unit-DestroyIndex generation
InstallTerritory::$Territories['Alamanni']->supply='Yes';
InstallTerritory::$Territories['Vandales']->supply='Yes';
InstallTerritory::$Territories['Ostrogothi']->supply='Yes';
InstallTerritory::$Territories['Franci']->supply='Yes';
InstallTerritory::$Territories['Hunni Primi']->supply='Yes';
InstallTerritory::$Territories['Teutones']->supply='Yes';

InstallTerritory::runSQL($this->mapID);

// Remove the fake Home-Supply-Centers created above
$DB->sql_put('UPDATE wD_Territories SET supply="No" WHERE mapID='.$this->mapID.' AND supply="Yes" AND countryID<>0;');

// install Javascript-cache
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

?>
