/**
 * Author:  Alex Ronke
 * Created: Aug 12, 2017
 */

ALTER TABLE `wD_DATC` CHANGE COLUMN `variantID` `variantID` SMALLINT(6) UNSIGNED NOT NULL ;
ALTER TABLE `wD_Backup_Games` CHANGE COLUMN `variantID` `variantID` SMALLINT(6) UNSIGNED NOT NULL ;
ALTER TABLE `wD_Borders` CHANGE COLUMN `mapID` `mapID` SMALLINT(6) UNSIGNED NOT NULL ;
ALTER TABLE `wD_CoastalBorders` CHANGE COLUMN `mapID` `mapID` SMALLINT(6) UNSIGNED NOT NULL ;
ALTER TABLE `wD_Games` CHANGE COLUMN `variantID` `variantID` SMALLINT(6) UNSIGNED NOT NULL ;
ALTER TABLE `wD_Territories` CHANGE COLUMN `mapID` `mapID` SMALLINT(6) UNSIGNED NOT NULL ;
ALTER TABLE `wD_UnitDestroyIndex` CHANGE COLUMN `mapID` `mapID` SMALLINT(6) UNSIGNED NOT NULL ;
ALTER TABLE `wD_VariantData` CHANGE COLUMN `variantID` `variantID` SMALLINT(6) UNSIGNED NOT NULL ;
