<?php
// This is file installs the map data for the ManifestDestiny variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Santo Domingo', 'Coast', 'Yes', 5, 1447, 1290, 731, 642),
	array('Haiti', 'Coast', 'No', 0, 1388, 1292, 682, 649),
	array('Cuba', 'Coast', 'Yes', 5, 1244, 1283, 624, 644),
	array('Havana', 'Coast', 'Yes', 5, 1072, 1277, 548, 630),
	array('Central America', 'Coast', 'Yes', 0, 1028, 1541, 486, 770),
	array('Yucatan', 'Coast', 'No', 4, 895, 1403, 463, 689),
	array('Oaxaca', 'Coast', 'No', 4, 784, 1475, 355, 735),
	array('Guadalajara', 'Coast', 'Yes', 4, 503, 1362, 248, 675),
	array('Mexico City', 'Land', 'Yes', 4, 581, 1358, 301, 675),
	array('Veracruz', 'Coast', 'Yes', 4, 698, 1370, 357, 688),
	array('Monterrey', 'Coast', 'No', 4, 656, 1206, 333, 632),
	array('Durango', 'Coast', 'No', 4, 491, 1242, 244, 605),
	array('Aguas Calientes', 'Land', 'No', 4, 610, 1292, 283, 635),
	array('Saltillo', 'Land', 'No', 4, 577, 1175, 289, 572),
	array('Chihuahua', 'Land', 'Yes', 0, 457, 1122, 238, 549),
	array('Sonora', 'Coast', 'Yes', 0, 374, 1074, 188, 531),
	array('San Diego', 'Coast', 'Yes', 0, 263, 923, 132, 465),
	array('San Francisco', 'Coast', 'Yes', 0, 202, 704, 106, 356),
	array('Arizona', 'Land', 'No', 0, 331, 758, 173, 383),
	array('New Mexico', 'Land', 'Yes', 0, 427, 863, 208, 423),
	array('El Paso', 'Land', 'Yes', 0, 530, 1017, 265, 508),
	array('San Antonio', 'Coast', 'Yes', 0, 683, 1127, 338, 568),
	array('Houston', 'Coast', 'Yes', 3, 743, 1056, 382, 537),
	array('Lousiana', 'Coast', 'Yes', 0, 862, 1070, 431, 532),
	array('Alabama', 'Coast', 'Yes', 0, 919, 1010, 480, 498),
	array('Florida', 'Coast', 'Yes', 0, 1111, 1133, 558, 570),
	array('Carolina', 'Coast', 'Yes', 2, 1046, 993, 561, 457),
	array('Virginia', 'Coast', 'Yes', 2, 1123, 806, 563, 404),
	array('Ohio', 'Land', 'Yes', 2, 1015, 755, 509, 378),
	array('Kentucky', 'Land', 'No', 2, 940, 879, 493, 434),
	array('Illinois', 'Land', 'Yes', 0, 884, 765, 448, 382),
	array('Michigan', 'Land', 'No', 0, 959, 645, 482, 324),
	array('Wisconsin', 'Land', 'No', 0, 848, 618, 425, 308),
	array('Iowa', 'Land', 'Yes', 0, 749, 695, 400, 351),
	array('Missouri', 'Land', 'No', 0, 815, 890, 409, 431),
	array('Indian Territory', 'Land', 'No', 0, 725, 924, 356, 445),
	array('Dallas', 'Land', 'Yes', 3, 614, 902, 310, 454),
	array('Austin', 'Land', 'Yes', 3, 664, 1037, 322, 514),
	array('Panhandle', 'Land', 'No', 3, 544, 890, 265, 434),
	array('Kansas', 'Land', 'Yes', 0, 596, 773, 304, 373),
	array('Wyoming', 'Land', 'No', 0, 509, 666, 251, 334),
	array('Dakota', 'Land', 'No', 0, 685, 560, 337, 288),
	array('Montana', 'Land', 'Yes', 0, 542, 563, 269, 284),
	array('Oregon', 'Coast', 'Yes', 0, 250, 603, 119, 301),
	array('Puget Sound', 'Coast', 'Yes', 0, 281, 396, 138, 192),
	array('British Columbia', 'Coast', 'Yes', 0, 218, 191, 114, 93),
	array('Yukon', 'Coast', 'Yes', 0, 170, 38, 100, 25),
	array('Great Slave Lake', 'Land', 'No', 0, 505, 45, 255, 21),
	array('Nunavut', 'Coast', 'Yes', 0, 752, 54, 379, 32),
	array('Canadian Shield', 'Coast', 'No', 1, 725, 234, 368, 124),
	array('Manitoba', 'Land', 'No', 0, 602, 251, 303, 124),
	array('Edmonton', 'Land', 'Yes', 0, 451, 285, 227, 143),
	array('Alberta', 'Land', 'No', 0, 475, 428, 236, 213),
	array('Saskatchewan', 'Land', 'Yes', 0, 581, 425, 305, 232),
	array('Winnipeg', 'Land', 'No', 0, 740, 387, 371, 192),
	array('Ontario', 'Coast', 'No', 1, 907, 362, 440, 179),
	array('Ottawa', 'Land', 'Yes', 0, 902, 471, 444, 234),
	array('Toronto', 'Land', 'Yes', 1, 1019, 548, 507, 272),
	array('New York', 'Coast', 'Yes', 2, 1162, 708, 583, 344),
	array('New England', 'Coast', 'No', 2, 1223, 618, 613, 303),
	array('New Brunswick', 'Coast', 'No', 1, 1369, 497, 679, 244),
	array('Montreal', 'Coast', 'Yes', 1, 1162, 524, 580, 261),
	array('Quebec', 'Coast', 'Yes', 1, 1183, 410, 598, 191),
	array('Quebec (West Coast)', 'Coast', 'No', 1, 1054, 368, 530, 183),
	array('Quebec (East Coast)', 'Coast', 'No', 1, 1300, 353, 644, 178),
	array('Umiujaq', 'Coast', 'No', 1, 1112, 192, 551, 107),
	array('Labrador', 'Coast', 'No', 1, 1349, 255, 664, 130),
	array('Hudson Bay', 'Sea', 'No', 0, 883, 155, 442, 87),
	array('Mid-Atlantic Ocean', 'Sea', 'No', 0, 1463, 183, 730, 83),
	array('Gulf of Saint Lawrence', 'Sea', 'No', 0, 1361, 411, 683, 204),
	array('New England Coast', 'Sea', 'No', 0, 1321, 728, 670, 335),
	array('Bermuda', 'Sea', 'No', 0, 1262, 939, 630, 462),
	array('Bahamas', 'Sea', 'No', 0, 1229, 1175, 609, 585),
	array('Key West', 'Sea', 'No', 0, 960, 1252, 491, 624),
	array('Mobile Bay', 'Sea', 'No', 0, 914, 1150, 464, 571),
	array('Galveston Bay', 'Sea', 'No', 0, 804, 1150, 397, 581),
	array('Gulf of Mexico', 'Sea', 'No', 0, 808, 1298, 398, 651),
	array('Western Caribbean', 'Sea', 'No', 0, 1040, 1408, 561, 686),
	array('Eastern Caribbean', 'Sea', 'No', 0, 1262, 1446, 609, 753),
	array('Central America (East Coast)', 'Coast', 'No', 0, 1060, 1504, 533, 751),
	array('Central America (West Coast)', 'Coast', 'No', 0, 876, 1536, 443, 772),
	array('Sargasso Sea', 'Sea', 'No', 0, 1450, 1196, 724, 598),
	array('South Pacific Ocean', 'Sea', 'No', 0, 596, 1532, 301, 764),
	array('Mid-Pacific Ocean', 'Sea', 'No', 5, 42, 1148, 20, 591),
	array('Gulf of California', 'Sea', 'No', 0, 330, 1338, 155, 676),
	array('San Diego Bay', 'Sea', 'No', 0, 174, 1120, 91, 563),
	array('San Francisco Bay', 'Sea', 'No', 0, 112, 848, 51, 394),
	array('Gulf of Alaska', 'Sea', 'No', 0, 68, 230, 34, 131)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Santo Domingo','Haiti','Yes','Yes'),
	array('Santo Domingo','Bahamas','Yes','No'),
	array('Santo Domingo','Eastern Caribbean','Yes','No'),
	array('Santo Domingo','Sargasso Sea','Yes','No'),
	array('Haiti','Bahamas','Yes','No'),
	array('Haiti','Eastern Caribbean','Yes','No'),
	array('Cuba','Havana','Yes','Yes'),
	array('Cuba','Bahamas','Yes','No'),
	array('Cuba','Western Caribbean','Yes','No'),
	array('Cuba','Eastern Caribbean','Yes','No'),
	array('Havana','Bahamas','Yes','No'),
	array('Havana','Key West','Yes','No'),
	array('Havana','Western Caribbean','Yes','No'),
	array('Central America','Yucatan','No','Yes'),
	array('Central America','Oaxaca','No','Yes'),
	array('Yucatan','Oaxaca','No','Yes'),
	array('Yucatan','Veracruz','Yes','Yes'),
	array('Yucatan','Key West','Yes','No'),
	array('Yucatan','Gulf of Mexico','Yes','No'),
	array('Yucatan','Western Caribbean','Yes','No'),
	array('Yucatan','Central America (East Coast)','Yes','No'),
	array('Oaxaca','Guadalajara','Yes','Yes'),
	array('Oaxaca','Mexico City','No','Yes'),
	array('Oaxaca','Veracruz','No','Yes'),
	array('Oaxaca','Central America (West Coast)','Yes','No'),
	array('Oaxaca','South Pacific Ocean','Yes','No'),
	array('Guadalajara','Mexico City','No','Yes'),
	array('Guadalajara','Veracruz','No','Yes'),
	array('Guadalajara','Durango','Yes','Yes'),
	array('Guadalajara','Aguas Calientes','No','Yes'),
	array('Guadalajara','South Pacific Ocean','Yes','No'),
	array('Guadalajara','Gulf of California','Yes','No'),
	array('Mexico City','Veracruz','No','Yes'),
	array('Mexico City','Aguas Calientes','No','Yes'),
	array('Veracruz','Monterrey','Yes','Yes'),
	array('Veracruz','Aguas Calientes','No','Yes'),
	array('Veracruz','Gulf of Mexico','Yes','No'),
	array('Monterrey','Aguas Calientes','No','Yes'),
	array('Monterrey','Saltillo','No','Yes'),
	array('Monterrey','San Antonio','Yes','Yes'),
	array('Monterrey','Galveston Bay','Yes','No'),
	array('Monterrey','Gulf of Mexico','Yes','No'),
	array('Durango','Aguas Calientes','No','Yes'),
	array('Durango','Saltillo','No','Yes'),
	array('Durango','Chihuahua','No','Yes'),
	array('Durango','Sonora','Yes','Yes'),
	array('Durango','Gulf of California','Yes','No'),
	array('Aguas Calientes','Saltillo','No','Yes'),
	array('Saltillo','Chihuahua','No','Yes'),
	array('Saltillo','El Paso','No','Yes'),
	array('Saltillo','San Antonio','No','Yes'),
	array('Chihuahua','Sonora','No','Yes'),
	array('Chihuahua','New Mexico','No','Yes'),
	array('Chihuahua','El Paso','No','Yes'),
	array('Sonora','San Diego','Yes','Yes'),
	array('Sonora','New Mexico','No','Yes'),
	array('Sonora','Gulf of California','Yes','No'),
	array('San Diego','San Francisco','Yes','Yes'),
	array('San Diego','Arizona','No','Yes'),
	array('San Diego','New Mexico','No','Yes'),
	array('San Diego','Gulf of California','Yes','No'),
	array('San Diego','San Diego Bay','Yes','No'),
	array('San Diego','San Francisco Bay','Yes','No'),
	array('San Francisco','Arizona','No','Yes'),
	array('San Francisco','Oregon','Yes','Yes'),
	array('San Francisco','San Francisco Bay','Yes','No'),
	array('Arizona','New Mexico','No','Yes'),
	array('Arizona','Panhandle','No','Yes'),
	array('Arizona','Wyoming','No','Yes'),
	array('Arizona','Oregon','No','Yes'),
	array('New Mexico','El Paso','No','Yes'),
	array('New Mexico','Panhandle','No','Yes'),
	array('El Paso','San Antonio','No','Yes'),
	array('El Paso','Austin','No','Yes'),
	array('El Paso','Panhandle','No','Yes'),
	array('San Antonio','Houston','Yes','Yes'),
	array('San Antonio','Austin','No','Yes'),
	array('San Antonio','Galveston Bay','Yes','No'),
	array('Houston','Lousiana','Yes','Yes'),
	array('Houston','Missouri','No','Yes'),
	array('Houston','Indian Territory','No','Yes'),
	array('Houston','Dallas','No','Yes'),
	array('Houston','Austin','No','Yes'),
	array('Houston','Galveston Bay','Yes','No'),
	array('Lousiana','Alabama','Yes','Yes'),
	array('Lousiana','Missouri','No','Yes'),
	array('Lousiana','Mobile Bay','Yes','No'),
	array('Lousiana','Galveston Bay','Yes','No'),
	array('Alabama','Florida','Yes','Yes'),
	array('Alabama','Carolina','No','Yes'),
	array('Alabama','Kentucky','No','Yes'),
	array('Alabama','Missouri','No','Yes'),
	array('Alabama','Mobile Bay','Yes','No'),
	array('Florida','Carolina','Yes','Yes'),
	array('Florida','Bermuda','Yes','No'),
	array('Florida','Bahamas','Yes','No'),
	array('Florida','Key West','Yes','No'),
	array('Florida','Mobile Bay','Yes','No'),
	array('Carolina','Virginia','Yes','Yes'),
	array('Carolina','Kentucky','No','Yes'),
	array('Carolina','Bermuda','Yes','No'),
	array('Virginia','Ohio','No','Yes'),
	array('Virginia','Kentucky','No','Yes'),
	array('Virginia','New York','Yes','Yes'),
	array('Virginia','New England Coast','Yes','No'),
	array('Virginia','Bermuda','Yes','No'),
	array('Ohio','Kentucky','No','Yes'),
	array('Ohio','Illinois','No','Yes'),
	array('Ohio','Michigan','No','Yes'),
	array('Ohio','New York','No','Yes'),
	array('Kentucky','Illinois','No','Yes'),
	array('Kentucky','Missouri','No','Yes'),
	array('Illinois','Michigan','No','Yes'),
	array('Illinois','Wisconsin','No','Yes'),
	array('Illinois','Iowa','No','Yes'),
	array('Illinois','Missouri','No','Yes'),
	array('Michigan','Wisconsin','No','Yes'),
	array('Michigan','Toronto','No','Yes'),
	array('Wisconsin','Iowa','No','Yes'),
	array('Wisconsin','Dakota','No','Yes'),
	array('Wisconsin','Winnipeg','No','Yes'),
	array('Wisconsin','Ottawa','No','Yes'),
	array('Iowa','Missouri','No','Yes'),
	array('Iowa','Kansas','No','Yes'),
	array('Iowa','Wyoming','No','Yes'),
	array('Iowa','Dakota','No','Yes'),
	array('Missouri','Indian Territory','No','Yes'),
	array('Missouri','Kansas','No','Yes'),
	array('Indian Territory','Dallas','No','Yes'),
	array('Indian Territory','Kansas','No','Yes'),
	array('Dallas','Austin','No','Yes'),
	array('Dallas','Panhandle','No','Yes'),
	array('Dallas','Kansas','No','Yes'),
	array('Austin','Panhandle','No','Yes'),
	array('Austin','Galveston Bay','Yes','No'),
	array('Panhandle','Kansas','No','Yes'),
	array('Panhandle','Wyoming','No','Yes'),
	array('Kansas','Wyoming','No','Yes'),
	array('Wyoming','Dakota','No','Yes'),
	array('Wyoming','Montana','No','Yes'),
	array('Wyoming','Oregon','No','Yes'),
	array('Dakota','Montana','No','Yes'),
	array('Dakota','Saskatchewan','No','Yes'),
	array('Dakota','Winnipeg','No','Yes'),
	array('Montana','Oregon','No','Yes'),
	array('Montana','Puget Sound','No','Yes'),
	array('Montana','Alberta','No','Yes'),
	array('Montana','Saskatchewan','No','Yes'),
	array('Oregon','Puget Sound','Yes','Yes'),
	array('Oregon','San Francisco Bay','Yes','No'),
	array('Puget Sound','British Columbia','Yes','Yes'),
	array('Puget Sound','Edmonton','No','Yes'),
	array('Puget Sound','Alberta','No','Yes'),
	array('Puget Sound','San Francisco Bay','Yes','No'),
	array('Puget Sound','Gulf of Alaska','Yes','No'),
	array('British Columbia','Yukon','Yes','Yes'),
	array('British Columbia','Great Slave Lake','No','Yes'),
	array('British Columbia','Edmonton','No','Yes'),
	array('British Columbia','Gulf of Alaska','Yes','No'),
	array('Yukon','Great Slave Lake','No','Yes'),
	array('Yukon','Gulf of Alaska','Yes','No'),
	array('Great Slave Lake','Nunavut','No','Yes'),
	array('Great Slave Lake','Manitoba','No','Yes'),
	array('Great Slave Lake','Edmonton','No','Yes'),
	array('Nunavut','Canadian Shield','Yes','Yes'),
	array('Nunavut','Manitoba','No','Yes'),
	array('Nunavut','Hudson Bay','Yes','No'),
	array('Canadian Shield','Manitoba','No','Yes'),
	array('Canadian Shield','Winnipeg','No','Yes'),
	array('Canadian Shield','Ontario','Yes','Yes'),
	array('Canadian Shield','Hudson Bay','Yes','No'),
	array('Manitoba','Edmonton','No','Yes'),
	array('Manitoba','Alberta','No','Yes'),
	array('Manitoba','Saskatchewan','No','Yes'),
	array('Manitoba','Winnipeg','No','Yes'),
	array('Edmonton','Alberta','No','Yes'),
	array('Alberta','Saskatchewan','No','Yes'),
	array('Saskatchewan','Winnipeg','No','Yes'),
	array('Winnipeg','Ontario','No','Yes'),
	array('Winnipeg','Ottawa','No','Yes'),
	array('Ontario','Ontario','Yes','Yes'),
	array('Ontario','Ottawa','No','Yes'),
	array('Ontario','Toronto','No','Yes'),
	array('Ontario','Montreal','No','Yes'),
	array('Ontario','Quebec','No','Yes'),
	array('Ontario','Quebec (West Coast)','Yes','No'),
	array('Ontario','Hudson Bay','Yes','No'),
	array('Ottawa','Toronto','No','Yes'),
	array('Toronto','New York','No','Yes'),
	array('Toronto','Montreal','No','Yes'),
	array('New York','New England','Yes','Yes'),
	array('New York','Montreal','No','Yes'),
	array('New York','New England Coast','Yes','No'),
	array('New England','New Brunswick','Yes','Yes'),
	array('New England','Montreal','No','Yes'),
	array('New England','New England Coast','Yes','No'),
	array('New Brunswick','Montreal','Yes','Yes'),
	array('New Brunswick','Gulf of Saint Lawrence','Yes','No'),
	array('New Brunswick','New England Coast','Yes','No'),
	array('Montreal','Quebec','No','Yes'),
	array('Montreal','Quebec (East Coast)','Yes','No'),
	array('Montreal','Gulf of Saint Lawrence','Yes','No'),
	array('Quebec','Umiujaq','No','Yes'),
	array('Quebec','Labrador','No','Yes'),
	array('Quebec (West Coast)','Umiujaq','Yes','No'),
	array('Quebec (West Coast)','Hudson Bay','Yes','No'),
	array('Quebec (East Coast)','Labrador','Yes','No'),
	array('Quebec (East Coast)','Gulf of Saint Lawrence','Yes','No'),
	array('Umiujaq','Labrador','Yes','Yes'),
	array('Umiujaq','Hudson Bay','Yes','No'),
	array('Labrador','Hudson Bay','Yes','No'),
	array('Labrador','Gulf of Saint Lawrence','Yes','No'),
	array('Hudson Bay','Mid-Atlantic Ocean','Yes','No'),
	array('Hudson Bay','Gulf of Saint Lawrence','Yes','No'),
	array('Mid-Atlantic Ocean','Gulf of Saint Lawrence','Yes','No'),
	array('Mid-Atlantic Ocean','New England Coast','Yes','No'),
	array('Mid-Atlantic Ocean','Bermuda','Yes','No'),
	array('Mid-Atlantic Ocean','Bahamas','Yes','No'),
	array('Mid-Atlantic Ocean','Sargasso Sea','Yes','No'),
	array('Gulf of Saint Lawrence','New England Coast','Yes','No'),
	array('New England Coast','Bermuda','Yes','No'),
	array('Bermuda','Bahamas','Yes','No'),
	array('Bahamas','Key West','Yes','No'),
	array('Bahamas','Eastern Caribbean','Yes','No'),
	array('Bahamas','Sargasso Sea','Yes','No'),
	array('Key West','Mobile Bay','Yes','No'),
	array('Key West','Galveston Bay','Yes','No'),
	array('Key West','Gulf of Mexico','Yes','No'),
	array('Key West','Western Caribbean','Yes','No'),
	array('Mobile Bay','Galveston Bay','Yes','No'),
	array('Mobile Bay','Gulf of Mexico','Yes','No'),
	array('Galveston Bay','Gulf of Mexico','Yes','No'),
	array('Western Caribbean','Eastern Caribbean','Yes','No'),
	array('Western Caribbean','Central America (East Coast)','Yes','No'),
	array('Eastern Caribbean','Central America (East Coast)','Yes','No'),
	array('Eastern Caribbean','Sargasso Sea','Yes','No'),
	array('Eastern Caribbean','Mid-Pacific Ocean','Yes','No'),
	array('Central America (West Coast)','South Pacific Ocean','Yes','No'),
	array('South Pacific Ocean','Mid-Pacific Ocean','Yes','No'),
	array('South Pacific Ocean','Gulf of California','Yes','No'),
	array('Mid-Pacific Ocean','Gulf of California','Yes','No'),
	array('Mid-Pacific Ocean','San Diego Bay','Yes','No'),
	array('Mid-Pacific Ocean','San Francisco Bay','Yes','No'),
	array('Mid-Pacific Ocean','Gulf of Alaska','Yes','No'),
	array('Gulf of California','San Diego Bay','Yes','No'),
	array('San Diego Bay','San Francisco Bay','Yes','No'),
	array('San Francisco Bay','Gulf of Alaska','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
