<?php
// This is file installs the map data for the Renaissance1453 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Clyde', 'Coast', 'No', 0, 314, 331, 162, 104),
	array('Scotland', 'Coast', 'Yes', 0, 343, 330, 177, 106),
	array('Yorkshire', 'Coast', 'No', 4, 348, 423, 183, 146),
	array('London', 'Coast', 'Yes', 4, 364, 480, 171, 186),
	array('Wales', 'Coast', 'No', 4, 308, 468, 147, 184),
	array('Chester', 'Coast', 'Yes', 4, 321, 403, 165, 139),
	array('Norway', 'Coast', 'Yes', 0, 492, 328, 261, 116),
	array('Sweden', 'Coast', 'Yes', 0, 576, 365, 310, 146),
	array('Denmark', 'Coast', 'Yes', 0, 496, 439, 267, 146),
	array('Finland', 'Coast', 'No', 0, 704, 236, 365, 114),
	array('Novgorod', 'Coast', 'Yes', 5, 938, 231, 473, 81),
	array('Novgorod (North Coast)', 'Coast', 'No', 5, 801, 186, 412, 87),
	array('Novgorod (South Coast)', 'Coast', 'No', 5, 760, 347, 384, 134),
	array('Livonia', 'Coast', 'No', 5, 724, 410, 375, 157),
	array('Muscovy', 'Land', 'Yes', 0, 990, 399, 439, 171),
	array('Warsaw', 'Land', 'Yes', 5, 682, 523, 364, 205),
	array('Prussia', 'Coast', 'No', 5, 666, 483, 316, 204),
	array('Berlin', 'Coast', 'Yes', 6, 558, 479, 292, 186),
	array('Silesia', 'Land', 'No', 6, 572, 534, 320, 223),
	array('Munich', 'Land', 'Yes', 6, 489, 583, 261, 226),
	array('Hannover', 'Coast', 'Yes', 0, 472, 499, 252, 189),
	array('Rheinland', 'Land', 'No', 6, 448, 576, 226, 222),
	array('Netherlands', 'Coast', 'Yes', 0, 432, 503, 238, 182),
	array('Brussels', 'Coast', 'Yes', 3, 414, 552, 217, 206),
	array('Picardy', 'Coast', 'No', 3, 360, 551, 183, 213),
	array('Brest', 'Coast', 'Yes', 4, 300, 574, 162, 220),
	array('Paris', 'Land', 'Yes', 3, 329, 624, 177, 231),
	array('Burgundy', 'Land', 'No', 3, 412, 619, 211, 237),
	array('Aquitaine', 'Coast', 'No', 3, 297, 656, 148, 258),
	array('Madrid', 'Coast', 'Yes', 2, 221, 742, 117, 300),
	array('Madrid (North Coast)', 'Coast', 'No', 2, 172, 680, 83, 275),
	array('Lisbon', 'Coast', 'Yes', 2, 70, 786, 52, 324),
	array('Madrid (South Coast)', 'Coast', 'No', 2, 192, 830, 115, 337),
	array('Marseilles', 'Coast', 'Yes', 3, 393, 724, 167, 298),
	array('Genoa', 'Coast', 'No', 6, 453, 695, 229, 274),
	array('Switzerland', 'Land', 'Yes', 0, 459, 640, 220, 256),
	array('Tyrolia', 'Land', 'No', 6, 553, 634, 284, 250),
	array('Tuscany', 'Coast', 'No', 6, 474, 750, 257, 314),
	array('Papal States', 'Coast', 'Yes', 0, 524, 807, 264, 328),
	array('Naples', 'Coast', 'Yes', 2, 530, 911, 267, 379),
	array('Apulia', 'Coast', 'No', 2, 564, 811, 294, 334),
	array('Venice', 'Coast', 'Yes', 1, 484, 707, 270, 301),
	array('Trieste', 'Coast', 'Yes', 1, 582, 700, 309, 282),
	array('Vienna', 'Land', 'Yes', 6, 604, 627, 318, 244),
	array('Bohemia', 'Land', 'No', 6, 562, 579, 298, 229),
	array('Galicia', 'Land', 'No', 5, 720, 615, 385, 244),
	array('Ukraine', 'Land', 'No', 5, 785, 560, 430, 213),
	array('Belgorod', 'Coast', 'Yes', 5, 1004, 651, 476, 243),
	array('Armenia', 'Coast', 'No', 7, 1073, 790, 550, 315),
	array('Syria', 'Coast', 'No', 7, 1012, 946, 532, 377),
	array('Smyrna', 'Coast', 'Yes', 7, 842, 904, 490, 354),
	array('Ankara', 'Coast', 'Yes', 7, 981, 816, 484, 316),
	array('Constantinople', 'Coast', 'Yes', 0, 836, 827, 432, 344),
	array('Sofia', 'Coast', 'Yes', 7, 728, 782, 404, 314),
	array('Sofia (North Coast)', 'Coast', 'No', 7, 784, 759, 412, 311),
	array('Sofia (South Coast)', 'Coast', 'No', 7, 752, 804, 400, 323),
	array('Athens', 'Coast', 'Yes', 1, 686, 911, 362, 375),
	array('Albania', 'Coast', 'No', 1, 645, 814, 345, 346),
	array('Serbia', 'Land', 'Yes', 0, 673, 752, 358, 326),
	array('Hungary', 'Land', 'Yes', 0, 657, 648, 351, 254),
	array('Moldavia', 'Coast', 'Yes', 0, 777, 716, 410, 264),
	array('North Africa', 'Coast', 'No', 0, 90, 918, 74, 372),
	array('Tunis', 'Coast', 'Yes', 0, 416, 967, 207, 378),
	array('Black Sea', 'Sea', 'No', 0, 842, 752, 449, 294),
	array('Aegean Sea', 'Sea', 'No', 0, 749, 879, 390, 359),
	array('Eastern Mediterranean', 'Sea', 'No', 0, 857, 955, 466, 382),
	array('Ionian Sea', 'Sea', 'No', 0, 601, 919, 322, 373),
	array('Adriatic Sea', 'Sea', 'No', 0, 604, 803, 323, 335),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 462, 836, 241, 334),
	array('Gulf of Lyon', 'Sea', 'No', 0, 353, 759, 169, 321),
	array('Western Mediterranean', 'Sea', 'No', 0, 358, 839, 187, 343),
	array('Mid-Atlantic Ocean', 'Sea', 'No', 0, 64, 554, 38, 201),
	array('North Atlantic Ocean', 'Sea', 'No', 0, 126, 202, 69, 114),
	array('Irish Sea', 'Sea', 'No', 0, 236, 468, 125, 166),
	array('English Channel', 'Sea', 'No', 0, 321, 530, 147, 207),
	array('North Sea', 'Sea', 'No', 0, 408, 335, 214, 112),
	array('Heligoland Bight', 'Sea', 'No', 0, 462, 438, 248, 158),
	array('Norwegian Sea', 'Sea', 'No', 0, 434, 102, 224, 63),
	array('Skagerrak', 'Sea', 'No', 0, 520, 360, 287, 146),
	array('Baltic Sea', 'Sea', 'No', 0, 637, 419, 342, 171),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 642, 292, 344, 138),
	array('Barents Sea', 'Sea', 'No', 0, 769, 27, 364, 11)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Clyde','Scotland','Yes','Yes'),
	array('Clyde','Chester','Yes','Yes'),
	array('Clyde','North Atlantic Ocean','Yes','No'),
	array('Clyde','Norwegian Sea','Yes','No'),
	array('Scotland','Yorkshire','Yes','Yes'),
	array('Scotland','Chester','No','Yes'),
	array('Scotland','North Sea','Yes','No'),
	array('Scotland','Norwegian Sea','Yes','No'),
	array('Yorkshire','London','Yes','Yes'),
	array('Yorkshire','Wales','No','Yes'),
	array('Yorkshire','Chester','No','Yes'),
	array('Yorkshire','North Sea','Yes','No'),
	array('London','Wales','Yes','Yes'),
	array('London','English Channel','Yes','No'),
	array('London','North Sea','Yes','No'),
	array('Wales','Chester','Yes','Yes'),
	array('Wales','Irish Sea','Yes','No'),
	array('Wales','English Channel','Yes','No'),
	array('Chester','Irish Sea','Yes','No'),
	array('Norway','Sweden','Yes','Yes'),
	array('Norway','Finland','No','Yes'),
	array('Norway','Novgorod','No','Yes'),
	array('Norway','Novgorod (North Coast)','Yes','No'),
	array('Norway','North Sea','Yes','No'),
	array('Norway','Norwegian Sea','Yes','No'),
	array('Norway','Skagerrak','Yes','No'),
	array('Norway','Barents Sea','Yes','No'),
	array('Sweden','Denmark','Yes','Yes'),
	array('Sweden','Finland','Yes','Yes'),
	array('Sweden','Skagerrak','Yes','No'),
	array('Sweden','Baltic Sea','Yes','No'),
	array('Sweden','Gulf of Bothnia','Yes','No'),
	array('Denmark','Hannover','Yes','Yes'),
	array('Denmark','North Sea','Yes','No'),
	array('Denmark','Heligoland Bight','Yes','No'),
	array('Denmark','Skagerrak','Yes','No'),
	array('Denmark','Baltic Sea','Yes','No'),
	array('Finland','Novgorod','No','Yes'),
	array('Finland','Novgorod (South Coast)','Yes','No'),
	array('Finland','Gulf of Bothnia','Yes','No'),
	array('Novgorod','Livonia','No','Yes'),
	array('Novgorod','Muscovy','No','Yes'),
	array('Novgorod (North Coast)','Barents Sea','Yes','No'),
	array('Novgorod (South Coast)','Livonia','Yes','No'),
	array('Novgorod (South Coast)','Gulf of Bothnia','Yes','No'),
	array('Livonia','Muscovy','No','Yes'),
	array('Livonia','Warsaw','No','Yes'),
	array('Livonia','Prussia','Yes','Yes'),
	array('Livonia','Baltic Sea','Yes','No'),
	array('Livonia','Gulf of Bothnia','Yes','No'),
	array('Muscovy','Warsaw','No','Yes'),
	array('Muscovy','Ukraine','No','Yes'),
	array('Muscovy','Belgorod','No','Yes'),
	array('Warsaw','Prussia','No','Yes'),
	array('Warsaw','Silesia','No','Yes'),
	array('Warsaw','Galicia','No','Yes'),
	array('Warsaw','Ukraine','No','Yes'),
	array('Prussia','Berlin','Yes','Yes'),
	array('Prussia','Silesia','No','Yes'),
	array('Prussia','Baltic Sea','Yes','No'),
	array('Berlin','Silesia','No','Yes'),
	array('Berlin','Munich','No','Yes'),
	array('Berlin','Hannover','Yes','Yes'),
	array('Berlin','Baltic Sea','Yes','No'),
	array('Silesia','Munich','No','Yes'),
	array('Silesia','Bohemia','No','Yes'),
	array('Silesia','Galicia','No','Yes'),
	array('Munich','Hannover','No','Yes'),
	array('Munich','Rheinland','No','Yes'),
	array('Munich','Burgundy','No','Yes'),
	array('Munich','Switzerland','No','Yes'),
	array('Munich','Tyrolia','No','Yes'),
	array('Munich','Bohemia','No','Yes'),
	array('Hannover','Rheinland','No','Yes'),
	array('Hannover','Netherlands','Yes','Yes'),
	array('Hannover','Heligoland Bight','Yes','No'),
	array('Hannover','Baltic Sea','Yes','No'),
	array('Rheinland','Netherlands','No','Yes'),
	array('Rheinland','Brussels','No','Yes'),
	array('Rheinland','Burgundy','No','Yes'),
	array('Netherlands','Brussels','Yes','Yes'),
	array('Netherlands','North Sea','Yes','No'),
	array('Netherlands','Heligoland Bight','Yes','No'),
	array('Brussels','Picardy','Yes','Yes'),
	array('Brussels','Burgundy','No','Yes'),
	array('Brussels','English Channel','Yes','No'),
	array('Brussels','North Sea','Yes','No'),
	array('Picardy','Brest','Yes','Yes'),
	array('Picardy','Paris','No','Yes'),
	array('Picardy','Burgundy','No','Yes'),
	array('Picardy','English Channel','Yes','No'),
	array('Brest','Paris','No','Yes'),
	array('Brest','Aquitaine','Yes','Yes'),
	array('Brest','Mid-Atlantic Ocean','Yes','No'),
	array('Brest','English Channel','Yes','No'),
	array('Paris','Burgundy','No','Yes'),
	array('Paris','Aquitaine','No','Yes'),
	array('Burgundy','Aquitaine','No','Yes'),
	array('Burgundy','Marseilles','No','Yes'),
	array('Burgundy','Switzerland','No','Yes'),
	array('Aquitaine','Madrid','No','Yes'),
	array('Aquitaine','Madrid (North Coast)','Yes','No'),
	array('Aquitaine','Marseilles','No','Yes'),
	array('Aquitaine','Mid-Atlantic Ocean','Yes','No'),
	array('Madrid','Lisbon','No','Yes'),
	array('Madrid','Marseilles','No','Yes'),
	array('Madrid (North Coast)','Lisbon','Yes','No'),
	array('Madrid (North Coast)','Mid-Atlantic Ocean','Yes','No'),
	array('Lisbon','Madrid (South Coast)','Yes','No'),
	array('Lisbon','Mid-Atlantic Ocean','Yes','No'),
	array('Madrid (South Coast)','Marseilles','Yes','No'),
	array('Madrid (South Coast)','Gulf of Lyon','Yes','No'),
	array('Madrid (South Coast)','Western Mediterranean','Yes','No'),
	array('Madrid (South Coast)','Mid-Atlantic Ocean','Yes','No'),
	array('Marseilles','Genoa','Yes','Yes'),
	array('Marseilles','Switzerland','No','Yes'),
	array('Marseilles','Gulf of Lyon','Yes','No'),
	array('Genoa','Switzerland','No','Yes'),
	array('Genoa','Tyrolia','No','Yes'),
	array('Genoa','Tuscany','Yes','Yes'),
	array('Genoa','Venice','No','Yes'),
	array('Genoa','Gulf of Lyon','Yes','No'),
	array('Switzerland','Tyrolia','No','Yes'),
	array('Tyrolia','Venice','No','Yes'),
	array('Tyrolia','Trieste','No','Yes'),
	array('Tyrolia','Vienna','No','Yes'),
	array('Tyrolia','Bohemia','No','Yes'),
	array('Tuscany','Papal States','Yes','Yes'),
	array('Tuscany','Venice','No','Yes'),
	array('Tuscany','Tyrrhenian Sea','Yes','No'),
	array('Tuscany','Gulf of Lyon','Yes','No'),
	array('Papal States','Naples','Yes','Yes'),
	array('Papal States','Apulia','No','Yes'),
	array('Papal States','Venice','No','Yes'),
	array('Papal States','Tyrrhenian Sea','Yes','No'),
	array('Naples','Apulia','Yes','Yes'),
	array('Naples','Ionian Sea','Yes','No'),
	array('Naples','Tyrrhenian Sea','Yes','No'),
	array('Apulia','Venice','Yes','Yes'),
	array('Apulia','Ionian Sea','Yes','No'),
	array('Apulia','Adriatic Sea','Yes','No'),
	array('Venice','Trieste','Yes','Yes'),
	array('Venice','Adriatic Sea','Yes','No'),
	array('Trieste','Vienna','No','Yes'),
	array('Trieste','Albania','Yes','Yes'),
	array('Trieste','Serbia','No','Yes'),
	array('Trieste','Hungary','No','Yes'),
	array('Trieste','Adriatic Sea','Yes','No'),
	array('Vienna','Bohemia','No','Yes'),
	array('Vienna','Galicia','No','Yes'),
	array('Vienna','Hungary','No','Yes'),
	array('Bohemia','Galicia','No','Yes'),
	array('Galicia','Ukraine','No','Yes'),
	array('Galicia','Hungary','No','Yes'),
	array('Galicia','Moldavia','No','Yes'),
	array('Ukraine','Belgorod','No','Yes'),
	array('Ukraine','Moldavia','No','Yes'),
	array('Belgorod','Armenia','Yes','Yes'),
	array('Belgorod','Moldavia','Yes','Yes'),
	array('Belgorod','Black Sea','Yes','No'),
	array('Armenia','Syria','No','Yes'),
	array('Armenia','Smyrna','No','Yes'),
	array('Armenia','Ankara','Yes','Yes'),
	array('Armenia','Black Sea','Yes','No'),
	array('Syria','Smyrna','Yes','Yes'),
	array('Syria','Eastern Mediterranean','Yes','No'),
	array('Smyrna','Ankara','No','Yes'),
	array('Smyrna','Constantinople','Yes','Yes'),
	array('Smyrna','Aegean Sea','Yes','No'),
	array('Smyrna','Eastern Mediterranean','Yes','No'),
	array('Ankara','Constantinople','Yes','Yes'),
	array('Ankara','Black Sea','Yes','No'),
	array('Constantinople','Sofia','No','Yes'),
	array('Constantinople','Sofia (North Coast)','Yes','No'),
	array('Constantinople','Sofia (South Coast)','Yes','No'),
	array('Constantinople','Black Sea','Yes','No'),
	array('Constantinople','Aegean Sea','Yes','No'),
	array('Sofia','Athens','No','Yes'),
	array('Sofia','Serbia','No','Yes'),
	array('Sofia','Moldavia','No','Yes'),
	array('Sofia (North Coast)','Moldavia','Yes','No'),
	array('Sofia (North Coast)','Black Sea','Yes','No'),
	array('Sofia (South Coast)','Athens','Yes','No'),
	array('Sofia (South Coast)','Aegean Sea','Yes','No'),
	array('Athens','Albania','Yes','Yes'),
	array('Athens','Serbia','No','Yes'),
	array('Athens','Aegean Sea','Yes','No'),
	array('Athens','Ionian Sea','Yes','No'),
	array('Albania','Serbia','No','Yes'),
	array('Albania','Ionian Sea','Yes','No'),
	array('Albania','Adriatic Sea','Yes','No'),
	array('Serbia','Hungary','No','Yes'),
	array('Serbia','Moldavia','No','Yes'),
	array('Hungary','Moldavia','No','Yes'),
	array('Moldavia','Black Sea','Yes','No'),
	array('North Africa','Tunis','Yes','Yes'),
	array('North Africa','Western Mediterranean','Yes','No'),
	array('North Africa','Mid-Atlantic Ocean','Yes','No'),
	array('Tunis','Ionian Sea','Yes','No'),
	array('Tunis','Tyrrhenian Sea','Yes','No'),
	array('Tunis','Western Mediterranean','Yes','No'),
	array('Aegean Sea','Eastern Mediterranean','Yes','No'),
	array('Aegean Sea','Ionian Sea','Yes','No'),
	array('Eastern Mediterranean','Ionian Sea','Yes','No'),
	array('Ionian Sea','Adriatic Sea','Yes','No'),
	array('Ionian Sea','Tyrrhenian Sea','Yes','No'),
	array('Tyrrhenian Sea','Gulf of Lyon','Yes','No'),
	array('Tyrrhenian Sea','Western Mediterranean','Yes','No'),
	array('Gulf of Lyon','Western Mediterranean','Yes','No'),
	array('Western Mediterranean','Mid-Atlantic Ocean','Yes','No'),
	array('Mid-Atlantic Ocean','North Atlantic Ocean','Yes','No'),
	array('Mid-Atlantic Ocean','Irish Sea','Yes','No'),
	array('Mid-Atlantic Ocean','English Channel','Yes','No'),
	array('North Atlantic Ocean','Irish Sea','Yes','No'),
	array('North Atlantic Ocean','Norwegian Sea','Yes','No'),
	array('Irish Sea','English Channel','Yes','No'),
	array('English Channel','North Sea','Yes','No'),
	array('North Sea','Heligoland Bight','Yes','No'),
	array('North Sea','Norwegian Sea','Yes','No'),
	array('North Sea','Skagerrak','Yes','No'),
	array('Norwegian Sea','Barents Sea','Yes','No'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
