<?php
// This is file installs the map data for the Edwardian variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Iceland', 'Coast', 'No', 0, 387, 132, 147, 44),
	array('Glasgow', 'Coast', 'Yes', 2, 487, 516, 170, 179),
	array('Belfast', 'Coast', 'Yes', 2, 325, 631, 137, 228),
	array('Liverpool', 'Coast', 'Yes', 2, 455, 624, 172, 227),
	array('Wales', 'Coast', 'No', 2, 410, 708, 157, 261),
	array('London', 'Coast', 'Yes', 2, 503, 730, 187, 281),
	array('Yorkshire', 'Coast', 'No', 2, 487, 663, 189, 248),
	array('Norway', 'Coast', 'Yes', 0, 740, 470, 276, 164),
	array('Sweden', 'Coast', 'Yes', 0, 857, 591, 336, 137),
	array('Finland', 'Coast', 'No', 6, 1084, 200, 403, 76),
	array('Kola', 'Coast', 'No', 6, 1164, 133, 444, 50),
	array('St. Petersburg', 'Coast', 'Yes', 6, 1288, 479, 499, 160),
	array('St. Petersburg (North Coast)', 'Coast', 'No', 6, 1318, 296, 509, 103),
	array('St. Petersburg (South Coast)', 'Coast', 'No', 6, 1174, 516, 446, 193),
	array('Moscow', 'Land', 'Yes', 6, 1442, 660, 567, 216),
	array('Reval', 'Coast', 'Yes', 6, 1052, 630, 404, 228),
	array('White Russia', 'Land', 'No', 6, 1202, 726, 447, 266),
	array('Ukraine', 'Land', 'No', 6, 1290, 814, 507, 312),
	array('Ciscaucasia', 'Coast', 'No', 6, 1688, 1086, 601, 343),
	array('Sevastopol', 'Coast', 'Yes', 6, 1342, 962, 497, 357),
	array('Kiev', 'Land', 'Yes', 6, 1180, 872, 436, 316),
	array('Warsaw', 'Land', 'Yes', 6, 1024, 772, 386, 290),
	array('Bessarabia', 'Coast', 'No', 6, 1237, 1019, 462, 378),
	array('Prussia', 'Coast', 'No', 4, 1008, 700, 359, 267),
	array('Silesia', 'Land', 'No', 4, 916, 834, 341, 307),
	array('Berlin', 'Coast', 'Yes', 4, 855, 747, 322, 284),
	array('Sudetenland', 'Land', 'No', 1, 804, 863, 315, 322),
	array('Dresden', 'Land', 'Yes', 4, 773, 827, 295, 308),
	array('Munich', 'Land', 'Yes', 4, 732, 896, 269, 342),
	array('Alsace', 'Land', 'No', 4, 660, 898, 243, 335),
	array('Essen', 'Land', 'Yes', 4, 665, 783, 252, 291),
	array('Frankfurt', 'Land', 'Yes', 4, 708, 826, 267, 309),
	array('Hanover', 'Coast', 'No', 4, 718, 732, 280, 282),
	array('Mecklenburg', 'Coast', 'No', 4, 794, 705, 304, 264),
	array('Kiel', 'Coast', 'Yes', 4, 744, 670, 281, 252),
	array('Denmark', 'Coast', 'Yes', 0, 727, 600, 283, 227),
	array('Bohemia', 'Land', 'No', 1, 893, 890, 342, 331),
	array('Galicia', 'Land', 'No', 1, 1088, 896, 404, 330),
	array('Budapest', 'Land', 'Yes', 1, 1003, 957, 370, 357),
	array('Vienna', 'Land', 'Yes', 1, 866, 972, 327, 357),
	array('Tyrol', 'Land', 'No', 1, 745, 989, 288, 364),
	array('Trieste', 'Coast', 'Yes', 1, 823, 1017, 315, 385),
	array('Croatia', 'Coast', 'No', 1, 850, 1101, 320, 410),
	array('Sarajevo', 'Land', 'Yes', 1, 931, 1108, 348, 414),
	array('Banat', 'Land', 'No', 1, 1001, 1058, 380, 392),
	array('Transylvania', 'Land', 'No', 1, 1081, 1022, 417, 375),
	array('Rumania', 'Coast', 'Yes', 0, 1203, 1074, 441, 397),
	array('Bulgaria', 'Coast', 'Yes', 0, 1168, 1158, 441, 431),
	array('Serbia', 'Land', 'Yes', 0, 1034, 1143, 386, 426),
	array('Montenegro', 'Coast', 'Yes', 0, 952, 1166, 361, 436),
	array('Albania', 'Coast', 'No', 7, 982, 1269, 368, 470),
	array('Greece', 'Coast', 'Yes', 0, 1048, 1385, 395, 518),
	array('Macedonia', 'Coast', 'No', 7, 1043, 1227, 393, 464),
	array('Constantinople', 'Coast', 'Yes', 7, 1268, 1264, 479, 471),
	array('Smyrna', 'Coast', 'Yes', 7, 1241, 1368, 464, 513),
	array('Konya', 'Coast', 'No', 7, 1360, 1356, 520, 514),
	array('Angora', 'Coast', 'No', 7, 1354, 1224, 514, 451),
	array('Erzurum', 'Coast', 'Yes', 7, 1572, 1250, 593, 470),
	array('Van', 'Land', 'No', 7, 1690, 1234, 631, 459),
	array('Persia', 'Coast', 'Yes', 0, 1928, 1406, 697, 492),
	array('Mesopotamia', 'Coast', 'No', 7, 1870, 1516, 683, 554),
	array('Jabal Shammar', 'Coast', 'No', 0, 1884, 1648, 692, 611),
	array('Damascus', 'Coast', 'Yes', 7, 1558, 1372, 586, 517),
	array('Hejaz', 'Coast', 'No', 7, 1524, 1640, 571, 613),
	array('Palestine', 'Coast', 'No', 7, 1484, 1562, 558, 582),
	array('Cairo', 'Coast', 'Yes', 2, 1296, 1658, 497, 621),
	array('Cyrenaica', 'Coast', 'No', 0, 1030, 1622, 389, 605),
	array('Tripolitania', 'Coast', 'Yes', 0, 778, 1636, 304, 612),
	array('Tunisia', 'Coast', 'No', 3, 648, 1406, 243, 536),
	array('Algiers', 'Coast', 'Yes', 3, 474, 1378, 172, 518),
	array('Morocco', 'Coast', 'Yes', 0, 186, 1422, 69, 535),
	array('Gibraltar', 'Coast', 'No', 2, 191, 1278, 69, 479),
	array('Spain', 'Coast', 'Yes', 0, 335, 1130, 130, 428),
	array('Spain (North Coast)', 'Coast', 'No', 0, 205, 1023, 86, 389),
	array('Spain (West Coast)', 'Coast', 'No', 0, 165, 1214, 68, 449),
	array('Spain (East Coast)', 'Coast', 'No', 0, 305, 1223, 109, 465),
	array('Portugal', 'Coast', 'Yes', 0, 155, 1096, 54, 414),
	array('Gascony', 'Coast', 'No', 3, 440, 991, 161, 373),
	array('Marseilles', 'Coast', 'Yes', 3, 578, 1087, 207, 409),
	array('Piedmont', 'Coast', 'No', 5, 638, 1059, 237, 404),
	array('Tuscany', 'Coast', 'No', 5, 721, 1121, 264, 417),
	array('Rome', 'Coast', 'Yes', 5, 744, 1174, 281, 442),
	array('Naples', 'Coast', 'Yes', 5, 804, 1370, 300, 513),
	array('Apulia', 'Coast', 'No', 5, 846, 1207, 308, 444),
	array('Bologna', 'Coast', 'Yes', 5, 780, 1126, 290, 418),
	array('Venetia', 'Coast', 'No', 5, 765, 1036, 287, 386),
	array('Milan', 'Land', 'Yes', 5, 700, 1020, 262, 380),
	array('Switzerland', 'Land', 'Yes', 0, 674, 969, 246, 362),
	array('Lyon', 'Land', 'Yes', 3, 559, 952, 204, 369),
	array('Paris', 'Land', 'Yes', 3, 495, 913, 185, 344),
	array('Brest', 'Coast', 'Yes', 3, 407, 885, 156, 332),
	array('Picardy', 'Coast', 'No', 3, 533, 826, 199, 307),
	array('Lorraine', 'Land', 'No', 3, 585, 883, 220, 328),
	array('Belgium', 'Coast', 'Yes', 0, 592, 789, 216, 292),
	array('Netherlands', 'Coast', 'Yes', 0, 649, 728, 240, 269),
	array('Barents Sea', 'Sea', 'No', 0, 1264, 63, 479, 14),
	array('Norwegian Sea', 'Sea', 'No', 0, 667, 210, 245, 74),
	array('North Atlantic', 'Sea', 'No', 0, 199, 350, 77, 115),
	array('Mid-Atlantic', 'Sea', 'No', 0, 181, 752, 45, 288),
	array('Irish Sea', 'Sea', 'No', 0, 329, 704, 121, 257),
	array('English Channel', 'Sea', 'No', 0, 355, 797, 137, 293),
	array('North Sea', 'Sea', 'No', 0, 596, 626, 221, 216),
	array('Helgoland Bight', 'Sea', 'No', 0, 688, 662, 254, 241),
	array('Skagerrak', 'Sea', 'No', 0, 775, 530, 293, 200),
	array('Baltic Sea', 'Sea', 'No', 0, 938, 630, 352, 231),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 995, 504, 374, 186),
	array('Bay of Biscay', 'Sea', 'No', 0, 308, 956, 101, 342),
	array('South Atlantic Ocean', 'Sea', 'No', 0, 44, 1280, 18, 481),
	array('Indian Ocean', 'Sea', 'No', 0, 1976, 1556, 737, 574),
	array('Western Mediterranean', 'Sea', 'No', 0, 592, 1323, 217, 494),
	array('Gulf of Lyon', 'Sea', 'No', 0, 571, 1185, 195, 439),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 725, 1271, 267, 482),
	array('Central Mediterranean', 'Sea', 'No', 0, 878, 1517, 338, 562),
	array('Ionian Sea', 'Sea', 'No', 0, 934, 1353, 348, 519),
	array('Adriatic Sea', 'Sea', 'No', 0, 895, 1205, 337, 450),
	array('Aegean Sea', 'Sea', 'No', 0, 1125, 1291, 432, 532),
	array('Eastern Mediterranean', 'Sea', 'No', 0, 1328, 1517, 492, 572),
	array('Black Sea', 'Sea', 'No', 0, 1333, 1125, 494, 425)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Iceland','Norwegian Sea','Yes','No'),
	array('Iceland','North Atlantic','Yes','No'),
	array('Glasgow','Belfast','Yes','Yes'),
	array('Glasgow','Liverpool','Yes','Yes'),
	array('Glasgow','Yorkshire','Yes','Yes'),
	array('Glasgow','Norwegian Sea','Yes','No'),
	array('Glasgow','North Atlantic','Yes','No'),
	array('Glasgow','Irish Sea','Yes','No'),
	array('Glasgow','North Sea','Yes','No'),
	array('Belfast','North Atlantic','Yes','No'),
	array('Belfast','Mid-Atlantic','Yes','No'),
	array('Belfast','Irish Sea','Yes','No'),
	array('Liverpool','Wales','Yes','Yes'),
	array('Liverpool','Yorkshire','No','Yes'),
	array('Liverpool','Irish Sea','Yes','No'),
	array('Wales','London','Yes','Yes'),
	array('Wales','Yorkshire','No','Yes'),
	array('Wales','Irish Sea','Yes','No'),
	array('Wales','English Channel','Yes','No'),
	array('London','Yorkshire','Yes','Yes'),
	array('London','English Channel','Yes','No'),
	array('London','North Sea','Yes','No'),
	array('Yorkshire','North Sea','Yes','No'),
	array('Norway','Sweden','Yes','Yes'),
	array('Norway','Finland','No','Yes'),
	array('Norway','Kola','Yes','Yes'),
	array('Norway','Barents Sea','Yes','No'),
	array('Norway','Norwegian Sea','Yes','No'),
	array('Norway','North Sea','Yes','No'),
	array('Norway','Skagerrak','Yes','No'),
	array('Sweden','Finland','Yes','Yes'),
	array('Sweden','Denmark','Yes','Yes'),
	array('Sweden','Skagerrak','Yes','No'),
	array('Sweden','Baltic Sea','Yes','No'),
	array('Sweden','Gulf of Bothnia','Yes','No'),
	array('Finland','Kola','No','Yes'),
	array('Finland','St. Petersburg','No','Yes'),
	array('Finland','St. Petersburg (South Coast)','Yes','No'),
	array('Finland','Gulf of Bothnia','Yes','No'),
	array('Kola','St. Petersburg','No','Yes'),
	array('Kola','St. Petersburg (North Coast)','Yes','No'),
	array('Kola','Barents Sea','Yes','No'),
	array('St. Petersburg','Moscow','No','Yes'),
	array('St. Petersburg','Reval','No','Yes'),
	array('St. Petersburg','White Russia','No','Yes'),
	array('St. Petersburg (North Coast)','Barents Sea','Yes','No'),
	array('St. Petersburg (South Coast)','Reval','Yes','No'),
	array('St. Petersburg (South Coast)','Gulf of Bothnia','Yes','No'),
	array('Moscow','White Russia','No','Yes'),
	array('Moscow','Ukraine','No','Yes'),
	array('Moscow','Ciscaucasia','No','Yes'),
	array('Reval','White Russia','No','Yes'),
	array('Reval','Warsaw','No','Yes'),
	array('Reval','Prussia','Yes','Yes'),
	array('Reval','Baltic Sea','Yes','No'),
	array('Reval','Gulf of Bothnia','Yes','No'),
	array('White Russia','Ukraine','No','Yes'),
	array('White Russia','Kiev','No','Yes'),
	array('White Russia','Warsaw','No','Yes'),
	array('Ukraine','Ciscaucasia','No','Yes'),
	array('Ukraine','Sevastopol','No','Yes'),
	array('Ukraine','Kiev','No','Yes'),
	array('Ciscaucasia','Sevastopol','Yes','Yes'),
	array('Ciscaucasia','Erzurum','Yes','Yes'),
	array('Ciscaucasia','Van','No','Yes'),
	array('Ciscaucasia','Persia','No','Yes'),
	array('Ciscaucasia','Black Sea','Yes','No'),
	array('Sevastopol','Kiev','No','Yes'),
	array('Sevastopol','Bessarabia','Yes','Yes'),
	array('Sevastopol','Black Sea','Yes','No'),
	array('Kiev','Warsaw','No','Yes'),
	array('Kiev','Bessarabia','No','Yes'),
	array('Kiev','Galicia','No','Yes'),
	array('Warsaw','Prussia','No','Yes'),
	array('Warsaw','Silesia','No','Yes'),
	array('Warsaw','Galicia','No','Yes'),
	array('Bessarabia','Galicia','No','Yes'),
	array('Bessarabia','Rumania','Yes','Yes'),
	array('Bessarabia','Black Sea','Yes','No'),
	array('Prussia','Silesia','No','Yes'),
	array('Prussia','Berlin','Yes','Yes'),
	array('Prussia','Baltic Sea','Yes','No'),
	array('Silesia','Berlin','No','Yes'),
	array('Silesia','Sudetenland','No','Yes'),
	array('Silesia','Dresden','No','Yes'),
	array('Silesia','Bohemia','No','Yes'),
	array('Silesia','Galicia','No','Yes'),
	array('Berlin','Dresden','No','Yes'),
	array('Berlin','Frankfurt','No','Yes'),
	array('Berlin','Hanover','No','Yes'),
	array('Berlin','Mecklenburg','Yes','Yes'),
	array('Berlin','Baltic Sea','Yes','No'),
	array('Sudetenland','Dresden','No','Yes'),
	array('Sudetenland','Munich','No','Yes'),
	array('Sudetenland','Bohemia','No','Yes'),
	array('Dresden','Munich','No','Yes'),
	array('Dresden','Frankfurt','No','Yes'),
	array('Munich','Alsace','No','Yes'),
	array('Munich','Essen','No','Yes'),
	array('Munich','Frankfurt','No','Yes'),
	array('Munich','Bohemia','No','Yes'),
	array('Munich','Tyrol','No','Yes'),
	array('Munich','Switzerland','No','Yes'),
	array('Alsace','Essen','No','Yes'),
	array('Alsace','Switzerland','No','Yes'),
	array('Alsace','Lyon','No','Yes'),
	array('Alsace','Lorraine','No','Yes'),
	array('Alsace','Belgium','No','Yes'),
	array('Essen','Frankfurt','No','Yes'),
	array('Essen','Hanover','No','Yes'),
	array('Essen','Belgium','No','Yes'),
	array('Essen','Netherlands','No','Yes'),
	array('Frankfurt','Hanover','No','Yes'),
	array('Hanover','Mecklenburg','Yes','Yes'),
	array('Hanover','Kiel','Yes','Yes'),
	array('Hanover','Netherlands','Yes','Yes'),
	array('Hanover','Helgoland Bight','Yes','No'),
	array('Mecklenburg','Kiel','Yes','Yes'),
	array('Mecklenburg','Baltic Sea','Yes','No'),
	array('Kiel','Denmark','Yes','Yes'),
	array('Kiel','Helgoland Bight','Yes','No'),
	array('Kiel','Baltic Sea','Yes','No'),
	array('Denmark','North Sea','Yes','No'),
	array('Denmark','Helgoland Bight','Yes','No'),
	array('Denmark','Skagerrak','Yes','No'),
	array('Denmark','Baltic Sea','Yes','No'),
	array('Bohemia','Galicia','No','Yes'),
	array('Bohemia','Budapest','No','Yes'),
	array('Bohemia','Vienna','No','Yes'),
	array('Bohemia','Tyrol','No','Yes'),
	array('Galicia','Budapest','No','Yes'),
	array('Galicia','Transylvania','No','Yes'),
	array('Galicia','Rumania','No','Yes'),
	array('Budapest','Vienna','No','Yes'),
	array('Budapest','Croatia','No','Yes'),
	array('Budapest','Banat','No','Yes'),
	array('Budapest','Transylvania','No','Yes'),
	array('Vienna','Tyrol','No','Yes'),
	array('Vienna','Trieste','No','Yes'),
	array('Vienna','Croatia','No','Yes'),
	array('Tyrol','Trieste','No','Yes'),
	array('Tyrol','Venetia','No','Yes'),
	array('Tyrol','Milan','No','Yes'),
	array('Tyrol','Switzerland','No','Yes'),
	array('Trieste','Croatia','Yes','Yes'),
	array('Trieste','Venetia','Yes','Yes'),
	array('Trieste','Adriatic Sea','Yes','No'),
	array('Croatia','Sarajevo','No','Yes'),
	array('Croatia','Banat','No','Yes'),
	array('Croatia','Serbia','No','Yes'),
	array('Croatia','Montenegro','Yes','Yes'),
	array('Croatia','Adriatic Sea','Yes','No'),
	array('Sarajevo','Serbia','No','Yes'),
	array('Sarajevo','Montenegro','No','Yes'),
	array('Sarajevo','Macedonia','No','Yes'),
	array('Banat','Transylvania','No','Yes'),
	array('Banat','Rumania','No','Yes'),
	array('Banat','Serbia','No','Yes'),
	array('Transylvania','Rumania','No','Yes'),
	array('Rumania','Bulgaria','Yes','Yes'),
	array('Rumania','Serbia','No','Yes'),
	array('Rumania','Black Sea','Yes','No'),
	array('Bulgaria','Serbia','No','Yes'),
	array('Bulgaria','Macedonia','No','Yes'),
	array('Bulgaria','Constantinople','Yes','Yes'),
	array('Bulgaria','Black Sea','Yes','No'),
	array('Serbia','Macedonia','No','Yes'),
	array('Montenegro','Albania','Yes','Yes'),
	array('Montenegro','Macedonia','No','Yes'),
	array('Montenegro','Adriatic Sea','Yes','No'),
	array('Albania','Greece','Yes','Yes'),
	array('Albania','Macedonia','No','Yes'),
	array('Albania','Ionian Sea','Yes','No'),
	array('Albania','Adriatic Sea','Yes','No'),
	array('Greece','Macedonia','Yes','Yes'),
	array('Greece','Central Mediterranean','Yes','No'),
	array('Greece','Ionian Sea','Yes','No'),
	array('Greece','Aegean Sea','Yes','No'),
	array('Macedonia','Constantinople','Yes','Yes'),
	array('Macedonia','Aegean Sea','Yes','No'),
	array('Constantinople','Smyrna','Yes','Yes'),
	array('Constantinople','Konya','No','Yes'),
	array('Constantinople','Angora','Yes','Yes'),
	array('Constantinople','Aegean Sea','Yes','No'),
	array('Constantinople','Black Sea','Yes','No'),
	array('Smyrna','Konya','Yes','Yes'),
	array('Smyrna','Aegean Sea','Yes','No'),
	array('Konya','Angora','No','Yes'),
	array('Konya','Erzurum','No','Yes'),
	array('Konya','Damascus','Yes','Yes'),
	array('Konya','Aegean Sea','Yes','No'),
	array('Konya','Eastern Mediterranean','Yes','No'),
	array('Angora','Erzurum','Yes','Yes'),
	array('Angora','Black Sea','Yes','No'),
	array('Erzurum','Van','No','Yes'),
	array('Erzurum','Mesopotamia','No','Yes'),
	array('Erzurum','Damascus','No','Yes'),
	array('Erzurum','Black Sea','Yes','No'),
	array('Van','Persia','No','Yes'),
	array('Van','Mesopotamia','No','Yes'),
	array('Persia','Mesopotamia','Yes','Yes'),
	array('Persia','Indian Ocean','Yes','No'),
	array('Mesopotamia','Jabal Shammar','Yes','Yes'),
	array('Mesopotamia','Damascus','No','Yes'),
	array('Mesopotamia','Indian Ocean','Yes','No'),
	array('Jabal Shammar','Indian Ocean','Yes','No'),
	array('Damascus','Hejaz','No','Yes'),
	array('Damascus','Palestine','Yes','Yes'),
	array('Damascus','Eastern Mediterranean','Yes','No'),
	array('Hejaz','Palestine','No','Yes'),
	array('Hejaz','Cairo','Yes','Yes'),
	array('Hejaz','Indian Ocean','Yes','No'),
	array('Palestine','Cairo','Yes','Yes'),
	array('Palestine','Eastern Mediterranean','Yes','No'),
	array('Cairo','Cyrenaica','Yes','Yes'),
	array('Cairo','South Atlantic Ocean','Yes','No'),
	array('Cairo','Indian Ocean','Yes','No'),
	array('Cairo','Eastern Mediterranean','Yes','No'),
	array('Cyrenaica','Tripolitania','Yes','Yes'),
	array('Cyrenaica','Central Mediterranean','Yes','No'),
	array('Cyrenaica','Eastern Mediterranean','Yes','No'),
	array('Tripolitania','Tunisia','Yes','Yes'),
	array('Tripolitania','Central Mediterranean','Yes','No'),
	array('Tunisia','Algiers','Yes','Yes'),
	array('Tunisia','Western Mediterranean','Yes','No'),
	array('Tunisia','Tyrrhenian Sea','Yes','No'),
	array('Tunisia','Central Mediterranean','Yes','No'),
	array('Algiers','Morocco','Yes','Yes'),
	array('Algiers','Western Mediterranean','Yes','No'),
	array('Morocco','Gibraltar','Yes','Yes'),
	array('Morocco','South Atlantic Ocean','Yes','No'),
	array('Morocco','Western Mediterranean','Yes','No'),
	array('Gibraltar','Spain','No','Yes'),
	array('Gibraltar','Spain (West Coast)','Yes','No'),
	array('Gibraltar','Spain (East Coast)','Yes','No'),
	array('Gibraltar','South Atlantic Ocean','Yes','No'),
	array('Gibraltar','Western Mediterranean','Yes','No'),
	array('Spain','Portugal','No','Yes'),
	array('Spain','Gascony','No','Yes'),
	array('Spain','Marseilles','No','Yes'),
	array('Spain (North Coast)','Portugal','Yes','No'),
	array('Spain (North Coast)','Gascony','Yes','No'),
	array('Spain (North Coast)','Bay of Biscay','Yes','No'),
	array('Spain (West Coast)','Portugal','Yes','No'),
	array('Spain (West Coast)','South Atlantic Ocean','Yes','No'),
	array('Spain (East Coast)','Marseilles','Yes','No'),
	array('Spain (East Coast)','Western Mediterranean','Yes','No'),
	array('Spain (East Coast)','Gulf of Lyon','Yes','No'),
	array('Portugal','Bay of Biscay','Yes','No'),
	array('Portugal','South Atlantic Ocean','Yes','No'),
	array('Gascony','Marseilles','No','Yes'),
	array('Gascony','Lyon','No','Yes'),
	array('Gascony','Paris','No','Yes'),
	array('Gascony','Brest','Yes','Yes'),
	array('Gascony','Bay of Biscay','Yes','No'),
	array('Marseilles','Piedmont','Yes','Yes'),
	array('Marseilles','Lyon','No','Yes'),
	array('Marseilles','Gulf of Lyon','Yes','No'),
	array('Piedmont','Tuscany','Yes','Yes'),
	array('Piedmont','Bologna','No','Yes'),
	array('Piedmont','Milan','No','Yes'),
	array('Piedmont','Switzerland','No','Yes'),
	array('Piedmont','Lyon','No','Yes'),
	array('Piedmont','Gulf of Lyon','Yes','No'),
	array('Tuscany','Rome','Yes','Yes'),
	array('Tuscany','Bologna','No','Yes'),
	array('Tuscany','Gulf of Lyon','Yes','No'),
	array('Tuscany','Tyrrhenian Sea','Yes','No'),
	array('Rome','Naples','Yes','Yes'),
	array('Rome','Apulia','No','Yes'),
	array('Rome','Bologna','No','Yes'),
	array('Rome','Tyrrhenian Sea','Yes','No'),
	array('Naples','Apulia','Yes','Yes'),
	array('Naples','Tyrrhenian Sea','Yes','No'),
	array('Naples','Central Mediterranean','Yes','No'),
	array('Naples','Ionian Sea','Yes','No'),
	array('Apulia','Bologna','Yes','Yes'),
	array('Apulia','Ionian Sea','Yes','No'),
	array('Apulia','Adriatic Sea','Yes','No'),
	array('Bologna','Venetia','Yes','Yes'),
	array('Bologna','Milan','No','Yes'),
	array('Bologna','Adriatic Sea','Yes','No'),
	array('Venetia','Milan','No','Yes'),
	array('Venetia','Adriatic Sea','Yes','No'),
	array('Milan','Switzerland','No','Yes'),
	array('Switzerland','Lyon','No','Yes'),
	array('Lyon','Paris','No','Yes'),
	array('Lyon','Lorraine','No','Yes'),
	array('Paris','Brest','No','Yes'),
	array('Paris','Picardy','No','Yes'),
	array('Paris','Lorraine','No','Yes'),
	array('Brest','Picardy','Yes','Yes'),
	array('Brest','English Channel','Yes','No'),
	array('Brest','Bay of Biscay','Yes','No'),
	array('Picardy','Lorraine','No','Yes'),
	array('Picardy','Belgium','Yes','Yes'),
	array('Picardy','English Channel','Yes','No'),
	array('Lorraine','Belgium','No','Yes'),
	array('Belgium','Netherlands','Yes','Yes'),
	array('Belgium','English Channel','Yes','No'),
	array('Belgium','North Sea','Yes','No'),
	array('Netherlands','North Sea','Yes','No'),
	array('Netherlands','Helgoland Bight','Yes','No'),
	array('Barents Sea','Norwegian Sea','Yes','No'),
	array('Norwegian Sea','North Atlantic','Yes','No'),
	array('Norwegian Sea','North Sea','Yes','No'),
	array('North Atlantic','Mid-Atlantic','Yes','No'),
	array('North Atlantic','Irish Sea','Yes','No'),
	array('Mid-Atlantic','Irish Sea','Yes','No'),
	array('Mid-Atlantic','English Channel','Yes','No'),
	array('Mid-Atlantic','Bay of Biscay','Yes','No'),
	array('Mid-Atlantic','South Atlantic Ocean','Yes','No'),
	array('Irish Sea','English Channel','Yes','No'),
	array('English Channel','North Sea','Yes','No'),
	array('English Channel','Bay of Biscay','Yes','No'),
	array('North Sea','Helgoland Bight','Yes','No'),
	array('North Sea','Skagerrak','Yes','No'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No'),
	array('Bay of Biscay','South Atlantic Ocean','Yes','No'),
	array('South Atlantic Ocean','Indian Ocean','Yes','No'),
	array('Western Mediterranean','Gulf of Lyon','Yes','No'),
	array('Western Mediterranean','Tyrrhenian Sea','Yes','No'),
	array('Gulf of Lyon','Tyrrhenian Sea','Yes','No'),
	array('Tyrrhenian Sea','Central Mediterranean','Yes','No'),
	array('Central Mediterranean','Ionian Sea','Yes','No'),
	array('Central Mediterranean','Aegean Sea','Yes','No'),
	array('Central Mediterranean','Eastern Mediterranean','Yes','No'),
	array('Ionian Sea','Adriatic Sea','Yes','No'),
	array('Aegean Sea','Eastern Mediterranean','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
