<?php
// This is file installs the map data for the PunicWars variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Mare Ligusticum', 'Sea', 'No', 0, 272, 85, 272, 85),
	array('Mare Corsicum', 'Sea', 'No', 0, 385, 250, 385, 250),
	array('Mare Sardoum', 'Sea', 'No', 0, 155, 367, 155, 367),
	array('Mare Barbarum', 'Sea', 'No', 0, 34, 163, 34, 163),
	array('Mare Mauretanum', 'Sea', 'No', 0, 31, 424, 31, 424),
	array('Mare Novum', 'Sea', 'No', 0, 100, 259, 100, 259),
	array('Mare Africum', 'Sea', 'No', 0, 398, 562, 398, 562),
	array('Mare Siculum', 'Sea', 'No', 0, 500, 463, 500, 463),
	array('Mare Tyrrhenum', 'Sea', 'No', 0, 548, 408, 548, 408),
	array('Mare Ionium', 'Sea', 'No', 0, 800, 455, 800, 455),
	array('Mare Libycum', 'Sea', 'No', 0, 418, 753, 418, 753),
	array('Mare Latium', 'Sea', 'No', 0, 352, 144, 352, 144),
	array('Mare Lucanum', 'Sea', 'No', 0, 605, 365, 605, 365),
	array('Punicum Sinus', 'Sea', 'No', 0, 380, 674, 380, 674),
	array('Luca', 'Coast', 'No', 0, 345, 31, 345, 31),
	array('Bononia', 'Land', 'No', 0, 465, 68, 465, 68),
	array('Pisae', 'Coast', 'Yes', 0, 388, 68, 388, 68),
	array('Volaterra', 'Coast', 'No', 0, 427, 148, 427, 148),
	array('Roma', 'Coast', 'Yes', 4, 480, 186, 480, 186),
	array('Capua', 'Land', 'No', 0, 570, 208, 570, 208),
	array('Casinum', 'Coast', 'No', 4, 513, 198, 513, 198),
	array('Neapolis', 'Coast', 'Yes', 4, 531, 228, 531, 228),
	array('Nola', 'Coast', 'No', 0, 562, 244, 562, 244),
	array('Beneventum', 'Coast', 'Yes', 0, 592, 273, 592, 273),
	array('Asculum', 'Land', 'No', 0, 490, 120, 490, 120),
	array('Herdonia', 'Land', 'No', 0, 610, 200, 610, 200),
	array('Cannae', 'Land', 'No', 0, 645, 252, 645, 252),
	array('Brundisium', 'Coast', 'No', 0, 830, 270, 830, 270),
	array('Pompei', 'Coast', 'No', 0, 610, 305, 610, 305),
	array('Grumentum', 'Coast', 'No', 0, 708, 390, 708, 390),
	array('Herculaneum', 'Coast', 'Yes', 2, 659, 306, 659, 306),
	array('Amalfi', 'Coast', 'No', 2, 672, 388, 672, 388),
	array('Locri', 'Coast', 'Yes', 2, 670, 455, 670, 455),
	array('Messana', 'Coast', 'No', 0, 599, 495, 599, 495),
	array('Syracusae', 'Coast', 'Yes', 0, 580, 610, 580, 610),
	array('Agrigentum', 'Coast', 'No', 0, 457, 532, 457, 532),
	array('Panormus', 'Coast', 'Yes', 0, 445, 478, 445, 478),
	array('Segesta', 'Land', 'Yes', 0, 540, 550, 540, 550),
	array('Mariana', 'Coast', 'Yes', 3, 161, 90, 161, 90),
	array('Aleria', 'Coast', 'No', 3, 173, 142, 173, 142),
	array('Aleria (East Coast)', 'Coast', 'No', 3, 188, 126, 188, 126),
	array('Aleria (West Coast)', 'Coast', 'No', 3, 147, 150, 147, 150),
	array('Titanis', 'Coast', 'Yes', 3, 187, 163, 187, 163),
	array('Olbia', 'Coast', 'Yes', 0, 268, 315, 268, 315),
	array('Caralis', 'Coast', 'No', 0, 236, 340, 236, 340),
	array('Caralis (North Coast)', 'Coast', 'No', 0, 205, 235, 205, 235),
	array('Caralis (South Coast)', 'Coast', 'No', 0, 280, 393, 280, 393),
	array('Sulci', 'Coast', 'Yes', 0, 200, 388, 200, 388),
	array('Carthago', 'Coast', 'Yes', 1, 355, 614, 355, 614),
	array('Utica', 'Coast', 'No', 1, 250, 580, 250, 580),
	array('Hippo Regius', 'Coast', 'Yes', 1, 155, 605, 155, 605),
	array('Hadrumetum', 'Coast', 'No', 0, 312, 700, 312, 700),
	array('Sicca', 'Land', 'No', 0, 124, 714, 124, 714),
	array('Thapsus', 'Coast', 'No', 0, 246, 722, 246, 722),
	array('Saldae', 'Coast', 'No', 0, 128, 577, 128, 577),
	array('Zama', 'Land', 'No', 0, 197, 719, 197, 719),
	array('Cirta', 'Land', 'No', 0, 90, 677, 90, 677),
	array('Iol', 'Coast', 'Yes', 0, 95, 590, 95, 590),
	array('Cartenna', 'Coast', 'No', 0, 59, 574, 59, 574),
	array('Russadir', 'Coast', 'No', 0, 25, 602, 25, 602),
	array('Tarentinus Sinus', 'Sea', 'No', 0, 735, 330, 735, 330),
	array('Tarentum', 'Land', 'No', 0, 764, 286, 764, 286),
	array('Iscia', 'Land', 'Yes', 0, 459, 277, 459, 277),
	array('Neapolis Sinus', 'Sea', 'No', 0, 498, 233, 498, 233)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Mare Ligusticum','Mare Corsicum','Yes','No'),
	array('Mare Ligusticum','Mare Barbarum','Yes','No'),
	array('Mare Ligusticum','Mare Latium','Yes','No'),
	array('Mare Ligusticum','Luca','Yes','No'),
	array('Mare Ligusticum','Pisae','Yes','No'),
	array('Mare Ligusticum','Mariana','Yes','No'),
	array('Mare Corsicum','Mare Sardoum','Yes','No'),
	array('Mare Corsicum','Mare Tyrrhenum','Yes','No'),
	array('Mare Corsicum','Mare Latium','Yes','No'),
	array('Mare Corsicum','Mariana','Yes','No'),
	array('Mare Corsicum','Aleria (East Coast)','Yes','No'),
	array('Mare Corsicum','Titanis','Yes','No'),
	array('Mare Corsicum','Olbia','Yes','No'),
	array('Mare Corsicum','Caralis (North Coast)','Yes','No'),
	array('Mare Corsicum','Sulci','Yes','No'),
	array('Mare Corsicum','Iscia','Yes','No'),
	array('Mare Sardoum','Mare Novum','Yes','No'),
	array('Mare Sardoum','Mare Africum','Yes','No'),
	array('Mare Sardoum','Mare Siculum','Yes','No'),
	array('Mare Sardoum','Panormus','Yes','No'),
	array('Mare Sardoum','Titanis','Yes','No'),
	array('Mare Sardoum','Sulci','Yes','No'),
	array('Mare Barbarum','Mare Mauretanum','Yes','No'),
	array('Mare Barbarum','Mare Novum','Yes','No'),
	array('Mare Barbarum','Mariana','Yes','No'),
	array('Mare Mauretanum','Mare Novum','Yes','No'),
	array('Mare Mauretanum','Iol','Yes','No'),
	array('Mare Mauretanum','Cartenna','Yes','No'),
	array('Mare Mauretanum','Russadir','Yes','No'),
	array('Mare Novum','Mare Africum','Yes','No'),
	array('Mare Novum','Mariana','Yes','No'),
	array('Mare Novum','Aleria (West Coast)','Yes','No'),
	array('Mare Novum','Titanis','Yes','No'),
	array('Mare Novum','Saldae','Yes','No'),
	array('Mare Novum','Iol','Yes','No'),
	array('Mare Africum','Punicum Sinus','Yes','No'),
	array('Mare Africum','Agrigentum','Yes','No'),
	array('Mare Africum','Panormus','Yes','No'),
	array('Mare Africum','Carthago','Yes','No'),
	array('Mare Africum','Utica','Yes','No'),
	array('Mare Africum','Hippo Regius','Yes','No'),
	array('Mare Africum','Saldae','Yes','No'),
	array('Mare Siculum','Mare Tyrrhenum','Yes','No'),
	array('Mare Siculum','Mare Ionium','Yes','No'),
	array('Mare Siculum','Locri','Yes','No'),
	array('Mare Siculum','Messana','Yes','No'),
	array('Mare Siculum','Panormus','Yes','No'),
	array('Mare Siculum','Olbia','Yes','No'),
	array('Mare Siculum','Caralis (South Coast)','Yes','No'),
	array('Mare Siculum','Sulci','Yes','No'),
	array('Mare Tyrrhenum','Mare Lucanum','Yes','No'),
	array('Mare Tyrrhenum','Amalfi','Yes','No'),
	array('Mare Tyrrhenum','Locri','Yes','No'),
	array('Mare Tyrrhenum','Olbia','Yes','No'),
	array('Mare Tyrrhenum','Iscia','Yes','No'),
	array('Mare Ionium','Mare Libycum','Yes','No'),
	array('Mare Ionium','Punicum Sinus','Yes','No'),
	array('Mare Ionium','Grumentum','Yes','No'),
	array('Mare Ionium','Locri','Yes','No'),
	array('Mare Ionium','Messana','Yes','No'),
	array('Mare Ionium','Syracusae','Yes','No'),
	array('Mare Ionium','Tarentinus Sinus','Yes','No'),
	array('Mare Libycum','Punicum Sinus','Yes','No'),
	array('Mare Libycum','Hadrumetum','Yes','No'),
	array('Mare Libycum','Thapsus','Yes','No'),
	array('Mare Latium','Pisae','Yes','No'),
	array('Mare Latium','Volaterra','Yes','No'),
	array('Mare Latium','Roma','Yes','No'),
	array('Mare Latium','Iscia','Yes','No'),
	array('Mare Latium','Neapolis Sinus','Yes','No'),
	array('Mare Lucanum','Nola','Yes','No'),
	array('Mare Lucanum','Beneventum','Yes','No'),
	array('Mare Lucanum','Pompei','Yes','No'),
	array('Mare Lucanum','Herculaneum','Yes','No'),
	array('Mare Lucanum','Amalfi','Yes','No'),
	array('Mare Lucanum','Iscia','Yes','No'),
	array('Mare Lucanum','Neapolis Sinus','Yes','No'),
	array('Punicum Sinus','Syracusae','Yes','No'),
	array('Punicum Sinus','Agrigentum','Yes','No'),
	array('Punicum Sinus','Carthago','Yes','No'),
	array('Punicum Sinus','Hadrumetum','Yes','No'),
	array('Luca','Bononia','No','Yes'),
	array('Luca','Pisae','Yes','Yes'),
	array('Bononia','Pisae','No','Yes'),
	array('Bononia','Volaterra','No','Yes'),
	array('Bononia','Roma','No','Yes'),
	array('Bononia','Asculum','No','Yes'),
	array('Pisae','Volaterra','Yes','Yes'),
	array('Volaterra','Roma','Yes','Yes'),
	array('Roma','Capua','No','Yes'),
	array('Roma','Casinum','Yes','Yes'),
	array('Roma','Asculum','No','Yes'),
	array('Roma','Neapolis Sinus','Yes','No'),
	array('Capua','Casinum','No','Yes'),
	array('Capua','Nola','No','Yes'),
	array('Capua','Beneventum','No','Yes'),
	array('Capua','Asculum','No','Yes'),
	array('Capua','Herdonia','No','Yes'),
	array('Casinum','Neapolis','Yes','Yes'),
	array('Casinum','Nola','No','Yes'),
	array('Casinum','Neapolis Sinus','Yes','No'),
	array('Neapolis','Nola','Yes','Yes'),
	array('Neapolis','Neapolis Sinus','Yes','No'),
	array('Nola','Beneventum','Yes','Yes'),
	array('Nola','Neapolis Sinus','Yes','No'),
	array('Beneventum','Herdonia','No','Yes'),
	array('Beneventum','Cannae','No','Yes'),
	array('Beneventum','Pompei','Yes','Yes'),
	array('Asculum','Herdonia','No','Yes'),
	array('Herdonia','Cannae','No','Yes'),
	array('Cannae','Brundisium','No','Yes'),
	array('Cannae','Pompei','No','Yes'),
	array('Cannae','Tarentum','No','Yes'),
	array('Brundisium','Tarentinus Sinus','Yes','No'),
	array('Brundisium','Tarentum','No','Yes'),
	array('Pompei','Herculaneum','Yes','Yes'),
	array('Pompei','Tarentum','No','Yes'),
	array('Grumentum','Herculaneum','No','Yes'),
	array('Grumentum','Amalfi','No','Yes'),
	array('Grumentum','Locri','Yes','Yes'),
	array('Grumentum','Tarentinus Sinus','Yes','No'),
	array('Grumentum','Tarentum','Yes','Yes'),
	array('Herculaneum','Amalfi','Yes','Yes'),
	array('Herculaneum','Tarentum','No','Yes'),
	array('Amalfi','Locri','Yes','Yes'),
	array('Messana','Syracusae','Yes','Yes'),
	array('Messana','Panormus','Yes','Yes'),
	array('Messana','Segesta','No','Yes'),
	array('Syracusae','Agrigentum','Yes','Yes'),
	array('Syracusae','Segesta','No','Yes'),
	array('Agrigentum','Panormus','Yes','Yes'),
	array('Agrigentum','Segesta','No','Yes'),
	array('Panormus','Segesta','No','Yes'),
	array('Mariana','Aleria','No','Yes'),
	array('Mariana','Aleria (East Coast)','Yes','No'),
	array('Mariana','Aleria (West Coast)','Yes','No'),
	array('Aleria','Titanis','No','Yes'),
	array('Aleria (East Coast)','Titanis','Yes','No'),
	array('Aleria (West Coast)','Titanis','Yes','No'),
	array('Olbia','Caralis','No','Yes'),
	array('Olbia','Caralis (North Coast)','Yes','No'),
	array('Olbia','Caralis (South Coast)','Yes','No'),
	array('Caralis','Sulci','No','Yes'),
	array('Caralis (North Coast)','Sulci','Yes','No'),
	array('Caralis (South Coast)','Sulci','Yes','No'),
	array('Carthago','Utica','Yes','Yes'),
	array('Carthago','Hadrumetum','Yes','Yes'),
	array('Carthago','Thapsus','No','Yes'),
	array('Carthago','Zama','No','Yes'),
	array('Utica','Hippo Regius','Yes','Yes'),
	array('Utica','Sicca','No','Yes'),
	array('Utica','Zama','No','Yes'),
	array('Hippo Regius','Sicca','No','Yes'),
	array('Hippo Regius','Saldae','Yes','Yes'),
	array('Hadrumetum','Thapsus','Yes','Yes'),
	array('Sicca','Saldae','No','Yes'),
	array('Sicca','Zama','No','Yes'),
	array('Sicca','Cirta','No','Yes'),
	array('Thapsus','Zama','No','Yes'),
	array('Saldae','Cirta','No','Yes'),
	array('Saldae','Iol','Yes','Yes'),
	array('Cirta','Iol','No','Yes'),
	array('Cirta','Russadir','No','Yes'),
	array('Iol','Cartenna','Yes','Yes'),
	array('Iol','Russadir','No','Yes'),
	array('Cartenna','Russadir','Yes','Yes'),
	array('Tarentinus Sinus','Tarentum','Yes','No'),
	array('Iscia','Neapolis Sinus','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
