<?php
// This is file installs the map data for the MachiavelliTTR variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Avignon', 'Coast', 'Yes', 3, 103, 63, 48, 30),
	array('Marseilles', 'Coast', 'Yes', 3, 237, 251, 119, 124),
	array('Provence', 'Coast', 'No', 3, 336, 307, 178, 119),
	array('Swiss', 'Land', 'Yes', 0, 641, 27, 315, 18),
	array('Saluzzo', 'Land', 'Yes', 0, 537, 180, 267, 103),
	array('Turin', 'Land', 'Yes', 0, 638, 117, 325, 71),
	array('Savoy', 'Coast', 'Yes', 5, 502, 287, 238, 143),
	array('Montferrat', 'Land', 'Yes', 0, 623, 283, 316, 141),
	array('Genoa', 'Coast', 'Yes', 5, 547, 354, 279, 178),
	array('Como', 'Land', 'No', 4, 785, 109, 395, 52),
	array('Pavia', 'Land', 'Yes', 4, 746, 215, 375, 105),
	array('Milan', 'Land', 'Yes', 4, 907, 168, 454, 79),
	array('Cremona', 'Land', 'Yes', 4, 874, 294, 437, 140),
	array('Parma', 'Land', 'No', 4, 814, 320, 407, 152),
	array('Formova', 'Land', 'No', 4, 742, 345, 372, 170),
	array('Tyrolia', 'Land', 'Yes', 0, 1024, 63, 507, 30),
	array('Carinthia', 'Land', 'No', 0, 1212, 190, 606, 89),
	array('Trent', 'Land', 'Yes', 0, 1077, 253, 535, 124),
	array('Bergamo', 'Land', 'No', 0, 952, 319, 473, 156),
	array('Verona', 'Land', 'No', 0, 1055, 351, 532, 170),
	array('Friuli', 'Coast', 'No', 0, 1201, 400, 599, 186),
	array('Treviso', 'Land', 'Yes', 0, 1137, 426, 571, 212),
	array('Venice', 'Coast', 'Yes', 7, 1139, 502, 577, 246),
	array('Padua', 'Coast', 'Yes', 7, 1033, 476, 519, 237),
	array('Mantua', 'Land', 'Yes', 0, 932, 411, 463, 202),
	array('Ferrara', 'Coast', 'Yes', 7, 998, 546, 502, 269),
	array('Modena', 'Coast', 'Yes', 5, 855, 468, 428, 234),
	array('Lucca', 'Coast', 'Yes', 0, 779, 537, 385, 266),
	array('Bologna', 'Coast', 'Yes', 0, 943, 578, 464, 277),
	array('Pistoia', 'Land', 'No', 2, 822, 582, 412, 288),
	array('Pisa', 'Coast', 'Yes', 2, 742, 642, 375, 312),
	array('Florence', 'Land', 'Yes', 2, 850, 664, 427, 331),
	array('Piombino', 'Coast', 'Yes', 2, 721, 711, 364, 353),
	array('Siena', 'Coast', 'Yes', 0, 743, 779, 376, 385),
	array('Arezzo', 'Land', 'Yes', 0, 818, 739, 412, 372),
	array('Urbino', 'Coast', 'No', 6, 975, 700, 483, 327),
	array('Ancona', 'Coast', 'Yes', 6, 1004, 780, 503, 393),
	array('Patrimony', 'Coast', 'No', 6, 752, 861, 376, 430),
	array('Rome', 'Coast', 'Yes', 6, 809, 915, 400, 468),
	array('Perugia', 'Land', 'Yes', 6, 811, 823, 407, 412),
	array('Spoleto', 'Land', 'No', 6, 877, 847, 442, 425),
	array('Capua', 'Coast', 'No', 3, 863, 1020, 427, 533),
	array('Aquila', 'Coast', 'No', 3, 1028, 1176, 488, 520),
	array('Naples', 'Coast', 'Yes', 3, 902, 1192, 445, 596),
	array('Bari', 'Coast', 'Yes', 3, 1117, 1351, 565, 675),
	array('Salerno', 'Coast', 'No', 3, 982, 1359, 487, 695),
	array('Otranto', 'Coast', 'No', 3, 988, 1611, 497, 805),
	array('Messina', 'Coast', 'Yes', 1, 670, 1683, 337, 849),
	array('Palermo', 'Coast', 'Yes', 1, 511, 1612, 254, 806),
	array('Tunis', 'Coast', 'Yes', 0, 44, 1518, 20, 730),
	array('Sardinia', 'Coast', 'Yes', 1, 259, 963, 148, 456),
	array('Corsica', 'Coast', 'Yes', 0, 479, 657, 236, 332),
	array('Slavonia', 'Land', 'No', 0, 1445, 364, 717, 155),
	array('Carniola', 'Coast', 'Yes', 0, 1286, 316, 647, 167),
	array('Croatia', 'Coast', 'Yes', 0, 1345, 603, 671, 290),
	array('Istria', 'Coast', 'No', 7, 1214, 621, 610, 306),
	array('Dalmatia', 'Coast', 'Yes', 0, 1292, 939, 649, 476),
	array('Herzogovina', 'Coast', 'No', 0, 1463, 1222, 731, 622),
	array('Bosnia', 'Land', 'No', 0, 1445, 951, 722, 482),
	array('Ragusa', 'Coast', 'Yes', 0, 1409, 1374, 707, 684),
	array('Albania', 'Coast', 'Yes', 0, 1457, 1485, 724, 745),
	array('Durazzo', 'Coast', 'Yes', 0, 1426, 1699, 714, 856),
	array('Ionian Sea', 'Sea', 'No', 0, 1166, 1782, 531, 897),
	array('Lower Adriatic Sea', 'Sea', 'No', 0, 1247, 1263, 576, 528),
	array('Upper Adriatic Sea', 'Sea', 'No', 0, 1100, 665, 550, 343),
	array('Central Mediterranean', 'Sea', 'No', 0, 292, 1659, 133, 847),
	array('Gulf of Naples', 'Sea', 'No', 0, 773, 1518, 389, 758),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 536, 1050, 262, 563),
	array('Western Mediterranean', 'Sea', 'No', 0, 116, 1239, 54, 617),
	array('Gulf of Lyon', 'Sea', 'No', 0, 176, 584, 62, 232),
	array('Ligurian Sea', 'Sea', 'No', 0, 544, 507, 278, 251)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Avignon','Marseilles','Yes','Yes'),
	array('Avignon','Provence','No','Yes'),
	array('Avignon','Swiss','No','Yes'),
	array('Avignon','Turin','No','Yes'),
	array('Avignon','Gulf of Lyon','Yes','No'),
	array('Marseilles','Provence','Yes','Yes'),
	array('Marseilles','Gulf of Lyon','Yes','No'),
	array('Provence','Saluzzo','No','Yes'),
	array('Provence','Turin','No','Yes'),
	array('Provence','Savoy','Yes','Yes'),
	array('Provence','Gulf of Lyon','Yes','No'),
	array('Provence','Ligurian Sea','Yes','No'),
	array('Swiss','Turin','No','Yes'),
	array('Swiss','Tyrolia','No','Yes'),
	array('Saluzzo','Turin','No','Yes'),
	array('Saluzzo','Savoy','No','Yes'),
	array('Turin','Savoy','No','Yes'),
	array('Turin','Montferrat','No','Yes'),
	array('Turin','Como','No','Yes'),
	array('Turin','Pavia','No','Yes'),
	array('Turin','Tyrolia','No','Yes'),
	array('Savoy','Montferrat','No','Yes'),
	array('Savoy','Genoa','Yes','Yes'),
	array('Savoy','Ligurian Sea','Yes','No'),
	array('Montferrat','Genoa','No','Yes'),
	array('Montferrat','Pavia','No','Yes'),
	array('Montferrat','Formova','No','Yes'),
	array('Genoa','Formova','No','Yes'),
	array('Genoa','Modena','Yes','Yes'),
	array('Genoa','Ligurian Sea','Yes','No'),
	array('Como','Pavia','No','Yes'),
	array('Como','Milan','No','Yes'),
	array('Como','Tyrolia','No','Yes'),
	array('Pavia','Milan','No','Yes'),
	array('Pavia','Parma','No','Yes'),
	array('Pavia','Formova','No','Yes'),
	array('Milan','Cremona','No','Yes'),
	array('Milan','Parma','No','Yes'),
	array('Milan','Tyrolia','No','Yes'),
	array('Milan','Carinthia','No','Yes'),
	array('Milan','Trent','No','Yes'),
	array('Milan','Bergamo','No','Yes'),
	array('Cremona','Parma','No','Yes'),
	array('Cremona','Bergamo','No','Yes'),
	array('Cremona','Mantua','No','Yes'),
	array('Parma','Formova','No','Yes'),
	array('Parma','Mantua','No','Yes'),
	array('Parma','Modena','No','Yes'),
	array('Formova','Modena','No','Yes'),
	array('Tyrolia','Carinthia','No','Yes'),
	array('Carinthia','Trent','No','Yes'),
	array('Carinthia','Verona','No','Yes'),
	array('Carinthia','Friuli','No','Yes'),
	array('Carinthia','Slavonia','No','Yes'),
	array('Carinthia','Carniola','No','Yes'),
	array('Trent','Bergamo','No','Yes'),
	array('Trent','Verona','No','Yes'),
	array('Bergamo','Verona','No','Yes'),
	array('Bergamo','Mantua','No','Yes'),
	array('Verona','Friuli','No','Yes'),
	array('Verona','Treviso','No','Yes'),
	array('Verona','Padua','No','Yes'),
	array('Verona','Mantua','No','Yes'),
	array('Verona','Ferrara','No','Yes'),
	array('Friuli','Treviso','No','Yes'),
	array('Friuli','Venice','Yes','Yes'),
	array('Friuli','Carniola','Yes','Yes'),
	array('Friuli','Upper Adriatic Sea','Yes','No'),
	array('Treviso','Venice','No','Yes'),
	array('Treviso','Padua','No','Yes'),
	array('Venice','Padua','Yes','Yes'),
	array('Venice','Upper Adriatic Sea','Yes','No'),
	array('Padua','Ferrara','Yes','Yes'),
	array('Padua','Upper Adriatic Sea','Yes','No'),
	array('Mantua','Ferrara','No','Yes'),
	array('Mantua','Modena','No','Yes'),
	array('Mantua','Bologna','No','Yes'),
	array('Ferrara','Bologna','Yes','Yes'),
	array('Ferrara','Upper Adriatic Sea','Yes','No'),
	array('Modena','Lucca','Yes','Yes'),
	array('Modena','Bologna','No','Yes'),
	array('Modena','Ligurian Sea','Yes','No'),
	array('Lucca','Bologna','No','Yes'),
	array('Lucca','Pistoia','No','Yes'),
	array('Lucca','Pisa','Yes','Yes'),
	array('Lucca','Ligurian Sea','Yes','No'),
	array('Bologna','Pistoia','No','Yes'),
	array('Bologna','Florence','No','Yes'),
	array('Bologna','Urbino','Yes','Yes'),
	array('Bologna','Upper Adriatic Sea','Yes','No'),
	array('Pistoia','Pisa','No','Yes'),
	array('Pistoia','Florence','No','Yes'),
	array('Pisa','Florence','No','Yes'),
	array('Pisa','Piombino','Yes','Yes'),
	array('Pisa','Siena','No','Yes'),
	array('Pisa','Tyrrhenian Sea','Yes','No'),
	array('Pisa','Ligurian Sea','Yes','No'),
	array('Florence','Siena','No','Yes'),
	array('Florence','Arezzo','No','Yes'),
	array('Florence','Urbino','No','Yes'),
	array('Piombino','Siena','Yes','Yes'),
	array('Piombino','Tyrrhenian Sea','Yes','No'),
	array('Siena','Arezzo','No','Yes'),
	array('Siena','Patrimony','Yes','Yes'),
	array('Siena','Perugia','No','Yes'),
	array('Siena','Tyrrhenian Sea','Yes','No'),
	array('Arezzo','Urbino','No','Yes'),
	array('Arezzo','Perugia','No','Yes'),
	array('Urbino','Ancona','Yes','Yes'),
	array('Urbino','Perugia','No','Yes'),
	array('Urbino','Spoleto','No','Yes'),
	array('Urbino','Upper Adriatic Sea','Yes','No'),
	array('Ancona','Spoleto','No','Yes'),
	array('Ancona','Aquila','Yes','Yes'),
	array('Ancona','Lower Adriatic Sea','Yes','No'),
	array('Ancona','Upper Adriatic Sea','Yes','No'),
	array('Patrimony','Rome','Yes','Yes'),
	array('Patrimony','Perugia','No','Yes'),
	array('Patrimony','Tyrrhenian Sea','Yes','No'),
	array('Rome','Perugia','No','Yes'),
	array('Rome','Spoleto','No','Yes'),
	array('Rome','Capua','Yes','Yes'),
	array('Rome','Tyrrhenian Sea','Yes','No'),
	array('Perugia','Spoleto','No','Yes'),
	array('Spoleto','Capua','No','Yes'),
	array('Spoleto','Aquila','No','Yes'),
	array('Capua','Aquila','No','Yes'),
	array('Capua','Naples','Yes','Yes'),
	array('Capua','Tyrrhenian Sea','Yes','No'),
	array('Aquila','Naples','No','Yes'),
	array('Aquila','Bari','Yes','Yes'),
	array('Aquila','Salerno','No','Yes'),
	array('Aquila','Lower Adriatic Sea','Yes','No'),
	array('Naples','Salerno','Yes','Yes'),
	array('Naples','Gulf of Naples','Yes','No'),
	array('Naples','Tyrrhenian Sea','Yes','No'),
	array('Bari','Salerno','No','Yes'),
	array('Bari','Otranto','Yes','Yes'),
	array('Bari','Lower Adriatic Sea','Yes','No'),
	array('Salerno','Otranto','Yes','Yes'),
	array('Salerno','Gulf of Naples','Yes','No'),
	array('Otranto','Messina','Yes','Yes'),
	array('Otranto','Ionian Sea','Yes','No'),
	array('Otranto','Lower Adriatic Sea','Yes','No'),
	array('Otranto','Gulf of Naples','Yes','No'),
	array('Messina','Palermo','Yes','Yes'),
	array('Messina','Ionian Sea','Yes','No'),
	array('Messina','Gulf of Naples','Yes','No'),
	array('Palermo','Ionian Sea','Yes','No'),
	array('Palermo','Central Mediterranean','Yes','No'),
	array('Palermo','Gulf of Naples','Yes','No'),
	array('Palermo','Tyrrhenian Sea','Yes','No'),
	array('Tunis','Central Mediterranean','Yes','No'),
	array('Tunis','Western Mediterranean','Yes','No'),
	array('Sardinia','Corsica','Yes','Yes'),
	array('Sardinia','Tyrrhenian Sea','Yes','No'),
	array('Sardinia','Western Mediterranean','Yes','No'),
	array('Sardinia','Gulf of Lyon','Yes','No'),
	array('Corsica','Tyrrhenian Sea','Yes','No'),
	array('Corsica','Gulf of Lyon','Yes','No'),
	array('Corsica','Ligurian Sea','Yes','No'),
	array('Slavonia','Carniola','No','Yes'),
	array('Slavonia','Croatia','No','Yes'),
	array('Carniola','Croatia','No','Yes'),
	array('Carniola','Istria','Yes','Yes'),
	array('Carniola','Upper Adriatic Sea','Yes','No'),
	array('Croatia','Istria','Yes','Yes'),
	array('Croatia','Dalmatia','Yes','Yes'),
	array('Croatia','Bosnia','No','Yes'),
	array('Istria','Upper Adriatic Sea','Yes','No'),
	array('Dalmatia','Herzogovina','Yes','Yes'),
	array('Dalmatia','Bosnia','No','Yes'),
	array('Dalmatia','Lower Adriatic Sea','Yes','No'),
	array('Dalmatia','Upper Adriatic Sea','Yes','No'),
	array('Herzogovina','Bosnia','No','Yes'),
	array('Herzogovina','Ragusa','Yes','Yes'),
	array('Herzogovina','Albania','No','Yes'),
	array('Herzogovina','Lower Adriatic Sea','Yes','No'),
	array('Ragusa','Albania','Yes','Yes'),
	array('Ragusa','Lower Adriatic Sea','Yes','No'),
	array('Albania','Durazzo','Yes','Yes'),
	array('Albania','Lower Adriatic Sea','Yes','No'),
	array('Durazzo','Ionian Sea','Yes','No'),
	array('Durazzo','Lower Adriatic Sea','Yes','No'),
	array('Ionian Sea','Lower Adriatic Sea','Yes','No'),
	array('Ionian Sea','Central Mediterranean','Yes','No'),
	array('Ionian Sea','Gulf of Naples','Yes','No'),
	array('Lower Adriatic Sea','Upper Adriatic Sea','Yes','No'),
	array('Central Mediterranean','Tyrrhenian Sea','Yes','No'),
	array('Central Mediterranean','Western Mediterranean','Yes','No'),
	array('Gulf of Naples','Tyrrhenian Sea','Yes','No'),
	array('Tyrrhenian Sea','Western Mediterranean','Yes','No'),
	array('Tyrrhenian Sea','Gulf of Lyon','Yes','No'),
	array('Tyrrhenian Sea','Ligurian Sea','Yes','No'),
	array('Western Mediterranean','Gulf of Lyon','Yes','No'),
	array('Gulf of Lyon','Ligurian Sea','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
