<?php
// This is file installs the map data for the Classic1913 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Clyde', 'Coast', 'No', 1, 317, 240, 158, 123),
	array('Edinburgh', 'Coast', 'Yes', 1, 348, 222, 177, 106),
	array('Liverpool', 'Coast', 'Yes', 1, 328, 276, 166, 142),
	array('Yorkshire', 'Coast', 'No', 1, 362, 302, 182, 148),
	array('Wales', 'Coast', 'No', 1, 310, 347, 148, 184),
	array('London', 'Coast', 'Yes', 1, 377, 352, 173, 185),
	array('Norway', 'Coast', 'Yes', 0, 511, 245, 262, 111),
	array('Sweden', 'Coast', 'Yes', 0, 609, 290, 303, 145),
	array('Denmark', 'Coast', 'Yes', 0, 527, 300, 261, 150),
	array('Finland', 'Coast', 'No', 7, 736, 166, 367, 109),
	array('St. Petersburg', 'Coast', 'Yes', 7, 934, 166, 458, 86),
	array('Livonia', 'Coast', 'No', 7, 756, 325, 379, 164),
	array('Moscow', 'Land', 'Yes', 7, 1000, 296, 442, 166),
	array('Warsaw', 'Land', 'Yes', 7, 724, 419, 361, 207),
	array('Ukraine', 'Land', 'No', 7, 835, 435, 422, 216),
	array('Sevastopol', 'Coast', 'Yes', 7, 996, 459, 468, 257),
	array('Black Sea', 'Sea', 'No', 0, 905, 583, 449, 302),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 676, 227, 344, 144),
	array('Baltic Sea', 'Sea', 'No', 0, 680, 330, 341, 177),
	array('Belgium', 'Coast', 'Yes', 0, 392, 389, 213, 202),
	array('Holland', 'Coast', 'Yes', 0, 456, 397, 237, 183),
	array('Kiel', 'Coast', 'Yes', 4, 512, 378, 252, 190),
	array('Berlin', 'Coast', 'Yes', 4, 563, 377, 290, 190),
	array('Prussia', 'Coast', 'No', 4, 683, 383, 318, 206),
	array('Cologne', 'Land', 'Yes', 4, 479, 418, 224, 220),
	array('Munich', 'Land', 'Yes', 4, 518, 462, 262, 225),
	array('Swabia', 'Land', 'No', 4, 463, 470, 243, 225),
	array('Silesia', 'Land', 'No', 4, 585, 430, 318, 225),
	array('Picardy', 'Coast', 'No', 2, 369, 410, 179, 214),
	array('Brest', 'Coast', 'Yes', 2, 269, 430, 132, 222),
	array('Gascony', 'Coast', 'No', 2, 289, 526, 146, 263),
	array('Paris', 'Land', 'Yes', 2, 345, 488, 176, 233),
	array('Burgundy', 'Land', 'No', 2, 417, 483, 207, 242),
	array('Marseilles', 'Coast', 'Yes', 2, 403, 562, 199, 275),
	array('Switzerland', 'Land', 'Yes', 0, 466, 500, 234, 250),
	array('Portugal', 'Coast', 'Yes', 0, 103, 652, 50, 328),
	array('Morocco', 'Coast', 'No', 2, 140, 748, 73, 374),
	array('Algeria', 'Coast', 'Yes', 0, 283, 777, 164, 380),
	array('North Africa', 'Land', 'No', 2, 176, 878, 167, 443),
	array('Tunisia', 'Coast', 'No', 2, 414, 788, 209, 387),
	array('Tripolitania', 'Coast', 'Yes', 0, 533, 889, 264, 440),
	array('Cyrenaica', 'Coast', 'No', 0, 758, 881, 338, 436),
	array('Egypt', 'Coast', 'Yes', 0, 923, 888, 438, 445),
	array('Constantinople', 'Coast', 'Yes', 6, 846, 651, 429, 346),
	array('Smyrna', 'Coast', 'Yes', 6, 865, 730, 478, 366),
	array('Syria', 'Coast', 'No', 6, 1057, 791, 528, 403),
	array('Ankara', 'Coast', 'Yes', 6, 988, 638, 481, 319),
	array('Armenia', 'Coast', 'No', 6, 1100, 630, 548, 318),
	array('Greece', 'Coast', 'Yes', 0, 722, 708, 366, 379),
	array('Bohemia', 'Land', 'No', 5, 605, 459, 297, 231),
	array('Tyrolia', 'Land', 'No', 5, 560, 506, 283, 251),
	array('Galicia', 'Land', 'No', 5, 766, 495, 382, 246),
	array('Vienna', 'Land', 'Yes', 5, 628, 489, 317, 247),
	array('Budapest', 'Land', 'Yes', 5, 707, 521, 353, 258),
	array('Trieste', 'Coast', 'Yes', 5, 601, 567, 306, 284),
	array('Albania', 'Coast', 'No', 0, 683, 669, 343, 345),
	array('Serbia', 'Land', 'Yes', 0, 713, 659, 358, 329),
	array('Bulgaria', 'Coast', 'Yes', 0, 786, 629, 390, 326),
	array('Rumania', 'Coast', 'Yes', 0, 817, 539, 419, 280),
	array('Spain', 'Coast', 'Yes', 0, 231, 615, 118, 312),
	array('Piedmont', 'Coast', 'No', 3, 436, 554, 220, 276),
	array('Venetia', 'Coast', 'No', 3, 532, 558, 266, 300),
	array('Milan', 'Land', 'Yes', 3, 496, 543, 247, 278),
	array('Rome', 'Coast', 'Yes', 3, 505, 627, 254, 313),
	array('Naples', 'Coast', 'Yes', 3, 568, 750, 283, 379),
	array('Eastern Mediterranean', 'Sea', 'No', 0, 887, 801, 407, 414),
	array('Ionian Sea', 'Sea', 'No', 0, 638, 779, 302, 421),
	array('Adriatic Sea', 'Sea', 'No', 0, 587, 633, 321, 335),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 481, 680, 238, 341),
	array('Heligoland Bight', 'Sea', 'No', 0, 482, 312, 243, 159),
	array('Western Mediterranean', 'Sea', 'No', 0, 367, 709, 183, 347),
	array('Gulf of Lyon', 'Sea', 'No', 0, 364, 614, 168, 324),
	array('Apulia', 'Coast', 'No', 3, 586, 669, 295, 334),
	array('Aegean Sea', 'Sea', 'No', 0, 782, 726, 393, 363),
	array('Mid-Atlantic Ocean', 'Sea', 'No', 0, 70, 416, 31, 271),
	array('North Atlantic Ocean', 'Sea', 'No', 0, 116, 101, 74, 107),
	array('Irish Sea', 'Sea', 'No', 0, 250, 350, 125, 171),
	array('English Channel', 'Sea', 'No', 0, 337, 402, 147, 205),
	array('North Sea', 'Sea', 'No', 0, 437, 228, 219, 119),
	array('Norwegian Sea', 'Sea', 'No', 0, 448, 62, 237, 31),
	array('Skagerrak', 'Sea', 'No', 0, 566, 298, 283, 147),
	array('Barents Sea', 'Sea', 'No', 0, 740, 30, 391, 13),
	array('Spain (North Coast)', 'Coast', 'No', 0, 174, 560, 82, 276),
	array('Spain (South Coast)', 'Coast', 'No', 0, 239, 673, 112, 334),
	array('Bulgaria (North Coast)', 'Coast', 'No', 0, 839, 610, 420, 307),
	array('Bulgaria (South Coast)', 'Coast', 'No', 0, 800, 664, 398, 330),
	array('St. Petersburg (North Coast)', 'Coast', 'No', 7, 829, 181, 409, 90),
	array('St. Petersburg (South Coast)', 'Coast', 'No', 7, 790, 275, 387, 132)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Clyde','Edinburgh','Yes','Yes'),
	array('Clyde','Liverpool','Yes','Yes'),
	array('Clyde','North Atlantic Ocean','Yes','No'),
	array('Clyde','Norwegian Sea','Yes','No'),
	array('Edinburgh','Liverpool','No','Yes'),
	array('Edinburgh','Yorkshire','Yes','Yes'),
	array('Edinburgh','North Sea','Yes','No'),
	array('Edinburgh','Norwegian Sea','Yes','No'),
	array('Liverpool','Yorkshire','No','Yes'),
	array('Liverpool','Wales','Yes','Yes'),
	array('Liverpool','North Atlantic Ocean','Yes','No'),
	array('Liverpool','Irish Sea','Yes','No'),
	array('Yorkshire','Wales','No','Yes'),
	array('Yorkshire','London','Yes','Yes'),
	array('Yorkshire','North Sea','Yes','No'),
	array('Wales','London','Yes','Yes'),
	array('Wales','Irish Sea','Yes','No'),
	array('Wales','English Channel','Yes','No'),
	array('London','English Channel','Yes','No'),
	array('London','North Sea','Yes','No'),
	array('Norway','Sweden','Yes','Yes'),
	array('Norway','Finland','No','Yes'),
	array('Norway','St. Petersburg','No','Yes'),
	array('Norway','North Sea','Yes','No'),
	array('Norway','Norwegian Sea','Yes','No'),
	array('Norway','Skagerrak','Yes','No'),
	array('Norway','Barents Sea','Yes','No'),
	array('Norway','St. Petersburg (North Coast)','Yes','No'),
	array('Sweden','Denmark','Yes','Yes'),
	array('Sweden','Finland','Yes','Yes'),
	array('Sweden','Gulf of Bothnia','Yes','No'),
	array('Sweden','Baltic Sea','Yes','No'),
	array('Sweden','Skagerrak','Yes','No'),
	array('Denmark','Baltic Sea','Yes','No'),
	array('Denmark','Kiel','Yes','Yes'),
	array('Denmark','Heligoland Bight','Yes','No'),
	array('Denmark','North Sea','Yes','No'),
	array('Denmark','Skagerrak','Yes','No'),
	array('Finland','St. Petersburg','No','Yes'),
	array('Finland','Gulf of Bothnia','Yes','No'),
	array('Finland','St. Petersburg (South Coast)','Yes','No'),
	array('St. Petersburg','Livonia','No','Yes'),
	array('St. Petersburg','Moscow','No','Yes'),
	array('Livonia','Moscow','No','Yes'),
	array('Livonia','Warsaw','No','Yes'),
	array('Livonia','Gulf of Bothnia','Yes','No'),
	array('Livonia','Baltic Sea','Yes','No'),
	array('Livonia','Prussia','Yes','Yes'),
	array('Livonia','St. Petersburg (South Coast)','Yes','No'),
	array('Moscow','Warsaw','No','Yes'),
	array('Moscow','Ukraine','No','Yes'),
	array('Moscow','Sevastopol','No','Yes'),
	array('Warsaw','Ukraine','No','Yes'),
	array('Warsaw','Prussia','No','Yes'),
	array('Warsaw','Silesia','No','Yes'),
	array('Warsaw','Galicia','No','Yes'),
	array('Ukraine','Sevastopol','No','Yes'),
	array('Ukraine','Galicia','No','Yes'),
	array('Ukraine','Rumania','No','Yes'),
	array('Sevastopol','Black Sea','Yes','No'),
	array('Sevastopol','Armenia','Yes','Yes'),
	array('Sevastopol','Rumania','Yes','Yes'),
	array('Black Sea','Constantinople','Yes','No'),
	array('Black Sea','Ankara','Yes','No'),
	array('Black Sea','Armenia','Yes','No'),
	array('Black Sea','Rumania','Yes','No'),
	array('Black Sea','Bulgaria (North Coast)','Yes','No'),
	array('Gulf of Bothnia','Baltic Sea','Yes','No'),
	array('Gulf of Bothnia','St. Petersburg (South Coast)','Yes','No'),
	array('Baltic Sea','Kiel','Yes','No'),
	array('Baltic Sea','Berlin','Yes','No'),
	array('Baltic Sea','Prussia','Yes','No'),
	array('Belgium','Holland','Yes','Yes'),
	array('Belgium','Cologne','No','Yes'),
	array('Belgium','Picardy','Yes','Yes'),
	array('Belgium','Burgundy','No','Yes'),
	array('Belgium','English Channel','Yes','No'),
	array('Belgium','North Sea','Yes','No'),
	array('Holland','Kiel','Yes','Yes'),
	array('Holland','Cologne','No','Yes'),
	array('Holland','Heligoland Bight','Yes','No'),
	array('Holland','North Sea','Yes','No'),
	array('Kiel','Berlin','Yes','Yes'),
	array('Kiel','Cologne','No','Yes'),
	array('Kiel','Munich','No','Yes'),
	array('Kiel','Heligoland Bight','Yes','No'),
	array('Berlin','Prussia','Yes','Yes'),
	array('Berlin','Munich','No','Yes'),
	array('Berlin','Silesia','No','Yes'),
	array('Prussia','Silesia','No','Yes'),
	array('Cologne','Munich','No','Yes'),
	array('Cologne','Swabia','No','Yes'),
	array('Cologne','Burgundy','No','Yes'),
	array('Munich','Swabia','No','Yes'),
	array('Munich','Silesia','No','Yes'),
	array('Munich','Switzerland','No','Yes'),
	array('Munich','Bohemia','No','Yes'),
	array('Munich','Tyrolia','No','Yes'),
	array('Swabia','Burgundy','No','Yes'),
	array('Swabia','Switzerland','No','Yes'),
	array('Silesia','Bohemia','No','Yes'),
	array('Silesia','Galicia','No','Yes'),
	array('Picardy','Brest','Yes','Yes'),
	array('Picardy','Paris','No','Yes'),
	array('Picardy','Burgundy','No','Yes'),
	array('Picardy','English Channel','Yes','No'),
	array('Brest','Gascony','Yes','Yes'),
	array('Brest','Paris','No','Yes'),
	array('Brest','Mid-Atlantic Ocean','Yes','No'),
	array('Brest','English Channel','Yes','No'),
	array('Gascony','Paris','No','Yes'),
	array('Gascony','Burgundy','No','Yes'),
	array('Gascony','Marseilles','No','Yes'),
	array('Gascony','Spain','No','Yes'),
	array('Gascony','Mid-Atlantic Ocean','Yes','No'),
	array('Gascony','Spain (North Coast)','Yes','No'),
	array('Paris','Burgundy','No','Yes'),
	array('Burgundy','Marseilles','No','Yes'),
	array('Burgundy','Switzerland','No','Yes'),
	array('Marseilles','Switzerland','No','Yes'),
	array('Marseilles','Spain','No','Yes'),
	array('Marseilles','Piedmont','Yes','Yes'),
	array('Marseilles','Gulf of Lyon','Yes','No'),
	array('Marseilles','Spain (South Coast)','Yes','No'),
	array('Switzerland','Tyrolia','No','Yes'),
	array('Switzerland','Piedmont','No','Yes'),
	array('Switzerland','Milan','No','Yes'),
	array('Portugal','Spain','No','Yes'),
	array('Portugal','Mid-Atlantic Ocean','Yes','No'),
	array('Portugal','Spain (North Coast)','Yes','No'),
	array('Portugal','Spain (South Coast)','Yes','No'),
	array('Morocco','Algeria','Yes','Yes'),
	array('Morocco','North Africa','No','Yes'),
	array('Morocco','Spain','No','Yes'),
	array('Morocco','Western Mediterranean','Yes','No'),
	array('Morocco','Mid-Atlantic Ocean','Yes','No'),
	array('Morocco','Spain (South Coast)','Yes','No'),
	array('Algeria','North Africa','No','Yes'),
	array('Algeria','Tunisia','Yes','Yes'),
	array('Algeria','Tyrrhenian Sea','Yes','No'),
	array('Algeria','Western Mediterranean','Yes','No'),
	array('North Africa','Tunisia','No','Yes'),
	array('North Africa','Tripolitania','No','Yes'),
	array('Tunisia','Tripolitania','Yes','Yes'),
	array('Tunisia','Ionian Sea','Yes','No'),
	array('Tunisia','Tyrrhenian Sea','Yes','No'),
	array('Tripolitania','Cyrenaica','Yes','Yes'),
	array('Tripolitania','Ionian Sea','Yes','No'),
	array('Cyrenaica','Egypt','Yes','Yes'),
	array('Cyrenaica','Eastern Mediterranean','Yes','No'),
	array('Cyrenaica','Ionian Sea','Yes','No'),
	array('Egypt','Syria','Yes','Yes'),
	array('Egypt','Eastern Mediterranean','Yes','No'),
	array('Egypt','North Atlantic Ocean','Yes','No'),
	array('Constantinople','Smyrna','Yes','Yes'),
	array('Constantinople','Ankara','Yes','Yes'),
	array('Constantinople','Bulgaria','No','Yes'),
	array('Constantinople','Aegean Sea','Yes','No'),
	array('Constantinople','Bulgaria (North Coast)','Yes','No'),
	array('Constantinople','Bulgaria (South Coast)','Yes','No'),
	array('Smyrna','Syria','Yes','Yes'),
	array('Smyrna','Ankara','No','Yes'),
	array('Smyrna','Armenia','No','Yes'),
	array('Smyrna','Eastern Mediterranean','Yes','No'),
	array('Smyrna','Aegean Sea','Yes','No'),
	array('Syria','Armenia','No','Yes'),
	array('Syria','Eastern Mediterranean','Yes','No'),
	array('Ankara','Armenia','Yes','Yes'),
	array('Greece','Albania','Yes','Yes'),
	array('Greece','Serbia','No','Yes'),
	array('Greece','Bulgaria','No','Yes'),
	array('Greece','Ionian Sea','Yes','No'),
	array('Greece','Aegean Sea','Yes','No'),
	array('Greece','Bulgaria (South Coast)','Yes','No'),
	array('Bohemia','Tyrolia','No','Yes'),
	array('Bohemia','Galicia','No','Yes'),
	array('Bohemia','Vienna','No','Yes'),
	array('Tyrolia','Vienna','No','Yes'),
	array('Tyrolia','Trieste','No','Yes'),
	array('Tyrolia','Venetia','No','Yes'),
	array('Tyrolia','Milan','No','Yes'),
	array('Galicia','Vienna','No','Yes'),
	array('Galicia','Budapest','No','Yes'),
	array('Galicia','Rumania','No','Yes'),
	array('Vienna','Budapest','No','Yes'),
	array('Vienna','Trieste','No','Yes'),
	array('Budapest','Trieste','No','Yes'),
	array('Budapest','Serbia','No','Yes'),
	array('Budapest','Rumania','No','Yes'),
	array('Trieste','Albania','Yes','Yes'),
	array('Trieste','Serbia','No','Yes'),
	array('Trieste','Venetia','Yes','Yes'),
	array('Trieste','Adriatic Sea','Yes','No'),
	array('Albania','Serbia','No','Yes'),
	array('Albania','Ionian Sea','Yes','No'),
	array('Albania','Adriatic Sea','Yes','No'),
	array('Serbia','Bulgaria','No','Yes'),
	array('Serbia','Rumania','No','Yes'),
	array('Bulgaria','Rumania','No','Yes'),
	array('Rumania','Bulgaria (North Coast)','Yes','No'),
	array('Piedmont','Milan','No','Yes'),
	array('Piedmont','Rome','Yes','Yes'),
	array('Piedmont','Gulf of Lyon','Yes','No'),
	array('Venetia','Milan','No','Yes'),
	array('Venetia','Rome','No','Yes'),
	array('Venetia','Adriatic Sea','Yes','No'),
	array('Venetia','Apulia','Yes','Yes'),
	array('Milan','Rome','No','Yes'),
	array('Rome','Naples','Yes','Yes'),
	array('Rome','Tyrrhenian Sea','Yes','No'),
	array('Rome','Gulf of Lyon','Yes','No'),
	array('Rome','Apulia','No','Yes'),
	array('Naples','Ionian Sea','Yes','No'),
	array('Naples','Tyrrhenian Sea','Yes','No'),
	array('Naples','Apulia','Yes','Yes'),
	array('Eastern Mediterranean','Ionian Sea','Yes','No'),
	array('Eastern Mediterranean','Aegean Sea','Yes','No'),
	array('Ionian Sea','Adriatic Sea','Yes','No'),
	array('Ionian Sea','Tyrrhenian Sea','Yes','No'),
	array('Ionian Sea','Apulia','Yes','No'),
	array('Ionian Sea','Aegean Sea','Yes','No'),
	array('Adriatic Sea','Apulia','Yes','No'),
	array('Tyrrhenian Sea','Western Mediterranean','Yes','No'),
	array('Tyrrhenian Sea','Gulf of Lyon','Yes','No'),
	array('Heligoland Bight','North Sea','Yes','No'),
	array('Western Mediterranean','Gulf of Lyon','Yes','No'),
	array('Western Mediterranean','Mid-Atlantic Ocean','Yes','No'),
	array('Western Mediterranean','Spain (South Coast)','Yes','No'),
	array('Gulf of Lyon','Spain (South Coast)','Yes','No'),
	array('Aegean Sea','Bulgaria (South Coast)','Yes','No'),
	array('Mid-Atlantic Ocean','North Atlantic Ocean','Yes','No'),
	array('Mid-Atlantic Ocean','Irish Sea','Yes','No'),
	array('Mid-Atlantic Ocean','English Channel','Yes','No'),
	array('Mid-Atlantic Ocean','Spain (North Coast)','Yes','No'),
	array('Mid-Atlantic Ocean','Spain (South Coast)','Yes','No'),
	array('North Atlantic Ocean','Irish Sea','Yes','No'),
	array('North Atlantic Ocean','Norwegian Sea','Yes','No'),
	array('Irish Sea','English Channel','Yes','No'),
	array('English Channel','North Sea','Yes','No'),
	array('North Sea','Norwegian Sea','Yes','No'),
	array('North Sea','Skagerrak','Yes','No'),
	array('Norwegian Sea','Barents Sea','Yes','No'),
	array('Barents Sea','St. Petersburg (North Coast)','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
