<?php
// This is file installs the map data for the WWII variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Iceland', 'Coast', 'Yes', 0, 40, 242, 26, 117),
	array('Inverness', 'Coast', 'Yes', 3, 302, 545, 152, 246),
	array('Oslo', 'Coast', 'Yes', 0, 632, 460, 301, 222),
	array('Narvik', 'Coast', 'No', 0, 730, 217, 347, 115),
	array('Edinburgh', 'Coast', 'No', 3, 346, 561, 160, 285),
	array('Norrland', 'Coast', 'No', 0, 841, 317, 388, 132),
	array('Denmark', 'Coast', 'No', 0, 628, 564, 298, 286),
	array('Stockholm', 'Coast', 'Yes', 0, 814, 458, 392, 218),
	array('Liverpool', 'Coast', 'Yes', 3, 358, 631, 173, 314),
	array('Newcastle', 'Coast', 'Yes', 3, 374, 610, 190, 300),
	array('Northern Ireland', 'Coast', 'Yes', 0, 271, 623, 132, 303),
	array('Ireland', 'Coast', 'No', 0, 231, 687, 123, 328),
	array('Cardiff', 'Coast', 'No', 3, 342, 701, 161, 337),
	array('Icelandic Sea', 'Sea', 'No', 0, 253, 183, 132, 97),
	array('Norwegian Sea', 'Sea', 'No', 0, 589, 244, 288, 104),
	array('Copenhagen', 'Coast', 'Yes', 0, 678, 587, 327, 286),
	array('Scapa Flow', 'Sea', 'No', 3, 317, 409, 154, 190),
	array('London', 'Coast', 'Yes', 3, 415, 728, 204, 351),
	array('Dorset', 'Coast', 'No', 3, 340, 735, 157, 355),
	array('Birmingham', 'Coast', 'No', 3, 384, 671, 186, 320),
	array('North Atlantic', 'Sea', 'No', 0, 112, 473, 47, 236),
	array('Gothenburg', 'Coast', 'No', 0, 742, 564, 362, 270),
	array('Irish Sea', 'Sea', 'No', 0, 289, 700, 143, 320),
	array('Finnmark', 'Coast', 'No', 0, 963, 86, 467, 46),
	array('Lapland', 'Coast', 'No', 0, 1011, 190, 480, 99),
	array('Murmansk', 'Coast', 'Yes', 5, 1190, 121, 602, 77),
	array('Barents Sea', 'Sea', 'No', 0, 1231, 72, 582, 34),
	array('North Sea', 'Sea', 'No', 0, 485, 643, 233, 309),
	array('Helsinki', 'Coast', 'Yes', 0, 951, 438, 454, 211),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 865, 441, 418, 209),
	array('Estonia', 'Coast', 'Yes', 0, 955, 482, 462, 235),
	array('Baltic Sea', 'Sea', 'No', 0, 858, 541, 411, 266),
	array('Kiel', 'Coast', 'Yes', 2, 646, 631, 310, 305),
	array('Bremen', 'Coast', 'No', 2, 605, 661, 287, 317),
	array('Brest', 'Coast', 'Yes', 1, 333, 802, 164, 391),
	array('English Channel', 'Sea', 'No', 0, 352, 785, 160, 375),
	array('Normandy', 'Coast', 'No', 1, 436, 774, 202, 376),
	array('Calais', 'Coast', 'No', 1, 466, 738, 225, 355),
	array('Paris', 'Land', 'Yes', 1, 473, 798, 231, 385),
	array('Orleans', 'Land', 'Yes', 1, 461, 835, 224, 414),
	array('Bordeaux', 'Coast', 'Yes', 1, 408, 902, 194, 432),
	array('Toulouse', 'Coast', 'Yes', 1, 478, 955, 231, 458),
	array('Marseille', 'Coast', 'Yes', 1, 558, 951, 268, 455),
	array('Rhone-Alpes', 'Land', 'No', 1, 554, 881, 265, 423),
	array('Champagne', 'Land', 'No', 1, 530, 835, 264, 398),
	array('Skagerrak', 'Sea', 'No', 0, 565, 570, 267, 274),
	array('Barcelona', 'Coast', 'Yes', 0, 472, 994, 213, 484),
	array('Basque', 'Coast', 'No', 0, 365, 960, 176, 460),
	array('Madrid', 'Coast', 'Yes', 0, 341, 1044, 163, 503),
	array('Galicia', 'Coast', 'No', 0, 322, 966, 122, 457),
	array('Atlantic Passage', 'Sea', 'No', 0, 165, 809, 51, 402),
	array('Bay of Biscay', 'Sea', 'No', 0, 266, 889, 127, 426),
	array('Portugal', 'Coast', 'Yes', 0, 228, 1032, 109, 497),
	array('Gibraltar', 'Coast', 'Yes', 3, 310, 1129, 139, 544),
	array('Andalucia', 'Coast', 'No', 0, 318, 1101, 160, 527),
	array('Valencia', 'Coast', 'Yes', 0, 398, 1086, 185, 523),
	array('Coast of Portugal', 'Sea', 'No', 0, 123, 1076, 41, 537),
	array('Gibraltar Passage', 'Sea', 'No', 0, 245, 1166, 86, 567),
	array('Belgium', 'Coast', 'Yes', 0, 493, 731, 237, 354),
	array('The Netherlands', 'Coast', 'Yes', 0, 555, 692, 258, 336),
	array('Essen', 'Land', 'No', 2, 563, 739, 274, 346),
	array('Luxembourg', 'Land', 'No', 0, 540, 782, 258, 378),
	array('Rheinland', 'Land', 'No', 2, 593, 816, 281, 383),
	array('Frankfurt', 'Land', 'Yes', 2, 615, 767, 291, 361),
	array('Munich', 'Land', 'Yes', 2, 668, 790, 330, 387),
	array('Switzerland', 'Land', 'Yes', 0, 614, 857, 293, 407),
	array('El Aaiun', 'Coast', 'No', 0, 110, 1406, 78, 646),
	array('Morocco', 'Coast', 'Yes', 0, 290, 1181, 142, 572),
	array('Sahara (Algeria)', 'Land', 'No', 0, 480, 1317, 226, 621),
	array('Algiers', 'Coast', 'Yes', 1, 518, 1130, 267, 550),
	array('Sahara (Libya)', 'Land', 'No', 0, 815, 1346, 392, 649),
	array('Tunis', 'Coast', 'Yes', 0, 631, 1131, 298, 543),
	array('Costa del Sol', 'Sea', 'No', 0, 397, 1130, 200, 537),
	array('Sardinia', 'Coast', 'Yes', 4, 621, 1043, 296, 501),
	array('Corsica', 'Coast', 'No', 1, 622, 980, 299, 467),
	array('Tripoli', 'Coast', 'Yes', 4, 734, 1239, 357, 605),
	array('Turin', 'Coast', 'No', 4, 592, 923, 289, 442),
	array('Milan', 'Coast', 'Yes', 4, 649, 897, 321, 433),
	array('Trieste', 'Coast', 'Yes', 4, 694, 880, 336, 426),
	array('Trento', 'Land', 'No', 4, 670, 862, 323, 411),
	array('Tuscany', 'Coast', 'No', 4, 675, 943, 322, 454),
	array('Rome', 'Coast', 'Yes', 4, 709, 964, 340, 462),
	array('Naples', 'Coast', 'Yes', 4, 761, 1007, 364, 486),
	array('Messina', 'Coast', 'No', 4, 785, 1037, 377, 498),
	array('Sicily', 'Coast', 'Yes', 4, 745, 1106, 357, 526),
	array('Balearic Sea', 'Sea', 'No', 0, 476, 1081, 230, 522),
	array('Cote DAzur', 'Sea', 'No', 0, 521, 978, 251, 471),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 662, 1007, 343, 503),
	array('Benghazi', 'Coast', 'Yes', 0, 902, 1240, 433, 595),
	array('Hannover', 'Land', 'Yes', 2, 623, 709, 310, 335),
	array('Weimar', 'Land', 'No', 2, 665, 753, 320, 363),
	array('Berlin', 'Land', 'Yes', 2, 678, 699, 357, 336),
	array('Rostock', 'Coast', 'No', 2, 704, 637, 344, 310),
	array('Stettin', 'Coast', 'No', 2, 793, 640, 377, 305),
	array('Konigsberg', 'Coast', 'Yes', 2, 879, 627, 428, 301),
	array('Breslau', 'Land', 'Yes', 2, 768, 726, 386, 356),
	array('Innsbruck', 'Land', 'No', 0, 653, 842, 320, 404),
	array('Vienna', 'Land', 'Yes', 0, 767, 814, 368, 394),
	array('Salzburg', 'Land', 'Yes', 0, 734, 850, 358, 410),
	array('Croatia', 'Coast', 'Yes', 0, 759, 906, 355, 430),
	array('North Adriatic Sea', 'Sea', 'No', 0, 720, 921, 357, 459),
	array('South Adriatic Sea', 'Sea', 'No', 0, 795, 982, 380, 470),
	array('Bosnia and Herzegovina', 'Coast', 'No', 0, 843, 952, 405, 456),
	array('Tirana', 'Coast', 'Yes', 0, 865, 1023, 415, 498),
	array('Macedonia', 'Land', 'No', 0, 904, 996, 440, 475),
	array('Serbia', 'Land', 'Yes', 0, 900, 959, 432, 450),
	array('Ionian Sea', 'Sea', 'No', 0, 834, 1130, 385, 548),
	array('Sea of Sicily', 'Sea', 'No', 0, 679, 1116, 331, 544),
	array('Prague', 'Land', 'Yes', 0, 720, 773, 347, 372),
	array('Danzig', 'Coast', 'No', 0, 822, 636, 394, 306),
	array('Warsaw', 'Land', 'Yes', 0, 803, 703, 422, 342),
	array('Libyan Sea', 'Sea', 'No', 0, 817, 1220, 430, 578),
	array('Bratislava', 'Land', 'Yes', 0, 844, 800, 401, 387),
	array('Hungary', 'Land', 'Yes', 0, 801, 851, 418, 410),
	array('Cracow', 'Land', 'Yes', 0, 865, 756, 418, 366),
	array('Thessalonica', 'Coast', 'No', 0, 915, 1030, 451, 490),
	array('Athens', 'Coast', 'Yes', 0, 909, 1058, 447, 518),
	array('Corinth', 'Coast', 'No', 0, 922, 1117, 441, 536),
	array('Latvia', 'Coast', 'Yes', 0, 933, 544, 442, 266),
	array('Lithuania', 'Coast', 'Yes', 0, 910, 585, 442, 285),
	array('Brest-Litovsk', 'Land', 'No', 0, 991, 655, 474, 315),
	array('Lwow', 'Land', 'No', 0, 953, 734, 461, 355),
	array('Transylvania', 'Land', 'No', 0, 956, 865, 451, 401),
	array('Craiova', 'Land', 'No', 0, 951, 916, 441, 430),
	array('Arkhangelskaya', 'Coast', 'No', 5, 1370, 230, 660, 113),
	array('Onega', 'Land', 'No', 5, 1251, 404, 562, 189),
	array('Black Sea', 'Sea', 'No', 0, 1206, 954, 589, 464),
	array('Leningrad', 'Coast', 'Yes', 5, 1062, 462, 513, 226),
	array('Smolensk', 'Land', 'No', 5, 1132, 606, 546, 288),
	array('Uwalli', 'Land', 'No', 5, 1372, 490, 655, 246),
	array('Moscow', 'Land', 'Yes', 5, 1201, 587, 580, 287),
	array('Nizhny Novgorod', 'Land', 'No', 5, 1313, 645, 626, 310),
	array('Minsk', 'Land', 'Yes', 5, 1067, 627, 513, 318),
	array('Gallipoli', 'Coast', 'No', 0, 986, 1009, 475, 485),
	array('Istanbul', 'Coast', 'Yes', 0, 1040, 1033, 515, 489),
	array('Bulgaria', 'Coast', 'Yes', 0, 1019, 971, 492, 466),
	array('Crete', 'Coast', 'No', 0, 956, 1163, 470, 561),
	array('Cyprus', 'Coast', 'No', 0, 1163, 1162, 562, 560),
	array('Sea of Crete', 'Sea', 'No', 0, 1041, 1190, 501, 593),
	array('Cilician Sea', 'Sea', 'No', 0, 1161, 1241, 561, 583),
	array('Kharkov', 'Land', 'No', 5, 1183, 731, 565, 357),
	array('Stalingrad', 'Coast', 'Yes', 5, 1377, 837, 642, 406),
	array('Rostov', 'Coast', 'No', 5, 1281, 831, 608, 396),
	array('Kiev', 'Coast', 'Yes', 5, 1092, 832, 528, 403),
	array('Crimea', 'Coast', 'No', 5, 1181, 897, 567, 429),
	array('Caucasus', 'Coast', 'No', 5, 1282, 912, 614, 435),
	array('Bucharest', 'Coast', 'Yes', 0, 1051, 915, 508, 440),
	array('Georgia', 'Coast', 'Yes', 5, 1360, 981, 653, 471),
	array('Tobruk', 'Coast', 'Yes', 0, 949, 1255, 463, 606),
	array('Sidi Barrani', 'Coast', 'No', 0, 1032, 1270, 482, 608),
	array('Cairo', 'Coast', 'Yes', 0, 1139, 1346, 542, 661),
	array('Alexandria', 'Coast', 'Yes', 3, 1120, 1264, 542, 618),
	array('Suez', 'Coast', 'No', 3, 1169, 1285, 562, 615),
	array('Aegean Sea', 'Sea', 'No', 0, 986, 1091, 475, 535),
	array('Izmir', 'Coast', 'No', 0, 1044, 1112, 517, 536),
	array('Mersin', 'Coast', 'Yes', 0, 1169, 1131, 559, 541),
	array('Ankara', 'Coast', 'Yes', 0, 1174, 1001, 575, 493),
	array('Van', 'Coast', 'No', 0, 1335, 1038, 641, 496),
	array('Iraq', 'Land', 'Yes', 0, 1354, 1197, 663, 579),
	array('Damascus', 'Coast', 'No', 0, 1233, 1211, 588, 577),
	array('Aleppo', 'Coast', 'No', 0, 1233, 1146, 590, 552),
	array('Palestine', 'Coast', 'Yes', 3, 1198, 1269, 576, 602),
	array('Arabia', 'Coast', 'No', 0, 1227, 1332, 619, 643),
	array('Jordan', 'Coast', 'No', 0, 1223, 1294, 590, 620),
	array('Red Sea', 'Sea', 'No', 0, 1194, 1377, 581, 675),
	array('Tuscany (East Coast)', 'Coast', 'No', 4, 692, 920, 332, 444),
	array('Tuscany (West Coast)', 'Coast', 'No', 4, 652, 941, 316, 455),
	array('Rome (North Coast)', 'Coast', 'No', 4, 722, 955, 347, 458),
	array('Naples (North Coast)', 'Coast', 'No', 4, 768, 991, 371, 475),
	array('Messina (East Coast) (deleted)', 'Sea', 'No', 0, 821, 1027, 395, 496),
	array('Messina (West Coast) (deleted)', 'Sea', 'No', 0, 783, 1061, 373, 503),
	array('Andalucia (West Coast)', 'Coast', 'No', 0, 259, 1108, 127, 532),
	array('Andalucia (East Coast)', 'Coast', 'No', 0, 362, 1115, 173, 535),
	array('Lapland (South Coast)', 'Coast', 'No', 0, 970, 242, 466, 114),
	array('Lapland (North Coast)', 'Coast', 'No', 0, 1136, 92, 547, 43),
	array('Thessalonica (East Coast)', 'Coast', 'No', 0, 954, 1015, 458, 487),
	array('Thessalonica (West Coast)', 'Coast', 'No', 0, 877, 1056, 421, 505),
	array('Athens (West Coast)', 'Coast', 'No', 0, 894, 1076, 431, 518),
	array('Rome (South Coast)', 'Coast', 'No', 4, 695, 992, 342, 479),
	array('Naples (South Coast)', 'Coast', 'No', 4, 760, 1035, 357, 490),
	array('Athens (East Coast)', 'Coast', 'No', 0, 951, 1078, 458, 520),
	array('Canary Islands', 'Coast', 'Yes', 0, 47, 1342, 23, 645),
	array('Palestine (North Coast)', 'Coast', 'No', 0, 1200, 1238, 576, 594),
	array('Palestine (South Coast)', 'Coast', 'No', 0, 1199, 1306, 575, 623),
	array('Edinburgh (East Coast)', 'Coast', 'No', 3, 359, 556, 166, 271),
	array('Edinburgh (West Coast)', 'Coast', 'No', 3, 315, 586, 151, 293)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Iceland','Icelandic Sea','Yes','No'),
	array('Iceland','North Atlantic','Yes','No'),
	array('Inverness','Edinburgh','No','Yes'),
	array('Inverness','Scapa Flow','Yes','No'),
	array('Inverness','Edinburgh (East Coast)','Yes','No'),
	array('Inverness','Edinburgh (West Coast)','Yes','No'),
	array('Oslo','Narvik','Yes','Yes'),
	array('Oslo','Norrland','No','Yes'),
	array('Oslo','Norwegian Sea','Yes','No'),
	array('Oslo','Gothenburg','Yes','Yes'),
	array('Oslo','Skagerrak','Yes','No'),
	array('Narvik','Norrland','No','Yes'),
	array('Narvik','Norwegian Sea','Yes','No'),
	array('Narvik','Finnmark','Yes','Yes'),
	array('Edinburgh','Liverpool','No','Yes'),
	array('Edinburgh','Newcastle','No','Yes'),
	array('Norrland','Stockholm','Yes','Yes'),
	array('Norrland','Gothenburg','No','Yes'),
	array('Norrland','Finnmark','No','Yes'),
	array('Norrland','Lapland','No','Yes'),
	array('Norrland','Gulf of Bothnia','Yes','No'),
	array('Norrland','Lapland (South Coast)','Yes','No'),
	array('Denmark','Copenhagen','Yes','Yes'),
	array('Denmark','Kiel','Yes','Yes'),
	array('Denmark','Skagerrak','Yes','No'),
	array('Stockholm','Gothenburg','Yes','Yes'),
	array('Stockholm','Gulf of Bothnia','Yes','No'),
	array('Stockholm','Baltic Sea','Yes','No'),
	array('Liverpool','Newcastle','No','Yes'),
	array('Liverpool','Cardiff','Yes','Yes'),
	array('Liverpool','Birmingham','No','Yes'),
	array('Liverpool','Irish Sea','Yes','No'),
	array('Liverpool','Edinburgh (West Coast)','Yes','No'),
	array('Newcastle','London','Yes','Yes'),
	array('Newcastle','Birmingham','No','Yes'),
	array('Newcastle','North Sea','Yes','No'),
	array('Newcastle','Edinburgh (East Coast)','Yes','No'),
	array('Northern Ireland','Ireland','Yes','Yes'),
	array('Northern Ireland','Irish Sea','Yes','No'),
	array('Ireland','North Atlantic','Yes','No'),
	array('Ireland','Irish Sea','Yes','No'),
	array('Ireland','Atlantic Passage','Yes','No'),
	array('Cardiff','Dorset','Yes','Yes'),
	array('Cardiff','Birmingham','No','Yes'),
	array('Cardiff','Irish Sea','Yes','No'),
	array('Icelandic Sea','Norwegian Sea','Yes','No'),
	array('Icelandic Sea','Scapa Flow','Yes','No'),
	array('Icelandic Sea','North Atlantic','Yes','No'),
	array('Norwegian Sea','Scapa Flow','Yes','No'),
	array('Norwegian Sea','Finnmark','Yes','No'),
	array('Norwegian Sea','Barents Sea','Yes','No'),
	array('Norwegian Sea','Skagerrak','Yes','No'),
	array('Norwegian Sea','Lapland (North Coast)','Yes','No'),
	array('Copenhagen','Gothenburg','Yes','Yes'),
	array('Copenhagen','Baltic Sea','Yes','No'),
	array('Copenhagen','Kiel','Yes','No'),
	array('Copenhagen','Skagerrak','Yes','No'),
	array('Copenhagen','Rostock','Yes','No'),
	array('Copenhagen','Stettin','Yes','No'),
	array('Scapa Flow','North Atlantic','Yes','No'),
	array('Scapa Flow','Irish Sea','Yes','No'),
	array('Scapa Flow','North Sea','Yes','No'),
	array('Scapa Flow','Skagerrak','Yes','No'),
	array('Scapa Flow','Edinburgh (East Coast)','Yes','No'),
	array('Scapa Flow','Edinburgh (West Coast)','Yes','No'),
	array('London','Dorset','Yes','Yes'),
	array('London','Birmingham','No','Yes'),
	array('London','North Sea','Yes','No'),
	array('London','English Channel','Yes','No'),
	array('Dorset','Birmingham','No','Yes'),
	array('Dorset','Irish Sea','Yes','No'),
	array('Dorset','English Channel','Yes','No'),
	array('North Atlantic','Irish Sea','Yes','No'),
	array('North Atlantic','Atlantic Passage','Yes','No'),
	array('Gothenburg','Baltic Sea','Yes','No'),
	array('Gothenburg','Skagerrak','Yes','No'),
	array('Irish Sea','English Channel','Yes','No'),
	array('Irish Sea','Atlantic Passage','Yes','No'),
	array('Irish Sea','Edinburgh (West Coast)','Yes','No'),
	array('Finnmark','Lapland','No','Yes'),
	array('Finnmark','Lapland (North Coast)','Yes','No'),
	array('Lapland','Murmansk','No','Yes'),
	array('Lapland','Helsinki','No','Yes'),
	array('Murmansk','Barents Sea','Yes','No'),
	array('Murmansk','Helsinki','No','Yes'),
	array('Murmansk','Arkhangelskaya','Yes','Yes'),
	array('Murmansk','Onega','No','Yes'),
	array('Murmansk','Lapland (North Coast)','Yes','No'),
	array('Barents Sea','Arkhangelskaya','Yes','No'),
	array('Barents Sea','Lapland (North Coast)','Yes','No'),
	array('North Sea','English Channel','Yes','No'),
	array('North Sea','Skagerrak','Yes','No'),
	array('North Sea','Belgium','Yes','No'),
	array('North Sea','The Netherlands','Yes','No'),
	array('North Sea','Edinburgh (East Coast)','Yes','No'),
	array('Helsinki','Gulf of Bothnia','Yes','No'),
	array('Helsinki','Onega','No','Yes'),
	array('Helsinki','Leningrad','Yes','Yes'),
	array('Helsinki','Lapland (South Coast)','Yes','No'),
	array('Gulf of Bothnia','Estonia','Yes','No'),
	array('Gulf of Bothnia','Baltic Sea','Yes','No'),
	array('Gulf of Bothnia','Leningrad','Yes','No'),
	array('Gulf of Bothnia','Lapland (South Coast)','Yes','No'),
	array('Estonia','Baltic Sea','Yes','No'),
	array('Estonia','Latvia','Yes','Yes'),
	array('Estonia','Leningrad','Yes','Yes'),
	array('Baltic Sea','Stettin','Yes','No'),
	array('Baltic Sea','Konigsberg','Yes','No'),
	array('Baltic Sea','Danzig','Yes','No'),
	array('Baltic Sea','Latvia','Yes','No'),
	array('Baltic Sea','Lithuania','Yes','No'),
	array('Kiel','Bremen','Yes','Yes'),
	array('Kiel','Skagerrak','Yes','No'),
	array('Kiel','Hannover','No','Yes'),
	array('Kiel','Rostock','Yes','Yes'),
	array('Bremen','Skagerrak','Yes','No'),
	array('Bremen','The Netherlands','Yes','Yes'),
	array('Bremen','Essen','No','Yes'),
	array('Bremen','Hannover','No','Yes'),
	array('Brest','English Channel','Yes','No'),
	array('Brest','Normandy','Yes','Yes'),
	array('Brest','Orleans','No','Yes'),
	array('Brest','Bordeaux','Yes','Yes'),
	array('Brest','Bay of Biscay','Yes','No'),
	array('English Channel','Normandy','Yes','No'),
	array('English Channel','Calais','Yes','No'),
	array('English Channel','Atlantic Passage','Yes','No'),
	array('English Channel','Bay of Biscay','Yes','No'),
	array('English Channel','Belgium','Yes','No'),
	array('Normandy','Calais','Yes','Yes'),
	array('Normandy','Paris','No','Yes'),
	array('Normandy','Orleans','No','Yes'),
	array('Calais','Paris','No','Yes'),
	array('Calais','Champagne','No','Yes'),
	array('Calais','Belgium','Yes','Yes'),
	array('Paris','Orleans','No','Yes'),
	array('Paris','Champagne','No','Yes'),
	array('Orleans','Bordeaux','No','Yes'),
	array('Orleans','Toulouse','No','Yes'),
	array('Orleans','Rhone-Alpes','No','Yes'),
	array('Orleans','Champagne','No','Yes'),
	array('Bordeaux','Toulouse','No','Yes'),
	array('Bordeaux','Basque','Yes','Yes'),
	array('Bordeaux','Bay of Biscay','Yes','No'),
	array('Toulouse','Marseille','Yes','Yes'),
	array('Toulouse','Rhone-Alpes','No','Yes'),
	array('Toulouse','Barcelona','Yes','Yes'),
	array('Toulouse','Cote DAzur','Yes','No'),
	array('Marseille','Rhone-Alpes','No','Yes'),
	array('Marseille','Turin','Yes','Yes'),
	array('Marseille','Cote DAzur','Yes','No'),
	array('Rhone-Alpes','Champagne','No','Yes'),
	array('Rhone-Alpes','Switzerland','No','Yes'),
	array('Rhone-Alpes','Turin','No','Yes'),
	array('Champagne','Belgium','No','Yes'),
	array('Champagne','Luxembourg','No','Yes'),
	array('Champagne','Rheinland','No','Yes'),
	array('Champagne','Switzerland','No','Yes'),
	array('Skagerrak','The Netherlands','Yes','No'),
	array('Barcelona','Basque','No','Yes'),
	array('Barcelona','Valencia','Yes','Yes'),
	array('Barcelona','Balearic Sea','Yes','No'),
	array('Barcelona','Cote DAzur','Yes','No'),
	array('Basque','Galicia','Yes','Yes'),
	array('Basque','Bay of Biscay','Yes','No'),
	array('Basque','Valencia','No','Yes'),
	array('Madrid','Galicia','No','Yes'),
	array('Madrid','Andalucia','No','Yes'),
	array('Madrid','Valencia','No','Yes'),
	array('Galicia','Bay of Biscay','Yes','No'),
	array('Galicia','Portugal','Yes','Yes'),
	array('Galicia','Andalucia','No','Yes'),
	array('Galicia','Valencia','No','Yes'),
	array('Galicia','Coast of Portugal','Yes','No'),
	array('Atlantic Passage','Bay of Biscay','Yes','No'),
	array('Atlantic Passage','Coast of Portugal','Yes','No'),
	array('Bay of Biscay','Coast of Portugal','Yes','No'),
	array('Portugal','Andalucia','No','Yes'),
	array('Portugal','Coast of Portugal','Yes','No'),
	array('Portugal','Gibraltar Passage','Yes','No'),
	array('Portugal','Andalucia (West Coast)','Yes','No'),
	array('Gibraltar','Andalucia','No','Yes'),
	array('Gibraltar','Gibraltar Passage','Yes','No'),
	array('Gibraltar','Morocco','Yes','Yes'),
	array('Gibraltar','Costa del Sol','Yes','No'),
	array('Gibraltar','Andalucia (West Coast)','Yes','No'),
	array('Gibraltar','Andalucia (East Coast)','Yes','No'),
	array('Andalucia','Valencia','No','Yes'),
	array('Valencia','Costa del Sol','Yes','No'),
	array('Valencia','Balearic Sea','Yes','No'),
	array('Valencia','Andalucia (East Coast)','Yes','No'),
	array('Coast of Portugal','Gibraltar Passage','Yes','No'),
	array('Coast of Portugal','Canary Islands','Yes','No'),
	array('Gibraltar Passage','Morocco','Yes','No'),
	array('Gibraltar Passage','Costa del Sol','Yes','No'),
	array('Gibraltar Passage','Andalucia (West Coast)','Yes','No'),
	array('Gibraltar Passage','Canary Islands','Yes','No'),
	array('Belgium','The Netherlands','Yes','Yes'),
	array('Belgium','Essen','No','Yes'),
	array('Belgium','Luxembourg','No','Yes'),
	array('Belgium','Rheinland','No','Yes'),
	array('The Netherlands','Essen','No','Yes'),
	array('Essen','Rheinland','No','Yes'),
	array('Essen','Frankfurt','No','Yes'),
	array('Essen','Hannover','No','Yes'),
	array('Luxembourg','Rheinland','No','Yes'),
	array('Rheinland','Frankfurt','No','Yes'),
	array('Rheinland','Munich','No','Yes'),
	array('Rheinland','Switzerland','No','Yes'),
	array('Frankfurt','Munich','No','Yes'),
	array('Frankfurt','Hannover','No','Yes'),
	array('Frankfurt','Weimar','No','Yes'),
	array('Munich','Weimar','No','Yes'),
	array('Munich','Innsbruck','No','Yes'),
	array('Munich','Vienna','No','Yes'),
	array('Munich','Salzburg','No','Yes'),
	array('Munich','Prague','No','Yes'),
	array('Switzerland','Turin','No','Yes'),
	array('Switzerland','Milan','No','Yes'),
	array('Switzerland','Trento','No','Yes'),
	array('Switzerland','Innsbruck','No','Yes'),
	array('El Aaiun','Morocco','Yes','Yes'),
	array('El Aaiun','Sahara (Algeria)','No','Yes'),
	array('El Aaiun','Canary Islands','Yes','No'),
	array('Morocco','Sahara (Algeria)','No','Yes'),
	array('Morocco','Algiers','Yes','Yes'),
	array('Morocco','Costa del Sol','Yes','No'),
	array('Morocco','Canary Islands','Yes','No'),
	array('Sahara (Algeria)','Algiers','No','Yes'),
	array('Sahara (Algeria)','Sahara (Libya)','No','Yes'),
	array('Sahara (Algeria)','Tunis','No','Yes'),
	array('Sahara (Algeria)','Tripoli','No','Yes'),
	array('Algiers','Tunis','Yes','Yes'),
	array('Algiers','Costa del Sol','Yes','No'),
	array('Algiers','Balearic Sea','Yes','No'),
	array('Algiers','Sea of Sicily','Yes','No'),
	array('Sahara (Libya)','Tripoli','No','Yes'),
	array('Sahara (Libya)','Benghazi','No','Yes'),
	array('Sahara (Libya)','Tobruk','No','Yes'),
	array('Sahara (Libya)','Sidi Barrani','No','Yes'),
	array('Sahara (Libya)','Cairo','No','Yes'),
	array('Tunis','Tripoli','Yes','Yes'),
	array('Tunis','Sea of Sicily','Yes','No'),
	array('Costa del Sol','Balearic Sea','Yes','No'),
	array('Costa del Sol','Andalucia (East Coast)','Yes','No'),
	array('Sardinia','Corsica','Yes','Yes'),
	array('Sardinia','Balearic Sea','Yes','No'),
	array('Sardinia','Cote DAzur','Yes','No'),
	array('Sardinia','Tyrrhenian Sea','Yes','No'),
	array('Sardinia','Sea of Sicily','Yes','No'),
	array('Corsica','Cote DAzur','Yes','No'),
	array('Corsica','Tyrrhenian Sea','Yes','No'),
	array('Tripoli','Benghazi','Yes','Yes'),
	array('Tripoli','Sea of Sicily','Yes','No'),
	array('Tripoli','Libyan Sea','Yes','No'),
	array('Turin','Milan','No','Yes'),
	array('Turin','Tuscany','No','Yes'),
	array('Turin','Cote DAzur','Yes','No'),
	array('Turin','Tyrrhenian Sea','Yes','No'),
	array('Turin','Tuscany (West Coast)','Yes','No'),
	array('Milan','Trieste','Yes','Yes'),
	array('Milan','Trento','No','Yes'),
	array('Milan','Tuscany','No','Yes'),
	array('Milan','North Adriatic Sea','Yes','No'),
	array('Milan','Tuscany (East Coast)','Yes','No'),
	array('Trieste','Trento','No','Yes'),
	array('Trieste','Salzburg','No','Yes'),
	array('Trieste','Croatia','Yes','Yes'),
	array('Trieste','North Adriatic Sea','Yes','No'),
	array('Trento','Innsbruck','No','Yes'),
	array('Trento','Salzburg','No','Yes'),
	array('Tuscany','Rome','No','Yes'),
	array('Rome','Naples','No','Yes'),
	array('Naples','Messina','No','Yes'),
	array('Messina','Sicily','Yes','Yes'),
	array('Messina','Tyrrhenian Sea','Yes','No'),
	array('Messina','South Adriatic Sea','Yes','No'),
	array('Messina','Ionian Sea','Yes','No'),
	array('Messina','Naples (North Coast)','Yes','No'),
	array('Messina','Naples (South Coast)','Yes','No'),
	array('Sicily','Tyrrhenian Sea','Yes','No'),
	array('Sicily','Ionian Sea','Yes','No'),
	array('Sicily','Sea of Sicily','Yes','No'),
	array('Balearic Sea','Cote DAzur','Yes','No'),
	array('Balearic Sea','Sea of Sicily','Yes','No'),
	array('Cote DAzur','Tyrrhenian Sea','Yes','No'),
	array('Tyrrhenian Sea','Ionian Sea','Yes','No'),
	array('Tyrrhenian Sea','Sea of Sicily','Yes','No'),
	array('Tyrrhenian Sea','Tuscany (West Coast)','Yes','No'),
	array('Tyrrhenian Sea','Rome (South Coast)','Yes','No'),
	array('Tyrrhenian Sea','Naples (South Coast)','Yes','No'),
	array('Benghazi','Libyan Sea','Yes','No'),
	array('Benghazi','Tobruk','Yes','Yes'),
	array('Hannover','Weimar','No','Yes'),
	array('Hannover','Berlin','No','Yes'),
	array('Hannover','Rostock','No','Yes'),
	array('Weimar','Berlin','No','Yes'),
	array('Weimar','Breslau','No','Yes'),
	array('Weimar','Prague','No','Yes'),
	array('Berlin','Rostock','No','Yes'),
	array('Berlin','Stettin','No','Yes'),
	array('Berlin','Breslau','No','Yes'),
	array('Berlin','Warsaw','No','Yes'),
	array('Rostock','Stettin','Yes','Yes'),
	array('Stettin','Danzig','Yes','Yes'),
	array('Stettin','Warsaw','No','Yes'),
	array('Konigsberg','Danzig','Yes','Yes'),
	array('Konigsberg','Warsaw','No','Yes'),
	array('Konigsberg','Lithuania','Yes','Yes'),
	array('Konigsberg','Brest-Litovsk','No','Yes'),
	array('Breslau','Prague','No','Yes'),
	array('Breslau','Warsaw','No','Yes'),
	array('Breslau','Cracow','No','Yes'),
	array('Innsbruck','Salzburg','No','Yes'),
	array('Vienna','Salzburg','No','Yes'),
	array('Vienna','Prague','No','Yes'),
	array('Vienna','Bratislava','No','Yes'),
	array('Vienna','Hungary','No','Yes'),
	array('Salzburg','Croatia','No','Yes'),
	array('Salzburg','Hungary','No','Yes'),
	array('Croatia','North Adriatic Sea','Yes','No'),
	array('Croatia','South Adriatic Sea','Yes','No'),
	array('Croatia','Bosnia and Herzegovina','Yes','Yes'),
	array('Croatia','Serbia','No','Yes'),
	array('Croatia','Hungary','No','Yes'),
	array('Croatia','Craiova','No','Yes'),
	array('North Adriatic Sea','South Adriatic Sea','Yes','No'),
	array('North Adriatic Sea','Tuscany (East Coast)','Yes','No'),
	array('North Adriatic Sea','Rome (North Coast)','Yes','No'),
	array('South Adriatic Sea','Bosnia and Herzegovina','Yes','No'),
	array('South Adriatic Sea','Tirana','Yes','No'),
	array('South Adriatic Sea','Ionian Sea','Yes','No'),
	array('South Adriatic Sea','Rome (North Coast)','Yes','No'),
	array('South Adriatic Sea','Naples (North Coast)','Yes','No'),
	array('Bosnia and Herzegovina','Tirana','Yes','Yes'),
	array('Bosnia and Herzegovina','Serbia','No','Yes'),
	array('Tirana','Macedonia','No','Yes'),
	array('Tirana','Serbia','No','Yes'),
	array('Tirana','Ionian Sea','Yes','No'),
	array('Tirana','Thessalonica','No','Yes'),
	array('Tirana','Thessalonica (West Coast)','Yes','No'),
	array('Macedonia','Serbia','No','Yes'),
	array('Macedonia','Thessalonica','No','Yes'),
	array('Macedonia','Bulgaria','No','Yes'),
	array('Serbia','Craiova','No','Yes'),
	array('Serbia','Bulgaria','No','Yes'),
	array('Ionian Sea','Sea of Sicily','Yes','No'),
	array('Ionian Sea','Libyan Sea','Yes','No'),
	array('Ionian Sea','Corinth','Yes','No'),
	array('Ionian Sea','Crete','Yes','No'),
	array('Ionian Sea','Aegean Sea','Yes','No'),
	array('Ionian Sea','Thessalonica (West Coast)','Yes','No'),
	array('Ionian Sea','Athens (West Coast)','Yes','No'),
	array('Sea of Sicily','Libyan Sea','Yes','No'),
	array('Prague','Bratislava','No','Yes'),
	array('Prague','Cracow','No','Yes'),
	array('Danzig','Warsaw','No','Yes'),
	array('Warsaw','Cracow','No','Yes'),
	array('Warsaw','Brest-Litovsk','No','Yes'),
	array('Warsaw','Lwow','No','Yes'),
	array('Libyan Sea','Crete','Yes','No'),
	array('Libyan Sea','Sea of Crete','Yes','No'),
	array('Libyan Sea','Tobruk','Yes','No'),
	array('Bratislava','Hungary','No','Yes'),
	array('Bratislava','Cracow','No','Yes'),
	array('Bratislava','Lwow','No','Yes'),
	array('Bratislava','Transylvania','No','Yes'),
	array('Hungary','Transylvania','No','Yes'),
	array('Hungary','Craiova','No','Yes'),
	array('Cracow','Lwow','No','Yes'),
	array('Thessalonica','Athens','No','Yes'),
	array('Thessalonica','Gallipoli','No','Yes'),
	array('Thessalonica','Bulgaria','No','Yes'),
	array('Athens','Corinth','No','Yes'),
	array('Corinth','Aegean Sea','Yes','No'),
	array('Corinth','Athens (West Coast)','Yes','No'),
	array('Corinth','Athens (East Coast)','Yes','No'),
	array('Latvia','Lithuania','Yes','Yes'),
	array('Latvia','Brest-Litovsk','No','Yes'),
	array('Latvia','Leningrad','No','Yes'),
	array('Latvia','Minsk','No','Yes'),
	array('Lithuania','Brest-Litovsk','No','Yes'),
	array('Brest-Litovsk','Lwow','No','Yes'),
	array('Brest-Litovsk','Minsk','No','Yes'),
	array('Brest-Litovsk','Kiev','No','Yes'),
	array('Lwow','Transylvania','No','Yes'),
	array('Lwow','Kiev','No','Yes'),
	array('Lwow','Bucharest','No','Yes'),
	array('Transylvania','Craiova','No','Yes'),
	array('Transylvania','Bucharest','No','Yes'),
	array('Craiova','Bulgaria','No','Yes'),
	array('Craiova','Bucharest','No','Yes'),
	array('Arkhangelskaya','Onega','No','Yes'),
	array('Arkhangelskaya','Uwalli','No','Yes'),
	array('Onega','Leningrad','No','Yes'),
	array('Onega','Smolensk','No','Yes'),
	array('Onega','Uwalli','No','Yes'),
	array('Black Sea','Istanbul','Yes','No'),
	array('Black Sea','Bulgaria','Yes','No'),
	array('Black Sea','Stalingrad','Yes','No'),
	array('Black Sea','Rostov','Yes','No'),
	array('Black Sea','Kiev','Yes','No'),
	array('Black Sea','Crimea','Yes','No'),
	array('Black Sea','Caucasus','Yes','No'),
	array('Black Sea','Bucharest','Yes','No'),
	array('Black Sea','Georgia','Yes','No'),
	array('Black Sea','Aegean Sea','Yes','No'),
	array('Black Sea','Ankara','Yes','No'),
	array('Black Sea','Van','Yes','No'),
	array('Leningrad','Smolensk','No','Yes'),
	array('Leningrad','Minsk','No','Yes'),
	array('Smolensk','Uwalli','No','Yes'),
	array('Smolensk','Moscow','No','Yes'),
	array('Smolensk','Nizhny Novgorod','No','Yes'),
	array('Smolensk','Minsk','No','Yes'),
	array('Smolensk','Kharkov','No','Yes'),
	array('Uwalli','Moscow','No','Yes'),
	array('Uwalli','Nizhny Novgorod','No','Yes'),
	array('Moscow','Nizhny Novgorod','No','Yes'),
	array('Nizhny Novgorod','Kharkov','No','Yes'),
	array('Nizhny Novgorod','Stalingrad','No','Yes'),
	array('Nizhny Novgorod','Rostov','No','Yes'),
	array('Minsk','Kharkov','No','Yes'),
	array('Minsk','Kiev','No','Yes'),
	array('Gallipoli','Istanbul','Yes','Yes'),
	array('Gallipoli','Bulgaria','No','Yes'),
	array('Gallipoli','Aegean Sea','Yes','No'),
	array('Gallipoli','Thessalonica (East Coast)','Yes','No'),
	array('Istanbul','Bulgaria','Yes','Yes'),
	array('Istanbul','Aegean Sea','Yes','No'),
	array('Istanbul','Izmir','Yes','Yes'),
	array('Istanbul','Ankara','Yes','Yes'),
	array('Bulgaria','Bucharest','Yes','Yes'),
	array('Crete','Sea of Crete','Yes','No'),
	array('Crete','Aegean Sea','Yes','No'),
	array('Cyprus','Cilician Sea','Yes','No'),
	array('Sea of Crete','Cilician Sea','Yes','No'),
	array('Sea of Crete','Tobruk','Yes','No'),
	array('Sea of Crete','Sidi Barrani','Yes','No'),
	array('Sea of Crete','Alexandria','Yes','No'),
	array('Sea of Crete','Aegean Sea','Yes','No'),
	array('Sea of Crete','Izmir','Yes','No'),
	array('Cilician Sea','Alexandria','Yes','No'),
	array('Cilician Sea','Suez','Yes','No'),
	array('Cilician Sea','Izmir','Yes','No'),
	array('Cilician Sea','Mersin','Yes','No'),
	array('Cilician Sea','Damascus','Yes','No'),
	array('Cilician Sea','Aleppo','Yes','No'),
	array('Cilician Sea','Red Sea','Yes','No'),
	array('Cilician Sea','Palestine (North Coast)','Yes','No'),
	array('Kharkov','Rostov','No','Yes'),
	array('Kharkov','Kiev','No','Yes'),
	array('Kharkov','Crimea','No','Yes'),
	array('Stalingrad','Rostov','Yes','Yes'),
	array('Stalingrad','Caucasus','Yes','Yes'),
	array('Rostov','Crimea','Yes','Yes'),
	array('Kiev','Crimea','Yes','Yes'),
	array('Kiev','Bucharest','Yes','Yes'),
	array('Caucasus','Georgia','Yes','Yes'),
	array('Georgia','Van','Yes','Yes'),
	array('Tobruk','Sidi Barrani','Yes','Yes'),
	array('Sidi Barrani','Cairo','No','Yes'),
	array('Sidi Barrani','Alexandria','Yes','Yes'),
	array('Cairo','Alexandria','Yes','Yes'),
	array('Cairo','Red Sea','Yes','No'),
	array('Alexandria','Suez','Yes','Yes'),
	array('Alexandria','Red Sea','Yes','No'),
	array('Suez','Palestine','No','Yes'),
	array('Suez','Red Sea','Yes','No'),
	array('Suez','Palestine (North Coast)','Yes','No'),
	array('Suez','Palestine (South Coast)','Yes','No'),
	array('Aegean Sea','Izmir','Yes','No'),
	array('Aegean Sea','Thessalonica (East Coast)','Yes','No'),
	array('Aegean Sea','Athens (East Coast)','Yes','No'),
	array('Izmir','Mersin','Yes','Yes'),
	array('Izmir','Ankara','No','Yes'),
	array('Mersin','Ankara','No','Yes'),
	array('Mersin','Van','No','Yes'),
	array('Mersin','Aleppo','Yes','Yes'),
	array('Ankara','Van','Yes','Yes'),
	array('Van','Iraq','No','Yes'),
	array('Van','Aleppo','No','Yes'),
	array('Iraq','Damascus','No','Yes'),
	array('Iraq','Aleppo','No','Yes'),
	array('Iraq','Arabia','No','Yes'),
	array('Iraq','Jordan','No','Yes'),
	array('Damascus','Aleppo','Yes','Yes'),
	array('Damascus','Palestine','No','Yes'),
	array('Damascus','Jordan','No','Yes'),
	array('Damascus','Palestine (North Coast)','Yes','No'),
	array('Palestine','Jordan','No','Yes'),
	array('Arabia','Jordan','Yes','Yes'),
	array('Arabia','Red Sea','Yes','No'),
	array('Jordan','Red Sea','Yes','No'),
	array('Jordan','Palestine (South Coast)','Yes','No'),
	array('Red Sea','Palestine (South Coast)','Yes','No'),
	array('Tuscany (East Coast)','Rome (North Coast)','Yes','No'),
	array('Tuscany (West Coast)','Rome (South Coast)','Yes','No'),
	array('Rome (North Coast)','Naples (North Coast)','Yes','No'),
	array('Thessalonica (East Coast)','Athens (East Coast)','Yes','No'),
	array('Thessalonica (West Coast)','Athens (West Coast)','Yes','No'),
	array('Rome (South Coast)','Naples (South Coast)','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
