<?php
// This is file installs the map data for the Canton variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Rumania', 'Coast', 'Yes', 0, 130, 73, 73, 39),
	array('Sevastopol', 'Coast', 'Yes', 6, 218, 80, 118, 36),
	array('Bulgaria', 'Coast', 'No', 0, 85, 85, 48, 50),
	array('Bulgaria (South Coast)', 'Coast', 'No', 0, 60, 97, 31, 53),
	array('Bulgaria (East Coast)', 'Coast', 'No', 0, 99, 95, 61, 52),
	array('Moscow', 'Land', 'Yes', 6, 348, 72, 184, 34),
	array('Siberia', 'Land', 'No', 6, 507, 60, 294, 32),
	array('Kirghizstan', 'Land', 'No', 6, 430, 151, 249, 84),
	array('Tomsk', 'Land', 'No', 6, 530, 181, 342, 110),
	array('Turkestan', 'Land', 'No', 6, 478, 277, 224, 155),
	array('Irkutsk', 'Land', 'Yes', 6, 911, 61, 518, 47),
	array('Khabarovsk', 'Coast', 'Yes', 6, 1081, 73, 632, 36),
	array('Maritime Province', 'Coast', 'No', 6, 1111, 154, 634, 105),
	array('Amur', 'Land', 'No', 6, 1012, 103, 587, 57),
	array('Constantinople', 'Coast', 'Yes', 7, 77, 163, 47, 92),
	array('Damascus', 'Coast', 'Yes', 7, 95, 279, 52, 164),
	array('Damascus (West Coast)', 'Coast', 'No', 7, 82, 262, 45, 150),
	array('Damascus (South Coast)', 'Coast', 'No', 7, 79, 303, 53, 170),
	array('Egypt', 'Coast', 'No', 7, 17, 287, 12, 201),
	array('Arabia', 'Coast', 'No', 7, 257, 522, 109, 285),
	array('Baghdad', 'Coast', 'Yes', 7, 193, 328, 108, 184),
	array('Armenia', 'Coast', 'No', 7, 239, 176, 138, 93),
	array('Persia', 'Coast', 'Yes', 0, 321, 325, 188, 188),
	array('Baluchistan', 'Coast', 'Yes', 0, 379, 445, 226, 274),
	array('Afghanistan', 'Land', 'Yes', 0, 392, 372, 224, 218),
	array('Kashmir', 'Land', 'No', 1, 492, 441, 285, 254),
	array('Delhi', 'Land', 'Yes', 1, 539, 511, 323, 290),
	array('Bombay', 'Coast', 'No', 1, 486, 640, 272, 316),
	array('Assam', 'Land', 'No', 1, 752, 502, 418, 304),
	array('Calcutta', 'Coast', 'Yes', 1, 664, 543, 361, 334),
	array('Madras', 'Coast', 'Yes', 1, 526, 748, 303, 422),
	array('Burma', 'Coast', 'Yes', 0, 758, 641, 439, 360),
	array('Siam', 'Coast', 'Yes', 0, 822, 693, 468, 365),
	array('Siam (West Coast)', 'Coast', 'No', 0, 789, 772, 456, 446),
	array('Siam (East Coast)', 'Coast', 'No', 0, 821, 791, 477, 408),
	array('Malaya', 'Coast', 'Yes', 0, 836, 832, 483, 490),
	array('Laos', 'Land', 'No', 3, 859, 620, 494, 358),
	array('Saigon', 'Coast', 'Yes', 3, 913, 728, 516, 435),
	array('Hue', 'Coast', 'Yes', 3, 932, 690, 529, 381),
	array('Cambodia', 'Coast', 'Yes', 0, 893, 711, 501, 419),
	array('Hanoi', 'Coast', 'Yes', 3, 883, 601, 516, 354),
	array('Sumatra', 'Coast', 'Yes', 4, 796, 875, 453, 499),
	array('Java', 'Coast', 'Yes', 4, 944, 956, 547, 553),
	array('Borneo', 'Coast', 'Yes', 4, 970, 871, 592, 503),
	array('Sarawak', 'Coast', 'No', 0, 998, 814, 583, 465),
	array('Philippines', 'Coast', 'Yes', 0, 1160, 716, 672, 408),
	array('Sasebo', 'Coast', 'Yes', 5, 1149, 356, 662, 203),
	array('Kyoto', 'Coast', 'Yes', 5, 1157, 296, 664, 171),
	array('Tokyo', 'Coast', 'Yes', 5, 1210, 188, 697, 103),
	array('Yesso', 'Coast', 'No', 5, 1184, 123, 669, 57),
	array('Akita', 'Coast', 'No', 5, 1181, 182, 686, 134),
	array('Shikoku', 'Coast', 'No', 5, 1200, 263, 686, 170),
	array('Sinkiang', 'Land', 'No', 2, 640, 279, 331, 196),
	array('Tibet', 'Land', 'Yes', 2, 686, 442, 401, 255),
	array('Kansu', 'Land', 'No', 2, 752, 318, 460, 215),
	array('Chungking', 'Land', 'Yes', 2, 894, 442, 444, 254),
	array('Yunnan', 'Land', 'No', 2, 844, 552, 491, 307),
	array('Mongolia', 'Land', 'No', 2, 872, 216, 501, 121),
	array('Canton', 'Coast', 'No', 2, 978, 464, 558, 267),
	array('Canton (South Coast)', 'Coast', 'No', 2, 945, 548, 544, 314),
	array('Canton (East Coast)', 'Coast', 'No', 2, 1038, 478, 590, 268),
	array('Hong Kong', 'Coast', 'Yes', 0, 982, 530, 564, 304),
	array('Formosa', 'Coast', 'Yes', 0, 1072, 487, 619, 277),
	array('Shanghai', 'Coast', 'Yes', 2, 1012, 396, 585, 220),
	array('Peking', 'Coast', 'Yes', 2, 996, 327, 574, 185),
	array('Korea', 'Coast', 'Yes', 0, 1092, 314, 628, 180),
	array('Manchuria', 'Coast', 'Yes', 0, 1021, 251, 569, 132),
	array('Black Sea', 'Sea', 'No', 0, 138, 122, 80, 65),
	array('Mediterranean Sea', 'Sea', 'No', 0, 64, 210, 35, 117),
	array('Red Sea', 'Sea', 'No', 0, 126, 607, 83, 350),
	array('Arabian Sea', 'Sea', 'No', 0, 310, 628, 227, 373),
	array('West Indian Ocean', 'Sea', 'No', 0, 349, 834, 164, 452),
	array('Persian Gulf', 'Sea', 'No', 0, 318, 503, 187, 289),
	array('East Indian Ocean', 'Sea', 'No', 0, 606, 848, 400, 492),
	array('South Indian Ocean', 'Sea', 'No', 0, 605, 944, 436, 549),
	array('Bay of Bengal', 'Sea', 'No', 0, 644, 734, 370, 418),
	array('Java Sea', 'Sea', 'No', 0, 893, 876, 524, 508),
	array('Karimata Strait', 'Sea', 'No', 0, 929, 780, 545, 437),
	array('Gulf of Siam', 'Sea', 'No', 0, 861, 787, 493, 444),
	array('Banda Sea', 'Sea', 'No', 0, 1157, 907, 701, 515),
	array('Philippine Sea', 'Sea', 'No', 0, 1150, 503, 663, 290),
	array('South China Sea', 'Sea', 'No', 0, 1024, 599, 585, 348),
	array('Central Pacific Ocean', 'Sea', 'No', 0, 1265, 442, 734, 249),
	array('Celebes Sea', 'Sea', 'No', 0, 1121, 771, 645, 446),
	array('East China Sea', 'Sea', 'No', 0, 1089, 436, 636, 218),
	array('Yellow Sea', 'Sea', 'No', 0, 1046, 344, 603, 194),
	array('Sea of Japan', 'Sea', 'No', 0, 1126, 278, 643, 148),
	array('Sea of Okhotsk', 'Sea', 'No', 0, 1185, 48, 686, 34),
	array('Gulf of Martaban', 'Sea', 'No', 0, 752, 718, 435, 432)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Rumania','Sevastopol','Yes','Yes'),
	array('Rumania','Bulgaria','No','Yes'),
	array('Rumania','Bulgaria (East Coast)','Yes','No'),
	array('Rumania','Black Sea','Yes','No'),
	array('Sevastopol','Moscow','No','Yes'),
	array('Sevastopol','Kirghizstan','No','Yes'),
	array('Sevastopol','Armenia','Yes','Yes'),
	array('Sevastopol','Black Sea','Yes','No'),
	array('Bulgaria','Constantinople','No','Yes'),
	array('Bulgaria (South Coast)','Constantinople','Yes','No'),
	array('Bulgaria (South Coast)','Mediterranean Sea','Yes','No'),
	array('Bulgaria (East Coast)','Constantinople','Yes','No'),
	array('Bulgaria (East Coast)','Black Sea','Yes','No'),
	array('Moscow','Siberia','No','Yes'),
	array('Moscow','Kirghizstan','No','Yes'),
	array('Siberia','Kirghizstan','No','Yes'),
	array('Siberia','Tomsk','No','Yes'),
	array('Siberia','Irkutsk','No','Yes'),
	array('Kirghizstan','Tomsk','No','Yes'),
	array('Kirghizstan','Turkestan','No','Yes'),
	array('Kirghizstan','Armenia','No','Yes'),
	array('Tomsk','Turkestan','No','Yes'),
	array('Tomsk','Irkutsk','No','Yes'),
	array('Tomsk','Sinkiang','No','Yes'),
	array('Tomsk','Mongolia','No','Yes'),
	array('Turkestan','Persia','No','Yes'),
	array('Turkestan','Afghanistan','No','Yes'),
	array('Turkestan','Sinkiang','No','Yes'),
	array('Irkutsk','Khabarovsk','No','Yes'),
	array('Irkutsk','Amur','No','Yes'),
	array('Irkutsk','Mongolia','No','Yes'),
	array('Khabarovsk','Maritime Province','Yes','Yes'),
	array('Khabarovsk','Amur','No','Yes'),
	array('Khabarovsk','Sea of Japan','Yes','No'),
	array('Khabarovsk','Sea of Okhotsk','Yes','No'),
	array('Maritime Province','Amur','No','Yes'),
	array('Maritime Province','Korea','Yes','Yes'),
	array('Maritime Province','Manchuria','No','Yes'),
	array('Maritime Province','Sea of Japan','Yes','No'),
	array('Amur','Mongolia','No','Yes'),
	array('Amur','Manchuria','No','Yes'),
	array('Constantinople','Damascus','No','Yes'),
	array('Constantinople','Damascus (West Coast)','Yes','No'),
	array('Constantinople','Baghdad','No','Yes'),
	array('Constantinople','Armenia','Yes','Yes'),
	array('Constantinople','Persia','No','Yes'),
	array('Constantinople','Black Sea','Yes','No'),
	array('Constantinople','Mediterranean Sea','Yes','No'),
	array('Damascus','Egypt','No','Yes'),
	array('Damascus','Arabia','No','Yes'),
	array('Damascus','Baghdad','No','Yes'),
	array('Damascus (West Coast)','Egypt','Yes','No'),
	array('Damascus (West Coast)','Mediterranean Sea','Yes','No'),
	array('Damascus (South Coast)','Egypt','Yes','No'),
	array('Damascus (South Coast)','Arabia','Yes','No'),
	array('Damascus (South Coast)','Red Sea','Yes','No'),
	array('Egypt','Mediterranean Sea','Yes','No'),
	array('Egypt','Red Sea','Yes','No'),
	array('Arabia','Baghdad','Yes','Yes'),
	array('Arabia','Red Sea','Yes','No'),
	array('Arabia','Arabian Sea','Yes','No'),
	array('Arabia','Persian Gulf','Yes','No'),
	array('Baghdad','Persia','Yes','Yes'),
	array('Baghdad','Persian Gulf','Yes','No'),
	array('Armenia','Persia','No','Yes'),
	array('Armenia','Black Sea','Yes','No'),
	array('Persia','Baluchistan','Yes','Yes'),
	array('Persia','Afghanistan','No','Yes'),
	array('Persia','Persian Gulf','Yes','No'),
	array('Baluchistan','Afghanistan','No','Yes'),
	array('Baluchistan','Kashmir','No','Yes'),
	array('Baluchistan','Delhi','No','Yes'),
	array('Baluchistan','Bombay','Yes','Yes'),
	array('Baluchistan','Arabian Sea','Yes','No'),
	array('Baluchistan','Persian Gulf','Yes','No'),
	array('Afghanistan','Kashmir','No','Yes'),
	array('Afghanistan','Sinkiang','No','Yes'),
	array('Kashmir','Delhi','No','Yes'),
	array('Kashmir','Sinkiang','No','Yes'),
	array('Kashmir','Tibet','No','Yes'),
	array('Delhi','Bombay','No','Yes'),
	array('Delhi','Calcutta','No','Yes'),
	array('Delhi','Madras','No','Yes'),
	array('Bombay','Madras','Yes','Yes'),
	array('Bombay','Arabian Sea','Yes','No'),
	array('Bombay','West Indian Ocean','Yes','No'),
	array('Assam','Calcutta','No','Yes'),
	array('Assam','Burma','No','Yes'),
	array('Assam','Tibet','No','Yes'),
	array('Assam','Chungking','No','Yes'),
	array('Assam','Yunnan','No','Yes'),
	array('Calcutta','Madras','Yes','Yes'),
	array('Calcutta','Burma','Yes','Yes'),
	array('Calcutta','Bay of Bengal','Yes','No'),
	array('Madras','West Indian Ocean','Yes','No'),
	array('Madras','Bay of Bengal','Yes','No'),
	array('Burma','Siam','No','Yes'),
	array('Burma','Siam (West Coast)','Yes','No'),
	array('Burma','Laos','No','Yes'),
	array('Burma','Yunnan','No','Yes'),
	array('Burma','Bay of Bengal','Yes','No'),
	array('Burma','Gulf of Martaban','Yes','No'),
	array('Siam','Malaya','No','Yes'),
	array('Siam','Laos','No','Yes'),
	array('Siam','Cambodia','No','Yes'),
	array('Siam (West Coast)','Malaya','Yes','No'),
	array('Siam (West Coast)','Gulf of Martaban','Yes','No'),
	array('Siam (East Coast)','Malaya','Yes','No'),
	array('Siam (East Coast)','Cambodia','Yes','No'),
	array('Siam (East Coast)','Gulf of Siam','Yes','No'),
	array('Malaya','Java Sea','Yes','No'),
	array('Malaya','Gulf of Siam','Yes','No'),
	array('Malaya','Gulf of Martaban','Yes','No'),
	array('Laos','Hue','No','Yes'),
	array('Laos','Cambodia','No','Yes'),
	array('Laos','Hanoi','No','Yes'),
	array('Laos','Yunnan','No','Yes'),
	array('Saigon','Hue','Yes','Yes'),
	array('Saigon','Cambodia','Yes','Yes'),
	array('Saigon','Karimata Strait','Yes','No'),
	array('Saigon','Gulf of Siam','Yes','No'),
	array('Hue','Cambodia','No','Yes'),
	array('Hue','Hanoi','Yes','Yes'),
	array('Hue','Karimata Strait','Yes','No'),
	array('Hue','South China Sea','Yes','No'),
	array('Cambodia','Gulf of Siam','Yes','No'),
	array('Hanoi','Yunnan','No','Yes'),
	array('Hanoi','Canton','No','Yes'),
	array('Hanoi','Canton (South Coast)','Yes','No'),
	array('Hanoi','South China Sea','Yes','No'),
	array('Sumatra','East Indian Ocean','Yes','No'),
	array('Sumatra','South Indian Ocean','Yes','No'),
	array('Sumatra','Java Sea','Yes','No'),
	array('Sumatra','Gulf of Martaban','Yes','No'),
	array('Java','South Indian Ocean','Yes','No'),
	array('Java','Java Sea','Yes','No'),
	array('Java','Banda Sea','Yes','No'),
	array('Borneo','Sarawak','Yes','Yes'),
	array('Borneo','Java Sea','Yes','No'),
	array('Borneo','Karimata Strait','Yes','No'),
	array('Borneo','Celebes Sea','Yes','No'),
	array('Sarawak','Karimata Strait','Yes','No'),
	array('Sarawak','South China Sea','Yes','No'),
	array('Sarawak','Celebes Sea','Yes','No'),
	array('Philippines','Philippine Sea','Yes','No'),
	array('Philippines','South China Sea','Yes','No'),
	array('Philippines','Central Pacific Ocean','Yes','No'),
	array('Philippines','Celebes Sea','Yes','No'),
	array('Sasebo','Kyoto','Yes','Yes'),
	array('Sasebo','Shikoku','Yes','Yes'),
	array('Sasebo','Philippine Sea','Yes','No'),
	array('Sasebo','East China Sea','Yes','No'),
	array('Sasebo','Sea of Japan','Yes','No'),
	array('Kyoto','Akita','Yes','Yes'),
	array('Kyoto','Shikoku','No','Yes'),
	array('Kyoto','Sea of Japan','Yes','No'),
	array('Tokyo','Yesso','Yes','Yes'),
	array('Tokyo','Akita','No','Yes'),
	array('Tokyo','Shikoku','Yes','Yes'),
	array('Tokyo','Philippine Sea','Yes','No'),
	array('Tokyo','Central Pacific Ocean','Yes','No'),
	array('Yesso','Akita','Yes','Yes'),
	array('Yesso','Central Pacific Ocean','Yes','No'),
	array('Yesso','Sea of Japan','Yes','No'),
	array('Yesso','Sea of Okhotsk','Yes','No'),
	array('Akita','Shikoku','No','Yes'),
	array('Akita','Sea of Japan','Yes','No'),
	array('Shikoku','Philippine Sea','Yes','No'),
	array('Sinkiang','Tibet','No','Yes'),
	array('Sinkiang','Kansu','No','Yes'),
	array('Sinkiang','Mongolia','No','Yes'),
	array('Tibet','Kansu','No','Yes'),
	array('Tibet','Chungking','No','Yes'),
	array('Kansu','Chungking','No','Yes'),
	array('Kansu','Mongolia','No','Yes'),
	array('Kansu','Peking','No','Yes'),
	array('Chungking','Yunnan','No','Yes'),
	array('Chungking','Canton','No','Yes'),
	array('Chungking','Shanghai','No','Yes'),
	array('Chungking','Peking','No','Yes'),
	array('Yunnan','Canton','No','Yes'),
	array('Mongolia','Peking','No','Yes'),
	array('Mongolia','Manchuria','No','Yes'),
	array('Canton','Hong Kong','No','Yes'),
	array('Canton','Shanghai','No','Yes'),
	array('Canton (South Coast)','Hong Kong','Yes','No'),
	array('Canton (South Coast)','South China Sea','Yes','No'),
	array('Canton (East Coast)','Hong Kong','Yes','No'),
	array('Canton (East Coast)','Shanghai','Yes','No'),
	array('Canton (East Coast)','South China Sea','Yes','No'),
	array('Canton (East Coast)','East China Sea','Yes','No'),
	array('Hong Kong','South China Sea','Yes','No'),
	array('Formosa','Philippine Sea','Yes','No'),
	array('Formosa','South China Sea','Yes','No'),
	array('Formosa','East China Sea','Yes','No'),
	array('Shanghai','Peking','Yes','Yes'),
	array('Shanghai','East China Sea','Yes','No'),
	array('Shanghai','Yellow Sea','Yes','No'),
	array('Peking','Manchuria','Yes','Yes'),
	array('Peking','Yellow Sea','Yes','No'),
	array('Korea','Manchuria','Yes','Yes'),
	array('Korea','East China Sea','Yes','No'),
	array('Korea','Yellow Sea','Yes','No'),
	array('Korea','Sea of Japan','Yes','No'),
	array('Manchuria','Yellow Sea','Yes','No'),
	array('Red Sea','Arabian Sea','Yes','No'),
	array('Red Sea','West Indian Ocean','Yes','No'),
	array('Arabian Sea','West Indian Ocean','Yes','No'),
	array('Arabian Sea','Persian Gulf','Yes','No'),
	array('West Indian Ocean','East Indian Ocean','Yes','No'),
	array('West Indian Ocean','South Indian Ocean','Yes','No'),
	array('West Indian Ocean','Bay of Bengal','Yes','No'),
	array('East Indian Ocean','South Indian Ocean','Yes','No'),
	array('East Indian Ocean','Bay of Bengal','Yes','No'),
	array('East Indian Ocean','Gulf of Martaban','Yes','No'),
	array('South Indian Ocean','Java Sea','Yes','No'),
	array('South Indian Ocean','Banda Sea','Yes','No'),
	array('Bay of Bengal','Gulf of Martaban','Yes','No'),
	array('Java Sea','Karimata Strait','Yes','No'),
	array('Java Sea','Gulf of Siam','Yes','No'),
	array('Java Sea','Banda Sea','Yes','No'),
	array('Java Sea','Celebes Sea','Yes','No'),
	array('Java Sea','Gulf of Martaban','Yes','No'),
	array('Karimata Strait','Gulf of Siam','Yes','No'),
	array('Karimata Strait','South China Sea','Yes','No'),
	array('Banda Sea','Celebes Sea','Yes','No'),
	array('Philippine Sea','South China Sea','Yes','No'),
	array('Philippine Sea','Central Pacific Ocean','Yes','No'),
	array('Philippine Sea','East China Sea','Yes','No'),
	array('South China Sea','Celebes Sea','Yes','No'),
	array('South China Sea','East China Sea','Yes','No'),
	array('Central Pacific Ocean','Celebes Sea','Yes','No'),
	array('Central Pacific Ocean','Sea of Okhotsk','Yes','No'),
	array('East China Sea','Yellow Sea','Yes','No'),
	array('East China Sea','Sea of Japan','Yes','No'),
	array('Sea of Japan','Sea of Okhotsk','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
