<?php
// This is file installs the map data for the MongolianEmpire variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('#1 Jerusalem', 'Coast', 'Yes', 12, 574, 328, 288, 168),
	array('#2 Moscow', 'Coast', 'Yes', 2, 796, 416, 398, 211),
	array('#3 Bagdhad', 'Coast', 'Yes', 5, 484, 406, 242, 208),
	array('Yemen', 'Coast', 'Yes', 8, 334, 376, 176, 184),
	array('#5 Khotum', 'Coast', 'Yes', 12, 433, 675, 218, 343),
	array('#6 Kandahar', 'Coast', 'Yes', 3, 334, 676, 167, 341),
	array('Tugnusess', 'Coast', 'Yes', 0, 906, 1088, 440, 528),
	array('#8 Lhasar', 'Land', 'Yes', 10, 409, 767, 206, 390),
	array('#9 Si-Ning-Fu', 'Coast', 'Yes', 12, 442, 844, 223, 427),
	array('#10 Kharakorum', 'Coast', 'Yes', 12, 535, 856, 272, 432),
	array('#11 Lo-Yang', 'Coast', 'Yes', 12, 410, 936, 206, 471),
	array('Morroco', 'Coast', 'Yes', 0, 899, 104, 431, 34),
	array('Berber', 'Land', 'No', 8, 668, 127, 345, 58),
	array('Chadic', 'Land', 'No', 8, 444, 156, 225, 82),
	array('Axum', 'Coast', 'No', 8, 250, 172, 126, 88),
	array('Somalia', 'Coast', 'Yes', 0, 233, 271, 116, 133),
	array('Makura', 'Coast', 'No', 8, 421, 232, 208, 113),
	array('Angola', 'Coast', 'No', 0, 826, 157, 407, 75),
	array('Almohad', 'Coast', 'Yes', 8, 704, 166, 350, 82),
	array('Ayyubid', 'Coast', 'Yes', 8, 570, 227, 280, 119),
	array('African Coast', 'Sea', 'No', 0, 954, 132, 489, 62),
	array('Western Mediterranean Sea', 'Sea', 'No', 0, 837, 226, 414, 116),
	array('Central Mediterranean Sea', 'Sea', 'No', 0, 708, 249, 355, 121),
	array('Eastern Mediterranean Sea', 'Sea', 'No', 0, 674, 224, 314, 126),
	array('Constantinople', 'Coast', 'Yes', 0, 682, 320, 349, 158),
	array('Western Byzantine', 'Coast', 'No', 2, 718, 319, 363, 160),
	array('Eastern Byzantine', 'Coast', 'No', 5, 631, 340, 296, 192),
	array('Crusader States', 'Coast', 'No', 2, 546, 315, 273, 164),
	array('Egypt', 'Coast', 'Yes', 0, 500, 308, 249, 161),
	array('Seljuk', 'Land', 'No', 5, 518, 356, 268, 180),
	array('Mecca', 'Coast', 'Yes', 8, 426, 325, 220, 167),
	array('Red Sea', 'Sea', 'No', 0, 286, 371, 226, 134),
	array('Zanzibar Coast', 'Sea', 'No', 0, 80, 301, 42, 139),
	array('Arabian Sea', 'Sea', 'No', 0, 261, 448, 69, 227),
	array('Portugal', 'Coast', 'Yes', 0, 940, 181, 473, 93),
	array('Spain', 'Coast', 'No', 2, 882, 248, 443, 125),
	array('Papal States', 'Coast', 'Yes', 0, 802, 277, 381, 132),
	array('Holy Roman Empire', 'Coast', 'Yes', 0, 897, 312, 459, 150),
	array('Albion', 'Coast', 'Yes', 0, 969, 393, 482, 191),
	array('North Sea', 'Sea', 'No', 0, 970, 306, 494, 154),
	array('The Danes', 'Coast', 'No', 2, 874, 378, 441, 194),
	array('Norsk Territories', 'Coast', 'No', 2, 898, 539, 450, 255),
	array('Choralan', 'Coast', 'Yes', 5, 434, 473, 222, 225),
	array('Armenia', 'Coast', 'Yes', 5, 499, 541, 248, 245),
	array('Sevast Politi', 'Coast', 'Yes', 0, 682, 440, 340, 214),
	array('Cumanis', 'Coast', 'Yes', 0, 678, 496, 342, 252),
	array('Bashkir', 'Coast', 'No', 4, 682, 617, 343, 303),
	array('Sindh', 'Coast', 'No', 3, 345, 619, 168, 310),
	array('Urgent', 'Land', 'Yes', 0, 564, 665, 284, 330),
	array('Urgrian', 'Coast', 'No', 4, 714, 749, 357, 369),
	array('#4 Samarkand', 'Land', 'Yes', 12, 582, 592, 293, 302),
	array('Kiva', 'Coast', 'Yes', 0, 569, 548, 293, 258),
	array('Merv', 'Land', 'No', 5, 554, 596, 274, 300),
	array('Zangid', 'Land', 'No', 5, 507, 392, 244, 192),
	array('Diyarnakir', 'Coast', 'No', 5, 553, 440, 279, 219),
	array('Georgia', 'Coast', 'No', 5, 597, 444, 297, 219),
	array('Caucasus', 'Coast', 'No', 0, 636, 460, 317, 229),
	array('Muscovy', 'Coast', 'Yes', 4, 772, 453, 385, 228),
	array('Moldavia', 'Coast', 'No', 0, 728, 412, 364, 211),
	array('Teutonic Order', 'Coast', 'No', 2, 820, 440, 411, 219),
	array('Baltic Sea', 'Sea', 'No', 0, 848, 450, 425, 228),
	array('Riga', 'Coast', 'No', 4, 848, 500, 422, 247),
	array('Venice', 'Coast', 'Yes', 2, 817, 308, 412, 148),
	array('Hungary', 'Coast', 'Yes', 2, 786, 350, 395, 177),
	array('Poland', 'Coast', 'No', 2, 835, 391, 419, 191),
	array('Lithuania', 'Land', 'No', 2, 783, 388, 391, 195),
	array('Novogorad', 'Coast', 'Yes', 4, 752, 620, 378, 306),
	array('Bulgars', 'Coast', 'No', 4, 749, 507, 377, 252),
	array('Pitzorke Sea', 'Sea', 'No', 0, 885, 633, 444, 320),
	array('Septentrional Ocean', 'Sea', 'No', 0, 942, 920, 468, 463),
	array('Aniafret Sea', 'Sea', 'No', 0, 911, 1224, 455, 616),
	array('North Cathay', 'Coast', 'No', 9, 712, 1028, 365, 517),
	array('Samoyedes', 'Coast', 'No', 1, 676, 820, 341, 412),
	array('Tunguska', 'Coast', 'No', 0, 800, 845, 400, 396),
	array('Bjarmaland', 'Coast', 'No', 4, 798, 632, 399, 312),
	array('South Cathay', 'Coast', 'No', 9, 690, 1072, 352, 534),
	array('Sungar', 'Coast', 'No', 9, 630, 1113, 315, 555),
	array('Black Sea', 'Sea', 'No', 0, 656, 392, 327, 200),
	array('Caspian Sea', 'Sea', 'No', 0, 604, 492, 300, 243),
	array('Abbasid', 'Coast', 'No', 8, 369, 439, 182, 220),
	array('Axum (South Coast)', 'Coast', 'No', 8, 71, 152, 38, 85),
	array('Axum (North Coast)', 'Coast', 'No', 8, 292, 275, 142, 139),
	array('Tashkent', 'Land', 'Yes', 0, 624, 676, 314, 342),
	array('Kudchan', 'Land', 'No', 1, 590, 723, 292, 358),
	array('#7 Almalik', 'Land', 'Yes', 1, 618, 730, 307, 370),
	array('Vraye', 'Land', 'No', 0, 758, 907, 380, 455),
	array('Kyoto Prefecture West', 'Coast', 'No', 0, 556, 1201, 273, 599),
	array('Kyoto', 'Coast', 'Yes', 0, 519, 1192, 258, 593),
	array('#14 Yedo', 'Coast', 'Yes', 12, 562, 1227, 283, 621),
	array('Yedo Prefecture', 'Coast', 'No', 0, 626, 1220, 312, 610),
	array('Naiman', 'Land', 'Yes', 1, 512, 798, 296, 383),
	array('Xanadu', 'Land', 'Yes', 9, 595, 892, 290, 450),
	array('Bargul', 'Land', 'Yes', 9, 680, 895, 334, 447),
	array('Stingui', 'Coast', 'No', 9, 624, 948, 316, 473),
	array('Curguth', 'Coast', 'Yes', 9, 618, 976, 310, 488),
	array('Kyoto Prefecture East', 'Coast', 'No', 0, 533, 1246, 268, 610),
	array('Guam', 'Coast', 'Yes', 0, 238, 1299, 121, 650),
	array('Waters of Cathay', 'Sea', 'No', 0, 750, 1184, 372, 595),
	array('Xiam', 'Coast', 'Yes', 11, 485, 903, 242, 452),
	array('Sanchi', 'Coast', 'No', 11, 382, 928, 190, 465),
	array('Honao', 'Coast', 'No', 11, 458, 992, 230, 495),
	array('Sinfai', 'Coast', 'No', 11, 410, 1045, 205, 521),
	array('Fokien', 'Coast', 'Yes', 11, 374, 1036, 187, 519),
	array('Xanton', 'Coast', 'No', 11, 449, 1040, 223, 520),
	array('Nanqi', 'Coast', 'No', 11, 400, 1088, 212, 550),
	array('Carazan', 'Land', 'No', 1, 468, 835, 239, 415),
	array('Lop', 'Land', 'No', 9, 536, 884, 266, 459),
	array('Qamdo', 'Land', 'No', 10, 444, 812, 222, 394),
	array('Chamdo', 'Land', 'Yes', 10, 415, 840, 208, 420),
	array('Nagqu', 'Land', 'No', 10, 441, 724, 221, 362),
	array('Ngari', 'Land', 'No', 10, 410, 724, 206, 361),
	array('Xigaze', 'Land', 'No', 10, 377, 726, 193, 364),
	array('Nyingchi', 'Coast', 'No', 10, 386, 814, 190, 388),
	array('Spain (North Coast)', 'Coast', 'No', 2, 948, 220, 475, 111),
	array('Spain (South Coast)', 'Coast', 'No', 2, 866, 221, 431, 112),
	array('Western Byzantine (South Coast)', 'Coast', 'No', 2, 723, 292, 350, 134),
	array('Western Byzantine (East Coast)', 'Coast', 'No', 2, 695, 348, 347, 174),
	array('Eastern Byzantine (North Coast)', 'Coast', 'No', 5, 645, 372, 327, 174),
	array('Eastern Byzantine (South Coast)', 'Coast', 'No', 5, 645, 303, 304, 165),
	array('Tugnusess (West Coast)', 'Coast', 'No', 0, 944, 1048, 437, 482),
	array('Tugnusess (East Coast)', 'Coast', 'No', 0, 822, 1173, 429, 571),
	array('Yupi', 'Coast', 'Yes', 9, 576, 1097, 288, 543),
	array('Yupi (East Coast)', 'Coast', 'No', 9, 586, 1133, 290, 566),
	array('Yupi (South Coast)', 'Coast', 'No', 9, 538, 1096, 270, 550),
	array('Peking', 'Coast', 'Yes', 11, 496, 1050, 248, 523),
	array('Corea', 'Coast', 'Yes', 9, 510, 1144, 248, 563),
	array('Kilango', 'Land', 'No', 9, 538, 953, 268, 476),
	array('Leaotung', 'Coast', 'No', 9, 545, 1072, 273, 535),
	array('Serra', 'Coast', 'No', 9, 646, 1043, 306, 519),
	array('Quan', 'Coast', 'No', 11, 388, 996, 192, 502),
	array('Yarkand', 'Land', 'Yes', 0, 483, 756, 245, 371),
	array('Furghana', 'Land', 'Yes', 1, 518, 706, 260, 354),
	array('Pamir', 'Land', 'No', 1, 478, 722, 238, 359),
	array('Herat', 'Coast', 'No', 5, 429, 612, 226, 283),
	array('Khuram', 'Land', 'No', 1, 452, 656, 231, 321),
	array('Java Isles', 'Coast', 'Yes', 7, 16, 1117, 14, 554),
	array('Borneo', 'Coast', 'Yes', 7, 87, 1115, 44, 558),
	array('Sarawak', 'Coast', 'No', 7, 118, 1140, 61, 575),
	array('Makkassar', 'Coast', 'Yes', 0, 109, 1204, 53, 597),
	array('Luzon', 'Coast', 'No', 7, 264, 1153, 132, 575),
	array('Taiwan', 'Coast', 'Yes', 0, 346, 1132, 172, 567),
	array('Sumatra', 'Coast', 'Yes', 7, 92, 924, 49, 455),
	array('Malaya', 'Coast', 'Yes', 0, 135, 937, 88, 455),
	array('Siam', 'Land', 'Yes', 6, 255, 904, 130, 450),
	array('Siam (West Coast)', 'Coast', 'No', 6, 214, 901, 110, 450),
	array('Siam (East Coast)', 'Coast', 'No', 6, 207, 934, 102, 464),
	array('#13 Angkor', 'Coast', 'Yes', 6, 239, 978, 119, 495),
	array('Champa', 'Coast', 'No', 6, 206, 995, 99, 494),
	array('Khmer', 'Coast', 'No', 6, 261, 951, 129, 477),
	array('Annam', 'Coast', 'Yes', 0, 304, 992, 127, 507),
	array('Laos', 'Coast', 'No', 11, 337, 966, 166, 466),
	array('Pegu', 'Coast', 'No', 6, 293, 947, 158, 457),
	array('Lower Pagan', 'Coast', 'No', 6, 258, 886, 126, 420),
	array('Upper Pagan', 'Coast', 'Yes', 0, 310, 856, 154, 431),
	array('#12 Kainan', 'Coast', 'Yes', 12, 342, 895, 170, 452),
	array('Bhutan', 'Coast', 'Yes', 10, 367, 842, 166, 432),
	array('Nan Chao', 'Coast', 'No', 11, 371, 896, 198, 431),
	array('Hanoi', 'Coast', 'No', 11, 323, 1020, 159, 509),
	array('Bengal', 'Coast', 'Yes', 3, 278, 751, 143, 372),
	array('Nepal East', 'Land', 'No', 3, 342, 773, 169, 383),
	array('Nepal West', 'Land', 'No', 3, 353, 707, 175, 351),
	array('Malwa', 'Coast', 'No', 3, 312, 722, 153, 360),
	array('Chola', 'Coast', 'Yes', 0, 212, 686, 101, 347),
	array('Karala', 'Coast', 'Yes', 0, 181, 648, 88, 321),
	array('Ceylon', 'Coast', 'Yes', 0, 143, 688, 76, 342),
	array('Kamataka', 'Coast', 'No', 3, 293, 657, 145, 326),
	array('Siestan', 'Coast', 'Yes', 0, 414, 559, 209, 279),
	array('Bakkar', 'Coast', 'Yes', 0, 392, 603, 198, 298),
	array('Hindhu Kush', 'Coast', 'No', 10, 408, 663, 200, 333),
	array('Chintapur Coast', 'Sea', 'No', 0, 264, 580, 133, 286),
	array('Persian Gulf', 'Sea', 'No', 0, 360, 499, 181, 252),
	array('Maldive Islands', 'Sea', 'No', 0, 110, 609, 63, 304),
	array('Indian Ocean', 'Sea', 'No', 0, 19, 768, 14, 444),
	array('Ceylon Sea', 'Sea', 'No', 0, 112, 736, 58, 415),
	array('Adaman Sea', 'Sea', 'No', 0, 200, 871, 101, 434),
	array('Bengali Sea', 'Sea', 'No', 0, 211, 792, 101, 397),
	array('Khmer Coast', 'Sea', 'No', 0, 157, 991, 78, 496),
	array('Borneo Bay', 'Sea', 'No', 7, 183, 1052, 93, 525),
	array('Mollacas Sea', 'Sea', 'No', 0, 266, 1223, 84, 642),
	array('Flores Sea', 'Sea', 'No', 7, 51, 1423, 27, 708),
	array('West Pacific Ocean', 'Sea', 'No', 0, 538, 1326, 176, 643),
	array('South Pacific Ocean', 'Sea', 'No', 0, 394, 1531, 115, 729),
	array('North China Sea', 'Sea', 'No', 0, 424, 1138, 211, 569),
	array('Palawan Strait', 'Sea', 'No', 0, 319, 1124, 153, 554),
	array('South China Sea', 'Sea', 'No', 0, 236, 1129, 116, 559),
	array('Sea of Nipon', 'Sea', 'No', 0, 493, 1252, 247, 629),
	array('North Pacific Ocean', 'Sea', 'No', 0, 853, 1510, 342, 748),
	array('Corean Sea', 'Sea', 'No', 0, 570, 1175, 292, 592),
	array('Yezo Sea', 'Sea', 'No', 0, 666, 1177, 334, 588),
	array('Sumatra Strait', 'Sea', 'No', 0, 90, 1004, 53, 502),
	array('Sindh (River Coast)', 'Coast', 'No', 3, 351, 636, 174, 315),
	array('Sindh (Sea Coast)', 'Coast', 'No', 3, 302, 571, 166, 285),
	array('Armenia (Sea Coast)', 'Coast', 'No', 5, 516, 491, 256, 248),
	array('Armenia (River Coast)', 'Coast', 'No', 5, 443, 543, 227, 271),
	array('Moldavia (Sea Coast)', 'Coast', 'No', 0, 707, 376, 355, 192),
	array('Moldavia (River Coast)', 'Coast', 'No', 0, 728, 430, 364, 212),
	array('Peking (Sea Coast)', 'Coast', 'No', 11, 501, 1054, 249, 527),
	array('Peking (River Coast)', 'Coast', 'No', 11, 491, 965, 248, 486),
	array('Annam (Sea Coast)', 'Coast', 'No', 0, 258, 1010, 128, 506),
	array('Annam (River Coast)', 'Coast', 'No', 0, 278, 975, 144, 484),
	array('Yupi (River Coast)', 'Coast', 'No', 9, 607, 1080, 285, 543),
	array('Novogorad (West Coast)', 'Coast', 'No', 4, 866, 539, 430, 263),
	array('Novogorad (East Coast)', 'Coast', 'No', 4, 833, 554, 415, 279)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('#1 Jerusalem','Central Mediterranean Sea','Yes','No'),
	array('#1 Jerusalem','Eastern Mediterranean Sea','Yes','No'),
	array('#1 Jerusalem','Eastern Byzantine','No','Yes'),
	array('#1 Jerusalem','Crusader States','Yes','Yes'),
	array('#1 Jerusalem','Seljuk','No','Yes'),
	array('#1 Jerusalem','Eastern Byzantine (South Coast)','Yes','No'),
	array('#2 Moscow','Muscovy','Yes','Yes'),
	array('#2 Moscow','Teutonic Order','Yes','Yes'),
	array('#2 Moscow','Poland','No','Yes'),
	array('#2 Moscow','Lithuania','No','Yes'),
	array('#3 Bagdhad','Choralan','Yes','Yes'),
	array('#3 Bagdhad','Armenia','No','Yes'),
	array('#3 Bagdhad','Zangid','No','Yes'),
	array('#3 Bagdhad','Abbasid','Yes','Yes'),
	array('#3 Bagdhad','Persian Gulf','Yes','No'),
	array('Yemen','Mecca','Yes','Yes'),
	array('Yemen','Red Sea','Yes','No'),
	array('Yemen','Arabian Sea','Yes','No'),
	array('Yemen','Abbasid','Yes','Yes'),
	array('#5 Khotum','Nagqu','No','Yes'),
	array('#5 Khotum','Ngari','No','Yes'),
	array('#5 Khotum','Pamir','No','Yes'),
	array('#5 Khotum','Khuram','No','Yes'),
	array('#5 Khotum','Hindhu Kush','No','Yes'),
	array('#6 Kandahar','Sindh','No','Yes'),
	array('#6 Kandahar','Nepal West','No','Yes'),
	array('#6 Kandahar','Malwa','Yes','Yes'),
	array('#6 Kandahar','Sindh (River Coast)','Yes','No'),
	array('Tugnusess','North Cathay','No','Yes'),
	array('Tugnusess','Tunguska','No','Yes'),
	array('Tugnusess','Vraye','No','Yes'),
	array('#8 Lhasar','Qamdo','No','Yes'),
	array('#8 Lhasar','Chamdo','No','Yes'),
	array('#8 Lhasar','Nagqu','No','Yes'),
	array('#8 Lhasar','Xigaze','No','Yes'),
	array('#8 Lhasar','Nyingchi','No','Yes'),
	array('#9 Si-Ning-Fu','Sanchi','No','Yes'),
	array('#9 Si-Ning-Fu','Carazan','No','Yes'),
	array('#9 Si-Ning-Fu','Qamdo','No','Yes'),
	array('#9 Si-Ning-Fu','Chamdo','No','Yes'),
	array('#10 Kharakorum','Naiman','No','Yes'),
	array('#10 Kharakorum','Xanadu','No','Yes'),
	array('#10 Kharakorum','Lop','No','Yes'),
	array('#11 Lo-Yang','Sanchi','Yes','Yes'),
	array('#11 Lo-Yang','Honao','Yes','Yes'),
	array('#11 Lo-Yang','Sinfai','Yes','Yes'),
	array('#11 Lo-Yang','Quan','Yes','Yes'),
	array('Morroco','Berber','No','Yes'),
	array('Morroco','Angola','Yes','Yes'),
	array('Morroco','African Coast','Yes','No'),
	array('Morroco','Western Mediterranean Sea','Yes','No'),
	array('Morroco','Spain','No','Yes'),
	array('Morroco','Spain (South Coast)','Yes','No'),
	array('Berber','Chadic','No','Yes'),
	array('Berber','Makura','No','Yes'),
	array('Berber','Angola','No','Yes'),
	array('Berber','Almohad','No','Yes'),
	array('Chadic','Axum','No','Yes'),
	array('Chadic','Makura','No','Yes'),
	array('Axum','Somalia','No','Yes'),
	array('Axum','Makura','No','Yes'),
	array('Somalia','Red Sea','Yes','No'),
	array('Somalia','Zanzibar Coast','Yes','No'),
	array('Somalia','Arabian Sea','Yes','No'),
	array('Somalia','Axum (South Coast)','Yes','No'),
	array('Somalia','Axum (North Coast)','Yes','No'),
	array('Makura','Almohad','No','Yes'),
	array('Makura','Ayyubid','Yes','Yes'),
	array('Makura','Red Sea','Yes','No'),
	array('Makura','Axum (North Coast)','Yes','No'),
	array('Angola','Almohad','Yes','Yes'),
	array('Angola','Western Mediterranean Sea','Yes','No'),
	array('Almohad','Ayyubid','Yes','Yes'),
	array('Almohad','Western Mediterranean Sea','Yes','No'),
	array('Almohad','Central Mediterranean Sea','Yes','No'),
	array('Almohad','Eastern Mediterranean Sea','Yes','No'),
	array('Ayyubid','Eastern Mediterranean Sea','Yes','No'),
	array('Ayyubid','Egypt','Yes','Yes'),
	array('Ayyubid','Red Sea','Yes','No'),
	array('African Coast','Western Mediterranean Sea','Yes','No'),
	array('African Coast','Portugal','Yes','No'),
	array('African Coast','North Sea','Yes','No'),
	array('African Coast','Spain (South Coast)','Yes','No'),
	array('Western Mediterranean Sea','Central Mediterranean Sea','Yes','No'),
	array('Western Mediterranean Sea','Papal States','Yes','No'),
	array('Western Mediterranean Sea','Spain (South Coast)','Yes','No'),
	array('Central Mediterranean Sea','Eastern Mediterranean Sea','Yes','No'),
	array('Central Mediterranean Sea','Constantinople','Yes','No'),
	array('Central Mediterranean Sea','Papal States','Yes','No'),
	array('Central Mediterranean Sea','Venice','Yes','No'),
	array('Central Mediterranean Sea','Hungary','Yes','No'),
	array('Central Mediterranean Sea','Western Byzantine (South Coast)','Yes','No'),
	array('Central Mediterranean Sea','Eastern Byzantine (South Coast)','Yes','No'),
	array('Eastern Mediterranean Sea','Crusader States','Yes','No'),
	array('Eastern Mediterranean Sea','Egypt','Yes','No'),
	array('Eastern Mediterranean Sea','Red Sea','Yes','No'),
	array('Constantinople','Western Byzantine','No','Yes'),
	array('Constantinople','Eastern Byzantine','No','Yes'),
	array('Constantinople','Black Sea','Yes','No'),
	array('Constantinople','Western Byzantine (South Coast)','Yes','No'),
	array('Constantinople','Western Byzantine (East Coast)','Yes','No'),
	array('Constantinople','Eastern Byzantine (North Coast)','Yes','No'),
	array('Constantinople','Eastern Byzantine (South Coast)','Yes','No'),
	array('Western Byzantine','Moldavia','No','Yes'),
	array('Western Byzantine','Hungary','No','Yes'),
	array('Western Byzantine','Lithuania','No','Yes'),
	array('Eastern Byzantine','Seljuk','No','Yes'),
	array('Eastern Byzantine','Zangid','No','Yes'),
	array('Eastern Byzantine','Diyarnakir','No','Yes'),
	array('Crusader States','Egypt','Yes','Yes'),
	array('Crusader States','Seljuk','No','Yes'),
	array('Egypt','Seljuk','No','Yes'),
	array('Egypt','Mecca','Yes','Yes'),
	array('Egypt','Red Sea','Yes','No'),
	array('Seljuk','Mecca','No','Yes'),
	array('Seljuk','Zangid','No','Yes'),
	array('Seljuk','Diyarnakir','No','Yes'),
	array('Seljuk','Abbasid','No','Yes'),
	array('Mecca','Red Sea','Yes','No'),
	array('Mecca','Abbasid','No','Yes'),
	array('Red Sea','Zanzibar Coast','Yes','No'),
	array('Red Sea','Arabian Sea','Yes','No'),
	array('Red Sea','Axum (North Coast)','Yes','No'),
	array('Red Sea','Chintapur Coast','Yes','No'),
	array('Red Sea','Maldive Islands','Yes','No'),
	array('Zanzibar Coast','Arabian Sea','Yes','No'),
	array('Zanzibar Coast','Axum (South Coast)','Yes','No'),
	array('Zanzibar Coast','Chintapur Coast','Yes','No'),
	array('Zanzibar Coast','Maldive Islands','Yes','No'),
	array('Zanzibar Coast','Indian Ocean','Yes','No'),
	array('Arabian Sea','Abbasid','Yes','No'),
	array('Arabian Sea','Chintapur Coast','Yes','No'),
	array('Arabian Sea','Persian Gulf','Yes','No'),
	array('Arabian Sea','Maldive Islands','Yes','No'),
	array('Arabian Sea','Indian Ocean','Yes','No'),
	array('Arabian Sea','Ceylon Sea','Yes','No'),
	array('Portugal','Spain','No','Yes'),
	array('Portugal','North Sea','Yes','No'),
	array('Portugal','Spain (North Coast)','Yes','No'),
	array('Portugal','Spain (South Coast)','Yes','No'),
	array('Spain','Papal States','No','Yes'),
	array('Spain','Holy Roman Empire','No','Yes'),
	array('Papal States','Holy Roman Empire','No','Yes'),
	array('Papal States','Venice','Yes','Yes'),
	array('Papal States','Spain (South Coast)','Yes','No'),
	array('Holy Roman Empire','Albion','Yes','Yes'),
	array('Holy Roman Empire','North Sea','Yes','No'),
	array('Holy Roman Empire','The Danes','Yes','Yes'),
	array('Holy Roman Empire','Venice','No','Yes'),
	array('Holy Roman Empire','Poland','No','Yes'),
	array('Holy Roman Empire','Spain (North Coast)','Yes','No'),
	array('Albion','North Sea','Yes','No'),
	array('Albion','Norsk Territories','Yes','Yes'),
	array('North Sea','The Danes','Yes','No'),
	array('North Sea','Norsk Territories','Yes','No'),
	array('North Sea','Baltic Sea','Yes','No'),
	array('North Sea','Pitzorke Sea','Yes','No'),
	array('North Sea','Spain (North Coast)','Yes','No'),
	array('The Danes','Baltic Sea','Yes','No'),
	array('The Danes','Poland','Yes','Yes'),
	array('Norsk Territories','Baltic Sea','Yes','No'),
	array('Norsk Territories','Novogorad','No','Yes'),
	array('Norsk Territories','Pitzorke Sea','Yes','No'),
	array('Norsk Territories','Bjarmaland','Yes','Yes'),
	array('Norsk Territories','Novogorad (West Coast)','Yes','No'),
	array('Norsk Territories','Novogorad (East Coast)','Yes','No'),
	array('Choralan','Armenia','No','Yes'),
	array('Choralan','Siestan','Yes','Yes'),
	array('Choralan','Persian Gulf','Yes','No'),
	array('Choralan','Armenia (River Coast)','Yes','No'),
	array('Armenia','Urgent','No','Yes'),
	array('Armenia','Kiva','No','Yes'),
	array('Armenia','Merv','No','Yes'),
	array('Armenia','Zangid','No','Yes'),
	array('Armenia','Diyarnakir','No','Yes'),
	array('Armenia','Herat','No','Yes'),
	array('Armenia','Khuram','No','Yes'),
	array('Armenia','Siestan','No','Yes'),
	array('Sevast Politi','Cumanis','Yes','Yes'),
	array('Sevast Politi','Caucasus','Yes','Yes'),
	array('Sevast Politi','Moldavia','No','Yes'),
	array('Sevast Politi','Black Sea','Yes','No'),
	array('Sevast Politi','Moldavia (Sea Coast)','Yes','No'),
	array('Sevast Politi','Moldavia (River Coast)','Yes','No'),
	array('Cumanis','Bashkir','No','Yes'),
	array('Cumanis','Kiva','Yes','Yes'),
	array('Cumanis','Caucasus','Yes','Yes'),
	array('Cumanis','Muscovy','Yes','Yes'),
	array('Cumanis','Moldavia','No','Yes'),
	array('Cumanis','Novogorad','No','Yes'),
	array('Cumanis','Bulgars','Yes','Yes'),
	array('Cumanis','Caspian Sea','Yes','No'),
	array('Cumanis','Moldavia (River Coast)','Yes','No'),
	array('Bashkir','Urgrian','No','Yes'),
	array('Bashkir','Kiva','No','Yes'),
	array('Bashkir','Merv','No','Yes'),
	array('Bashkir','Novogorad','No','Yes'),
	array('Bashkir','Tashkent','No','Yes'),
	array('Sindh','Nepal West','No','Yes'),
	array('Sindh','Malwa','No','Yes'),
	array('Sindh','Kamataka','No','Yes'),
	array('Sindh','Siestan','No','Yes'),
	array('Sindh','Bakkar','No','Yes'),
	array('Sindh','Hindhu Kush','No','Yes'),
	array('Urgent','#4 Samarkand','No','Yes'),
	array('Urgent','Kiva','No','Yes'),
	array('Urgent','Merv','No','Yes'),
	array('Urgent','Tashkent','No','Yes'),
	array('Urgent','Kudchan','No','Yes'),
	array('Urgent','Naiman','No','Yes'),
	array('Urgent','Furghana','No','Yes'),
	array('Urgent','Khuram','No','Yes'),
	array('Urgrian','Novogorad','No','Yes'),
	array('Urgrian','Pitzorke Sea','Yes','No'),
	array('Urgrian','Samoyedes','Yes','Yes'),
	array('Urgrian','Tunguska','Yes','Yes'),
	array('Urgrian','Bjarmaland','Yes','Yes'),
	array('Urgrian','Tashkent','No','Yes'),
	array('#4 Samarkand','Kiva','No','Yes'),
	array('#4 Samarkand','Merv','No','Yes'),
	array('#4 Samarkand','Tashkent','No','Yes'),
	array('Kiva','Merv','No','Yes'),
	array('Kiva','Samoyedes','No','Yes'),
	array('Kiva','Caspian Sea','Yes','No'),
	array('Kiva','Tashkent','No','Yes'),
	array('Kiva','Armenia (Sea Coast)','Yes','No'),
	array('Merv','Tashkent','No','Yes'),
	array('Merv','Furghana','No','Yes'),
	array('Merv','Khuram','No','Yes'),
	array('Zangid','Diyarnakir','No','Yes'),
	array('Zangid','Abbasid','No','Yes'),
	array('Zangid','Khuram','No','Yes'),
	array('Diyarnakir','Georgia','Yes','Yes'),
	array('Diyarnakir','Caspian Sea','Yes','No'),
	array('Diyarnakir','Armenia (Sea Coast)','Yes','No'),
	array('Georgia','Caucasus','Yes','Yes'),
	array('Georgia','Black Sea','Yes','No'),
	array('Georgia','Caspian Sea','Yes','No'),
	array('Caucasus','Black Sea','Yes','No'),
	array('Caucasus','Caspian Sea','Yes','No'),
	array('Muscovy','Moldavia','No','Yes'),
	array('Muscovy','Teutonic Order','No','Yes'),
	array('Muscovy','Riga','No','Yes'),
	array('Muscovy','Lithuania','No','Yes'),
	array('Muscovy','Bulgars','Yes','Yes'),
	array('Muscovy','Moldavia (River Coast)','Yes','No'),
	array('Moldavia','Lithuania','No','Yes'),
	array('Teutonic Order','Baltic Sea','Yes','No'),
	array('Teutonic Order','Riga','Yes','Yes'),
	array('Teutonic Order','Poland','Yes','Yes'),
	array('Baltic Sea','Riga','Yes','No'),
	array('Baltic Sea','Poland','Yes','No'),
	array('Baltic Sea','Novogorad (West Coast)','Yes','No'),
	array('Riga','Novogorad','No','Yes'),
	array('Riga','Bulgars','No','Yes'),
	array('Riga','Novogorad (West Coast)','Yes','No'),
	array('Venice','Hungary','Yes','Yes'),
	array('Venice','Poland','No','Yes'),
	array('Hungary','Poland','No','Yes'),
	array('Hungary','Lithuania','No','Yes'),
	array('Hungary','Western Byzantine (South Coast)','Yes','No'),
	array('Poland','Lithuania','No','Yes'),
	array('Novogorad','Bulgars','No','Yes'),
	array('Novogorad','Bjarmaland','No','Yes'),
	array('Pitzorke Sea','Septentrional Ocean','Yes','No'),
	array('Pitzorke Sea','Tunguska','Yes','No'),
	array('Pitzorke Sea','Bjarmaland','Yes','No'),
	array('Pitzorke Sea','Novogorad (East Coast)','Yes','No'),
	array('Septentrional Ocean','Aniafret Sea','Yes','No'),
	array('Septentrional Ocean','Tunguska','Yes','No'),
	array('Septentrional Ocean','Tugnusess (West Coast)','Yes','No'),
	array('Aniafret Sea','Waters of Cathay','Yes','No'),
	array('Aniafret Sea','Tugnusess (East Coast)','Yes','No'),
	array('Aniafret Sea','West Pacific Ocean','Yes','No'),
	array('Aniafret Sea','North Pacific Ocean','Yes','No'),
	array('Aniafret Sea','Yezo Sea','Yes','No'),
	array('North Cathay','South Cathay','Yes','Yes'),
	array('North Cathay','Vraye','No','Yes'),
	array('North Cathay','Bargul','No','Yes'),
	array('North Cathay','Stingui','Yes','Yes'),
	array('North Cathay','Curguth','Yes','Yes'),
	array('North Cathay','Waters of Cathay','Yes','No'),
	array('North Cathay','Tugnusess (East Coast)','Yes','No'),
	array('North Cathay','Serra','Yes','No'),
	array('Samoyedes','Tunguska','Yes','Yes'),
	array('Samoyedes','Tashkent','No','Yes'),
	array('Samoyedes','#7 Almalik','No','Yes'),
	array('Samoyedes','Vraye','No','Yes'),
	array('Samoyedes','Naiman','No','Yes'),
	array('Samoyedes','Xanadu','No','Yes'),
	array('Samoyedes','Carazan','No','Yes'),
	array('Samoyedes','Furghana','No','Yes'),
	array('Tunguska','Vraye','No','Yes'),
	array('Tunguska','Tugnusess (West Coast)','Yes','No'),
	array('Bjarmaland','Novogorad (East Coast)','Yes','No'),
	array('South Cathay','Sungar','Yes','Yes'),
	array('South Cathay','Waters of Cathay','Yes','No'),
	array('South Cathay','Serra','Yes','Yes'),
	array('Sungar','Waters of Cathay','Yes','No'),
	array('Sungar','Yupi','No','Yes'),
	array('Sungar','Yupi (East Coast)','Yes','No'),
	array('Sungar','Serra','No','Yes'),
	array('Sungar','Corean Sea','Yes','No'),
	array('Sungar','Yezo Sea','Yes','No'),
	array('Black Sea','Western Byzantine (East Coast)','Yes','No'),
	array('Black Sea','Eastern Byzantine (North Coast)','Yes','No'),
	array('Black Sea','Moldavia (Sea Coast)','Yes','No'),
	array('Caspian Sea','Armenia (Sea Coast)','Yes','No'),
	array('Abbasid','Persian Gulf','Yes','No'),
	array('Tashkent','Kudchan','No','Yes'),
	array('Tashkent','#7 Almalik','No','Yes'),
	array('Tashkent','Naiman','No','Yes'),
	array('Kudchan','#7 Almalik','No','Yes'),
	array('Kudchan','Naiman','No','Yes'),
	array('#7 Almalik','Naiman','No','Yes'),
	array('Vraye','Xanadu','No','Yes'),
	array('Vraye','Bargul','No','Yes'),
	array('Kyoto Prefecture West','Kyoto','Yes','Yes'),
	array('Kyoto Prefecture West','#14 Yedo','Yes','Yes'),
	array('Kyoto Prefecture West','Corean Sea','Yes','No'),
	array('Kyoto','Kyoto Prefecture East','Yes','Yes'),
	array('Kyoto','North China Sea','Yes','No'),
	array('Kyoto','Sea of Nipon','Yes','No'),
	array('Kyoto','Corean Sea','Yes','No'),
	array('#14 Yedo','Yedo Prefecture','Yes','Yes'),
	array('#14 Yedo','Kyoto Prefecture East','Yes','Yes'),
	array('#14 Yedo','West Pacific Ocean','Yes','No'),
	array('#14 Yedo','Sea of Nipon','Yes','No'),
	array('#14 Yedo','Corean Sea','Yes','No'),
	array('#14 Yedo','Yezo Sea','Yes','No'),
	array('Yedo Prefecture','West Pacific Ocean','Yes','No'),
	array('Yedo Prefecture','Yezo Sea','Yes','No'),
	array('Naiman','Xanadu','No','Yes'),
	array('Naiman','Bargul','No','Yes'),
	array('Naiman','Sanchi','No','Yes'),
	array('Naiman','Carazan','No','Yes'),
	array('Naiman','Lop','No','Yes'),
	array('Naiman','Yarkand','No','Yes'),
	array('Naiman','Furghana','No','Yes'),
	array('Naiman','Khuram','No','Yes'),
	array('Xanadu','Bargul','No','Yes'),
	array('Xanadu','Stingui','No','Yes'),
	array('Xanadu','Carazan','No','Yes'),
	array('Xanadu','Lop','No','Yes'),
	array('Xanadu','Furghana','No','Yes'),
	array('Stingui','Curguth','Yes','Yes'),
	array('Stingui','Lop','No','Yes'),
	array('Stingui','Kilango','No','Yes'),
	array('Curguth','Kilango','No','Yes'),
	array('Curguth','Serra','Yes','Yes'),
	array('Kyoto Prefecture East','Sea of Nipon','Yes','No'),
	array('Guam','Mollacas Sea','Yes','No'),
	array('Guam','West Pacific Ocean','Yes','No'),
	array('Waters of Cathay','Tugnusess (East Coast)','Yes','No'),
	array('Waters of Cathay','Yezo Sea','Yes','No'),
	array('Xiam','Sanchi','Yes','Yes'),
	array('Xiam','Honao','Yes','No'),
	array('Xiam','Lop','No','Yes'),
	array('Xiam','Peking','No','Yes'),
	array('Xiam','Peking (River Coast)','Yes','No'),
	array('Sanchi','Honao','Yes','Yes'),
	array('Sanchi','Carazan','No','Yes'),
	array('Sanchi','Quan','Yes','No'),
	array('Sanchi','Nan Chao','No','Yes'),
	array('Sanchi','Hanoi','Yes','Yes'),
	array('Honao','Sinfai','Yes','Yes'),
	array('Honao','Xanton','Yes','Yes'),
	array('Honao','Peking','No','Yes'),
	array('Honao','Peking (River Coast)','Yes','No'),
	array('Sinfai','Fokien','No','Yes'),
	array('Sinfai','Xanton','Yes','No'),
	array('Sinfai','Nanqi','Yes','Yes'),
	array('Sinfai','Quan','No','Yes'),
	array('Fokien','Nanqi','Yes','Yes'),
	array('Fokien','Quan','Yes','Yes'),
	array('Fokien','Hanoi','Yes','No'),
	array('Fokien','Palawan Strait','Yes','No'),
	array('Fokien','South China Sea','Yes','No'),
	array('Xanton','Nanqi','Yes','Yes'),
	array('Xanton','Peking','No','Yes'),
	array('Nanqi','Peking','No','Yes'),
	array('Nanqi','North China Sea','Yes','No'),
	array('Nanqi','Palawan Strait','Yes','No'),
	array('Nanqi','Peking (Sea Coast)','Yes','No'),
	array('Carazan','Lop','No','Yes'),
	array('Carazan','Furghana','No','Yes'),
	array('Lop','Kilango','No','Yes'),
	array('Qamdo','Chamdo','No','Yes'),
	array('Qamdo','Nagqu','No','Yes'),
	array('Chamdo','Nyingchi','No','Yes'),
	array('Nagqu','Ngari','No','Yes'),
	array('Nagqu','Xigaze','No','Yes'),
	array('Nagqu','Pamir','No','Yes'),
	array('Ngari','Xigaze','No','Yes'),
	array('Xigaze','Nyingchi','No','Yes'),
	array('Xigaze','Nepal West','No','Yes'),
	array('Nyingchi','Bhutan','No','Yes'),
	array('Nyingchi','Nepal East','No','Yes'),
	array('Western Byzantine (East Coast)','Moldavia (Sea Coast)','Yes','No'),
	array('Yupi','Corea','No','Yes'),
	array('Yupi','Leaotung','No','Yes'),
	array('Yupi','Serra','No','Yes'),
	array('Yupi (East Coast)','Corea','Yes','No'),
	array('Yupi (East Coast)','Corean Sea','Yes','No'),
	array('Yupi (South Coast)','Corea','Yes','No'),
	array('Yupi (South Coast)','Leaotung','Yes','No'),
	array('Yupi (South Coast)','North China Sea','Yes','No'),
	array('Peking','Kilango','No','Yes'),
	array('Peking','Leaotung','No','Yes'),
	array('Corea','North China Sea','Yes','No'),
	array('Corea','Corean Sea','Yes','No'),
	array('Kilango','Leaotung','No','Yes'),
	array('Kilango','Serra','No','Yes'),
	array('Leaotung','Serra','No','Yes'),
	array('Leaotung','North China Sea','Yes','No'),
	array('Leaotung','Peking (Sea Coast)','Yes','No'),
	array('Serra','Yupi (River Coast)','Yes','No'),
	array('Quan','Hanoi','Yes','Yes'),
	array('Yarkand','Furghana','No','Yes'),
	array('Yarkand','Pamir','No','Yes'),
	array('Furghana','Pamir','No','Yes'),
	array('Furghana','Khuram','No','Yes'),
	array('Furghana','Hindhu Kush','No','Yes'),
	array('Pamir','Khuram','No','Yes'),
	array('Herat','Khuram','No','Yes'),
	array('Herat','Siestan','Yes','Yes'),
	array('Herat','Bakkar','Yes','Yes'),
	array('Herat','Hindhu Kush','Yes','Yes'),
	array('Herat','Armenia (River Coast)','Yes','No'),
	array('Khuram','Nepal West','No','Yes'),
	array('Khuram','Hindhu Kush','No','Yes'),
	array('Java Isles','Sumatra','Yes','Yes'),
	array('Java Isles','Indian Ocean','Yes','No'),
	array('Java Isles','Flores Sea','Yes','No'),
	array('Java Isles','Sumatra Strait','Yes','No'),
	array('Borneo','Sarawak','Yes','Yes'),
	array('Borneo','Borneo Bay','Yes','No'),
	array('Borneo','Flores Sea','Yes','No'),
	array('Borneo','South China Sea','Yes','No'),
	array('Borneo','Sumatra Strait','Yes','No'),
	array('Sarawak','Mollacas Sea','Yes','No'),
	array('Sarawak','Flores Sea','Yes','No'),
	array('Sarawak','South China Sea','Yes','No'),
	array('Makkassar','Mollacas Sea','Yes','No'),
	array('Makkassar','Flores Sea','Yes','No'),
	array('Luzon','Mollacas Sea','Yes','No'),
	array('Luzon','Palawan Strait','Yes','No'),
	array('Luzon','South China Sea','Yes','No'),
	array('Taiwan','North China Sea','Yes','No'),
	array('Taiwan','Palawan Strait','Yes','No'),
	array('Sumatra','Malaya','Yes','Yes'),
	array('Sumatra','Indian Ocean','Yes','No'),
	array('Sumatra','Ceylon Sea','Yes','No'),
	array('Sumatra','Sumatra Strait','Yes','No'),
	array('Malaya','Siam','No','Yes'),
	array('Malaya','Siam (West Coast)','Yes','No'),
	array('Malaya','Siam (East Coast)','Yes','No'),
	array('Malaya','Ceylon Sea','Yes','No'),
	array('Malaya','Adaman Sea','Yes','No'),
	array('Malaya','Khmer Coast','Yes','No'),
	array('Malaya','Borneo Bay','Yes','No'),
	array('Malaya','Sumatra Strait','Yes','No'),
	array('Siam','Khmer','No','Yes'),
	array('Siam','Pegu','No','Yes'),
	array('Siam','Lower Pagan','No','Yes'),
	array('Siam','Upper Pagan','No','Yes'),
	array('Siam','Bhutan','No','Yes'),
	array('Siam (West Coast)','Lower Pagan','Yes','No'),
	array('Siam (West Coast)','Adaman Sea','Yes','No'),
	array('Siam (East Coast)','Khmer','Yes','No'),
	array('Siam (East Coast)','Khmer Coast','Yes','No'),
	array('#13 Angkor','Champa','Yes','Yes'),
	array('#13 Angkor','Khmer','Yes','Yes'),
	array('#13 Angkor','Annam','No','Yes'),
	array('#13 Angkor','Annam (River Coast)','Yes','No'),
	array('Champa','Khmer','Yes','Yes'),
	array('Champa','Annam','No','Yes'),
	array('Champa','Khmer Coast','Yes','No'),
	array('Champa','Borneo Bay','Yes','No'),
	array('Champa','South China Sea','Yes','No'),
	array('Champa','Annam (Sea Coast)','Yes','No'),
	array('Champa','Annam (River Coast)','Yes','No'),
	array('Khmer','Pegu','Yes','Yes'),
	array('Khmer','Khmer Coast','Yes','No'),
	array('Khmer','Annam (River Coast)','Yes','No'),
	array('Annam','Laos','No','Yes'),
	array('Annam','Hanoi','No','Yes'),
	array('Laos','Pegu','Yes','Yes'),
	array('Laos','Nan Chao','Yes','Yes'),
	array('Laos','Hanoi','No','Yes'),
	array('Laos','Annam (River Coast)','Yes','No'),
	array('Pegu','#12 Kainan','Yes','Yes'),
	array('Pegu','Bhutan','No','Yes'),
	array('Pegu','Nan Chao','Yes','No'),
	array('Pegu','Annam (River Coast)','Yes','No'),
	array('Lower Pagan','Upper Pagan','Yes','Yes'),
	array('Lower Pagan','Adaman Sea','Yes','No'),
	array('Upper Pagan','Bhutan','No','Yes'),
	array('Upper Pagan','Bengal','Yes','Yes'),
	array('Upper Pagan','Nepal East','No','Yes'),
	array('Upper Pagan','Adaman Sea','Yes','No'),
	array('Upper Pagan','Bengali Sea','Yes','No'),
	array('#12 Kainan','Bhutan','Yes','Yes'),
	array('#12 Kainan','Nan Chao','Yes','Yes'),
	array('Bhutan','Nan Chao','Yes','Yes'),
	array('Bhutan','Nepal East','No','Yes'),
	array('Nan Chao','Hanoi','No','Yes'),
	array('Hanoi','South China Sea','Yes','No'),
	array('Hanoi','Annam (Sea Coast)','Yes','No'),
	array('Bengal','Nepal East','No','Yes'),
	array('Bengal','Nepal West','No','Yes'),
	array('Bengal','Malwa','Yes','Yes'),
	array('Bengal','Chola','Yes','Yes'),
	array('Bengal','Bengali Sea','Yes','No'),
	array('Nepal East','Nepal West','No','Yes'),
	array('Nepal East','Malwa','No','Yes'),
	array('Nepal West','Malwa','No','Yes'),
	array('Nepal West','Hindhu Kush','No','Yes'),
	array('Malwa','Chola','No','Yes'),
	array('Malwa','Karala','No','Yes'),
	array('Malwa','Kamataka','No','Yes'),
	array('Chola','Karala','Yes','Yes'),
	array('Chola','Ceylon','Yes','Yes'),
	array('Chola','Maldive Islands','Yes','No'),
	array('Chola','Bengali Sea','Yes','No'),
	array('Karala','Kamataka','Yes','Yes'),
	array('Karala','Maldive Islands','Yes','No'),
	array('Ceylon','Maldive Islands','Yes','No'),
	array('Ceylon','Ceylon Sea','Yes','No'),
	array('Kamataka','Chintapur Coast','Yes','No'),
	array('Kamataka','Maldive Islands','Yes','No'),
	array('Kamataka','Sindh (Sea Coast)','Yes','No'),
	array('Siestan','Bakkar','Yes','Yes'),
	array('Siestan','Chintapur Coast','Yes','No'),
	array('Siestan','Persian Gulf','Yes','No'),
	array('Siestan','Sindh (Sea Coast)','Yes','No'),
	array('Siestan','Armenia (River Coast)','Yes','No'),
	array('Bakkar','Hindhu Kush','Yes','Yes'),
	array('Bakkar','Sindh (River Coast)','Yes','No'),
	array('Chintapur Coast','Persian Gulf','Yes','No'),
	array('Chintapur Coast','Maldive Islands','Yes','No'),
	array('Chintapur Coast','Ceylon Sea','Yes','No'),
	array('Chintapur Coast','Sindh (Sea Coast)','Yes','No'),
	array('Maldive Islands','Indian Ocean','Yes','No'),
	array('Maldive Islands','Ceylon Sea','Yes','No'),
	array('Maldive Islands','Adaman Sea','Yes','No'),
	array('Maldive Islands','Bengali Sea','Yes','No'),
	array('Indian Ocean','Ceylon Sea','Yes','No'),
	array('Indian Ocean','Flores Sea','Yes','No'),
	array('Indian Ocean','Sumatra Strait','Yes','No'),
	array('Ceylon Sea','Adaman Sea','Yes','No'),
	array('Ceylon Sea','Bengali Sea','Yes','No'),
	array('Ceylon Sea','Sumatra Strait','Yes','No'),
	array('Adaman Sea','Bengali Sea','Yes','No'),
	array('Khmer Coast','Borneo Bay','Yes','No'),
	array('Borneo Bay','South China Sea','Yes','No'),
	array('Borneo Bay','Sumatra Strait','Yes','No'),
	array('Mollacas Sea','Flores Sea','Yes','No'),
	array('Mollacas Sea','West Pacific Ocean','Yes','No'),
	array('Mollacas Sea','South Pacific Ocean','Yes','No'),
	array('Mollacas Sea','Palawan Strait','Yes','No'),
	array('Mollacas Sea','South China Sea','Yes','No'),
	array('Flores Sea','South Pacific Ocean','Yes','No'),
	array('Flores Sea','Sumatra Strait','Yes','No'),
	array('West Pacific Ocean','South Pacific Ocean','Yes','No'),
	array('West Pacific Ocean','Palawan Strait','Yes','No'),
	array('West Pacific Ocean','Sea of Nipon','Yes','No'),
	array('West Pacific Ocean','North Pacific Ocean','Yes','No'),
	array('West Pacific Ocean','Yezo Sea','Yes','No'),
	array('South Pacific Ocean','North Pacific Ocean','Yes','No'),
	array('North China Sea','Palawan Strait','Yes','No'),
	array('North China Sea','Sea of Nipon','Yes','No'),
	array('North China Sea','Corean Sea','Yes','No'),
	array('North China Sea','Peking (Sea Coast)','Yes','No'),
	array('Palawan Strait','South China Sea','Yes','No'),
	array('Palawan Strait','Sea of Nipon','Yes','No'),
	array('South China Sea','Annam (Sea Coast)','Yes','No'),
	array('Corean Sea','Yezo Sea','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
