<?php
// This is file installs the map data for the Scottish_Clan_Wars variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Eyemouth', 'Coast', 'Yes', 0, 1088, 1086, 553, 541),
	array('Dunbar', 'Coast', 'Yes', 1, 1006, 1027, 503, 514),
	array('Edinburgh', 'Coast', 'Yes', 1, 903, 1050, 451, 527),
	array('Falkirk', 'Land', 'No', 1, 849, 1040, 429, 523),
	array('Peebles', 'Land', 'No', 0, 891, 1117, 447, 561),
	array('Douglas', 'Land', 'Yes', 0, 834, 1153, 419, 575),
	array('Langholm', 'Land', 'No', 0, 951, 1233, 473, 621),
	array('Dumfries', 'Coast', 'No', 0, 764, 1400, 377, 703),
	array('Portpatrick', 'Coast', 'Yes', 0, 563, 1411, 291, 689),
	array('Girvan', 'Coast', 'No', 0, 588, 1319, 298, 660),
	array('Ayr', 'Coast', 'No', 0, 651, 1211, 324, 606),
	array('Isle of Arran', 'Coast', 'Yes', 0, 516, 1122, 260, 563),
	array('Kilmarnock', 'Coast', 'No', 2, 671, 1136, 336, 564),
	array('Largs', 'Coast', 'Yes', 2, 620, 1103, 313, 552),
	array('Glasgow', 'Land', 'Yes', 2, 728, 1079, 363, 553),
	array('Hamilton', 'Land', 'No', 2, 754, 1120, 379, 558),
	array('Dumbarton', 'Coast', 'Yes', 2, 652, 1016, 341, 507),
	array('Paisley', 'Coast', 'No', 2, 605, 1039, 304, 523),
	array('Stirling', 'Land', 'Yes', 0, 806, 1033, 403, 516),
	array('Kirkcaldy', 'Coast', 'Yes', 1, 890, 989, 445, 481),
	array('St. Andrews', 'Coast', 'Yes', 3, 1028, 933, 488, 454),
	array('Dundee', 'Coast', 'Yes', 3, 1023, 849, 510, 425),
	array('Arbroath', 'Coast', 'Yes', 3, 1043, 793, 521, 400),
	array('Forfar', 'Land', 'Yes', 3, 978, 726, 486, 367),
	array('Banchory', 'Coast', 'No', 4, 1064, 712, 536, 356),
	array('Montrose', 'Coast', 'No', 3, 1084, 752, 536, 383),
	array('North Sea', 'Sea', 'No', 0, 1256, 941, 629, 465),
	array('Inner North Sea', 'Sea', 'No', 0, 1152, 932, 562, 434),
	array('Firth of Tay', 'Sea', 'No', 0, 1075, 938, 522, 449),
	array('Firth of Forth', 'Sea', 'No', 0, 949, 1018, 506, 494),
	array('Banchory Coast', 'Sea', 'No', 0, 1161, 700, 578, 383),
	array('Shotts', 'Land', 'No', 2, 777, 1067, 398, 552),
	array('Angus', 'Land', 'No', 0, 892, 752, 458, 409),
	array('Pitlochry', 'Land', 'Yes', 0, 828, 803, 423, 398),
	array('Perth', 'Land', 'No', 0, 874, 872, 436, 456),
	array('Trossachs', 'Land', 'No', 0, 754, 953, 361, 467),
	array('Helensburgh', 'Coast', 'No', 0, 616, 996, 311, 499),
	array('Tighnabruaich', 'Coast', 'No', 0, 530, 1039, 262, 508),
	array('Argyll', 'Land', 'No', 0, 533, 924, 291, 427),
	array('Crieff', 'Land', 'Yes', 0, 760, 887, 383, 447),
	array('Cairngorms', 'Land', 'No', 0, 699, 686, 355, 347),
	array('Ben Nevis', 'Coast', 'Yes', 0, 541, 829, 261, 415),
	array('Invermark Castle', 'Land', 'Yes', 0, 912, 646, 455, 323),
	array('Aviemore', 'Land', 'No', 0, 808, 652, 409, 317),
	array('Dufftown', 'Land', 'Yes', 4, 929, 537, 461, 281),
	array('Insch', 'Land', 'No', 4, 1032, 528, 513, 265),
	array('Aberdeen', 'Coast', 'Yes', 4, 1124, 599, 560, 302),
	array('Peterhead', 'Coast', 'Yes', 4, 1130, 459, 565, 227),
	array('Moray', 'Coast', 'No', 0, 912, 437, 453, 223),
	array('Loch Ness', 'Coast', 'Yes', 0, 685, 520, 345, 261),
	array('Inverness', 'Coast', 'Yes', 0, 697, 439, 375, 225),
	array('Sutherland', 'Coast', 'No', 0, 654, 242, 327, 119),
	array('Sutherland (North Coast)', 'Coast', 'No', 0, 591, 179, 299, 97),
	array('Sutherland (South Coast)', 'Coast', 'No', 0, 765, 351, 385, 175),
	array('John o Groats', 'Coast', 'Yes', 5, 920, 136, 445, 73),
	array('Orkney', 'Coast', 'Yes', 5, 1094, 138, 549, 69),
	array('Isle of Harris', 'Coast', 'Yes', 6, 292, 222, 153, 103),
	array('Ullapool', 'Coast', 'Yes', 0, 519, 411, 257, 197),
	array('Isle of Skye', 'Coast', 'No', 0, 344, 540, 179, 273),
	array('Uist Isles', 'Coast', 'Yes', 6, 138, 548, 79, 211),
	array('Fort William', 'Coast', 'No', 0, 456, 746, 231, 377),
	array('Isle of Mull', 'Coast', 'Yes', 0, 367, 823, 183, 412),
	array('Oban', 'Coast', 'No', 0, 490, 884, 238, 451),
	array('Islay', 'Coast', 'Yes', 7, 341, 1096, 173, 529),
	array('Campbeltown', 'Coast', 'Yes', 7, 449, 1156, 225, 575),
	array('Kilmartin', 'Coast', 'Yes', 7, 484, 967, 249, 475),
	array('Rattray Coast', 'Sea', 'No', 0, 1241, 511, 623, 245),
	array('Spey Bay', 'Sea', 'No', 0, 1049, 396, 521, 193),
	array('Moray Firth', 'Sea', 'No', 0, 883, 368, 441, 183),
	array('Orkney Coast', 'Sea', 'No', 0, 1221, 262, 609, 125),
	array('The North Sound', 'Sea', 'No', 0, 1035, 90, 503, 49),
	array('Cape Wrath', 'Sea', 'No', 0, 737, 81, 369, 35),
	array('The Minch', 'Sea', 'No', 0, 464, 256, 229, 123),
	array('North Atlantic Ocean', 'Sea', 'No', 0, 158, 164, 63, 65),
	array('Sound of Monach', 'Sea', 'No', 0, 60, 520, 17, 241),
	array('The Little Minch', 'Sea', 'No', 0, 264, 411, 135, 203),
	array('Cuillin Sound', 'Sea', 'No', 0, 204, 743, 93, 365),
	array('South Atlantic Ocean', 'Sea', 'No', 0, 89, 1176, 41, 513),
	array('Firth of Lorn', 'Sea', 'No', 0, 261, 1018, 125, 495),
	array('Loch Linnhe', 'Sea', 'No', 0, 410, 944, 217, 451),
	array('North Channel', 'Sea', 'No', 0, 355, 1211, 179, 609),
	array('Firth of Doon', 'Sea', 'No', 0, 507, 1251, 253, 629),
	array('Solway Firth', 'Sea', 'No', 0, 473, 1471, 203, 693),
	array('Firth of Clyde', 'Sea', 'No', 0, 522, 1087, 277, 557),
	array('Kilmartin (North Coast)', 'Coast', 'No', 7, 470, 953, 244, 474),
	array('Kilmartin (South Coast)', 'Coast', 'No', 7, 482, 1010, 244, 494)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Eyemouth','Dunbar','Yes','Yes'),
	array('Eyemouth','Edinburgh','No','Yes'),
	array('Eyemouth','Peebles','No','Yes'),
	array('Eyemouth','Langholm','No','Yes'),
	array('Eyemouth','North Sea','Yes','No'),
	array('Eyemouth','Inner North Sea','Yes','No'),
	array('Dunbar','Edinburgh','Yes','Yes'),
	array('Dunbar','Inner North Sea','Yes','No'),
	array('Dunbar','Firth of Forth','Yes','No'),
	array('Edinburgh','Falkirk','No','Yes'),
	array('Edinburgh','Peebles','No','Yes'),
	array('Edinburgh','Kirkcaldy','Yes','Yes'),
	array('Edinburgh','Firth of Forth','Yes','No'),
	array('Falkirk','Peebles','No','Yes'),
	array('Falkirk','Douglas','No','Yes'),
	array('Falkirk','Stirling','No','Yes'),
	array('Falkirk','Kirkcaldy','No','Yes'),
	array('Falkirk','Shotts','No','Yes'),
	array('Peebles','Douglas','No','Yes'),
	array('Peebles','Langholm','No','Yes'),
	array('Douglas','Langholm','No','Yes'),
	array('Douglas','Dumfries','No','Yes'),
	array('Douglas','Ayr','No','Yes'),
	array('Douglas','Hamilton','No','Yes'),
	array('Douglas','Shotts','No','Yes'),
	array('Langholm','Dumfries','No','Yes'),
	array('Dumfries','Portpatrick','Yes','Yes'),
	array('Dumfries','Ayr','No','Yes'),
	array('Dumfries','Solway Firth','Yes','No'),
	array('Portpatrick','Girvan','Yes','Yes'),
	array('Portpatrick','Firth of Doon','Yes','No'),
	array('Portpatrick','Solway Firth','Yes','No'),
	array('Girvan','Ayr','Yes','Yes'),
	array('Girvan','Firth of Doon','Yes','No'),
	array('Ayr','Kilmarnock','Yes','Yes'),
	array('Ayr','Hamilton','No','Yes'),
	array('Ayr','Firth of Doon','Yes','No'),
	array('Isle of Arran','Firth of Doon','Yes','No'),
	array('Isle of Arran','Firth of Clyde','Yes','No'),
	array('Kilmarnock','Largs','Yes','Yes'),
	array('Kilmarnock','Glasgow','No','Yes'),
	array('Kilmarnock','Hamilton','No','Yes'),
	array('Kilmarnock','Firth of Doon','Yes','No'),
	array('Largs','Glasgow','No','Yes'),
	array('Largs','Paisley','Yes','Yes'),
	array('Largs','Firth of Doon','Yes','No'),
	array('Largs','Firth of Clyde','Yes','No'),
	array('Glasgow','Hamilton','No','Yes'),
	array('Glasgow','Dumbarton','No','Yes'),
	array('Glasgow','Paisley','No','Yes'),
	array('Glasgow','Shotts','No','Yes'),
	array('Hamilton','Shotts','No','Yes'),
	array('Dumbarton','Paisley','Yes','Yes'),
	array('Dumbarton','Stirling','No','Yes'),
	array('Dumbarton','Shotts','No','Yes'),
	array('Dumbarton','Trossachs','No','Yes'),
	array('Dumbarton','Helensburgh','Yes','Yes'),
	array('Dumbarton','Firth of Clyde','Yes','No'),
	array('Paisley','Firth of Clyde','Yes','No'),
	array('Stirling','Kirkcaldy','No','Yes'),
	array('Stirling','Shotts','No','Yes'),
	array('Stirling','Perth','No','Yes'),
	array('Stirling','Trossachs','No','Yes'),
	array('Kirkcaldy','St. Andrews','Yes','Yes'),
	array('Kirkcaldy','Firth of Forth','Yes','No'),
	array('Kirkcaldy','Perth','No','Yes'),
	array('St. Andrews','Dundee','Yes','Yes'),
	array('St. Andrews','Firth of Tay','Yes','No'),
	array('St. Andrews','Firth of Forth','Yes','No'),
	array('St. Andrews','Perth','No','Yes'),
	array('Dundee','Arbroath','Yes','Yes'),
	array('Dundee','Forfar','No','Yes'),
	array('Dundee','Inner North Sea','Yes','No'),
	array('Dundee','Firth of Tay','Yes','No'),
	array('Dundee','Angus','No','Yes'),
	array('Dundee','Perth','No','Yes'),
	array('Arbroath','Forfar','No','Yes'),
	array('Arbroath','Montrose','Yes','Yes'),
	array('Arbroath','Inner North Sea','Yes','No'),
	array('Arbroath','Banchory Coast','Yes','No'),
	array('Forfar','Banchory','No','Yes'),
	array('Forfar','Montrose','No','Yes'),
	array('Forfar','Angus','No','Yes'),
	array('Forfar','Invermark Castle','No','Yes'),
	array('Banchory','Montrose','Yes','Yes'),
	array('Banchory','Banchory Coast','Yes','No'),
	array('Banchory','Invermark Castle','No','Yes'),
	array('Banchory','Dufftown','No','Yes'),
	array('Banchory','Insch','No','Yes'),
	array('Banchory','Aberdeen','Yes','Yes'),
	array('Montrose','Banchory Coast','Yes','No'),
	array('North Sea','Inner North Sea','Yes','No'),
	array('North Sea','Banchory Coast','Yes','No'),
	array('North Sea','Rattray Coast','Yes','No'),
	array('Inner North Sea','Firth of Tay','Yes','No'),
	array('Inner North Sea','Firth of Forth','Yes','No'),
	array('Inner North Sea','Banchory Coast','Yes','No'),
	array('Firth of Tay','Firth of Forth','Yes','No'),
	array('Banchory Coast','Aberdeen','Yes','No'),
	array('Banchory Coast','Rattray Coast','Yes','No'),
	array('Angus','Pitlochry','No','Yes'),
	array('Angus','Perth','No','Yes'),
	array('Angus','Cairngorms','No','Yes'),
	array('Angus','Invermark Castle','No','Yes'),
	array('Angus','Aviemore','No','Yes'),
	array('Pitlochry','Perth','No','Yes'),
	array('Pitlochry','Crieff','No','Yes'),
	array('Pitlochry','Cairngorms','No','Yes'),
	array('Perth','Trossachs','No','Yes'),
	array('Perth','Crieff','No','Yes'),
	array('Trossachs','Helensburgh','No','Yes'),
	array('Trossachs','Crieff','No','Yes'),
	array('Helensburgh','Tighnabruaich','Yes','Yes'),
	array('Helensburgh','Argyll','No','Yes'),
	array('Helensburgh','Crieff','No','Yes'),
	array('Helensburgh','Firth of Clyde','Yes','No'),
	array('Tighnabruaich','Argyll','No','Yes'),
	array('Tighnabruaich','Kilmartin','No','Yes'),
	array('Tighnabruaich','Firth of Clyde','Yes','No'),
	array('Tighnabruaich','Kilmartin (South Coast)','Yes','No'),
	array('Argyll','Crieff','No','Yes'),
	array('Argyll','Cairngorms','No','Yes'),
	array('Argyll','Ben Nevis','No','Yes'),
	array('Argyll','Oban','No','Yes'),
	array('Argyll','Kilmartin','No','Yes'),
	array('Crieff','Cairngorms','No','Yes'),
	array('Cairngorms','Ben Nevis','No','Yes'),
	array('Cairngorms','Aviemore','No','Yes'),
	array('Cairngorms','Loch Ness','No','Yes'),
	array('Cairngorms','Fort William','No','Yes'),
	array('Ben Nevis','Fort William','Yes','Yes'),
	array('Ben Nevis','Oban','Yes','Yes'),
	array('Ben Nevis','Loch Linnhe','Yes','No'),
	array('Invermark Castle','Aviemore','No','Yes'),
	array('Invermark Castle','Dufftown','No','Yes'),
	array('Aviemore','Dufftown','No','Yes'),
	array('Aviemore','Moray','No','Yes'),
	array('Aviemore','Loch Ness','No','Yes'),
	array('Dufftown','Insch','No','Yes'),
	array('Dufftown','Peterhead','No','Yes'),
	array('Dufftown','Moray','No','Yes'),
	array('Insch','Aberdeen','No','Yes'),
	array('Insch','Peterhead','No','Yes'),
	array('Aberdeen','Peterhead','Yes','Yes'),
	array('Aberdeen','Rattray Coast','Yes','No'),
	array('Peterhead','Moray','Yes','Yes'),
	array('Peterhead','Rattray Coast','Yes','No'),
	array('Peterhead','Spey Bay','Yes','No'),
	array('Moray','Loch Ness','Yes','Yes'),
	array('Moray','Spey Bay','Yes','No'),
	array('Moray','Moray Firth','Yes','No'),
	array('Loch Ness','Inverness','Yes','Yes'),
	array('Loch Ness','Ullapool','No','Yes'),
	array('Loch Ness','Fort William','No','Yes'),
	array('Loch Ness','Moray Firth','Yes','No'),
	array('Inverness','Sutherland','No','Yes'),
	array('Inverness','Sutherland (South Coast)','Yes','No'),
	array('Inverness','Ullapool','No','Yes'),
	array('Inverness','Moray Firth','Yes','No'),
	array('Sutherland','John o Groats','No','Yes'),
	array('Sutherland','Ullapool','No','Yes'),
	array('Sutherland (North Coast)','John o Groats','Yes','No'),
	array('Sutherland (North Coast)','Ullapool','Yes','No'),
	array('Sutherland (North Coast)','Cape Wrath','Yes','No'),
	array('Sutherland (North Coast)','The Minch','Yes','No'),
	array('Sutherland (South Coast)','John o Groats','Yes','No'),
	array('Sutherland (South Coast)','Moray Firth','Yes','No'),
	array('John o Groats','Orkney','Yes','Yes'),
	array('John o Groats','Moray Firth','Yes','No'),
	array('John o Groats','The North Sound','Yes','No'),
	array('John o Groats','Cape Wrath','Yes','No'),
	array('Orkney','Orkney Coast','Yes','No'),
	array('Orkney','The North Sound','Yes','No'),
	array('Isle of Harris','Uist Isles','Yes','Yes'),
	array('Isle of Harris','The Minch','Yes','No'),
	array('Isle of Harris','North Atlantic Ocean','Yes','No'),
	array('Isle of Harris','Sound of Monach','Yes','No'),
	array('Isle of Harris','The Little Minch','Yes','No'),
	array('Ullapool','Isle of Skye','Yes','Yes'),
	array('Ullapool','Fort William','Yes','Yes'),
	array('Ullapool','The Minch','Yes','No'),
	array('Ullapool','The Little Minch','Yes','No'),
	array('Ullapool','Cuillin Sound','Yes','No'),
	array('Isle of Skye','The Little Minch','Yes','No'),
	array('Isle of Skye','Cuillin Sound','Yes','No'),
	array('Uist Isles','Sound of Monach','Yes','No'),
	array('Uist Isles','The Little Minch','Yes','No'),
	array('Uist Isles','Cuillin Sound','Yes','No'),
	array('Fort William','Isle of Mull','Yes','Yes'),
	array('Fort William','Cuillin Sound','Yes','No'),
	array('Fort William','Loch Linnhe','Yes','No'),
	array('Isle of Mull','Cuillin Sound','Yes','No'),
	array('Isle of Mull','Firth of Lorn','Yes','No'),
	array('Isle of Mull','Loch Linnhe','Yes','No'),
	array('Oban','Kilmartin','No','Yes'),
	array('Oban','Loch Linnhe','Yes','No'),
	array('Oban','Kilmartin (North Coast)','Yes','No'),
	array('Islay','Kilmartin','No','Yes'),
	array('Islay','Firth of Lorn','Yes','No'),
	array('Islay','Loch Linnhe','Yes','No'),
	array('Islay','North Channel','Yes','No'),
	array('Islay','Kilmartin (North Coast)','Yes','No'),
	array('Campbeltown','Kilmartin','No','Yes'),
	array('Campbeltown','North Channel','Yes','No'),
	array('Campbeltown','Firth of Doon','Yes','No'),
	array('Campbeltown','Firth of Clyde','Yes','No'),
	array('Campbeltown','Kilmartin (North Coast)','Yes','No'),
	array('Campbeltown','Kilmartin (South Coast)','Yes','No'),
	array('Rattray Coast','Spey Bay','Yes','No'),
	array('Rattray Coast','Orkney Coast','Yes','No'),
	array('Spey Bay','Moray Firth','Yes','No'),
	array('Spey Bay','Orkney Coast','Yes','No'),
	array('Moray Firth','Orkney Coast','Yes','No'),
	array('Moray Firth','The North Sound','Yes','No'),
	array('Orkney Coast','The North Sound','Yes','No'),
	array('The North Sound','Cape Wrath','Yes','No'),
	array('Cape Wrath','The Minch','Yes','No'),
	array('Cape Wrath','North Atlantic Ocean','Yes','No'),
	array('The Minch','North Atlantic Ocean','Yes','No'),
	array('The Minch','The Little Minch','Yes','No'),
	array('North Atlantic Ocean','Sound of Monach','Yes','No'),
	array('Sound of Monach','The Little Minch','Yes','No'),
	array('Sound of Monach','Cuillin Sound','Yes','No'),
	array('Sound of Monach','South Atlantic Ocean','Yes','No'),
	array('The Little Minch','Cuillin Sound','Yes','No'),
	array('Cuillin Sound','South Atlantic Ocean','Yes','No'),
	array('Cuillin Sound','Firth of Lorn','Yes','No'),
	array('Cuillin Sound','Loch Linnhe','Yes','No'),
	array('South Atlantic Ocean','Firth of Lorn','Yes','No'),
	array('South Atlantic Ocean','North Channel','Yes','No'),
	array('South Atlantic Ocean','Solway Firth','Yes','No'),
	array('Firth of Lorn','Loch Linnhe','Yes','No'),
	array('Firth of Lorn','North Channel','Yes','No'),
	array('Loch Linnhe','North Channel','Yes','No'),
	array('Loch Linnhe','Kilmartin (North Coast)','Yes','No'),
	array('North Channel','Firth of Doon','Yes','No'),
	array('North Channel','Solway Firth','Yes','No'),
	array('North Channel','Kilmartin (North Coast)','Yes','No'),
	array('Firth of Doon','Solway Firth','Yes','No'),
	array('Firth of Doon','Firth of Clyde','Yes','No'),
	array('Firth of Clyde','Kilmartin (South Coast)','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
