<?php
// This is file installs the map data for the Sengoku6 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Aki', 'Coast', 'Yes', 2, 438, 1002, 219, 501),
	array('Awa', 'Coast', 'Yes', 6, 662, 1084, 331, 542),
	array('Bingo', 'Coast', 'No', 0, 560, 980, 280, 490),
	array('Bungo', 'Coast', 'Yes', 6, 282, 1116, 141, 558),
	array('Dewa', 'Coast', 'Yes', 6, 1328, 272, 664, 136),
	array('Echigo', 'Coast', 'Yes', 5, 1210, 564, 605, 282),
	array('Echizen', 'Coast', 'Yes', 3, 882, 780, 441, 390),
	array('Etchu', 'Coast', 'No', 0, 1036, 692, 518, 346),
	array('Harima', 'Coast', 'Yes', 6, 716, 936, 358, 468),
	array('Hida', 'Land', 'No', 0, 1002, 804, 501, 402),
	array('Higo', 'Coast', 'No', 0, 246, 1252, 123, 626),
	array('Hitachi', 'Coast', 'Yes', 6, 1362, 712, 681, 356),
	array('Hizen', 'Coast', 'Yes', 6, 154, 1142, 77, 571),
	array('Hyuga', 'Coast', 'Yes', 1, 292, 1322, 146, 661),
	array('Inaba', 'Coast', 'Yes', 6, 706, 862, 353, 431),
	array('Ise', 'Coast', 'No', 3, 914, 1016, 457, 508),
	array('Iwami', 'Coast', 'Yes', 2, 449, 922, 222, 456),
	array('Iyo', 'Coast', 'Yes', 6, 508, 1084, 254, 542),
	array('Izu', 'Coast', 'No', 0, 1196, 934, 598, 467),
	array('Izumo', 'Coast', 'No', 0, 528, 862, 264, 431),
	array('Kai', 'Land', 'Yes', 6, 1132, 864, 566, 432),
	array('Kazusa', 'Coast', 'Yes', 6, 1352, 864, 676, 432),
	array('Kii', 'Coast', 'Yes', 6, 838, 1106, 419, 553),
	array('North Kozuke', 'Land', 'Yes', 5, 1212, 686, 606, 343),
	array('Kumano Sea', 'Sea', 'No', 0, 842, 1192, 421, 596),
	array('Mikawa (8)', 'Coast', 'Yes', 3, 1018, 948, 509, 474),
	array('Mino', 'Land', 'Yes', 3, 1004, 870, 502, 435),
	array('Musashi', 'Coast', 'Yes', 4, 1264, 840, 632, 420),
	array('Mutsu', 'Coast', 'Yes', 6, 1458, 330, 729, 165),
	array('Nagato', 'Coast', 'Yes', 2, 312, 1016, 156, 508),
	array('North Pacific Ocean', 'Sea', 'No', 0, 1460, 1154, 730, 577),
	array('North Sea of Japan', 'Sea', 'No', 0, 1054, 285, 482, 159),
	array('Osumi (3)', 'Coast', 'Yes', 1, 254, 1416, 127, 708),
	array('Owari (7)', 'Coast', 'Yes', 3, 960, 936, 480, 468),
	array('Satsuma (2)', 'Coast', 'Yes', 1, 200, 1336, 100, 668),
	array('Sea of Japan', 'Sea', 'No', 0, 698, 620, 349, 310),
	array('Settsu (4)', 'Coast', 'Yes', 6, 776, 968, 388, 484),
	array('Shimosa', 'Coast', 'Yes', 4, 1372, 824, 686, 412),
	array('Shimotsuke', 'Land', 'Yes', 6, 1286, 672, 643, 336),
	array('South Pacific Ocean', 'Sea', 'No', 0, 629, 1447, 315, 710),
	array('South Sea of Japan', 'Sea', 'No', 0, 222, 774, 111, 387),
	array('South Shinano', 'Land', 'Yes', 6, 1064, 856, 532, 428),
	array('Suruga (11)', 'Coast', 'Yes', 6, 1130, 924, 565, 462),
	array('Tango', 'Coast', 'No', 0, 778, 876, 389, 438),
	array('Tosa', 'Coast', 'Yes', 6, 514, 1158, 257, 579),
	array('Totomi (10)', 'Coast', 'No', 0, 1074, 964, 537, 482),
	array('Tsushima Strait', 'Sea', 'No', 0, 106, 1040, 53, 520),
	array('Yamashiro (6)', 'Land', 'Yes', 3, 822, 936, 411, 468),
	array('Yamato (5)', 'Land', 'No', 0, 842, 1026, 421, 513),
	array('Mutsu Bay', 'Sea', 'No', 0, 1478, 110, 739, 55),
	array('Tanegashima', 'Sea', 'No', 0, 58, 1432, 29, 716),
	array('Omi', 'Coast', 'Yes', 3, 842, 870, 421, 435),
	array('Aiizu', 'Land', 'Yes', 5, 1332, 616, 666, 308),
	array('South Kozuke (12)', 'Land', 'No', 0, 1194, 756, 597, 378),
	array('Noto (9)', 'Coast', 'Yes', 6, 978, 614, 489, 307),
	array('Tsushima (1)', 'Coast', 'Yes', 6, 98, 992, 49, 496),
	array('Sagami', 'Coast', 'Yes', 4, 1232, 898, 616, 449),
	array('North Shinano', 'Land', 'Yes', 6, 1094, 704, 547, 352),
	array('Izu Archipelago', 'Sea', 'No', 0, 1184, 1126, 592, 563)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Aki','Awa','Yes','Yes'),
	array('Aki','Bingo','Yes','Yes'),
	array('Aki','Bungo','Yes','Yes'),
	array('Aki','Harima','Yes','Yes'),
	array('Aki','Iwami','No','Yes'),
	array('Aki','Iyo','Yes','Yes'),
	array('Aki','Nagato','Yes','Yes'),
	array('Awa','Bingo','Yes','Yes'),
	array('Awa','Harima','Yes','Yes'),
	array('Awa','Iyo','Yes','Yes'),
	array('Awa','Kii','Yes','Yes'),
	array('Awa','Kumano Sea','Yes','No'),
	array('Awa','Settsu (4)','Yes','Yes'),
	array('Awa','Tosa','Yes','Yes'),
	array('Bingo','Harima','Yes','Yes'),
	array('Bingo','Iwami','No','Yes'),
	array('Bingo','Iyo','Yes','Yes'),
	array('Bingo','Izumo','No','Yes'),
	array('Bungo','Higo','No','Yes'),
	array('Bungo','Hizen','Yes','Yes'),
	array('Bungo','Hyuga','Yes','Yes'),
	array('Bungo','Iwami','Yes','Yes'),
	array('Bungo','Iyo','Yes','Yes'),
	array('Bungo','Izumo','Yes','Yes'),
	array('Bungo','Nagato','Yes','Yes'),
	array('Bungo','South Pacific Ocean','Yes','No'),
	array('Bungo','South Sea of Japan','Yes','No'),
	array('Bungo','Tosa','Yes','Yes'),
	array('Bungo','Tsushima Strait','Yes','No'),
	array('Bungo','Tsushima (1)','Yes','Yes'),
	array('Dewa','Echigo','Yes','Yes'),
	array('Dewa','Etchu','Yes','Yes'),
	array('Dewa','Mutsu','Yes','Yes'),
	array('Dewa','North Sea of Japan','Yes','No'),
	array('Dewa','Mutsu Bay','Yes','No'),
	array('Dewa','Aiizu','No','Yes'),
	array('Dewa','Noto (9)','Yes','Yes'),
	array('Echigo','Etchu','Yes','Yes'),
	array('Echigo','North Kozuke','No','Yes'),
	array('Echigo','North Sea of Japan','Yes','No'),
	array('Echigo','Aiizu','No','Yes'),
	array('Echigo','Noto (9)','Yes','Yes'),
	array('Echigo','North Shinano','No','Yes'),
	array('Echizen','Etchu','No','Yes'),
	array('Echizen','Hida','No','Yes'),
	array('Echizen','Inaba','Yes','Yes'),
	array('Echizen','Izumo','Yes','Yes'),
	array('Echizen','Mino','No','Yes'),
	array('Echizen','Sea of Japan','Yes','No'),
	array('Echizen','Tango','Yes','Yes'),
	array('Echizen','Omi','Yes','Yes'),
	array('Echizen','Noto (9)','Yes','Yes'),
	array('Etchu','Hida','No','Yes'),
	array('Etchu','North Sea of Japan','Yes','No'),
	array('Etchu','Noto (9)','Yes','Yes'),
	array('Etchu','North Shinano','No','Yes'),
	array('Harima','Inaba','No','Yes'),
	array('Harima','Iyo','Yes','Yes'),
	array('Harima','Izumo','No','Yes'),
	array('Harima','Kii','Yes','Yes'),
	array('Harima','Settsu (4)','Yes','Yes'),
	array('Harima','Tango','No','Yes'),
	array('Hida','Mino','No','Yes'),
	array('Hida','South Shinano','No','Yes'),
	array('Hida','North Shinano','No','Yes'),
	array('Higo','Hizen','Yes','Yes'),
	array('Higo','Hyuga','No','Yes'),
	array('Higo','Osumi (3)','Yes','Yes'),
	array('Higo','Satsuma (2)','Yes','Yes'),
	array('Higo','Tsushima Strait','Yes','No'),
	array('Higo','Tanegashima','Yes','No'),
	array('Hitachi','Kazusa','Yes','Yes'),
	array('Hitachi','Mutsu','Yes','Yes'),
	array('Hitachi','North Pacific Ocean','Yes','No'),
	array('Hitachi','Shimosa','Yes','Yes'),
	array('Hitachi','Shimotsuke','No','Yes'),
	array('Hitachi','Izu Archipelago','Yes','No'),
	array('Hizen','Osumi (3)','Yes','Yes'),
	array('Hizen','Satsuma (2)','Yes','Yes'),
	array('Hizen','Tsushima Strait','Yes','No'),
	array('Hizen','Tanegashima','Yes','No'),
	array('Hyuga','Iyo','Yes','Yes'),
	array('Hyuga','Osumi (3)','Yes','Yes'),
	array('Hyuga','Satsuma (2)','No','Yes'),
	array('Hyuga','South Pacific Ocean','Yes','No'),
	array('Hyuga','Tosa','Yes','Yes'),
	array('Inaba','Izumo','Yes','Yes'),
	array('Inaba','Sea of Japan','Yes','No'),
	array('Inaba','Tango','Yes','Yes'),
	array('Inaba','Omi','Yes','Yes'),
	array('Inaba','Noto (9)','Yes','Yes'),
	array('Ise','Kii','Yes','Yes'),
	array('Ise','Kumano Sea','Yes','No'),
	array('Ise','Mikawa (8)','Yes','Yes'),
	array('Ise','Mino','No','Yes'),
	array('Ise','Owari (7)','Yes','Yes'),
	array('Ise','Yamashiro (6)','No','Yes'),
	array('Ise','Yamato (5)','No','Yes'),
	array('Ise','Omi','No','Yes'),
	array('Iwami','Izumo','Yes','Yes'),
	array('Iwami','Nagato','Yes','Yes'),
	array('Iwami','South Sea of Japan','Yes','No'),
	array('Iwami','Tsushima Strait','Yes','No'),
	array('Iwami','Tsushima (1)','Yes','Yes'),
	array('Iyo','Nagato','Yes','Yes'),
	array('Iyo','South Pacific Ocean','Yes','No'),
	array('Iyo','Tosa','Yes','Yes'),
	array('Izu','Kazusa','Yes','Yes'),
	array('Izu','Kumano Sea','Yes','No'),
	array('Izu','Musashi','Yes','Yes'),
	array('Izu','Suruga (11)','Yes','Yes'),
	array('Izu','Sagami','Yes','Yes'),
	array('Izu','Izu Archipelago','Yes','No'),
	array('Izumo','Nagato','Yes','Yes'),
	array('Izumo','Sea of Japan','Yes','No'),
	array('Izumo','South Sea of Japan','Yes','No'),
	array('Izumo','Tango','Yes','Yes'),
	array('Izumo','Tsushima Strait','Yes','No'),
	array('Izumo','Omi','Yes','Yes'),
	array('Izumo','Noto (9)','Yes','Yes'),
	array('Izumo','Tsushima (1)','Yes','Yes'),
	array('Kai','Musashi','No','Yes'),
	array('Kai','South Shinano','No','Yes'),
	array('Kai','Suruga (11)','No','Yes'),
	array('Kai','South Kozuke (12)','No','Yes'),
	array('Kai','Sagami','No','Yes'),
	array('Kai','North Shinano','No','Yes'),
	array('Kazusa','Musashi','Yes','Yes'),
	array('Kazusa','Mutsu','Yes','Yes'),
	array('Kazusa','North Pacific Ocean','Yes','No'),
	array('Kazusa','Shimosa','Yes','Yes'),
	array('Kazusa','Sagami','Yes','Yes'),
	array('Kazusa','Izu Archipelago','Yes','No'),
	array('Kii','Kumano Sea','Yes','No'),
	array('Kii','Settsu (4)','Yes','Yes'),
	array('Kii','Tosa','Yes','Yes'),
	array('Kii','Yamato (5)','No','Yes'),
	array('North Kozuke','Shimotsuke','No','Yes'),
	array('North Kozuke','Aiizu','No','Yes'),
	array('North Kozuke','South Kozuke (12)','No','Yes'),
	array('North Kozuke','North Shinano','No','Yes'),
	array('Kumano Sea','Mikawa (8)','Yes','No'),
	array('Kumano Sea','Owari (7)','Yes','No'),
	array('Kumano Sea','South Pacific Ocean','Yes','No'),
	array('Kumano Sea','Suruga (11)','Yes','No'),
	array('Kumano Sea','Tosa','Yes','No'),
	array('Kumano Sea','Totomi (10)','Yes','No'),
	array('Kumano Sea','Izu Archipelago','Yes','No'),
	array('Mikawa (8)','Mino','No','Yes'),
	array('Mikawa (8)','Owari (7)','Yes','Yes'),
	array('Mikawa (8)','South Shinano','No','Yes'),
	array('Mikawa (8)','Totomi (10)','Yes','Yes'),
	array('Mino','Owari (7)','No','Yes'),
	array('Mino','South Shinano','No','Yes'),
	array('Mino','Totomi (10)','No','Yes'),
	array('Mino','Omi','No','Yes'),
	array('Musashi','Shimosa','No','Yes'),
	array('Musashi','Shimotsuke','No','Yes'),
	array('Musashi','South Kozuke (12)','No','Yes'),
	array('Musashi','Sagami','Yes','Yes'),
	array('Musashi','Izu Archipelago','Yes','No'),
	array('Mutsu','North Pacific Ocean','Yes','No'),
	array('Mutsu','Shimosa','Yes','Yes'),
	array('Mutsu','Shimotsuke','No','Yes'),
	array('Mutsu','Mutsu Bay','Yes','No'),
	array('Mutsu','Aiizu','No','Yes'),
	array('Mutsu','Izu Archipelago','Yes','No'),
	array('Nagato','South Sea of Japan','Yes','No'),
	array('Nagato','Tsushima Strait','Yes','No'),
	array('Nagato','Tsushima (1)','Yes','Yes'),
	array('North Pacific Ocean','Shimosa','Yes','No'),
	array('North Pacific Ocean','South Pacific Ocean','Yes','No'),
	array('North Pacific Ocean','Mutsu Bay','Yes','No'),
	array('North Pacific Ocean','Izu Archipelago','Yes','No'),
	array('North Sea of Japan','Sea of Japan','Yes','No'),
	array('North Sea of Japan','Mutsu Bay','Yes','No'),
	array('North Sea of Japan','Noto (9)','Yes','No'),
	array('Osumi (3)','Satsuma (2)','Yes','Yes'),
	array('Osumi (3)','South Pacific Ocean','Yes','No'),
	array('Osumi (3)','Tsushima Strait','Yes','No'),
	array('Osumi (3)','Tanegashima','Yes','No'),
	array('Satsuma (2)','Tsushima Strait','Yes','No'),
	array('Satsuma (2)','Tanegashima','Yes','No'),
	array('Sea of Japan','South Sea of Japan','Yes','No'),
	array('Sea of Japan','Tango','Yes','No'),
	array('Sea of Japan','Omi','Yes','No'),
	array('Sea of Japan','Noto (9)','Yes','No'),
	array('Settsu (4)','Tango','No','Yes'),
	array('Settsu (4)','Yamashiro (6)','No','Yes'),
	array('Settsu (4)','Yamato (5)','No','Yes'),
	array('Shimosa','Shimotsuke','No','Yes'),
	array('Shimosa','Izu Archipelago','Yes','No'),
	array('Shimotsuke','Aiizu','No','Yes'),
	array('Shimotsuke','South Kozuke (12)','No','Yes'),
	array('South Pacific Ocean','Tosa','Yes','No'),
	array('South Pacific Ocean','Tanegashima','Yes','No'),
	array('South Pacific Ocean','Izu Archipelago','Yes','No'),
	array('South Sea of Japan','Tsushima Strait','Yes','No'),
	array('South Sea of Japan','Tsushima (1)','Yes','No'),
	array('South Shinano','Suruga (11)','No','Yes'),
	array('South Shinano','Totomi (10)','No','Yes'),
	array('South Shinano','North Shinano','No','Yes'),
	array('Suruga (11)','Totomi (10)','Yes','Yes'),
	array('Suruga (11)','Sagami','No','Yes'),
	array('Tango','Yamashiro (6)','No','Yes'),
	array('Tango','Omi','Yes','Yes'),
	array('Tango','Noto (9)','Yes','Yes'),
	array('Tsushima Strait','Tanegashima','Yes','No'),
	array('Tsushima Strait','Tsushima (1)','Yes','No'),
	array('Yamashiro (6)','Yamato (5)','No','Yes'),
	array('Yamashiro (6)','Omi','No','Yes'),
	array('Omi','Noto (9)','Yes','Yes'),
	array('South Kozuke (12)','North Shinano','No','Yes'),
	array('Sagami','Izu Archipelago','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
