<?php
// This is file installs the map data for the World10 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Great Britain', 'Coast', 'Yes', 0, 668, 149, 668, 149),
	array('Thule', 'Coast', 'No', 0, 588, 66, 588, 66),
	array('Godthab', 'Coast', 'Yes', 0, 585, 90, 585, 90),
	array('Baffin Island', 'Coast', 'No', 0, 476, 93, 476, 93),
	array('Newfoundland', 'Coast', 'Yes', 12, 472, 150, 472, 150),
	array('Quebec', 'Coast', 'Yes', 12, 434, 178, 434, 178),
	array('Ontario', 'Coast', 'Yes', 12, 383, 165, 383, 165),
	array('Manitoba', 'Coast', 'Yes', 0, 355, 150, 355, 150),
	array('Saskatchewan', 'Land', 'No', 16, 320, 158, 320, 158),
	array('Alberta', 'Land', 'No', 16, 289, 165, 289, 165),
	array('British Columbia', 'Coast', 'Yes', 16, 264, 152, 264, 152),
	array('Northwest Territories', 'Coast', 'Yes', 16, 305, 115, 305, 115),
	array('Yukon', 'Coast', 'Yes', 16, 269, 116, 269, 116),
	array('Alaska', 'Coast', 'Yes', 0, 205, 124, 205, 124),
	array('Indian Territories', 'Coast', 'Yes', 0, 266, 208, 266, 208),
	array('Midwest', 'Land', 'No', 0, 320, 200, 320, 200),
	array('Union', 'Coast', 'Yes', 0, 380, 220, 380, 220),
	array('Florida', 'Coast', 'Yes', 15, 357, 257, 357, 257),
	array('Deep South', 'Coast', 'No', 15, 318, 242, 318, 242),
	array('Texas', 'Coast', 'Yes', 15, 294, 252, 294, 252),
	array('Nevada', 'Land', 'No', 15, 265, 230, 265, 230),
	array('California', 'Coast', 'Yes', 15, 235, 217, 235, 217),
	array('Monterrey', 'Coast', 'No', 0, 266, 272, 266, 272),
	array('Mexico', 'Coast', 'Yes', 0, 285, 308, 285, 308),
	array('Central America', 'Coast', 'No', 0, 334, 347, 334, 347),
	array('Colombia', 'Coast', 'Yes', 0, 383, 394, 383, 394),
	array('Venezuela', 'Coast', 'Yes', 0, 415, 374, 415, 374),
	array('Carribean Islands', 'Coast', 'No', 0, 395, 314, 395, 314),
	array('Chile', 'Coast', 'Yes', 1, 410, 586, 410, 586),
	array('Guyana', 'Coast', 'No', 0, 446, 374, 446, 374),
	array('Recife', 'Coast', 'Yes', 2, 486, 414, 486, 414),
	array('Brasillia', 'Land', 'Yes', 2, 446, 445, 446, 445),
	array('Amazon', 'Land', 'No', 2, 412, 414, 412, 414),
	array('Bolivia', 'Land', 'No', 0, 420, 470, 420, 470),
	array('Salvador', 'Coast', 'No', 2, 514, 448, 514, 448),
	array('Belo Horizonte', 'Land', 'No', 2, 486, 444, 486, 444),
	array('Rio de Janeiro', 'Coast', 'Yes', 2, 503, 468, 503, 468),
	array('Sao Paulo', 'Coast', 'No', 2, 465, 490, 465, 490),
	array('Uruguay', 'Coast', 'Yes', 0, 468, 534, 468, 534),
	array('Buenos Aires', 'Coast', 'Yes', 1, 441, 568, 441, 568),
	array('Mendoza', 'Land', 'No', 1, 426, 534, 426, 534),
	array('Santa Cruz', 'Coast', 'Yes', 1, 432, 605, 432, 605),
	array('Northwest Indian', 'Sea', 'No', 0, 922, 389, 922, 389),
	array('Red Sea', 'Sea', 'No', 0, 860, 342, 860, 342),
	array('Java Sea', 'Sea', 'No', 0, 1137, 467, 1137, 467),
	array('Bay of Bengal', 'Sea', 'No', 0, 1024, 326, 1024, 326),
	array('Spain', 'Coast', 'No', 4, 659, 215, 659, 215),
	array('France', 'Coast', 'Yes', 4, 681, 200, 681, 200),
	array('Germany', 'Coast', 'Yes', 4, 710, 183, 710, 183),
	array('Italy', 'Coast', 'Yes', 4, 735, 221, 735, 221),
	array('Austria-Hungary', 'Coast', 'No', 4, 737, 189, 737, 189),
	array('Poland', 'Coast', 'No', 4, 744, 164, 744, 164),
	array('Baltic States', 'Coast', 'No', 0, 760, 145, 760, 145),
	array('Saint Petersburg', 'Coast', 'Yes', 13, 796, 128, 796, 128),
	array('Belorussia', 'Land', 'Yes', 13, 780, 155, 780, 155),
	array('Ukraine', 'Coast', 'Yes', 0, 788, 175, 788, 175),
	array('Black Sea', 'Sea', 'No', 0, 803, 208, 803, 208),
	array('Balkans', 'Coast', 'No', 0, 760, 208, 760, 208),
	array('Moscow', 'Coast', 'Yes', 13, 827, 157, 827, 157),
	array('Perm', 'Coast', 'Yes', 0, 890, 136, 886, 124),
	array('Norilsk', 'Coast', 'Yes', 11, 998, 106, 952, 95),
	array('Yakutsk', 'Coast', 'Yes', 11, 1090, 114, 1096, 121),
	array('Omsk', 'Land', 'No', 11, 994, 158, 956, 169),
	array('Irkutsk', 'Land', 'No', 11, 1052, 154, 1042, 153),
	array('Inner Mongolia', 'Land', 'No', 3, 1078, 214, 1078, 214),
	array('Western China', 'Land', 'No', 3, 988, 218, 988, 218),
	array('Beijing', 'Coast', 'Yes', 0, 1097, 238, 1097, 238),
	array('Vladivostok', 'Coast', 'Yes', 0, 1128, 168, 1128, 168),
	array('Heilongjiang', 'Land', 'No', 3, 1128, 196, 1128, 196),
	array('Korea', 'Coast', 'Yes', 8, 1148, 236, 1148, 236),
	array('Shanghai', 'Coast', 'Yes', 3, 1111, 255, 1111, 255),
	array('Guangzhou', 'Coast', 'Yes', 3, 1095, 295, 1095, 295),
	array('Vietnam', 'Coast', 'No', 0, 1090, 338, 1090, 338),
	array('Thailand', 'Coast', 'Yes', 0, 1061, 350, 1061, 350),
	array('Burma', 'Coast', 'No', 0, 1043, 297, 1043, 297),
	array('Bangladesh', 'Coast', 'Yes', 0, 1022, 291, 1022, 291),
	array('Lanzhou', 'Land', 'Yes', 3, 1042, 250, 1042, 250),
	array('Bombay', 'Coast', 'Yes', 7, 975, 332, 975, 332),
	array('Delhi', 'Land', 'Yes', 7, 965, 267, 965, 267),
	array('Pakistan', 'Coast', 'No', 0, 938, 265, 938, 265),
	array('Afghanistan', 'Land', 'Yes', 0, 919, 246, 919, 246),
	array('Iran', 'Coast', 'No', 10, 878, 258, 878, 258),
	array('Armenia', 'Coast', 'Yes', 0, 828, 207, 828, 207),
	array('Turkey', 'Coast', 'Yes', 0, 785, 228, 785, 228),
	array('Syria', 'Coast', 'Yes', 10, 818, 244, 818, 244),
	array('Iraq', 'Coast', 'Yes', 10, 848, 260, 848, 260),
	array('Saudi Arabia', 'Coast', 'Yes', 10, 838, 300, 838, 300),
	array('Western Australia', 'Coast', 'Yes', 17, 1136, 516, 1136, 516),
	array('Northern Territory', 'Coast', 'No', 17, 1186, 473, 1186, 473),
	array('Queensland', 'Coast', 'No', 17, 1230, 496, 1230, 496),
	array('New South Wales', 'Coast', 'Yes', 17, 1224, 536, 1224, 536),
	array('Victoria', 'Coast', 'Yes', 17, 1210, 550, 1210, 550),
	array('South Australia', 'Coast', 'No', 17, 1197, 517, 1197, 517),
	array('New Zealand', 'Coast', 'Yes', 0, 1285, 593, 1285, 593),
	array('Indonesia', 'Coast', 'Yes', 0, 1126, 412, 1126, 412),
	array('Phillipines', 'Coast', 'No', 0, 1143, 330, 1143, 330),
	array('Morocco', 'Coast', 'Yes', 0, 644, 268, 644, 268),
	array('Algeria', 'Coast', 'Yes', 0, 684, 270, 684, 270),
	array('Libya', 'Coast', 'Yes', 9, 736, 270, 736, 270),
	array('Egypt', 'Coast', 'Yes', 9, 782, 273, 782, 273),
	array('Sudan', 'Coast', 'Yes', 9, 795, 322, 795, 322),
	array('Ethiopia', 'Coast', 'No', 0, 830, 359, 830, 359),
	array('Somalia', 'Coast', 'No', 0, 859, 370, 859, 370),
	array('Mauritania', 'Coast', 'No', 0, 624, 304, 624, 304),
	array('Mali', 'Land', 'Yes', 6, 666, 316, 666, 316),
	array('Niger', 'Land', 'No', 0, 714, 312, 714, 312),
	array('Chad', 'Land', 'Yes', 0, 744, 326, 744, 326),
	array('Guinea', 'Coast', 'Yes', 6, 636, 358, 636, 358),
	array('Ghana', 'Coast', 'Yes', 6, 670, 359, 670, 359),
	array('Cameroon', 'Coast', 'No', 0, 717, 375, 717, 375),
	array('Central African Republic', 'Land', 'No', 0, 760, 368, 760, 368),
	array('Congo', 'Coast', 'Yes', 0, 726, 410, 726, 410),
	array('Zaire', 'Land', 'No', 0, 762, 406, 762, 406),
	array('Mozambique', 'Coast', 'Yes', 14, 814, 461, 814, 461),
	array('South Africa', 'Coast', 'Yes', 14, 777, 533, 777, 533),
	array('Zimbabwe', 'Land', 'No', 0, 786, 484, 786, 484),
	array('Namibia', 'Coast', 'Yes', 14, 739, 510, 739, 510),
	array('Angola', 'Coast', 'No', 0, 740, 454, 740, 454),
	array('Zambia', 'Land', 'Yes', 0, 792, 455, 792, 455),
	array('Yukon (North Coast)', 'Coast', 'No', 0, 282, 100, 282, 100),
	array('Yukon (South Coast)', 'Coast', 'No', 0, 244, 132, 244, 132),
	array('Quebec (North Coast)', 'Coast', 'No', 0, 432, 144, 432, 144),
	array('Quebec (South Coast)', 'Coast', 'No', 0, 458, 192, 458, 192),
	array('Monterrey (West Coast)', 'Coast', 'No', 0, 236, 275, 236, 275),
	array('Monterrey (East Coast)', 'Coast', 'No', 0, 293, 292, 293, 292),
	array('Mexico (West Coast)', 'Coast', 'No', 0, 280, 326, 280, 326),
	array('Mexico (East Coast)', 'Coast', 'No', 0, 315, 308, 315, 308),
	array('Colombia (West Coast)', 'Coast', 'No', 0, 358, 383, 358, 383),
	array('Colombia (North Coast)', 'Coast', 'No', 0, 376, 353, 376, 353),
	array('France (North Coast)', 'Coast', 'No', 0, 668, 184, 668, 184),
	array('France (South Coast)', 'Coast', 'No', 0, 692, 208, 692, 208),
	array('Saint Petersburg (North Coast)', 'Coast', 'No', 0, 786, 100, 786, 100),
	array('Saint Petersburg (South Coast)', 'Coast', 'No', 0, 770, 132, 770, 132),
	array('Balkans (South Coast)', 'Coast', 'No', 0, 757, 228, 757, 228),
	array('Balkans (East Coast)', 'Coast', 'No', 0, 774, 202, 774, 202),
	array('Saudi Arabia (North Coast)', 'Coast', 'No', 0, 810, 258, 810, 258),
	array('Saudi Arabia (South Coast)', 'Coast', 'No', 0, 890, 320, 890, 320),
	array('Yakutsk (North Coast)', 'Coast', 'No', 0, 1076, 92, 1061, 92),
	array('Yakutsk (South Coast)', 'Coast', 'No', 0, 1137, 135, 1137, 135),
	array('Kenya', 'Coast', 'Yes', 0, 813, 426, 813, 426),
	array('Botswana', 'Land', 'No', 0, 763, 494, 763, 494),
	array('Scandinavia', 'Coast', 'Yes', 0, 723, 124, 723, 124),
	array('Peru', 'Coast', 'Yes', 0, 372, 438, 372, 438),
	array('Kamchatka', 'Coast', 'Yes', 11, 1182, 115, 1182, 115),
	array('Hokkaido', 'Coast', 'Yes', 8, 1187, 200, 1186, 201),
	array('Honshu', 'Coast', 'Yes', 8, 1181, 242, 1179, 242),
	array('Mongolia', 'Coast', 'Yes', 0, 1051, 194, 1051, 194),
	array('West Central Asia', 'Land', 'No', 0, 901, 177, 901, 177),
	array('East Central Asia', 'Land', 'No', 0, 906, 226, 906, 226),
	array('Calcutta', 'Coast', 'Yes', 7, 990, 299, 990, 299),
	array('Tibet', 'Land', 'No', 0, 993, 264, 993, 264),
	array('Wilkes Land', 'Coast', 'Yes', 5, 958, 705, 960, 704),
	array('Marie Byrd Land', 'Coast', 'Yes', 5, 395, 730, 395, 730),
	array('Northeast Atlantic', 'Sea', 'No', 0, 576, 266, 576, 266),
	array('Mid Atlantic Ocean', 'Sea', 'No', 0, 583, 384, 583, 384),
	array('West Atlantic Ocean', 'Sea', 'No', 0, 569, 531, 569, 531),
	array('East Atlantic Ocean', 'Sea', 'No', 0, 679, 472, 679, 472),
	array('Southwest Atlantic', 'Sea', 'No', 0, 552, 643, 552, 643),
	array('Northwest Atlantic', 'Sea', 'No', 0, 448, 291, 448, 291),
	array('Southeast Atlantic', 'Sea', 'No', 0, 736, 618, 736, 618),
	array('Gulf of Mexico', 'Sea', 'No', 0, 341, 281, 341, 281),
	array('Carribean Sea', 'Sea', 'No', 0, 356, 319, 356, 319),
	array('Labrador Sea', 'Sea', 'No', 0, 578, 152, 578, 152),
	array('Norwegian Sea', 'Sea', 'No', 0, 692, 152, 692, 152),
	array('Baltic Sea', 'Sea', 'No', 0, 744, 132, 744, 132),
	array('Western Mediterranean', 'Sea', 'No', 0, 684, 229, 684, 229),
	array('Eastern Mediterranean', 'Sea', 'No', 0, 787, 249, 787, 249),
	array('Greenland Sea', 'Sea', 'No', 0, 691, 63, 691, 63),
	array('Hudson Bay', 'Sea', 'No', 0, 414, 127, 414, 127),
	array('Siberian Sea', 'Sea', 'No', 0, 895, 61, 895, 61),
	array('Chukchi Sea', 'Sea', 'No', 0, 301, 75, 301, 75),
	array('Arctic Circle', 'Sea', 'No', 0, 674, 36, 674, 36),
	array('Graham Land', 'Coast', 'No', 5, 499, 718, 499, 718),
	array('Maud Land', 'Coast', 'Yes', 5, 703, 718, 702, 719),
	array('Enderby Land', 'Coast', 'No', 5, 835, 702, 832, 702),
	array('Victoria Land', 'Coast', 'No', 5, 1070, 738, 1070, 737),
	array('South Pole', 'Land', 'Yes', 0, 735, 751, 735, 751),
	array('Southeast Pacific', 'Sea', 'No', 0, 349, 637, 349, 637),
	array('Southwest Pacific', 'Sea', 'No', 0, 157, 624, 157, 624),
	array('East Pacific Ocean', 'Sea', 'No', 0, 237, 481, 237, 481),
	array('Northeast Pacific', 'Sea', 'No', 0, 188, 369, 188, 369),
	array('North Pacific Ocean', 'Sea', 'No', 0, 183, 191, 183, 191),
	array('Oceanian Islands', 'Coast', 'Yes', 0, 45, 480, 45, 480),
	array('Hawaii', 'Coast', 'Yes', 0, 45, 299, 45, 299),
	array('Madagascar', 'Coast', 'Yes', 0, 850, 498, 850, 498),
	array('Central Pacific Ocean', 'Sea', 'No', 0, 1370, 361, 1370, 361),
	array('Bering Sea', 'Sea', 'No', 0, 1271, 165, 1271, 165),
	array('Northwest Pacific', 'Sea', 'No', 0, 1278, 214, 1278, 214),
	array('Sea of Othoksk', 'Sea', 'No', 0, 1172, 152, 1172, 152),
	array('Sea of Japan', 'Sea', 'No', 0, 1165, 216, 1165, 216),
	array('West Pacific Ocean', 'Sea', 'No', 0, 1230, 361, 1230, 361),
	array('Yellow Sea', 'Sea', 'No', 0, 1155, 275, 1155, 275),
	array('South China Sea', 'Sea', 'No', 0, 1102, 367, 1102, 367),
	array('Coral Sea', 'Sea', 'No', 0, 1283, 485, 1283, 485),
	array('Tasman Sea', 'Sea', 'No', 0, 1257, 572, 1257, 572),
	array('Southeast Indian', 'Sea', 'No', 0, 1090, 632, 1102, 630),
	array('Southwest Indian', 'Sea', 'No', 0, 899, 611, 926, 628),
	array('Mid Indian Ocean', 'Sea', 'No', 0, 1007, 528, 1007, 528),
	array('Northeast Indian', 'Sea', 'No', 0, 1029, 419, 1029, 419),
	array('Mozambique Channel', 'Sea', 'No', 0, 822, 510, 822, 510)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Great Britain','Northeast Atlantic','Yes','No'),
	array('Great Britain','Labrador Sea','Yes','No'),
	array('Great Britain','Norwegian Sea','Yes','No'),
	array('Thule','Godthab','Yes','Yes'),
	array('Thule','Labrador Sea','Yes','No'),
	array('Thule','Greenland Sea','Yes','No'),
	array('Godthab','Labrador Sea','Yes','No'),
	array('Godthab','Norwegian Sea','Yes','No'),
	array('Godthab','Greenland Sea','Yes','No'),
	array('Baffin Island','Labrador Sea','Yes','No'),
	array('Baffin Island','Greenland Sea','Yes','No'),
	array('Baffin Island','Hudson Bay','Yes','No'),
	array('Newfoundland','Quebec','No','Yes'),
	array('Newfoundland','Quebec (North Coast)','Yes','No'),
	array('Newfoundland','Quebec (South Coast)','Yes','No'),
	array('Newfoundland','Northwest Atlantic','Yes','No'),
	array('Newfoundland','Labrador Sea','Yes','No'),
	array('Newfoundland','Hudson Bay','Yes','No'),
	array('Quebec','Ontario','No','Yes'),
	array('Quebec','Union','No','Yes'),
	array('Ontario','Manitoba','Yes','Yes'),
	array('Ontario','Midwest','No','Yes'),
	array('Ontario','Union','No','Yes'),
	array('Ontario','Quebec (North Coast)','Yes','No'),
	array('Ontario','Hudson Bay','Yes','No'),
	array('Manitoba','Saskatchewan','No','Yes'),
	array('Manitoba','Northwest Territories','Yes','Yes'),
	array('Manitoba','Midwest','No','Yes'),
	array('Manitoba','Hudson Bay','Yes','No'),
	array('Saskatchewan','Alberta','No','Yes'),
	array('Saskatchewan','Northwest Territories','No','Yes'),
	array('Saskatchewan','Indian Territories','No','Yes'),
	array('Saskatchewan','Midwest','No','Yes'),
	array('Alberta','British Columbia','No','Yes'),
	array('Alberta','Northwest Territories','No','Yes'),
	array('Alberta','Indian Territories','No','Yes'),
	array('British Columbia','Northwest Territories','No','Yes'),
	array('British Columbia','Yukon','No','Yes'),
	array('British Columbia','Indian Territories','Yes','Yes'),
	array('British Columbia','Yukon (South Coast)','Yes','No'),
	array('British Columbia','North Pacific Ocean','Yes','No'),
	array('Northwest Territories','Yukon','No','Yes'),
	array('Northwest Territories','Yukon (North Coast)','Yes','No'),
	array('Northwest Territories','Greenland Sea','Yes','No'),
	array('Northwest Territories','Hudson Bay','Yes','No'),
	array('Northwest Territories','Chukchi Sea','Yes','No'),
	array('Yukon','Alaska','No','Yes'),
	array('Alaska','Yukon (North Coast)','Yes','No'),
	array('Alaska','Yukon (South Coast)','Yes','No'),
	array('Alaska','Kamchatka','Yes','Yes'),
	array('Alaska','Chukchi Sea','Yes','No'),
	array('Alaska','North Pacific Ocean','Yes','No'),
	array('Alaska','Bering Sea','Yes','No'),
	array('Indian Territories','Midwest','No','Yes'),
	array('Indian Territories','Nevada','No','Yes'),
	array('Indian Territories','California','Yes','Yes'),
	array('Indian Territories','North Pacific Ocean','Yes','No'),
	array('Midwest','Union','No','Yes'),
	array('Midwest','Deep South','No','Yes'),
	array('Midwest','Nevada','No','Yes'),
	array('Union','Florida','Yes','Yes'),
	array('Union','Deep South','No','Yes'),
	array('Union','Quebec (South Coast)','Yes','No'),
	array('Union','Northwest Atlantic','Yes','No'),
	array('Florida','Deep South','Yes','Yes'),
	array('Florida','Northwest Atlantic','Yes','No'),
	array('Florida','Gulf of Mexico','Yes','No'),
	array('Deep South','Texas','Yes','Yes'),
	array('Deep South','Nevada','No','Yes'),
	array('Deep South','Gulf of Mexico','Yes','No'),
	array('Texas','Nevada','No','Yes'),
	array('Texas','Monterrey','No','Yes'),
	array('Texas','Monterrey (East Coast)','Yes','No'),
	array('Texas','Gulf of Mexico','Yes','No'),
	array('Nevada','California','No','Yes'),
	array('Nevada','Monterrey','No','Yes'),
	array('California','Monterrey','No','Yes'),
	array('California','Monterrey (West Coast)','Yes','No'),
	array('California','North Pacific Ocean','Yes','No'),
	array('Monterrey','Mexico','No','Yes'),
	array('Mexico','Central America','No','Yes'),
	array('Central America','Colombia','No','Yes'),
	array('Central America','Mexico (West Coast)','Yes','No'),
	array('Central America','Mexico (East Coast)','Yes','No'),
	array('Central America','Colombia (West Coast)','Yes','No'),
	array('Central America','Colombia (North Coast)','Yes','No'),
	array('Central America','Carribean Sea','Yes','No'),
	array('Central America','Northeast Pacific','Yes','No'),
	array('Colombia','Venezuela','No','Yes'),
	array('Colombia','Amazon','No','Yes'),
	array('Colombia','Peru','No','Yes'),
	array('Venezuela','Guyana','Yes','Yes'),
	array('Venezuela','Brasillia','No','Yes'),
	array('Venezuela','Amazon','No','Yes'),
	array('Venezuela','Colombia (North Coast)','Yes','No'),
	array('Venezuela','Northwest Atlantic','Yes','No'),
	array('Venezuela','Carribean Sea','Yes','No'),
	array('Carribean Islands','Northwest Atlantic','Yes','No'),
	array('Carribean Islands','Gulf of Mexico','Yes','No'),
	array('Carribean Islands','Carribean Sea','Yes','No'),
	array('Chile','Bolivia','No','Yes'),
	array('Chile','Mendoza','No','Yes'),
	array('Chile','Santa Cruz','Yes','Yes'),
	array('Chile','Peru','Yes','Yes'),
	array('Chile','Southwest Atlantic','Yes','No'),
	array('Chile','Southeast Pacific','Yes','No'),
	array('Chile','East Pacific Ocean','Yes','No'),
	array('Guyana','Recife','Yes','Yes'),
	array('Guyana','Brasillia','No','Yes'),
	array('Guyana','Northwest Atlantic','Yes','No'),
	array('Recife','Brasillia','No','Yes'),
	array('Recife','Salvador','Yes','Yes'),
	array('Recife','Mid Atlantic Ocean','Yes','No'),
	array('Recife','Northwest Atlantic','Yes','No'),
	array('Brasillia','Amazon','No','Yes'),
	array('Brasillia','Bolivia','No','Yes'),
	array('Brasillia','Salvador','No','Yes'),
	array('Brasillia','Belo Horizonte','No','Yes'),
	array('Brasillia','Rio de Janeiro','No','Yes'),
	array('Brasillia','Sao Paulo','No','Yes'),
	array('Amazon','Bolivia','No','Yes'),
	array('Amazon','Peru','No','Yes'),
	array('Bolivia','Sao Paulo','No','Yes'),
	array('Bolivia','Mendoza','No','Yes'),
	array('Bolivia','Peru','No','Yes'),
	array('Salvador','Belo Horizonte','No','Yes'),
	array('Salvador','Rio de Janeiro','Yes','Yes'),
	array('Salvador','Mid Atlantic Ocean','Yes','No'),
	array('Salvador','West Atlantic Ocean','Yes','No'),
	array('Belo Horizonte','Rio de Janeiro','No','Yes'),
	array('Rio de Janeiro','Sao Paulo','Yes','Yes'),
	array('Rio de Janeiro','West Atlantic Ocean','Yes','No'),
	array('Sao Paulo','Uruguay','Yes','Yes'),
	array('Sao Paulo','Mendoza','No','Yes'),
	array('Sao Paulo','West Atlantic Ocean','Yes','No'),
	array('Uruguay','Buenos Aires','Yes','Yes'),
	array('Uruguay','Mendoza','No','Yes'),
	array('Uruguay','West Atlantic Ocean','Yes','No'),
	array('Buenos Aires','Mendoza','No','Yes'),
	array('Buenos Aires','Santa Cruz','Yes','Yes'),
	array('Buenos Aires','West Atlantic Ocean','Yes','No'),
	array('Buenos Aires','Southwest Atlantic','Yes','No'),
	array('Mendoza','Santa Cruz','No','Yes'),
	array('Santa Cruz','Southwest Atlantic','Yes','No'),
	array('Northwest Indian','Red Sea','Yes','No'),
	array('Northwest Indian','Bombay','Yes','No'),
	array('Northwest Indian','Pakistan','Yes','No'),
	array('Northwest Indian','Iran','Yes','No'),
	array('Northwest Indian','Iraq','Yes','No'),
	array('Northwest Indian','Somalia','Yes','No'),
	array('Northwest Indian','Saudi Arabia (South Coast)','Yes','No'),
	array('Northwest Indian','Kenya','Yes','No'),
	array('Northwest Indian','Madagascar','Yes','No'),
	array('Northwest Indian','Mid Indian Ocean','Yes','No'),
	array('Northwest Indian','Northeast Indian','Yes','No'),
	array('Northwest Indian','Mozambique Channel','Yes','No'),
	array('Red Sea','Egypt','Yes','No'),
	array('Red Sea','Sudan','Yes','No'),
	array('Red Sea','Ethiopia','Yes','No'),
	array('Red Sea','Somalia','Yes','No'),
	array('Red Sea','Saudi Arabia (South Coast)','Yes','No'),
	array('Java Sea','Western Australia','Yes','No'),
	array('Java Sea','Northern Territory','Yes','No'),
	array('Java Sea','Queensland','Yes','No'),
	array('Java Sea','Indonesia','Yes','No'),
	array('Java Sea','Coral Sea','Yes','No'),
	array('Java Sea','Northeast Indian','Yes','No'),
	array('Bay of Bengal','Thailand','Yes','No'),
	array('Bay of Bengal','Burma','Yes','No'),
	array('Bay of Bengal','Bangladesh','Yes','No'),
	array('Bay of Bengal','Bombay','Yes','No'),
	array('Bay of Bengal','Calcutta','Yes','No'),
	array('Bay of Bengal','Northeast Indian','Yes','No'),
	array('Spain','France','No','Yes'),
	array('Spain','France (North Coast)','Yes','No'),
	array('Spain','France (South Coast)','Yes','No'),
	array('Spain','Northeast Atlantic','Yes','No'),
	array('Spain','Western Mediterranean','Yes','No'),
	array('France','Germany','No','Yes'),
	array('France','Italy','No','Yes'),
	array('Germany','Italy','No','Yes'),
	array('Germany','Austria-Hungary','No','Yes'),
	array('Germany','Poland','Yes','Yes'),
	array('Germany','France (North Coast)','Yes','No'),
	array('Germany','Scandinavia','Yes','Yes'),
	array('Germany','Norwegian Sea','Yes','No'),
	array('Germany','Baltic Sea','Yes','No'),
	array('Italy','Austria-Hungary','Yes','Yes'),
	array('Italy','France (South Coast)','Yes','No'),
	array('Italy','Western Mediterranean','Yes','No'),
	array('Italy','Eastern Mediterranean','Yes','No'),
	array('Austria-Hungary','Poland','No','Yes'),
	array('Austria-Hungary','Ukraine','No','Yes'),
	array('Austria-Hungary','Balkans','No','Yes'),
	array('Austria-Hungary','Balkans (South Coast)','Yes','No'),
	array('Austria-Hungary','Eastern Mediterranean','Yes','No'),
	array('Poland','Baltic States','Yes','Yes'),
	array('Poland','Belorussia','No','Yes'),
	array('Poland','Ukraine','No','Yes'),
	array('Poland','Baltic Sea','Yes','No'),
	array('Baltic States','Saint Petersburg','No','Yes'),
	array('Baltic States','Belorussia','No','Yes'),
	array('Baltic States','Saint Petersburg (South Coast)','Yes','No'),
	array('Baltic States','Baltic Sea','Yes','No'),
	array('Saint Petersburg','Belorussia','No','Yes'),
	array('Saint Petersburg','Moscow','No','Yes'),
	array('Saint Petersburg','Perm','No','Yes'),
	array('Saint Petersburg','Scandinavia','No','Yes'),
	array('Belorussia','Ukraine','No','Yes'),
	array('Belorussia','Moscow','No','Yes'),
	array('Ukraine','Black Sea','Yes','No'),
	array('Ukraine','Balkans','No','Yes'),
	array('Ukraine','Moscow','Yes','Yes'),
	array('Ukraine','Balkans (East Coast)','Yes','No'),
	array('Black Sea','Moscow','Yes','No'),
	array('Black Sea','Armenia','Yes','No'),
	array('Black Sea','Turkey','Yes','No'),
	array('Black Sea','Balkans (East Coast)','Yes','No'),
	array('Balkans','Turkey','No','Yes'),
	array('Moscow','Perm','No','Yes'),
	array('Moscow','Armenia','Yes','Yes'),
	array('Moscow','West Central Asia','No','Yes'),
	array('Perm','Norilsk','Yes','Yes'),
	array('Perm','Omsk','No','Yes'),
	array('Perm','Saint Petersburg (North Coast)','Yes','No'),
	array('Perm','West Central Asia','No','Yes'),
	array('Perm','Siberian Sea','Yes','No'),
	array('Norilsk','Yakutsk','No','Yes'),
	array('Norilsk','Omsk','No','Yes'),
	array('Norilsk','Irkutsk','No','Yes'),
	array('Norilsk','Yakutsk (North Coast)','Yes','No'),
	array('Norilsk','Siberian Sea','Yes','No'),
	array('Yakutsk','Irkutsk','No','Yes'),
	array('Yakutsk','Vladivostok','No','Yes'),
	array('Yakutsk','Kamchatka','No','Yes'),
	array('Omsk','Irkutsk','No','Yes'),
	array('Omsk','Western China','No','Yes'),
	array('Omsk','Mongolia','No','Yes'),
	array('Omsk','West Central Asia','No','Yes'),
	array('Omsk','East Central Asia','No','Yes'),
	array('Irkutsk','Inner Mongolia','No','Yes'),
	array('Irkutsk','Vladivostok','No','Yes'),
	array('Irkutsk','Mongolia','No','Yes'),
	array('Inner Mongolia','Western China','No','Yes'),
	array('Inner Mongolia','Beijing','No','Yes'),
	array('Inner Mongolia','Vladivostok','No','Yes'),
	array('Inner Mongolia','Heilongjiang','No','Yes'),
	array('Inner Mongolia','Lanzhou','No','Yes'),
	array('Inner Mongolia','Mongolia','No','Yes'),
	array('Western China','Lanzhou','No','Yes'),
	array('Western China','Delhi','No','Yes'),
	array('Western China','Pakistan','No','Yes'),
	array('Western China','Afghanistan','No','Yes'),
	array('Western China','Mongolia','No','Yes'),
	array('Western China','East Central Asia','No','Yes'),
	array('Western China','Tibet','No','Yes'),
	array('Beijing','Heilongjiang','No','Yes'),
	array('Beijing','Korea','Yes','Yes'),
	array('Beijing','Shanghai','Yes','Yes'),
	array('Beijing','Lanzhou','No','Yes'),
	array('Beijing','Yellow Sea','Yes','No'),
	array('Vladivostok','Heilongjiang','No','Yes'),
	array('Vladivostok','Korea','Yes','Yes'),
	array('Vladivostok','Yakutsk (South Coast)','Yes','No'),
	array('Vladivostok','Sea of Othoksk','Yes','No'),
	array('Vladivostok','Sea of Japan','Yes','No'),
	array('Heilongjiang','Korea','No','Yes'),
	array('Korea','Sea of Japan','Yes','No'),
	array('Korea','Yellow Sea','Yes','No'),
	array('Shanghai','Guangzhou','Yes','Yes'),
	array('Shanghai','Lanzhou','No','Yes'),
	array('Shanghai','Yellow Sea','Yes','No'),
	array('Guangzhou','Vietnam','Yes','Yes'),
	array('Guangzhou','Lanzhou','No','Yes'),
	array('Guangzhou','Yellow Sea','Yes','No'),
	array('Guangzhou','South China Sea','Yes','No'),
	array('Vietnam','Thailand','Yes','Yes'),
	array('Vietnam','Burma','No','Yes'),
	array('Vietnam','Lanzhou','No','Yes'),
	array('Vietnam','South China Sea','Yes','No'),
	array('Thailand','Burma','Yes','Yes'),
	array('Thailand','South China Sea','Yes','No'),
	array('Thailand','Northeast Indian','Yes','No'),
	array('Burma','Bangladesh','Yes','Yes'),
	array('Burma','Lanzhou','No','Yes'),
	array('Bangladesh','Lanzhou','No','Yes'),
	array('Bangladesh','Calcutta','Yes','Yes'),
	array('Bangladesh','Tibet','No','Yes'),
	array('Lanzhou','Tibet','No','Yes'),
	array('Bombay','Delhi','No','Yes'),
	array('Bombay','Pakistan','Yes','Yes'),
	array('Bombay','Calcutta','Yes','Yes'),
	array('Bombay','Northeast Indian','Yes','No'),
	array('Delhi','Pakistan','No','Yes'),
	array('Delhi','Calcutta','No','Yes'),
	array('Delhi','Tibet','No','Yes'),
	array('Pakistan','Afghanistan','No','Yes'),
	array('Pakistan','Iran','Yes','Yes'),
	array('Afghanistan','Iran','No','Yes'),
	array('Afghanistan','East Central Asia','No','Yes'),
	array('Iran','Armenia','No','Yes'),
	array('Iran','Turkey','No','Yes'),
	array('Iran','Iraq','Yes','Yes'),
	array('Iran','West Central Asia','No','Yes'),
	array('Iran','East Central Asia','No','Yes'),
	array('Armenia','Turkey','Yes','Yes'),
	array('Turkey','Syria','Yes','Yes'),
	array('Turkey','Iraq','No','Yes'),
	array('Turkey','Balkans (South Coast)','Yes','No'),
	array('Turkey','Balkans (East Coast)','Yes','No'),
	array('Turkey','Eastern Mediterranean','Yes','No'),
	array('Syria','Iraq','No','Yes'),
	array('Syria','Saudi Arabia','No','Yes'),
	array('Syria','Saudi Arabia (North Coast)','Yes','No'),
	array('Syria','Eastern Mediterranean','Yes','No'),
	array('Iraq','Saudi Arabia','No','Yes'),
	array('Iraq','Saudi Arabia (South Coast)','Yes','No'),
	array('Saudi Arabia','Egypt','No','Yes'),
	array('Western Australia','Northern Territory','Yes','Yes'),
	array('Western Australia','South Australia','Yes','Yes'),
	array('Western Australia','Southeast Indian','Yes','No'),
	array('Western Australia','Mid Indian Ocean','Yes','No'),
	array('Western Australia','Northeast Indian','Yes','No'),
	array('Northern Territory','Queensland','Yes','Yes'),
	array('Northern Territory','South Australia','No','Yes'),
	array('Queensland','New South Wales','Yes','Yes'),
	array('Queensland','South Australia','No','Yes'),
	array('Queensland','Coral Sea','Yes','No'),
	array('New South Wales','Victoria','Yes','Yes'),
	array('New South Wales','South Australia','No','Yes'),
	array('New South Wales','Coral Sea','Yes','No'),
	array('New South Wales','Tasman Sea','Yes','No'),
	array('Victoria','South Australia','Yes','Yes'),
	array('Victoria','Tasman Sea','Yes','No'),
	array('Victoria','Southeast Indian','Yes','No'),
	array('South Australia','Southeast Indian','Yes','No'),
	array('New Zealand','Southwest Pacific','Yes','No'),
	array('New Zealand','Coral Sea','Yes','No'),
	array('New Zealand','Tasman Sea','Yes','No'),
	array('New Zealand','Southeast Indian','Yes','No'),
	array('Indonesia','West Pacific Ocean','Yes','No'),
	array('Indonesia','South China Sea','Yes','No'),
	array('Indonesia','Coral Sea','Yes','No'),
	array('Indonesia','Northeast Indian','Yes','No'),
	array('Phillipines','West Pacific Ocean','Yes','No'),
	array('Phillipines','Yellow Sea','Yes','No'),
	array('Phillipines','South China Sea','Yes','No'),
	array('Morocco','Algeria','Yes','Yes'),
	array('Morocco','Mauritania','Yes','Yes'),
	array('Morocco','Northeast Atlantic','Yes','No'),
	array('Morocco','Western Mediterranean','Yes','No'),
	array('Algeria','Libya','Yes','Yes'),
	array('Algeria','Mauritania','No','Yes'),
	array('Algeria','Mali','No','Yes'),
	array('Algeria','Niger','No','Yes'),
	array('Algeria','Western Mediterranean','Yes','No'),
	array('Libya','Egypt','Yes','Yes'),
	array('Libya','Sudan','No','Yes'),
	array('Libya','Niger','No','Yes'),
	array('Libya','Chad','No','Yes'),
	array('Libya','Western Mediterranean','Yes','No'),
	array('Libya','Eastern Mediterranean','Yes','No'),
	array('Egypt','Sudan','Yes','Yes'),
	array('Egypt','Saudi Arabia (North Coast)','Yes','No'),
	array('Egypt','Saudi Arabia (South Coast)','Yes','No'),
	array('Egypt','Eastern Mediterranean','Yes','No'),
	array('Sudan','Ethiopia','Yes','Yes'),
	array('Sudan','Chad','No','Yes'),
	array('Sudan','Central African Republic','No','Yes'),
	array('Sudan','Zaire','No','Yes'),
	array('Sudan','Kenya','No','Yes'),
	array('Ethiopia','Somalia','Yes','Yes'),
	array('Ethiopia','Kenya','No','Yes'),
	array('Somalia','Kenya','Yes','Yes'),
	array('Mauritania','Mali','No','Yes'),
	array('Mauritania','Guinea','Yes','Yes'),
	array('Mauritania','Northeast Atlantic','Yes','No'),
	array('Mauritania','Mid Atlantic Ocean','Yes','No'),
	array('Mali','Niger','No','Yes'),
	array('Mali','Guinea','No','Yes'),
	array('Mali','Ghana','No','Yes'),
	array('Niger','Chad','No','Yes'),
	array('Niger','Ghana','No','Yes'),
	array('Niger','Cameroon','No','Yes'),
	array('Chad','Cameroon','No','Yes'),
	array('Chad','Central African Republic','No','Yes'),
	array('Guinea','Ghana','Yes','Yes'),
	array('Guinea','Mid Atlantic Ocean','Yes','No'),
	array('Guinea','East Atlantic Ocean','Yes','No'),
	array('Ghana','Cameroon','Yes','Yes'),
	array('Ghana','East Atlantic Ocean','Yes','No'),
	array('Cameroon','Central African Republic','No','Yes'),
	array('Cameroon','Congo','Yes','Yes'),
	array('Cameroon','East Atlantic Ocean','Yes','No'),
	array('Central African Republic','Congo','No','Yes'),
	array('Central African Republic','Zaire','No','Yes'),
	array('Congo','Zaire','No','Yes'),
	array('Congo','Angola','Yes','Yes'),
	array('Congo','East Atlantic Ocean','Yes','No'),
	array('Zaire','Angola','No','Yes'),
	array('Zaire','Zambia','No','Yes'),
	array('Zaire','Kenya','No','Yes'),
	array('Mozambique','South Africa','Yes','Yes'),
	array('Mozambique','Zimbabwe','No','Yes'),
	array('Mozambique','Zambia','No','Yes'),
	array('Mozambique','Kenya','Yes','Yes'),
	array('Mozambique','Mozambique Channel','Yes','No'),
	array('South Africa','Zimbabwe','No','Yes'),
	array('South Africa','Namibia','Yes','Yes'),
	array('South Africa','Botswana','No','Yes'),
	array('South Africa','East Atlantic Ocean','Yes','No'),
	array('South Africa','Southeast Atlantic','Yes','No'),
	array('South Africa','Southwest Indian','Yes','No'),
	array('South Africa','Mozambique Channel','Yes','No'),
	array('Zimbabwe','Zambia','No','Yes'),
	array('Zimbabwe','Botswana','No','Yes'),
	array('Namibia','Angola','Yes','Yes'),
	array('Namibia','Botswana','No','Yes'),
	array('Namibia','East Atlantic Ocean','Yes','No'),
	array('Angola','Zambia','No','Yes'),
	array('Angola','Botswana','No','Yes'),
	array('Angola','East Atlantic Ocean','Yes','No'),
	array('Zambia','Kenya','No','Yes'),
	array('Zambia','Botswana','No','Yes'),
	array('Yukon (North Coast)','Chukchi Sea','Yes','No'),
	array('Yukon (South Coast)','North Pacific Ocean','Yes','No'),
	array('Quebec (North Coast)','Hudson Bay','Yes','No'),
	array('Quebec (South Coast)','Northwest Atlantic','Yes','No'),
	array('Monterrey (West Coast)','Mexico (West Coast)','Yes','No'),
	array('Monterrey (West Coast)','Northeast Pacific','Yes','No'),
	array('Monterrey (West Coast)','North Pacific Ocean','Yes','No'),
	array('Monterrey (East Coast)','Mexico (East Coast)','Yes','No'),
	array('Monterrey (East Coast)','Gulf of Mexico','Yes','No'),
	array('Mexico (West Coast)','Northeast Pacific','Yes','No'),
	array('Mexico (East Coast)','Gulf of Mexico','Yes','No'),
	array('Mexico (East Coast)','Carribean Sea','Yes','No'),
	array('Colombia (West Coast)','Peru','Yes','No'),
	array('Colombia (West Coast)','Northeast Pacific','Yes','No'),
	array('Colombia (North Coast)','Carribean Sea','Yes','No'),
	array('France (North Coast)','Northeast Atlantic','Yes','No'),
	array('France (North Coast)','Norwegian Sea','Yes','No'),
	array('France (South Coast)','Western Mediterranean','Yes','No'),
	array('Saint Petersburg (North Coast)','Scandinavia','Yes','No'),
	array('Saint Petersburg (North Coast)','Greenland Sea','Yes','No'),
	array('Saint Petersburg (North Coast)','Siberian Sea','Yes','No'),
	array('Saint Petersburg (South Coast)','Scandinavia','Yes','No'),
	array('Saint Petersburg (South Coast)','Baltic Sea','Yes','No'),
	array('Balkans (South Coast)','Eastern Mediterranean','Yes','No'),
	array('Saudi Arabia (North Coast)','Eastern Mediterranean','Yes','No'),
	array('Yakutsk (North Coast)','Kamchatka','Yes','No'),
	array('Yakutsk (North Coast)','Siberian Sea','Yes','No'),
	array('Yakutsk (North Coast)','Chukchi Sea','Yes','No'),
	array('Yakutsk (South Coast)','Kamchatka','Yes','No'),
	array('Yakutsk (South Coast)','Sea of Othoksk','Yes','No'),
	array('Kenya','Mozambique Channel','Yes','No'),
	array('Scandinavia','Norwegian Sea','Yes','No'),
	array('Scandinavia','Baltic Sea','Yes','No'),
	array('Scandinavia','Greenland Sea','Yes','No'),
	array('Peru','East Pacific Ocean','Yes','No'),
	array('Peru','Northeast Pacific','Yes','No'),
	array('Kamchatka','Chukchi Sea','Yes','No'),
	array('Kamchatka','Bering Sea','Yes','No'),
	array('Kamchatka','Northwest Pacific','Yes','No'),
	array('Kamchatka','Sea of Othoksk','Yes','No'),
	array('Hokkaido','Honshu','Yes','Yes'),
	array('Hokkaido','Northwest Pacific','Yes','No'),
	array('Hokkaido','Sea of Othoksk','Yes','No'),
	array('Hokkaido','Sea of Japan','Yes','No'),
	array('Honshu','Northwest Pacific','Yes','No'),
	array('Honshu','Sea of Japan','Yes','No'),
	array('Honshu','West Pacific Ocean','Yes','No'),
	array('Honshu','Yellow Sea','Yes','No'),
	array('West Central Asia','East Central Asia','No','Yes'),
	array('Calcutta','Tibet','No','Yes'),
	array('Wilkes Land','Enderby Land','Yes','Yes'),
	array('Wilkes Land','Victoria Land','Yes','Yes'),
	array('Wilkes Land','South Pole','No','Yes'),
	array('Wilkes Land','Southeast Indian','Yes','No'),
	array('Wilkes Land','Southwest Indian','Yes','No'),
	array('Marie Byrd Land','Graham Land','Yes','Yes'),
	array('Marie Byrd Land','Victoria Land','Yes','Yes'),
	array('Marie Byrd Land','South Pole','No','Yes'),
	array('Marie Byrd Land','Southeast Pacific','Yes','No'),
	array('Marie Byrd Land','Southwest Pacific','Yes','No'),
	array('Northeast Atlantic','Mid Atlantic Ocean','Yes','No'),
	array('Northeast Atlantic','Northwest Atlantic','Yes','No'),
	array('Northeast Atlantic','Labrador Sea','Yes','No'),
	array('Northeast Atlantic','Norwegian Sea','Yes','No'),
	array('Northeast Atlantic','Western Mediterranean','Yes','No'),
	array('Mid Atlantic Ocean','West Atlantic Ocean','Yes','No'),
	array('Mid Atlantic Ocean','East Atlantic Ocean','Yes','No'),
	array('Mid Atlantic Ocean','Northwest Atlantic','Yes','No'),
	array('West Atlantic Ocean','East Atlantic Ocean','Yes','No'),
	array('West Atlantic Ocean','Southwest Atlantic','Yes','No'),
	array('West Atlantic Ocean','Southeast Atlantic','Yes','No'),
	array('East Atlantic Ocean','Southeast Atlantic','Yes','No'),
	array('Southwest Atlantic','Southeast Atlantic','Yes','No'),
	array('Southwest Atlantic','Graham Land','Yes','No'),
	array('Southwest Atlantic','Maud Land','Yes','No'),
	array('Southwest Atlantic','Southeast Pacific','Yes','No'),
	array('Northwest Atlantic','Gulf of Mexico','Yes','No'),
	array('Northwest Atlantic','Carribean Sea','Yes','No'),
	array('Northwest Atlantic','Labrador Sea','Yes','No'),
	array('Southeast Atlantic','Maud Land','Yes','No'),
	array('Southeast Atlantic','Enderby Land','Yes','No'),
	array('Southeast Atlantic','Southwest Indian','Yes','No'),
	array('Gulf of Mexico','Carribean Sea','Yes','No'),
	array('Labrador Sea','Norwegian Sea','Yes','No'),
	array('Labrador Sea','Greenland Sea','Yes','No'),
	array('Labrador Sea','Hudson Bay','Yes','No'),
	array('Norwegian Sea','Greenland Sea','Yes','No'),
	array('Western Mediterranean','Eastern Mediterranean','Yes','No'),
	array('Greenland Sea','Hudson Bay','Yes','No'),
	array('Greenland Sea','Siberian Sea','Yes','No'),
	array('Greenland Sea','Chukchi Sea','Yes','No'),
	array('Greenland Sea','Arctic Circle','Yes','No'),
	array('Siberian Sea','Chukchi Sea','Yes','No'),
	array('Siberian Sea','Arctic Circle','Yes','No'),
	array('Chukchi Sea','Arctic Circle','Yes','No'),
	array('Graham Land','Maud Land','Yes','Yes'),
	array('Graham Land','South Pole','No','Yes'),
	array('Graham Land','Southeast Pacific','Yes','No'),
	array('Maud Land','Enderby Land','Yes','Yes'),
	array('Maud Land','South Pole','No','Yes'),
	array('Enderby Land','South Pole','No','Yes'),
	array('Enderby Land','Southwest Indian','Yes','No'),
	array('Victoria Land','South Pole','No','Yes'),
	array('Victoria Land','Southwest Pacific','Yes','No'),
	array('Victoria Land','Southeast Indian','Yes','No'),
	array('Southeast Pacific','Southwest Pacific','Yes','No'),
	array('Southeast Pacific','East Pacific Ocean','Yes','No'),
	array('Southwest Pacific','East Pacific Ocean','Yes','No'),
	array('Southwest Pacific','Oceanian Islands','Yes','No'),
	array('Southwest Pacific','Coral Sea','Yes','No'),
	array('Southwest Pacific','Southeast Indian','Yes','No'),
	array('East Pacific Ocean','Northeast Pacific','Yes','No'),
	array('East Pacific Ocean','Oceanian Islands','Yes','No'),
	array('Northeast Pacific','North Pacific Ocean','Yes','No'),
	array('Northeast Pacific','Oceanian Islands','Yes','No'),
	array('Northeast Pacific','Hawaii','Yes','No'),
	array('Northeast Pacific','Central Pacific Ocean','Yes','No'),
	array('North Pacific Ocean','Hawaii','Yes','No'),
	array('North Pacific Ocean','Bering Sea','Yes','No'),
	array('North Pacific Ocean','Northwest Pacific','Yes','No'),
	array('Oceanian Islands','Central Pacific Ocean','Yes','No'),
	array('Oceanian Islands','Coral Sea','Yes','No'),
	array('Hawaii','Central Pacific Ocean','Yes','No'),
	array('Hawaii','Northwest Pacific','Yes','No'),
	array('Madagascar','Southwest Indian','Yes','No'),
	array('Madagascar','Mid Indian Ocean','Yes','No'),
	array('Madagascar','Mozambique Channel','Yes','No'),
	array('Central Pacific Ocean','Northwest Pacific','Yes','No'),
	array('Central Pacific Ocean','West Pacific Ocean','Yes','No'),
	array('Central Pacific Ocean','Coral Sea','Yes','No'),
	array('Bering Sea','Northwest Pacific','Yes','No'),
	array('Northwest Pacific','Sea of Othoksk','Yes','No'),
	array('Northwest Pacific','West Pacific Ocean','Yes','No'),
	array('Sea of Othoksk','Sea of Japan','Yes','No'),
	array('Sea of Japan','Yellow Sea','Yes','No'),
	array('West Pacific Ocean','Yellow Sea','Yes','No'),
	array('West Pacific Ocean','South China Sea','Yes','No'),
	array('West Pacific Ocean','Coral Sea','Yes','No'),
	array('Yellow Sea','South China Sea','Yes','No'),
	array('South China Sea','Northeast Indian','Yes','No'),
	array('Coral Sea','Tasman Sea','Yes','No'),
	array('Tasman Sea','Southeast Indian','Yes','No'),
	array('Southeast Indian','Southwest Indian','Yes','No'),
	array('Southeast Indian','Mid Indian Ocean','Yes','No'),
	array('Southwest Indian','Mid Indian Ocean','Yes','No'),
	array('Southwest Indian','Mozambique Channel','Yes','No'),
	array('Mid Indian Ocean','Northeast Indian','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

// Custom footer not changed by edit tool

// Just create the database as usual:
InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);

// Copy the smallmap-sample to the cache-directory to avoid a screwed variantpage (there is no smallmap available)
if (!file_exists('variants/'.$this->name.'/cache/sampleMap.png'))
	copy ('variants/'.$this->name.'/resources/sampleMap.png','variants/'.$this->name.'/cache/sampleMap.png');

?>


