<?php
// This is file installs the map data for the TiglathPileser variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Greece', 'Coast', 'No', 0, 170, 18, 103, 19),
	array('Midaeion', 'Coast', 'Yes', 7, 247, 83, 156, 51),
	array('Sea of Sunset', 'Sea', 'No', 0, 270, 374, 168, 228),
	array('Sea of Amurru', 'Sea', 'No', 0, 294, 291, 200, 169),
	array('Sea of Zalpa', 'Sea', 'No', 0, 634, 35, 409, 22),
	array('Sea of Philistia', 'Sea', 'No', 0, 430, 526, 256, 317),
	array('Great Green', 'Sea', 'No', 0, 60, 460, 80, 288),
	array('Erythraean Sea', 'Sea', 'No', 0, 1471, 1327, 904, 761),
	array('Hadramut', 'Coast', 'No', 0, 1266, 1265, 765, 772),
	array('Sea of Sunrise', 'Sea', 'No', 0, 1234, 705, 733, 421),
	array('Gordion', 'Land', 'Yes', 7, 386, 113, 244, 46),
	array('Paphlagonia', 'Coast', 'No', 0, 357, 49, 234, 25),
	array('Thamud', 'Coast', 'Yes', 0, 711, 941, 432, 555),
	array('Halitu', 'Land', 'No', 0, 594, 113, 364, 66),
	array('Kaska', 'Coast', 'No', 0, 579, 61, 405, 41),
	array('Quwe', 'Coast', 'Yes', 0, 512, 257, 308, 154),
	array('Kilizu', 'Land', 'No', 0, 934, 328, 564, 175),
	array('Tabal', 'Land', 'No', 0, 522, 172, 316, 100),
	array('Punt', 'Coast', 'Yes', 0, 748, 1333, 436, 800),
	array('Sirwah', 'Coast', 'Yes', 8, 1052, 1274, 641, 758),
	array('Kition', 'Coast', 'Yes', 0, 432, 344, 269, 214),
	array('Hamath', 'Coast', 'Yes', 0, 562, 296, 336, 194),
	array('Sidon', 'Coast', 'Yes', 0, 530, 413, 324, 249),
	array('Carchemish', 'Coast', 'Yes', 0, 609, 284, 368, 171),
	array('Hatarikka', 'Land', 'No', 0, 604, 366, 368, 215),
	array('Suhu', 'Coast', 'No', 0, 781, 445, 474, 272),
	array('Harran', 'Land', 'No', 1, 722, 273, 434, 149),
	array('Bit-Zamani', 'Land', 'No', 0, 754, 183, 416, 106),
	array('Nineveh', 'Coast', 'Yes', 1, 866, 258, 525, 150),
	array('Kalhu', 'Coast', 'Yes', 1, 892, 317, 544, 194),
	array('Babylon', 'Coast', 'Yes', 2, 967, 516, 579, 311),
	array('Arzashkun', 'Coast', 'Yes', 3, 853, 91, 516, 52),
	array('Colchis', 'Coast', 'No', 0, 850, 23, 505, 10),
	array('Tushpa', 'Land', 'Yes', 3, 829, 162, 504, 100),
	array('Erebuni', 'Land', 'No', 3, 995, 130, 584, 53),
	array('Arbela', 'Land', 'Yes', 0, 982, 286, 592, 170),
	array('Arrapha', 'Land', 'Yes', 0, 1040, 336, 615, 205),
	array('Mannea', 'Land', 'Yes', 0, 1015, 226, 613, 137),
	array('Ellipi', 'Land', 'No', 0, 1151, 432, 661, 250),
	array('Shupria', 'Land', 'No', 0, 770, 229, 468, 133),
	array('Opis', 'Coast', 'Yes', 0, 970, 458, 600, 275),
	array('Der', 'Land', 'No', 0, 1023, 397, 617, 236),
	array('Lahiru', 'Coast', 'No', 0, 924, 365, 564, 242),
	array('Gilzan', 'Land', 'No', 3, 911, 123, 560, 78),
	array('Ur', 'Coast', 'Yes', 2, 998, 581, 597, 354),
	array('Media', 'Land', 'No', 0, 1222, 385, 739, 234),
	array('Gambulu', 'Coast', 'No', 5, 1064, 506, 645, 306),
	array('Susa', 'Coast', 'Yes', 5, 1128, 538, 699, 346),
	array('Galilee', 'Coast', 'No', 0, 502, 491, 306, 297),
	array('Parsua', 'Coast', 'No', 0, 1372, 676, 820, 415),
	array('Dilmun', 'Coast', 'Yes', 0, 1339, 904, 802, 547),
	array('Qade', 'Coast', 'Yes', 0, 1568, 903, 915, 529),
	array('North Arbaya', 'Land', 'No', 0, 906, 808, 544, 483),
	array('North Qedar', 'Coast', 'No', 0, 797, 593, 456, 369),
	array('Tayma', 'Coast', 'Yes', 0, 590, 781, 350, 467),
	array('Damascus', 'Land', 'Yes', 0, 543, 519, 325, 320),
	array('Bazu', 'Coast', 'No', 0, 1047, 665, 640, 383),
	array('Tanis', 'Coast', 'Yes', 6, 357, 569, 216, 343),
	array('Heliopolis', 'Coast', 'Yes', 6, 330, 637, 205, 370),
	array('Libya', 'Coast', 'No', 0, 238, 715, 145, 424),
	array('Tarut', 'Coast', 'Yes', 0, 1157, 786, 695, 477),
	array('Akine', 'Coast', 'No', 4, 266, 966, 152, 600),
	array('Ardini', 'Land', 'No', 0, 902, 210, 553, 146),
	array('Ma&#039;rib', 'Coast', 'Yes', 8, 913, 1273, 560, 770),
	array('Rub&#039; al Khali', 'Land', 'No', 0, 1271, 1061, 789, 628),
	array('Ma&#039;in', 'Coast', 'No', 0, 853, 1181, 498, 694),
	array('Hatallu', 'Coast', 'No', 0, 864, 405, 529, 265),
	array('Hatallu (West Coast)', 'Coast', 'No', 0, 846, 416, 514, 254),
	array('Hatallu (East Coast)', 'Coast', 'No', 0, 914, 454, 551, 256),
	array('Anshan', 'Coast', 'Yes', 5, 1207, 574, 742, 374),
	array('Libya (North Coast)', 'Coast', 'No', 0, 225, 596, 140, 367),
	array('Libya (East Coast)', 'Coast', 'No', 0, 312, 819, 152, 476),
	array('Memphis', 'Coast', 'Yes', 6, 282, 584, 179, 334),
	array('South Arbaya', 'Land', 'No', 0, 957, 1058, 640, 650),
	array('Lagash', 'Coast', 'Yes', 2, 1022, 513, 628, 330),
	array('Antt', 'Coast', 'No', 6, 334, 682, 204, 414),
	array('Antt (West Coast)', 'Coast', 'No', 6, 366, 694, 181, 429),
	array('Antt (East Coast)', 'Coast', 'No', 6, 296, 713, 221, 425),
	array('Straits of Tiran', 'Sea', 'No', 0, 504, 785, 304, 478),
	array('Upper Nubia', 'Land', 'No', 0, 454, 1303, 278, 793),
	array('D&#039;mt', 'Coast', 'Yes', 0, 610, 1224, 362, 742),
	array('Thebes', 'Coast', 'Yes', 4, 403, 801, 244, 481),
	array('Thebes (West Coast)', 'Coast', 'No', 4, 341, 767, 198, 467),
	array('Thebes (East Coast)', 'Coast', 'No', 4, 422, 800, 256, 484),
	array('Napata', 'Coast', 'Yes', 4, 350, 1002, 236, 600),
	array('Napata (West Coast)', 'Coast', 'No', 4, 258, 1092, 161, 637),
	array('Napata (East Coast)', 'Coast', 'No', 4, 462, 953, 272, 586),
	array('Meroe', 'Coast', 'Yes', 4, 349, 1179, 208, 713),
	array('Lydia', 'Coast', 'No', 0, 209, 196, 130, 120),
	array('Kelainai', 'Coast', 'Yes', 7, 271, 249, 165, 158),
	array('Pamphylia', 'Coast', 'No', 0, 344, 225, 210, 140),
	array('Hilakku', 'Coast', 'Yes', 0, 434, 237, 258, 145),
	array('Diauehi', 'Land', 'Yes', 3, 725, 117, 444, 67),
	array('Ashkelon', 'Coast', 'Yes', 0, 435, 574, 257, 349),
	array('Israel', 'Coast', 'Yes', 0, 478, 547, 293, 329),
	array('Judah', 'Land', 'No', 0, 513, 556, 311, 338),
	array('Mafkat', 'Coast', 'No', 0, 419, 648, 256, 400),
	array('Melid', 'Land', 'Yes', 0, 617, 191, 373, 118),
	array('Sam&#039;al', 'Coast', 'No', 0, 576, 257, 348, 157),
	array('Til Barsip', 'Coast', 'Yes', 0, 662, 277, 404, 172),
	array('Arwad', 'Coast', 'No', 0, 549, 370, 335, 218),
	array('Tyre', 'Coast', 'Yes', 0, 514, 446, 315, 267),
	array('Suburu', 'Land', 'No', 0, 560, 441, 336, 268),
	array('Aram', 'Land', 'No', 0, 630, 528, 378, 321),
	array('Blemmyia', 'Coast', 'No', 0, 501, 1063, 303, 641),
	array('Laqe', 'Coast', 'No', 0, 691, 410, 420, 245),
	array('Rasappa', 'Coast', 'No', 1, 779, 360, 449, 192),
	array('Assur', 'Coast', 'Yes', 1, 821, 317, 497, 192),
	array('Rhodes', 'Coast', 'Yes', 0, 178, 281, 108, 167),
	array('Ammon', 'Land', 'No', 0, 576, 597, 353, 364),
	array('Dumah', 'Land', 'Yes', 0, 670, 709, 408, 422),
	array('South Qedar', 'Land', 'No', 0, 881, 718, 545, 399),
	array('Ecbatana', 'Coast', 'Yes', 0, 1097, 325, 656, 189),
	array('Qataban', 'Coast', 'No', 0, 980, 1314, 597, 794),
	array('Qana&#039;', 'Coast', 'Yes', 8, 1120, 1318, 700, 792),
	array('Dhofar', 'Coast', 'Yes', 0, 1525, 1073, 909, 679),
	array('Hajar', 'Land', 'No', 0, 1186, 938, 712, 597),
	array('Edom', 'Land', 'No', 0, 509, 618, 300, 356),
	array('Knossos', 'Coast', 'Yes', 0, 56, 301, 32, 180),
	array('Swenett', 'Coast', 'No', 4, 419, 870, 256, 533),
	array('Swenett (East Coast)', 'Coast', 'No', 4, 461, 866, 288, 536),
	array('Swenett (West Coast)', 'Coast', 'No', 4, 390, 919, 234, 536),
	array('Aegean Sea', 'Sea', 'No', 0, 137, 215, 66, 141),
	array('Red Sea', 'Sea', 'No', 0, 615, 1045, 367, 598),
	array('Gate of Grief', 'Sea', 'No', 0, 834, 1321, 520, 808),
	array('Coast of Canaan', 'Sea', 'No', 0, 469, 417, 270, 264),
	array('Hidalu', 'Land', 'Yes', 5, 1159, 509, 706, 306)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Greece','Midaeion','Yes','Yes'),
	array('Greece','Sea of Zalpa','Yes','No'),
	array('Greece','Great Green','Yes','No'),
	array('Greece','Paphlagonia','Yes','Yes'),
	array('Greece','Aegean Sea','Yes','No'),
	array('Midaeion','Sea of Zalpa','Yes','No'),
	array('Midaeion','Gordion','No','Yes'),
	array('Midaeion','Paphlagonia','Yes','Yes'),
	array('Midaeion','Tabal','No','Yes'),
	array('Midaeion','Lydia','Yes','Yes'),
	array('Midaeion','Kelainai','No','Yes'),
	array('Midaeion','Pamphylia','No','Yes'),
	array('Midaeion','Aegean Sea','Yes','No'),
	array('Sea of Sunset','Sea of Amurru','Yes','No'),
	array('Sea of Sunset','Sea of Philistia','Yes','No'),
	array('Sea of Sunset','Great Green','Yes','No'),
	array('Sea of Sunset','Kition','Yes','No'),
	array('Sea of Sunset','Memphis','Yes','No'),
	array('Sea of Sunset','Rhodes','Yes','No'),
	array('Sea of Sunset','Knossos','Yes','No'),
	array('Sea of Sunset','Aegean Sea','Yes','No'),
	array('Sea of Sunset','Coast of Canaan','Yes','No'),
	array('Sea of Amurru','Quwe','Yes','No'),
	array('Sea of Amurru','Kition','Yes','No'),
	array('Sea of Amurru','Hamath','Yes','No'),
	array('Sea of Amurru','Kelainai','Yes','No'),
	array('Sea of Amurru','Pamphylia','Yes','No'),
	array('Sea of Amurru','Hilakku','Yes','No'),
	array('Sea of Amurru','Sam&#039;al','Yes','No'),
	array('Sea of Amurru','Rhodes','Yes','No'),
	array('Sea of Amurru','Aegean Sea','Yes','No'),
	array('Sea of Amurru','Coast of Canaan','Yes','No'),
	array('Sea of Zalpa','Paphlagonia','Yes','No'),
	array('Sea of Zalpa','Kaska','Yes','No'),
	array('Sea of Zalpa','Arzashkun','Yes','No'),
	array('Sea of Zalpa','Colchis','Yes','No'),
	array('Sea of Zalpa','Aegean Sea','Yes','No'),
	array('Sea of Philistia','Tanis','Yes','No'),
	array('Sea of Philistia','Memphis','Yes','No'),
	array('Sea of Philistia','Ashkelon','Yes','No'),
	array('Sea of Philistia','Israel','Yes','No'),
	array('Sea of Philistia','Coast of Canaan','Yes','No'),
	array('Great Green','Libya (North Coast)','Yes','No'),
	array('Great Green','Memphis','Yes','No'),
	array('Great Green','Knossos','Yes','No'),
	array('Great Green','Aegean Sea','Yes','No'),
	array('Erythraean Sea','Hadramut','Yes','No'),
	array('Erythraean Sea','Sea of Sunrise','Yes','No'),
	array('Erythraean Sea','Parsua','Yes','No'),
	array('Erythraean Sea','Dilmun','Yes','No'),
	array('Erythraean Sea','Qade','Yes','No'),
	array('Erythraean Sea','Qana&#039;','Yes','No'),
	array('Erythraean Sea','Dhofar','Yes','No'),
	array('Erythraean Sea','Gate of Grief','Yes','No'),
	array('Hadramut','Rub&#039; al Khali','No','Yes'),
	array('Hadramut','Qana&#039;','Yes','Yes'),
	array('Hadramut','Dhofar','Yes','Yes'),
	array('Sea of Sunrise','Babylon','Yes','No'),
	array('Sea of Sunrise','Ur','Yes','No'),
	array('Sea of Sunrise','Gambulu','Yes','No'),
	array('Sea of Sunrise','Susa','Yes','No'),
	array('Sea of Sunrise','Parsua','Yes','No'),
	array('Sea of Sunrise','Dilmun','Yes','No'),
	array('Sea of Sunrise','Bazu','Yes','No'),
	array('Sea of Sunrise','Tarut','Yes','No'),
	array('Sea of Sunrise','Anshan','Yes','No'),
	array('Sea of Sunrise','Lagash','Yes','No'),
	array('Gordion','Paphlagonia','No','Yes'),
	array('Gordion','Halitu','No','Yes'),
	array('Gordion','Tabal','No','Yes'),
	array('Paphlagonia','Halitu','No','Yes'),
	array('Paphlagonia','Kaska','Yes','Yes'),
	array('Thamud','North Arbaya','No','Yes'),
	array('Thamud','Tayma','Yes','Yes'),
	array('Thamud','Ma&#039;in','Yes','Yes'),
	array('Thamud','South Arbaya','No','Yes'),
	array('Thamud','Dumah','No','Yes'),
	array('Thamud','South Qedar','No','Yes'),
	array('Thamud','Red Sea','Yes','No'),
	array('Halitu','Kaska','No','Yes'),
	array('Halitu','Tabal','No','Yes'),
	array('Halitu','Diauehi','No','Yes'),
	array('Halitu','Melid','No','Yes'),
	array('Kaska','Arzashkun','Yes','Yes'),
	array('Kaska','Diauehi','No','Yes'),
	array('Quwe','Tabal','No','Yes'),
	array('Quwe','Hilakku','Yes','Yes'),
	array('Quwe','Sam&#039;al','Yes','Yes'),
	array('Kilizu','Nineveh','No','Yes'),
	array('Kilizu','Kalhu','No','Yes'),
	array('Kilizu','Arbela','No','Yes'),
	array('Kilizu','Arrapha','No','Yes'),
	array('Kilizu','Mannea','No','Yes'),
	array('Kilizu','Lahiru','No','Yes'),
	array('Kilizu','Ardini','No','Yes'),
	array('Tabal','Pamphylia','No','Yes'),
	array('Tabal','Hilakku','No','Yes'),
	array('Tabal','Melid','No','Yes'),
	array('Tabal','Sam&#039;al','No','Yes'),
	array('Punt','Upper Nubia','No','Yes'),
	array('Punt','D&#039;mt','Yes','Yes'),
	array('Punt','Qataban','Yes','Yes'),
	array('Punt','Gate of Grief','Yes','No'),
	array('Sirwah','Ma&#039;rib','No','Yes'),
	array('Sirwah','South Arbaya','No','Yes'),
	array('Sirwah','Qataban','Yes','Yes'),
	array('Sirwah','Qana&#039;','Yes','Yes'),
	array('Sirwah','Gate of Grief','Yes','No'),
	array('Kition','Coast of Canaan','Yes','No'),
	array('Hamath','Carchemish','No','Yes'),
	array('Hamath','Hatarikka','No','Yes'),
	array('Hamath','Sam&#039;al','Yes','Yes'),
	array('Hamath','Arwad','Yes','Yes'),
	array('Hamath','Coast of Canaan','Yes','No'),
	array('Sidon','Hatarikka','No','Yes'),
	array('Sidon','Arwad','Yes','Yes'),
	array('Sidon','Tyre','Yes','Yes'),
	array('Sidon','Suburu','No','Yes'),
	array('Sidon','Coast of Canaan','Yes','No'),
	array('Carchemish','Hatarikka','No','Yes'),
	array('Carchemish','Sam&#039;al','No','Yes'),
	array('Carchemish','Til Barsip','Yes','Yes'),
	array('Carchemish','Laqe','Yes','Yes'),
	array('Hatarikka','Arwad','No','Yes'),
	array('Hatarikka','Suburu','No','Yes'),
	array('Hatarikka','Aram','No','Yes'),
	array('Hatarikka','Laqe','No','Yes'),
	array('Suhu','North Qedar','Yes','Yes'),
	array('Suhu','Hatallu','No','Yes'),
	array('Suhu','Hatallu (West Coast)','Yes','No'),
	array('Suhu','Aram','No','Yes'),
	array('Suhu','Laqe','Yes','Yes'),
	array('Suhu','Rasappa','Yes','Yes'),
	array('Harran','Bit-Zamani','No','Yes'),
	array('Harran','Shupria','No','Yes'),
	array('Harran','Til Barsip','No','Yes'),
	array('Harran','Rasappa','No','Yes'),
	array('Harran','Assur','No','Yes'),
	array('Bit-Zamani','Tushpa','No','Yes'),
	array('Bit-Zamani','Shupria','No','Yes'),
	array('Bit-Zamani','Diauehi','No','Yes'),
	array('Bit-Zamani','Melid','No','Yes'),
	array('Bit-Zamani','Sam&#039;al','No','Yes'),
	array('Bit-Zamani','Til Barsip','No','Yes'),
	array('Nineveh','Kalhu','Yes','Yes'),
	array('Nineveh','Shupria','No','Yes'),
	array('Nineveh','Ardini','No','Yes'),
	array('Nineveh','Assur','Yes','Yes'),
	array('Kalhu','Lahiru','Yes','Yes'),
	array('Kalhu','Assur','Yes','Yes'),
	array('Babylon','Opis','Yes','Yes'),
	array('Babylon','Ur','Yes','Yes'),
	array('Babylon','North Qedar','Yes','Yes'),
	array('Babylon','Hatallu','No','Yes'),
	array('Babylon','Hatallu (West Coast)','Yes','No'),
	array('Babylon','Hatallu (East Coast)','Yes','No'),
	array('Babylon','Lagash','Yes','Yes'),
	array('Arzashkun','Colchis','Yes','Yes'),
	array('Arzashkun','Tushpa','No','Yes'),
	array('Arzashkun','Erebuni','No','Yes'),
	array('Arzashkun','Gilzan','No','Yes'),
	array('Arzashkun','Diauehi','No','Yes'),
	array('Colchis','Erebuni','No','Yes'),
	array('Tushpa','Shupria','No','Yes'),
	array('Tushpa','Gilzan','No','Yes'),
	array('Tushpa','Diauehi','No','Yes'),
	array('Erebuni','Mannea','No','Yes'),
	array('Erebuni','Gilzan','No','Yes'),
	array('Erebuni','Media','No','Yes'),
	array('Arbela','Arrapha','No','Yes'),
	array('Arbela','Mannea','No','Yes'),
	array('Arbela','Ecbatana','No','Yes'),
	array('Arrapha','Ellipi','No','Yes'),
	array('Arrapha','Der','No','Yes'),
	array('Arrapha','Lahiru','No','Yes'),
	array('Arrapha','Ecbatana','No','Yes'),
	array('Mannea','Gilzan','No','Yes'),
	array('Mannea','Media','No','Yes'),
	array('Mannea','Ardini','No','Yes'),
	array('Mannea','Ecbatana','No','Yes'),
	array('Ellipi','Der','No','Yes'),
	array('Ellipi','Media','No','Yes'),
	array('Ellipi','Susa','No','Yes'),
	array('Ellipi','Ecbatana','No','Yes'),
	array('Ellipi','Hidalu','No','Yes'),
	array('Shupria','Gilzan','No','Yes'),
	array('Shupria','Ardini','No','Yes'),
	array('Shupria','Assur','No','Yes'),
	array('Opis','Der','No','Yes'),
	array('Opis','Lahiru','Yes','Yes'),
	array('Opis','Gambulu','No','Yes'),
	array('Opis','Hatallu','No','Yes'),
	array('Opis','Hatallu (East Coast)','Yes','No'),
	array('Opis','Lagash','Yes','Yes'),
	array('Der','Lahiru','No','Yes'),
	array('Der','Gambulu','No','Yes'),
	array('Der','Susa','No','Yes'),
	array('Lahiru','Hatallu','No','Yes'),
	array('Lahiru','Hatallu (East Coast)','Yes','No'),
	array('Lahiru','Assur','Yes','Yes'),
	array('Gilzan','Ardini','No','Yes'),
	array('Ur','North Qedar','Yes','Yes'),
	array('Ur','Bazu','Yes','Yes'),
	array('Ur','South Qedar','No','Yes'),
	array('Media','Parsua','No','Yes'),
	array('Media','Ecbatana','No','Yes'),
	array('Media','Hidalu','No','Yes'),
	array('Gambulu','Susa','Yes','Yes'),
	array('Gambulu','Lagash','Yes','Yes'),
	array('Susa','Anshan','Yes','Yes'),
	array('Susa','Hidalu','No','Yes'),
	array('Galilee','Damascus','No','Yes'),
	array('Galilee','Israel','Yes','Yes'),
	array('Galilee','Tyre','Yes','Yes'),
	array('Galilee','Suburu','No','Yes'),
	array('Galilee','Coast of Canaan','Yes','No'),
	array('Parsua','Qade','Yes','Yes'),
	array('Parsua','Anshan','Yes','Yes'),
	array('Parsua','Hidalu','No','Yes'),
	array('Dilmun','Qade','Yes','Yes'),
	array('Dilmun','Tarut','Yes','Yes'),
	array('Dilmun','Rub&#039; al Khali','No','Yes'),
	array('Dilmun','Hajar','No','Yes'),
	array('Qade','Rub&#039; al Khali','No','Yes'),
	array('Qade','Dhofar','Yes','Yes'),
	array('North Arbaya','Bazu','No','Yes'),
	array('North Arbaya','Tarut','No','Yes'),
	array('North Arbaya','South Arbaya','No','Yes'),
	array('North Arbaya','South Qedar','No','Yes'),
	array('North Arbaya','Hajar','No','Yes'),
	array('North Qedar','Hatallu','No','Yes'),
	array('North Qedar','Hatallu (West Coast)','Yes','No'),
	array('North Qedar','Aram','No','Yes'),
	array('North Qedar','Ammon','No','Yes'),
	array('North Qedar','Dumah','No','Yes'),
	array('North Qedar','South Qedar','No','Yes'),
	array('Tayma','Straits of Tiran','Yes','No'),
	array('Tayma','Mafkat','Yes','Yes'),
	array('Tayma','Dumah','No','Yes'),
	array('Tayma','Edom','No','Yes'),
	array('Tayma','Red Sea','Yes','No'),
	array('Damascus','Israel','No','Yes'),
	array('Damascus','Judah','No','Yes'),
	array('Damascus','Suburu','No','Yes'),
	array('Damascus','Aram','No','Yes'),
	array('Damascus','Ammon','No','Yes'),
	array('Bazu','Tarut','Yes','Yes'),
	array('Bazu','Lagash','Yes','Yes'),
	array('Bazu','South Qedar','No','Yes'),
	array('Tanis','Heliopolis','Yes','Yes'),
	array('Tanis','Memphis','Yes','Yes'),
	array('Tanis','Straits of Tiran','Yes','No'),
	array('Tanis','Ashkelon','Yes','Yes'),
	array('Tanis','Mafkat','Yes','Yes'),
	array('Heliopolis','Libya (East Coast)','Yes','No'),
	array('Heliopolis','Memphis','Yes','Yes'),
	array('Heliopolis','Antt','No','Yes'),
	array('Heliopolis','Antt (West Coast)','Yes','No'),
	array('Heliopolis','Antt (East Coast)','Yes','No'),
	array('Heliopolis','Straits of Tiran','Yes','No'),
	array('Heliopolis','Mafkat','Yes','Yes'),
	array('Libya','Akine','No','Yes'),
	array('Libya','Memphis','No','Yes'),
	array('Libya','Antt','No','Yes'),
	array('Libya','Thebes','No','Yes'),
	array('Libya','Swenett','No','Yes'),
	array('Tarut','Hajar','No','Yes'),
	array('Akine','Libya (East Coast)','Yes','No'),
	array('Akine','Napata','No','Yes'),
	array('Akine','Napata (West Coast)','Yes','No'),
	array('Akine','Meroe','Yes','Yes'),
	array('Akine','Swenett','No','Yes'),
	array('Ma&#039;rib','Ma&#039;in','Yes','Yes'),
	array('Ma&#039;rib','South Arbaya','No','Yes'),
	array('Ma&#039;rib','Qataban','Yes','Yes'),
	array('Ma&#039;rib','Gate of Grief','Yes','No'),
	array('Rub&#039; al Khali','South Arbaya','No','Yes'),
	array('Rub&#039; al Khali','Qana&#039;','No','Yes'),
	array('Rub&#039; al Khali','Dhofar','No','Yes'),
	array('Rub&#039; al Khali','Hajar','No','Yes'),
	array('Ma&#039;in','South Arbaya','No','Yes'),
	array('Ma&#039;in','Red Sea','Yes','No'),
	array('Hatallu','Rasappa','No','Yes'),
	array('Hatallu','Assur','No','Yes'),
	array('Hatallu (West Coast)','Rasappa','Yes','No'),
	array('Hatallu (East Coast)','Assur','Yes','No'),
	array('Anshan','Hidalu','No','Yes'),
	array('Libya (North Coast)','Memphis','Yes','No'),
	array('Libya (East Coast)','Memphis','Yes','No'),
	array('Libya (East Coast)','Antt (West Coast)','Yes','No'),
	array('Libya (East Coast)','Thebes (West Coast)','Yes','No'),
	array('Libya (East Coast)','Swenett (West Coast)','Yes','No'),
	array('South Arbaya','Qana&#039;','No','Yes'),
	array('South Arbaya','Hajar','No','Yes'),
	array('Antt','Thebes','No','Yes'),
	array('Antt','Mafkat','No','Yes'),
	array('Antt (West Coast)','Thebes (West Coast)','Yes','No'),
	array('Antt (East Coast)','Straits of Tiran','Yes','No'),
	array('Antt (East Coast)','Thebes (East Coast)','Yes','No'),
	array('Antt (East Coast)','Mafkat','Yes','No'),
	array('Straits of Tiran','Thebes (East Coast)','Yes','No'),
	array('Straits of Tiran','Mafkat','Yes','No'),
	array('Straits of Tiran','Red Sea','Yes','No'),
	array('Upper Nubia','D&#039;mt','No','Yes'),
	array('Upper Nubia','Meroe','No','Yes'),
	array('Upper Nubia','Blemmyia','No','Yes'),
	array('D&#039;mt','Blemmyia','Yes','Yes'),
	array('D&#039;mt','Red Sea','Yes','No'),
	array('D&#039;mt','Gate of Grief','Yes','No'),
	array('Thebes','Swenett','No','Yes'),
	array('Thebes (West Coast)','Swenett (West Coast)','Yes','No'),
	array('Thebes (East Coast)','Swenett (East Coast)','Yes','No'),
	array('Thebes (East Coast)','Red Sea','Yes','No'),
	array('Napata','Meroe','No','Yes'),
	array('Napata','Blemmyia','No','Yes'),
	array('Napata','Swenett','No','Yes'),
	array('Napata (West Coast)','Meroe','Yes','No'),
	array('Napata (West Coast)','Swenett (West Coast)','Yes','No'),
	array('Napata (East Coast)','Blemmyia','Yes','No'),
	array('Napata (East Coast)','Swenett (East Coast)','Yes','No'),
	array('Napata (East Coast)','Red Sea','Yes','No'),
	array('Meroe','Blemmyia','No','Yes'),
	array('Lydia','Kelainai','Yes','Yes'),
	array('Lydia','Aegean Sea','Yes','No'),
	array('Kelainai','Pamphylia','Yes','Yes'),
	array('Kelainai','Aegean Sea','Yes','No'),
	array('Pamphylia','Hilakku','Yes','Yes'),
	array('Diauehi','Melid','No','Yes'),
	array('Ashkelon','Israel','Yes','Yes'),
	array('Ashkelon','Mafkat','No','Yes'),
	array('Israel','Judah','No','Yes'),
	array('Israel','Mafkat','No','Yes'),
	array('Israel','Edom','No','Yes'),
	array('Israel','Coast of Canaan','Yes','No'),
	array('Judah','Ammon','No','Yes'),
	array('Judah','Edom','No','Yes'),
	array('Mafkat','Edom','No','Yes'),
	array('Melid','Sam&#039;al','No','Yes'),
	array('Til Barsip','Laqe','Yes','Yes'),
	array('Til Barsip','Rasappa','Yes','Yes'),
	array('Arwad','Coast of Canaan','Yes','No'),
	array('Tyre','Suburu','No','Yes'),
	array('Tyre','Coast of Canaan','Yes','No'),
	array('Suburu','Aram','No','Yes'),
	array('Aram','Laqe','No','Yes'),
	array('Aram','Ammon','No','Yes'),
	array('Blemmyia','Red Sea','Yes','No'),
	array('Laqe','Rasappa','Yes','Yes'),
	array('Rasappa','Assur','No','Yes'),
	array('Rhodes','Aegean Sea','Yes','No'),
	array('Ammon','Dumah','No','Yes'),
	array('Ammon','Edom','No','Yes'),
	array('Dumah','South Qedar','No','Yes'),
	array('Dumah','Edom','No','Yes'),
	array('Qataban','Gate of Grief','Yes','No'),
	array('Qana&#039;','Gate of Grief','Yes','No'),
	array('Knossos','Aegean Sea','Yes','No'),
	array('Swenett (East Coast)','Red Sea','Yes','No'),
	array('Red Sea','Gate of Grief','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
