<?php
// This is file installs the map data for the Crusades1201 variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Scotland', 'Coast', 'Yes', 0, 658, 355, 244, 136),
	array('Wales', 'Coast', 'No', 3, 609, 574, 227, 213),
	array('England', 'Coast', 'Yes', 3, 685, 588, 254, 202),
	array('Norway', 'Coast', 'No', 0, 977, 269, 362, 100),
	array('Sweden', 'Coast', 'Yes', 0, 1097, 341, 413, 112),
	array('Sweden (West Coast)', 'Coast', 'No', 0, 1058, 422, 401, 164),
	array('Sweden (East Coast)', 'Coast', 'No', 0, 1109, 431, 421, 144),
	array('Scania', 'Coast', 'Yes', 6, 1049, 503, 394, 193),
	array('Finland', 'Coast', 'No', 0, 1298, 269, 503, 74),
	array('Novgorod', 'Coast', 'Yes', 9, 1481, 365, 554, 139),
	array('Moscow', 'Land', 'No', 9, 1678, 547, 660, 215),
	array('Crimea', 'Coast', 'No', 0, 1805, 886, 676, 335),
	array('Kiev', 'Coast', 'Yes', 9, 1424, 844, 568, 298),
	array('Smolensk', 'Land', 'No', 9, 1472, 578, 554, 214),
	array('Lithuania', 'Coast', 'No', 0, 1339, 472, 503, 179),
	array('Prussia', 'Coast', 'No', 0, 1189, 614, 441, 229),
	array('Poland', 'Land', 'Yes', 0, 1171, 727, 438, 270),
	array('Moravia', 'Land', 'No', 5, 1133, 830, 426, 300),
	array('Bohemia', 'Land', 'Yes', 0, 1046, 787, 390, 288),
	array('Brandenburg', 'Land', 'No', 5, 1034, 670, 383, 256),
	array('Pomerania', 'Coast', 'Yes', 0, 1064, 592, 410, 223),
	array('Mecklenburg', 'Coast', 'No', 5, 977, 604, 362, 227),
	array('Frisia', 'Coast', 'No', 5, 896, 611, 335, 227),
	array('Westphalia', 'Land', 'No', 5, 859, 682, 314, 267),
	array('Lorraine', 'Land', 'No', 5, 835, 815, 320, 294),
	array('Bavaria', 'Land', 'Yes', 5, 940, 836, 352, 303),
	array('Tyrol', 'Land', 'No', 5, 944, 893, 352, 331),
	array('Austria', 'Land', 'No', 5, 1046, 896, 393, 329),
	array('Bosnia', 'Coast', 'No', 8, 1120, 1027, 423, 382),
	array('Buda', 'Land', 'Yes', 8, 1139, 926, 427, 348),
	array('Pest', 'Land', 'Yes', 8, 1241, 935, 469, 352),
	array('Carpathia', 'Land', 'No', 8, 1271, 850, 458, 315),
	array('Transylvania', 'Land', 'No', 8, 1354, 907, 507, 341),
	array('Bulgaria', 'Coast', 'No', 0, 1394, 1004, 518, 378),
	array('Serbia', 'Coast', 'Yes', 0, 1198, 1081, 453, 403),
	array('Athens', 'Coast', 'Yes', 10, 1246, 1214, 473, 460),
	array('Macedonia', 'Coast', 'No', 10, 1306, 1156, 497, 429),
	array('Constantinople', 'Coast', 'Yes', 10, 1486, 1162, 556, 439),
	array('Pontus', 'Coast', 'No', 10, 1672, 1111, 630, 415),
	array('Caucasus', 'Coast', 'No', 0, 1919, 1090, 718, 419),
	array('Anatolia', 'Land', 'Yes', 0, 1622, 1198, 654, 446),
	array('Smyrna', 'Coast', 'No', 10, 1514, 1295, 571, 489),
	array('Antioch', 'Coast', 'Yes', 0, 1798, 1270, 671, 500),
	array('Syria', 'Land', 'No', 0, 1865, 1360, 702, 497),
	array('Jerusalem', 'Coast', 'Yes', 11, 1786, 1531, 668, 578),
	array('Egypt', 'Coast', 'Yes', 11, 1604, 1643, 573, 630),
	array('Libya', 'Coast', 'No', 11, 989, 1595, 371, 598),
	array('Hesse', 'Land', 'Yes', 5, 928, 731, 351, 261),
	array('Denmark', 'Coast', 'Yes', 6, 926, 493, 346, 185),
	array('Tunis', 'Coast', 'Yes', 2, 799, 1393, 287, 522),
	array('Morocco', 'Coast', 'No', 2, 310, 1294, 119, 492),
	array('Cordoba', 'Coast', 'Yes', 2, 338, 1184, 125, 443),
	array('Andalusia', 'Coast', 'No', 2, 266, 1121, 100, 417),
	array('Portugal', 'Coast', 'Yes', 0, 320, 1001, 118, 380),
	array('Leon', 'Coast', 'No', 0, 373, 928, 139, 346),
	array('Toledo', 'Land', 'Yes', 1, 413, 1058, 153, 406),
	array('Valencia', 'Coast', 'No', 2, 511, 1120, 188, 428),
	array('Aragon', 'Coast', 'Yes', 0, 625, 1046, 235, 395),
	array('Valladolid', 'Coast', 'Yes', 1, 464, 968, 175, 357),
	array('Navarre', 'Coast', 'No', 0, 523, 1007, 200, 375),
	array('Guyenne', 'Coast', 'Yes', 3, 583, 958, 228, 342),
	array('Langudoc', 'Coast', 'No', 4, 665, 974, 264, 356),
	array('Provence', 'Coast', 'Yes', 0, 781, 979, 296, 368),
	array('Tuscany', 'Coast', 'No', 5, 923, 1036, 339, 379),
	array('Rome', 'Coast', 'Yes', 7, 966, 1097, 357, 411),
	array('Naples', 'Coast', 'Yes', 0, 1066, 1174, 405, 457),
	array('Ravenna', 'Coast', 'Yes', 7, 999, 1053, 366, 385),
	array('Venice', 'Coast', 'Yes', 0, 977, 946, 365, 354),
	array('Lombardy', 'Land', 'No', 5, 900, 937, 319, 351),
	array('Alps', 'Land', 'No', 5, 874, 887, 324, 325),
	array('Burgundy', 'Land', 'Yes', 0, 773, 859, 292, 312),
	array('Auvergne', 'Land', 'Yes', 4, 714, 832, 267, 329),
	array('Bergerac', 'Land', 'No', 3, 658, 845, 245, 317),
	array('Poitou', 'Coast', 'No', 3, 590, 821, 220, 313),
	array('Brittany', 'Coast', 'Yes', 0, 556, 748, 219, 286),
	array('Normandy', 'Coast', 'No', 3, 637, 724, 240, 267),
	array('Paris', 'Land', 'Yes', 4, 686, 772, 257, 289),
	array('Champagne', 'Land', 'No', 4, 775, 766, 289, 282),
	array('Flanders', 'Coast', 'No', 4, 755, 665, 288, 254),
	array('Netherlands', 'Coast', 'Yes', 0, 808, 659, 309, 235),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 1192, 302, 449, 104),
	array('Baltic Sea', 'Sea', 'No', 0, 1198, 499, 439, 191),
	array('Kattegat', 'Sea', 'No', 0, 992, 410, 373, 168),
	array('Skagerrak', 'Sea', 'No', 0, 868, 436, 326, 150),
	array('Helgoland Bight', 'Sea', 'No', 0, 862, 526, 315, 199),
	array('North Sea', 'Sea', 'No', 0, 757, 478, 284, 171),
	array('Norwegian Sea', 'Sea', 'No', 0, 683, 179, 243, 74),
	array('English Channel', 'Sea', 'No', 0, 496, 611, 185, 229),
	array('Bay of Biscay', 'Sea', 'No', 0, 451, 838, 159, 298),
	array('Mid-Atlantic Ocean', 'Sea', 'No', 0, 205, 721, 75, 269),
	array('Western Mediterranean', 'Sea', 'No', 0, 748, 1229, 272, 459),
	array('Gulf of Lyon', 'Sea', 'No', 0, 770, 1093, 285, 409),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 928, 1189, 351, 451),
	array('South Ionian Sea', 'Sea', 'No', 0, 965, 1427, 352, 542),
	array('North Ionian Sea', 'Sea', 'No', 0, 1159, 1334, 445, 517),
	array('Adriatic Sea', 'Sea', 'No', 0, 1081, 1091, 422, 422),
	array('Eastern Mediterranean', 'Sea', 'No', 0, 1517, 1459, 581, 554),
	array('Aegean Sea', 'Sea', 'No', 0, 1366, 1244, 523, 494),
	array('Black Sea', 'Sea', 'No', 0, 1567, 1031, 584, 388),
	array('Sardinia', 'Coast', 'Yes', 0, 844, 1162, 318, 430)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Scotland','Wales','Yes','Yes'),
	array('Scotland','England','Yes','Yes'),
	array('Scotland','North Sea','Yes','No'),
	array('Scotland','Norwegian Sea','Yes','No'),
	array('Wales','England','Yes','Yes'),
	array('Wales','Norwegian Sea','Yes','No'),
	array('Wales','English Channel','Yes','No'),
	array('England','North Sea','Yes','No'),
	array('England','English Channel','Yes','No'),
	array('Norway','Sweden','No','Yes'),
	array('Norway','Sweden (West Coast)','Yes','No'),
	array('Norway','Kattegat','Yes','No'),
	array('Norway','Skagerrak','Yes','No'),
	array('Norway','Norwegian Sea','Yes','No'),
	array('Sweden','Scania','No','Yes'),
	array('Sweden','Finland','No','Yes'),
	array('Sweden (West Coast)','Scania','Yes','No'),
	array('Sweden (West Coast)','Kattegat','Yes','No'),
	array('Sweden (East Coast)','Scania','Yes','No'),
	array('Sweden (East Coast)','Finland','Yes','No'),
	array('Sweden (East Coast)','Gulf of Bothnia','Yes','No'),
	array('Sweden (East Coast)','Baltic Sea','Yes','No'),
	array('Scania','Denmark','Yes','Yes'),
	array('Scania','Baltic Sea','Yes','No'),
	array('Scania','Kattegat','Yes','No'),
	array('Finland','Novgorod','Yes','Yes'),
	array('Finland','Gulf of Bothnia','Yes','No'),
	array('Novgorod','Moscow','No','Yes'),
	array('Novgorod','Smolensk','No','Yes'),
	array('Novgorod','Lithuania','Yes','Yes'),
	array('Novgorod','Gulf of Bothnia','Yes','No'),
	array('Moscow','Crimea','No','Yes'),
	array('Moscow','Smolensk','No','Yes'),
	array('Crimea','Kiev','Yes','Yes'),
	array('Crimea','Smolensk','No','Yes'),
	array('Crimea','Caucasus','Yes','Yes'),
	array('Crimea','Black Sea','Yes','No'),
	array('Kiev','Smolensk','No','Yes'),
	array('Kiev','Poland','No','Yes'),
	array('Kiev','Carpathia','No','Yes'),
	array('Kiev','Transylvania','No','Yes'),
	array('Kiev','Bulgaria','Yes','Yes'),
	array('Kiev','Black Sea','Yes','No'),
	array('Smolensk','Lithuania','No','Yes'),
	array('Smolensk','Prussia','No','Yes'),
	array('Smolensk','Poland','No','Yes'),
	array('Lithuania','Prussia','Yes','Yes'),
	array('Lithuania','Gulf of Bothnia','Yes','No'),
	array('Lithuania','Baltic Sea','Yes','No'),
	array('Prussia','Poland','No','Yes'),
	array('Prussia','Brandenburg','No','Yes'),
	array('Prussia','Pomerania','Yes','Yes'),
	array('Prussia','Baltic Sea','Yes','No'),
	array('Poland','Moravia','No','Yes'),
	array('Poland','Bohemia','No','Yes'),
	array('Poland','Brandenburg','No','Yes'),
	array('Poland','Carpathia','No','Yes'),
	array('Moravia','Bohemia','No','Yes'),
	array('Moravia','Austria','No','Yes'),
	array('Moravia','Buda','No','Yes'),
	array('Moravia','Carpathia','No','Yes'),
	array('Bohemia','Brandenburg','No','Yes'),
	array('Bohemia','Bavaria','No','Yes'),
	array('Bohemia','Austria','No','Yes'),
	array('Bohemia','Hesse','No','Yes'),
	array('Brandenburg','Pomerania','No','Yes'),
	array('Brandenburg','Mecklenburg','No','Yes'),
	array('Brandenburg','Hesse','No','Yes'),
	array('Pomerania','Mecklenburg','Yes','Yes'),
	array('Pomerania','Baltic Sea','Yes','No'),
	array('Mecklenburg','Frisia','No','Yes'),
	array('Mecklenburg','Hesse','No','Yes'),
	array('Mecklenburg','Denmark','Yes','Yes'),
	array('Mecklenburg','Baltic Sea','Yes','No'),
	array('Frisia','Westphalia','No','Yes'),
	array('Frisia','Hesse','No','Yes'),
	array('Frisia','Denmark','Yes','Yes'),
	array('Frisia','Netherlands','Yes','Yes'),
	array('Frisia','Helgoland Bight','Yes','No'),
	array('Westphalia','Lorraine','No','Yes'),
	array('Westphalia','Hesse','No','Yes'),
	array('Westphalia','Champagne','No','Yes'),
	array('Westphalia','Flanders','No','Yes'),
	array('Westphalia','Netherlands','No','Yes'),
	array('Lorraine','Bavaria','No','Yes'),
	array('Lorraine','Hesse','No','Yes'),
	array('Lorraine','Alps','No','Yes'),
	array('Lorraine','Burgundy','No','Yes'),
	array('Lorraine','Champagne','No','Yes'),
	array('Bavaria','Tyrol','No','Yes'),
	array('Bavaria','Austria','No','Yes'),
	array('Bavaria','Hesse','No','Yes'),
	array('Bavaria','Alps','No','Yes'),
	array('Tyrol','Austria','No','Yes'),
	array('Tyrol','Venice','No','Yes'),
	array('Tyrol','Lombardy','No','Yes'),
	array('Tyrol','Alps','No','Yes'),
	array('Austria','Bosnia','No','Yes'),
	array('Austria','Buda','No','Yes'),
	array('Austria','Venice','No','Yes'),
	array('Bosnia','Buda','No','Yes'),
	array('Bosnia','Pest','No','Yes'),
	array('Bosnia','Serbia','Yes','Yes'),
	array('Bosnia','Venice','Yes','Yes'),
	array('Bosnia','Adriatic Sea','Yes','No'),
	array('Buda','Pest','No','Yes'),
	array('Buda','Carpathia','No','Yes'),
	array('Pest','Carpathia','No','Yes'),
	array('Pest','Transylvania','No','Yes'),
	array('Pest','Bulgaria','No','Yes'),
	array('Pest','Serbia','No','Yes'),
	array('Carpathia','Transylvania','No','Yes'),
	array('Transylvania','Bulgaria','No','Yes'),
	array('Bulgaria','Serbia','No','Yes'),
	array('Bulgaria','Macedonia','No','Yes'),
	array('Bulgaria','Constantinople','Yes','Yes'),
	array('Bulgaria','Black Sea','Yes','No'),
	array('Serbia','Athens','Yes','Yes'),
	array('Serbia','Macedonia','No','Yes'),
	array('Serbia','Adriatic Sea','Yes','No'),
	array('Athens','Macedonia','Yes','Yes'),
	array('Athens','North Ionian Sea','Yes','No'),
	array('Athens','Adriatic Sea','Yes','No'),
	array('Athens','Aegean Sea','Yes','No'),
	array('Macedonia','Constantinople','Yes','Yes'),
	array('Macedonia','Aegean Sea','Yes','No'),
	array('Constantinople','Pontus','Yes','Yes'),
	array('Constantinople','Anatolia','No','Yes'),
	array('Constantinople','Smyrna','Yes','Yes'),
	array('Constantinople','Aegean Sea','Yes','No'),
	array('Constantinople','Black Sea','Yes','No'),
	array('Pontus','Caucasus','Yes','Yes'),
	array('Pontus','Anatolia','No','Yes'),
	array('Pontus','Black Sea','Yes','No'),
	array('Caucasus','Anatolia','No','Yes'),
	array('Caucasus','Syria','No','Yes'),
	array('Caucasus','Black Sea','Yes','No'),
	array('Anatolia','Smyrna','No','Yes'),
	array('Anatolia','Antioch','No','Yes'),
	array('Anatolia','Syria','No','Yes'),
	array('Smyrna','Antioch','Yes','Yes'),
	array('Smyrna','Eastern Mediterranean','Yes','No'),
	array('Smyrna','Aegean Sea','Yes','No'),
	array('Antioch','Syria','No','Yes'),
	array('Antioch','Jerusalem','Yes','Yes'),
	array('Antioch','Eastern Mediterranean','Yes','No'),
	array('Syria','Jerusalem','No','Yes'),
	array('Jerusalem','Egypt','Yes','Yes'),
	array('Jerusalem','Eastern Mediterranean','Yes','No'),
	array('Egypt','Libya','Yes','Yes'),
	array('Egypt','Eastern Mediterranean','Yes','No'),
	array('Libya','Tunis','Yes','Yes'),
	array('Libya','South Ionian Sea','Yes','No'),
	array('Libya','Eastern Mediterranean','Yes','No'),
	array('Denmark','Baltic Sea','Yes','No'),
	array('Denmark','Kattegat','Yes','No'),
	array('Denmark','Skagerrak','Yes','No'),
	array('Denmark','Helgoland Bight','Yes','No'),
	array('Tunis','Morocco','Yes','Yes'),
	array('Tunis','Western Mediterranean','Yes','No'),
	array('Tunis','South Ionian Sea','Yes','No'),
	array('Morocco','Cordoba','Yes','Yes'),
	array('Morocco','Mid-Atlantic Ocean','Yes','No'),
	array('Morocco','Western Mediterranean','Yes','No'),
	array('Cordoba','Andalusia','Yes','Yes'),
	array('Cordoba','Valencia','Yes','Yes'),
	array('Cordoba','Mid-Atlantic Ocean','Yes','No'),
	array('Cordoba','Western Mediterranean','Yes','No'),
	array('Andalusia','Portugal','Yes','Yes'),
	array('Andalusia','Leon','No','Yes'),
	array('Andalusia','Toledo','No','Yes'),
	array('Andalusia','Mid-Atlantic Ocean','Yes','No'),
	array('Portugal','Leon','Yes','Yes'),
	array('Portugal','Mid-Atlantic Ocean','Yes','No'),
	array('Leon','Toledo','No','Yes'),
	array('Leon','Valladolid','Yes','Yes'),
	array('Leon','Bay of Biscay','Yes','No'),
	array('Leon','Mid-Atlantic Ocean','Yes','No'),
	array('Toledo','Valencia','No','Yes'),
	array('Toledo','Aragon','No','Yes'),
	array('Toledo','Valladolid','No','Yes'),
	array('Valencia','Aragon','Yes','Yes'),
	array('Valencia','Western Mediterranean','Yes','No'),
	array('Valencia','Gulf of Lyon','Yes','No'),
	array('Aragon','Valladolid','No','Yes'),
	array('Aragon','Navarre','No','Yes'),
	array('Aragon','Langudoc','Yes','Yes'),
	array('Aragon','Gulf of Lyon','Yes','No'),
	array('Valladolid','Navarre','Yes','Yes'),
	array('Valladolid','Bay of Biscay','Yes','No'),
	array('Navarre','Guyenne','Yes','Yes'),
	array('Navarre','Langudoc','No','Yes'),
	array('Navarre','Bay of Biscay','Yes','No'),
	array('Guyenne','Langudoc','No','Yes'),
	array('Guyenne','Bergerac','No','Yes'),
	array('Guyenne','Poitou','Yes','Yes'),
	array('Guyenne','Bay of Biscay','Yes','No'),
	array('Langudoc','Provence','Yes','Yes'),
	array('Langudoc','Burgundy','No','Yes'),
	array('Langudoc','Auvergne','No','Yes'),
	array('Langudoc','Bergerac','No','Yes'),
	array('Langudoc','Gulf of Lyon','Yes','No'),
	array('Provence','Tuscany','Yes','Yes'),
	array('Provence','Lombardy','No','Yes'),
	array('Provence','Alps','No','Yes'),
	array('Provence','Burgundy','No','Yes'),
	array('Provence','Gulf of Lyon','Yes','No'),
	array('Tuscany','Rome','Yes','Yes'),
	array('Tuscany','Ravenna','No','Yes'),
	array('Tuscany','Venice','No','Yes'),
	array('Tuscany','Lombardy','No','Yes'),
	array('Tuscany','Gulf of Lyon','Yes','No'),
	array('Tuscany','Tyrrhenian Sea','Yes','No'),
	array('Rome','Naples','Yes','Yes'),
	array('Rome','Ravenna','No','Yes'),
	array('Rome','Tyrrhenian Sea','Yes','No'),
	array('Naples','Ravenna','Yes','Yes'),
	array('Naples','Western Mediterranean','Yes','No'),
	array('Naples','Tyrrhenian Sea','Yes','No'),
	array('Naples','South Ionian Sea','Yes','No'),
	array('Naples','North Ionian Sea','Yes','No'),
	array('Naples','Adriatic Sea','Yes','No'),
	array('Ravenna','Venice','Yes','Yes'),
	array('Ravenna','Adriatic Sea','Yes','No'),
	array('Venice','Lombardy','No','Yes'),
	array('Venice','Adriatic Sea','Yes','No'),
	array('Lombardy','Alps','No','Yes'),
	array('Alps','Burgundy','No','Yes'),
	array('Burgundy','Auvergne','No','Yes'),
	array('Burgundy','Paris','No','Yes'),
	array('Burgundy','Champagne','No','Yes'),
	array('Auvergne','Bergerac','No','Yes'),
	array('Auvergne','Paris','No','Yes'),
	array('Bergerac','Poitou','No','Yes'),
	array('Bergerac','Normandy','No','Yes'),
	array('Bergerac','Paris','No','Yes'),
	array('Poitou','Brittany','Yes','Yes'),
	array('Poitou','Normandy','No','Yes'),
	array('Poitou','Bay of Biscay','Yes','No'),
	array('Brittany','Normandy','Yes','Yes'),
	array('Brittany','English Channel','Yes','No'),
	array('Brittany','Bay of Biscay','Yes','No'),
	array('Normandy','Paris','No','Yes'),
	array('Normandy','Champagne','No','Yes'),
	array('Normandy','Flanders','Yes','Yes'),
	array('Normandy','English Channel','Yes','No'),
	array('Paris','Champagne','No','Yes'),
	array('Champagne','Flanders','No','Yes'),
	array('Flanders','Netherlands','Yes','Yes'),
	array('Flanders','North Sea','Yes','No'),
	array('Flanders','English Channel','Yes','No'),
	array('Netherlands','Helgoland Bight','Yes','No'),
	array('Netherlands','North Sea','Yes','No'),
	array('Gulf of Bothnia','Baltic Sea','Yes','No'),
	array('Kattegat','Skagerrak','Yes','No'),
	array('Skagerrak','Helgoland Bight','Yes','No'),
	array('Skagerrak','North Sea','Yes','No'),
	array('Skagerrak','Norwegian Sea','Yes','No'),
	array('Helgoland Bight','North Sea','Yes','No'),
	array('North Sea','Norwegian Sea','Yes','No'),
	array('North Sea','English Channel','Yes','No'),
	array('Norwegian Sea','English Channel','Yes','No'),
	array('Norwegian Sea','Mid-Atlantic Ocean','Yes','No'),
	array('English Channel','Bay of Biscay','Yes','No'),
	array('English Channel','Mid-Atlantic Ocean','Yes','No'),
	array('Bay of Biscay','Mid-Atlantic Ocean','Yes','No'),
	array('Mid-Atlantic Ocean','Western Mediterranean','Yes','No'),
	array('Western Mediterranean','Gulf of Lyon','Yes','No'),
	array('Western Mediterranean','Tyrrhenian Sea','Yes','No'),
	array('Western Mediterranean','South Ionian Sea','Yes','No'),
	array('Western Mediterranean','Sardinia','Yes','No'),
	array('Gulf of Lyon','Tyrrhenian Sea','Yes','No'),
	array('Gulf of Lyon','Sardinia','Yes','No'),
	array('Tyrrhenian Sea','North Ionian Sea','Yes','No'),
	array('Tyrrhenian Sea','Sardinia','Yes','No'),
	array('South Ionian Sea','North Ionian Sea','Yes','No'),
	array('South Ionian Sea','Eastern Mediterranean','Yes','No'),
	array('North Ionian Sea','Adriatic Sea','Yes','No'),
	array('North Ionian Sea','Eastern Mediterranean','Yes','No'),
	array('North Ionian Sea','Aegean Sea','Yes','No'),
	array('Eastern Mediterranean','Aegean Sea','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
